### ISSUE TITLE
Add harness hooks for assert.throws.early

### ISSUE THREAD

**Issue by littledan** [tc39/test262#1016]
The way assert.throws.early is implemented does not tell the engine that test262 is looking for an early error. With a harness hook, such as `$.assertThrowsEarly`, users could improve test coverage to match what a well-written harness can do for `phase: early` frontmatter. Currently, I believe `assert.throws.early` will invoke just the parser and not the pre-parser for V8.

**Comment by rwaldron** [comment]
`assert.throws.early` no longer exists
