### ISSUE TITLE
Computed property missing in Object Rest Destructuring tests

### ISSUE THREAD

**Issue by caiolima** [tc39/test262#1035]
We are missing the following test case for Object Rest Destructuring:

```
let a = "foo";
let {[a]: b, ...rest} = { foo: 2, bar: 3};
```

This test case is broken in JSC implementation.

**Comment by leobalter** [comment]
do you mean the computed property names?

I guess it's not the reference error for `b`.

**Comment by caiolima** [comment]
If I didn't misunderstand spec, it will bind 2 to b here, since the evaluated key into [a] is "foo".

I think it is valid for Object Destructuring without Rest operation, BTW.

**Comment by caiolima** [comment]
@leobalter you are right, it is the computed property names. I'm going to work on that soon.
