### ISSUE TITLE
Incorrect for-await tests because implicit Await and Async-from-Sync iterator behaviour is ignored

### ISSUE THREAD

**Issue by anba** [tc39/test262#1043]
The following for-await tests are incorrect:

- test/language/statements/for-await-of/async-func-dstr-const-ary-ptrn-elision-step-err.js
- test/language/statements/for-await-of/async-func-dstr-const-ary-ptrn-rest-id-iter-step-err.js
- test/language/statements/for-await-of/async-func-dstr-let-ary-ptrn-elision-step-err.js
- test/language/statements/for-await-of/async-func-dstr-let-ary-ptrn-rest-id-iter-step-err.js
- test/language/statements/for-await-of/async-func-dstr-var-ary-ptrn-elision-step-err.js
- test/language/statements/for-await-of/async-func-dstr-var-ary-ptrn-rest-id-iter-step-err.js
- test/language/statements/for-await-of/async-gen-dstr-const-ary-ptrn-elision-step-err.js
- test/language/statements/for-await-of/async-gen-dstr-const-ary-ptrn-rest-id-iter-step-err.js
- test/language/statements/for-await-of/async-gen-dstr-let-ary-ptrn-elision-step-err.js
- test/language/statements/for-await-of/async-gen-dstr-let-ary-ptrn-rest-id-iter-step-err.js
- test/language/statements/for-await-of/async-gen-dstr-var-ary-ptrn-elision-step-err.js
- test/language/statements/for-await-of/async-gen-dstr-var-ary-ptrn-rest-id-iter-step-err.js

See https://github.com/tc39/test262/pull/1020#discussion_r116531160 for an explanation.

@syg, @caitp per discussion at http://logs.libuv.org/tc39/2017-05-19#01:10:48.834

**Comment by leobalter** [comment]
I'm trying to analyze the files and I need to write it down here to see if I get the error:

On `test/language/statements/for-await-of/async-func-dstr-const-ary-ptrn-rest-id-iter-step-err.js`: 

```js
var first = 0;
var second = 0;
var iter = function*() {
  first += 1;
  throw new Test262Error();
  second += 1;
}();

async function fn() {
  for await (const [...x] of [iter]) {
    return;
  }
}

fn()
  .then(_ => { throw new Test262Error("Expected async function to reject, but resolved."); }, ({ constructor }) => assert.sameValue(constructor, Test262Error))
  .then($DONE, $DONE);


iter.next();
assert.sameValue(first, 1);
assert.sameValue(second, 0, 'Iterator is closed following abrupt completion.');
```

I understand this call for `iter.next()` might be wrong placed, as I would need to have it inside the `.then` call.

so it would make more sense to have: 

```js
fn()
  .then(_ => {
    throw new Test262Error("Expected async function to reject, but resolved.");
  }, ({ constructor }) => {
    assert.sameValue(constructor, Test262Error);
  })
  .then(_ => {
    iter.next();
    assert.sameValue(first, 1);
    assert.sameValue(second, 0, 'Iterator is closed following abrupt completion.');
  })
  .then($DONE, $DONE);
```

So I can confirm I'm calling it after the iteration has happened inside the async function.

---

It's being really hard to identify why I would need to add any other step as I understand the abrupt completion from `iter` would be set as a rejection for the matching async function.

Is there anything else I'm missing?

**Comment by rwaldron** [comment]
- [for-await-of/async-func-dstr-const-ary-ptrn-elision-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-func-dstr-const-ary-ptrn-elision-step-err.js)
- [for-await-of/async-func-dstr-const-ary-ptrn-rest-id-iter-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-func-dstr-const-ary-ptrn-rest-id-iter-step-err.js)
- [for-await-of/async-func-dstr-let-ary-ptrn-elision-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-func-dstr-let-ary-ptrn-elision-step-err.js)
- [for-await-of/async-func-dstr-let-ary-ptrn-rest-id-iter-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-func-dstr-let-ary-ptrn-rest-id-iter-step-err.js)
- [for-await-of/async-func-dstr-var-ary-ptrn-elision-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-func-dstr-var-ary-ptrn-elision-step-err.js)
- [for-await-of/async-func-dstr-var-ary-ptrn-rest-id-iter-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-func-dstr-var-ary-ptrn-rest-id-iter-step-err.js)
- [for-await-of/async-gen-dstr-const-ary-ptrn-elision-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-gen-dstr-const-ary-ptrn-elision-step-err.js)
- [for-await-of/async-gen-dstr-const-ary-ptrn-rest-id-iter-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-gen-dstr-const-ary-ptrn-rest-id-iter-step-err.js)
- [for-await-of/async-gen-dstr-let-ary-ptrn-elision-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-gen-dstr-let-ary-ptrn-elision-step-err.js)
- [for-await-of/async-gen-dstr-let-ary-ptrn-rest-id-iter-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-gen-dstr-let-ary-ptrn-rest-id-iter-step-err.js)
- [for-await-of/async-gen-dstr-var-ary-ptrn-elision-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-gen-dstr-var-ary-ptrn-elision-step-err.js)
- [for-await-of/async-gen-dstr-var-ary-ptrn-rest-id-iter-step-err.js](/tc39/test262/tree/master/test/language/statements/for-await-of/async-gen-dstr-var-ary-ptrn-rest-id-iter-step-err.js)

**Comment by rwaldron** [comment]
Yep, these are wrong. They have incorrectly included case or template code. I feel bad that everyone went through a bunch of trouble trying to reason this out, when it was really just a miss-written case or template. I will get them fixed. 


Things that exist, but don't belong: 

- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-func-dstr-const-ary-ptrn-elision-step-err.js#L73-L74
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-func-dstr-const-ary-ptrn-rest-id-iter-step-err.js#L69-L71
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-func-dstr-let-ary-ptrn-elision-step-err.js#L73-L74
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-func-dstr-let-ary-ptrn-rest-id-iter-step-err.js#L69-L71
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-func-dstr-var-ary-ptrn-elision-step-err.js#L72-L73
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-func-dstr-var-ary-ptrn-rest-id-iter-step-err.js#L68-L70
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-dstr-const-ary-ptrn-elision-step-err.js#L73-L74
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-dstr-const-ary-ptrn-rest-id-iter-step-err.js#L69-L71
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-dstr-let-ary-ptrn-elision-step-err.js#L72-L73
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-dstr-let-ary-ptrn-rest-id-iter-step-err.js#L68-L70
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-dstr-var-ary-ptrn-elision-step-err.js#L73-L74
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-dstr-var-ary-ptrn-rest-id-iter-step-err.js#L69-L71

The good news is that this is something that I discovered later when doing the dstr-assignment tests, so the issue doesn't exist there.

**Comment by rwaldron** [comment]
The issue is that these cases have `//- teardown` which adds those erroneous lines, and I missed it in the mountain of files that were generated.

**Comment by rwaldron** [comment]
https://github.com/tc39/test262/pull/1044
