### ISSUE TITLE
Remove tests that allow `...[` and `...{` in object destructuring

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#1050]
per resolution of 16.i.h https://github.com/tc39/agendas/blob/master/2017/05.md

I'll work on this during my next cycle

**Comment by leobalter** [comment]
by object destructuring, this means rest operators (not spread) directly in object patterns for destructuring will only be valid with name identifiers.

```js
let {a, ...[]} = {/*...*/}; // invalid
let {a, ...[b]} = {/*...*/}; // invalid
let {a, ...{}} = {/*...*/}; // invalid
let {a, ...{b}} = {/*...*/}; // invalid
let {a, ...b} = {/*...*/}; // valid
let {...[]} = {/*...*/}; // valid
```

This needs to wait the respective proposal to be fixed and match the references.

**Comment by rwaldron** [comment]
> `let {...[]} = {/*...*/}; // valid`

I don't think that's correct. We need confirmation

> This needs to wait the respective proposal to be fixed and match the references.

Everything I've reviewed so far has `esid: pending`

**Comment by leobalter** [comment]
> I don't think that's correct. We need confirmation 

right you are, my copy-pasta fault.

> Everything I've reviewed so far has esid: pending

pending means only we don't have the reference on what the link would be in the specs yet. Still, we require a minimum spec text to reference each case. Of course, providing this in the info tag helps a lot.

**Comment by leobalter** [comment]
A few examples of test cases requiring a new review:

src/dstr-binding/obj-ptrn-rest-nested-obj.case
src/dstr-binding/obj-ptrn-rest-obj-nested-rest.case
src/dstr-binding/obj-ptrn-rest-obj-own-property.case

**Comment by rwaldron** [comment]
> pending means only we don't have the reference on what the link would be in the specs yet

I know, but all the cases I've seen said "esid: pending", so there is no reason to...

> This needs to wait the respective proposal to be fixed and match the references.

...

> A few examples of test cases requiring a new review:
> src/dstr-binding/obj-ptrn-rest-nested-obj.case
> src/dstr-binding/obj-ptrn-rest-obj-nested-rest.case
> src/dstr-binding/obj-ptrn-rest-obj-own-property.case

Yes, already removed in a branch.

**Comment by rwaldron** [comment]
I'll also include new negative syntax error tests.

**Comment by gsathya** [comment]
FYI, these are the obsolete tests that I had to disable in V8:
https://chromium-review.googlesource.com/c/550559/13/test/test262/test262.status

**Comment by rwaldron** [comment]
@gsathya thanks, you should update to latest test262 to get these changes: https://github.com/tc39/test262/commit/29e69ddb4ec2fa5ce263fb32f351a99ffde5cc24

**Comment by littledan** [comment]
Sorry, this is my fault on the late test262 update; I'll report any issues here if there are stray tests.

**Comment by rwaldron** [comment]
@littledan no problem!

**Comment by gsathya** [comment]
Thanks. If all the obsolete tests have been deleted, can this issue be closed now?

**Comment by littledan** [comment]
Have any tests been added that check that the old syntax is no longer allowed? I just upgraded V8 to the new version of test262, and Sathya's patch to use the new semantics hasn't landed yet, but the test262 tests all pass.

**Comment by gsathya** [comment]
Even with the latest roll, I had to skip a bunch of tests:
https://chromium-review.googlesource.com/c/550559/16/test/test262/test262.status

**Comment by littledan** [comment]
Note that the spec is not yet complete here. There is an open PR at https://github.com/tc39/proposal-object-rest-spread/pull/51 which seems to have consensus among implementers at least.

**Comment by gsathya** [comment]
@leobalter Is this fixed now with https://github.com/tc39/test262/pull/1187 ?

**Comment by leobalter** [comment]
yes, I believe we're all set on this. Thanks for the reminder.

**Comment by adrianheine** [comment]
@rwaldron Did you include those negative tests? I can't seem to find them.
