### ISSUE TITLE
Add tests for BigInt proposal

### ISSUE THREAD

**Issue by littledan** [tc39/test262#1056]
[spec](https://github.com/tc39/proposal-bigint). The proposal is at Stage 2, so it would not yet be appropriate to merge, but the development of tests would help [a Babel implementation](https://github.com/babel/babylon/issues/569) and any pioneering implementations in browsers, such as [Robin Templeton's in-progress work in SpiderMonkey](https://bugzilla.mozilla.org/show_bug.cgi?id=1366287). Robin may have tests to upstream from that effort.

**Comment by littledan** [comment]
This should be assigned to @cxielarko .

**Comment by cxielarko** [comment]
A checklist of functionality to be tested:

- [ ] BigInt literals
- Type conversion
  - [ ] ToPrimitive
  - [ ] ToBoolean
  - [ ] ToNumber
  - [ ] ToString
  - [ ] ToObject
  - [ ] ToNumeric
  - [ ] RequireObjectCoercible
- Testing/comparison
  - [ ] less than
  - [ ] less than or equal
  - [ ] greater than
  - [ ] greater than or equal
  - [ ] equal
  - [ ] not equal
  - [ ] strictly equal
  - [ ] strictly not equal
- Expressions
  - [ ] increment/decrement
  - [ ] typeof
  - [ ] prefix +
  - [ ] negation
  - [ ] bitwise operators
  - [ ] shifts
  - arithmetic operators
    - [ ] addition
    - [ ] subtraction
    - [ ] multiplication
    - [ ] division
    - [ ] modulo
    - [ ] exponentiation
- BigInt object
  - [ ] constructor
  - [ ] parseInt
  - [ ] asUintN
  - [ ] asIntN
  - prototype
    - [ ] attributes
    - [ ] constructor
    - [ ] toLocaleString
    - [ ] toString
    - [ ] valueOf
- [ ] JSON.stringify
- [ ] Number constructor
- TypedArrays
  - [ ] BigInt64Array
  - [ ] BigUint64Array
- DataViews
  - [ ] DataView.prototype.getInt64
  - [ ] DataView.prototype.getUint64
  - [ ] DataView.prototype.setInt64
  - [ ] DataView.prototype.setUint64

**Comment by gsathya** [comment]
cc @jakobkummerow

**Comment by littledan** [comment]
I am not aware of testing gaps for BigInt, so closing this issue.
