### ISSUE TITLE
Add negative tests for legacy octal escape sequences in strings

### ISSUE THREAD

**Issue by ajklein** [tc39/test262#1062]
[Annex B.1.2](https://tc39.github.io/ecma262/#sec-additional-syntax-string-literals) defines legacy octal escape sequences in string literals. From what I can tell, test262 doesn't have coverage of these, either for their acceptance in sloppy mode code nor for them being disallowed in strict mode code (as [Section 11.8.4](https://tc39.github.io/ecma262/#sec-literals-string-literals) requires).

Thanks to the reporter of [this v8 issue](https://bugs.chromium.org/p/v8/issues/detail?id=6504) for bringing this to my attention.

**Comment by bakkot** [comment]
There's four things to be covered here: octal escapes (`\01` etc) and non-octal escapes (`\08` and `\09`), each in sloppy and strict code.

In sloppy code both are [accepted](https://tc39.github.io/ecma262/#prod-annexB-LegacyOctalEscapeSequence) but with different semantics (`LegacyOctalEscapeSequence:: ZeroToThree OctalDigit [lookahead ∉ OctalDigit]` and `LegacyOctalEscapeSequence :: OctalDigit [lookahead ∉ OctalDigit]` respectively). In strict code both are [rejected](https://tc39.github.io/ecma262/#sec-literals-string-literals) (`EscapeSequence :: 0 [lookahead ∉ DecimalDigit]`).

I believe there's coverage for octal/sloppy and noctal/sloppy [here](https://github.com/tc39/test262/blob/0314c87b0816e78802533ba9b30d42fb30eebf19/test/annexB/language/literals/string/legacy-octal-escape-sequence.js), and coverage for octal/strict [here](https://github.com/tc39/test262/blob/0314c87b0816e78802533ba9b30d42fb30eebf19/test/language/literals/string/7.8.4-1gs.js).

The only missing case is noctals in strict code: that is, we don't test that `'\08'` is forbidden in strict code. (That's also, incidentally, the only case v8 gets wrong.)
