### ISSUE TITLE
extend metadata to say a test must be run as module code

### ISSUE THREAD

**Issue by erights** [tc39/test262#1065]
At https://groups.google.com/d/msg/v8-users/p55oUdNYtmY/KsIFmsPOAQAJ Adam Klein writes:

> I don't know if anyone has done such a thing, but test262 does already include metadata that allows tests to be run in strict mode, sloppy (non-strict) mode, or both; I could imagine it being extended to make it easy for test runners to run tests as modules as well. github.com/tc39/test262/issues would be the place to raise that feature request.

Excellent suggestion!

**Comment by GeorgNeis** [comment]
The way the title phrased, this already exists: the [module] flag (e.g. see the tests in language/module-code). What Adam perhaps had in mind, and what definitely would add value, is a way to specify that a test should be run as once as a module _and_ once as a classic script (in other words, the test is expected to pass in either interpretation).

**Comment by erights** [comment]
@GeorgNeis 
Whether that's what @ajklein had in mind or not, I like that suggestion. Thanks.

**Comment by leobalter** [comment]
That's a nice suggestion.

I believe it would be interesting to run all the tests as in module mode, adding it to non-strict and strict mode. Of course non-strict only tests wouldn't be part of it.

Most of the strict mode tests should be able to run as module-code, if we find exceptions we can flag them as non-module. We can add multiple flags so this should be fine even on the strict-mode-only tests.

This is probably the only extension we need to do on Test262, the other parts should be handled by the test runners.

@bterlson can we extend test262-harness to request the runtime to run in module-mode? If not already implemented, of course.

**Comment by bterlson** [comment]
@leobalter should be easy once I get modules working in eshost :)

**Comment by phistuck** [comment]
@bterlson - how can I help? Is this effort already underway?

**Comment by bterlson** [comment]
I have bits that work for chakra core. Hoping to get it working in the other engines this weekend. Maybe I'll push a branch and you can help with supporting jsc or nashorn? In fact, links to docs/commits for either for evalling a module would be appreciated.

**Comment by bterlson** [comment]
I won't have laptop internet til sat though (post talk traveling)

**Comment by phistuck** [comment]
@bterlson - this discussion should probably move to a eshost issue, though.

Note that I do not have a macOS machine (I have BrowserStack, though, if it helps here), so I am not sure I can help with JavaScriptCore in any way (I basically have a pretty limited Linux machine of some sort), but, let us continue this in eshost instead.

**Comment by rwaldron** [comment]
@leobalter IIUC, this is just a matter of adding new `flags`?

**Comment by rwaldron** [comment]
This was completed in 2018
