### ISSUE TITLE
Generated destructuring assignment rest test only valid in sloppy mode

### ISSUE THREAD

**Issue by littledan** [tc39/test262#1082]
The test in test/language/statements/for-of/dstr-obj-rest-computed-property.js writes to an undeclared variable `b`. In strict mode, a ReferenceError will be thrown for this reason. The test needs to have an \[onlySloppy] tag, added to the appropriate template.

**Comment by rwaldron** [comment]
I'll fix this asap

**Comment by rwaldron** [comment]
Also, the `rest` variable.
