### ISSUE TITLE
Missing test case for object rest restructuring order

### ISSUE THREAD

**Issue by caiolima** [tc39/test262#1132]
We have the following test case for Object Spread to test property access ordering in spread operation https://github.com/tc39/test262/blob/master/src/spread/obj-spread-order.case, however we don't test it for rest restructuring. We should be doing that.

**Comment by caiolima** [comment]
@rwaldron It's open for a while now. Do you mind if I send a PR with this test case?

**Comment by rwaldron** [comment]
@caiolima yes, that's fine
