### ISSUE TITLE
A number of incorrect async iteration tests

### ISSUE THREAD

**Issue by caitp** [tc39/test262#1154]
There are a few classes of these errors:

1. These are wrong because the test templates expect variables to be accessed
while still in TDZ, but since there's an `await` before they're accessed, loading those
variables does not throw a ReferenceError (not in TDZ)

- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-func-decl-dstr-array-elem-init-let.js
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-func-decl-dstr-array-elem-put-let.js
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-init-let.js
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-put-let.js

---

2. This test seems to expect an extra AsyncGeneratorRequest to be fulfilled, but
there's no `yield` in the generator to allow this.

- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-trlg-iter-elision-iter-abpt.js

---

3. These tests expects .return() on a suspended-at-start generator to reject the
AsyncGeneratorRequest promise, which can never happen.

- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-trlg-iter-get-err.js
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-trlg-iter-list-nrml-close-null.js
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-trlg-iter-list-rtrn-close-err.js
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-trlg-iter-list-rtrn-close-null.js
- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-trlg-iter-rest-rtrn-close-null.js

Similarly, this one expects the generator body to have been evaluated after .return() when in
the suspended-at-start state.

- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-trlg-iter-list-rtrn-close.js

---

4. This one incorrectly finishes before it should because of the extra chained .then() call on the first
AsyncGeneratorRequest

- https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-trlg-iter-rest-rtrn-close-err.js

**Comment by rwaldron** [comment]
I'll get these corrected or removed.
