### ISSUE TITLE
Add coverage for reserved words in shorthand properties

### ISSUE THREAD

**Issue by mroch** [tc39/test262#1179]
[test/language/expressions/object/let-non-strict-syntax.js](https://github.com/tc39/test262/blob/master/test/language/expressions/object/let-non-strict-syntax.js)
[test/language/expressions/object/yield-non-strict-syntax.js](https://github.com/tc39/test262/blob/master/test/language/expressions/object/yield-non-strict-syntax.js)

these test that `var object = {let};` is valid in non-strict mode. there is no corresponding test asserting that it's a SyntaxError in strict mode.

**Comment by rwaldron** [comment]
Thanks for the report.

> there is no corresponding test asserting that it's a SyntaxError in strict mode.

That's correct, because it's not a SyntaxError to use `let` (or any reserved word) as a property name: https://tc39.github.io/ecma262/#prod-PropertyName

```js
(function() { 
  "use strict"; var o = {let: 1}; 
  console.log(o.let); 
})();
// 1
```

**Comment by mroch** [comment]
```
(function() {
  var yield = 1;
  (function() {
    var o = {yield}; // ok
    console.log(o.yield);
  })();
})();
```

```
(function() {
  var yield = 1;
  (function() {
    "use strict"; 
    var o = {yield}; // not ok
    console.log(o.yield);
  })();
})();
```

**Comment by rwaldron** [comment]
Ok, I see now, sorry for the misunderstanding.

**Comment by rwaldron** [comment]
Do you want to add the test for `void let;`?

**Comment by rwaldron** [comment]
Covered in test/language/expressions/assignment/dstr/obj-id-identifier-yield-ident-invalid.js
