### ISSUE TITLE
nitpick: both "generator" and "generators" features

### ISSUE THREAD

**Issue by mroch** [tc39/test262#1181]
https://github.com/tc39/test262/blob/da4b85d58d3a340250cae5422f070fbc8bd60eb5/features.txt#L71-L72

I'm reporting test failures grouped by feature (see below) and noticed that both "generator" and "generators" are valid features. Would it be ok to change one to the other?

https://github.com/facebook/flow/blob/a4df443a4a4fb5f62b86f03ee8a12a2b1432296a/src/parser/test/test262_baseline.txt#L2200-L2218

**Comment by rwaldron** [comment]
Thanks for the report. This is a bug and I will fix immediately.

**Comment by mroch** [comment]
thanks! that was fast :)

**Comment by rwaldron** [comment]
👍
