### ISSUE TITLE
`SuperCall` tests missing parens

### ISSUE THREAD

**Issue by mroch** [tc39/test262#1183]
https://github.com/tc39/test262/blob/eaffe8671cade47b1990a1b703672b3098112a1f/test/language/expressions/object/method-definition/name-super-call-body.js#L17
https://github.com/tc39/test262/blob/eaffe8671cade47b1990a1b703672b3098112a1f/test/language/expressions/object/method-definition/name-super-call-param.js#L16

`HasDirectSuper` is true when there is a `SuperCall`. `super;` is not a `SuperCall` without parens.

https://tc39.github.io/ecma262/#sec-method-definitions-static-semantics-hasdirectsuper

This makes these tests test whether `super;` is a syntax error, not whether `super()` is allowed outside of constructors.

**Comment by littledan** [comment]
Sounds like it's valuable to have both tests.
