### ISSUE TITLE
Coverage: HTML Document Dot All Exotic Object

### ISSUE THREAD

**Issue by bakkot** [tc39/test262#1184]
See https://github.com/tc39/ecma262/pull/673.

**Comment by bakkot** [comment]
This will presumably require a new host hook to provide the object, but that should be doable.

**Comment by bterlson** [comment]
Should this go in WPT rather than test262 since there is no normative 262 changes and the only usage is in browsers?

**Comment by bakkot** [comment]
There are normative changes, it's just that there's no way to see them without the host doing something. But that's also true of, for example, the DetachArrayBuffer abstract operation, which is tested here.

I guess I don't care much either way, but I don't see a principled reason to test realms and detaching array buffers but not this.

**Comment by bakkot** [comment]
> DDA is only present in browsers and is only important for compat reasons.

That describes the whole of Annex B, but it's still tested.

**Comment by bterlson** [comment]
Actually, the rest of Annex B is also present in Node (at least the vast majority).

**Comment by bakkot** [comment]
So is `document.all`:

```js
$ node --allow-natives-syntax
> typeof %GetUndetectable() === 'undefined' && %GetUndetectable() !== void 0
true
```

Anyway, Annex B is described as being "for web browsers".

**Comment by bterlson** [comment]
I'm not trying to make any claims about the spec text or normativity or whatever, just saying that it seems like a lot of work to test this from test262 for no gain since only browsers are exposed to this (node --allow-natives-syntax notwithstanding, I guess).

**Comment by bakkot** [comment]
Ah. Well, like I say, I don't feel all that strongly. It's going to get tested somewhere either way.

I'd be interested in hearing from test262 maintainers.

**Comment by littledan** [comment]
I agree with @bterlson here.

**Comment by leobalter** [comment]
the Detach Array Buffer allows checking several operations in different kinds of hosts, it's a reasonable cost for Test262. This abstraction also allow us to verify other observable parts of the specs with a detached buffer, not the actual detach operation.

For this case, a harness abstraction can be overkill for a very specific target we can - and should - get very well covered in the WPT. Tests would be very similar if not duplicates, testing the exotic object directly. I don't see enough reason to host this here as well. 

In any case, it's great to have this documented and discussed here. Thanks!
