### ISSUE TITLE
Duplicate tests for `for (let in {})`

### ISSUE THREAD

**Issue by mroch** [tc39/test262#1192]
https://github.com/tc39/test262/blob/8422147c17aa3f4061e524a8f88c251a3b371ecf/test/language/statements/let/syntax/identifier-let-allowed-as-lefthandside-expression-non-strict.js#L10

https://github.com/tc39/test262/blob/8422147c17aa3f4061e524a8f88c251a3b371ecf/test/language/statements/for-in/head-lhs-let.js#L27

these two tests are for the same thing: `let` is allowed to be an identifier in a for-in loop in non-strict mode.

**Comment by leobalter** [comment]
That's interesting. The test in the let folder (test262/test/language/statements/let) is only checking a valid syntax and not really producing a `let` statement in a lefthand side expr. in a for-in. 

I'm inclined to remove this file, and keep the other test file properly checking the name usage in the for-in. 

@mroch are you interested in sending a PR for this?

**Comment by mroch** [comment]
sure. is there anything other than deleting the file I need to do?

**Comment by rwaldron** [comment]
@leobalter https://github.com/tc39/test262/pull/1201#issuecomment-325693455
