### ISSUE TITLE
CharacterRange abstract operation tests should be phase: runtime and not phase: early

### ISSUE THREAD

**Issue by jirkamarsik** [tc39/test262#1193]
The [Early Errors rule for regular expression literals](https://tc39.github.io/ecma262/#sec-primary-expression-regular-expression-literals-static-semantics-early-errors) states that the literals must be parsed using the `Pattern` goal symbol of the regular expression grammar. This might trigger early `SyntaxError`s when the regular expression in the literal is malformed. However, there are some "malformed" regular expressions which still pass the grammar and its early errors conditions, e.g. `/[\s-\d]/u`, where the bounds of a character range are character sets, not single characters. Such expressions also lead to `SyntaxError`s, but only during the evaluation of the regular expression literal, when interpreting the pattern as a `RegExpMatcher` using the [Pattern Semantics](https://tc39.github.io/ecma262/#sec-pattern-semantics).

Therefore, I believe the tests in the following files to be incorrect as of their current state:
  * [u-invalid-non-empty-class-ranges.js](https://github.com/tc39/test262/blob/master/test/language/literals/regexp/u-invalid-non-empty-class-ranges.js)
  * [u-invalid-non-empty-class-ranges-no-dash-a.js](https://github.com/tc39/test262/blob/master/test/language/literals/regexp/u-invalid-non-empty-class-ranges-no-dash-a.js)
  * [u-invalid-non-empty-class-ranges-no-dash-b.js](https://github.com/tc39/test262/blob/master/test/language/literals/regexp/u-invalid-non-empty-class-ranges-no-dash-b.js)
  * [u-invalid-non-empty-class-ranges-no-dash-ab.js](https://github.com/tc39/test262/blob/master/test/language/literals/regexp/u-invalid-non-empty-class-ranges-no-dash-ab.js)

The phase of the `SyntaxError` should be `runtime` instead of `early` and therefore they shouldn't be prefixed with the throw statements. The RegExp validation is performed in [Runtime Semantics: Character Range](https://tc39.github.io/ecma262/#sec-runtime-semantics-characterrange-abstract-operation) and not in Static Semantics.

NB: In ES5.1, `SyntaxError`s thrown by the runtime semantics of constructing a `RegExp` object [actually did cause early errors](https://www.ecma-international.org/ecma-262/5.1/#sec-7.8.5), but this behaviour disappeared from the spec in ES6.

NB2: These tests contradict the test [built-ins/RegExp/property-escapes/character-class.js)](https://github.com/tc39/test262/blob/master/test/built-ins/RegExp/property-escapes/character-class.js), in which the regular expression literal `/[\p{Hex}-\uFFFF]/u` is expected to throw a `SyntaxError` at runtime.

**Comment by jirkamarsik** [comment]
The same issue now also manifests in [built-ins/RegExp/property-escapes/character-class.js](https://github.com/tc39/test262/blob/master/test/built-ins/RegExp/property-escapes/character-class.js) (as of commit [e44d737](https://github.com/tc39/test262/commit/e44d73733bd93ed2bc85801f55c8a8fefd1ee072)). The abstract operation [CharacterRange](https://tc39.github.io/ecma262/#sec-runtime-semantics-characterrange-abstract-operation) should throw `SyntaxError`s at runtime (during RegExp literal evaluation) and not earlier.

**Comment by leobalter** [comment]
Thanks for the raising these issues!

This topic is not really in my best field of experience, I might need some feedback from @anba, @jugglinmike, or @mathiasbynens here.

In any case, PRs are most welcome!

**Comment by anba** [comment]
Spec PR to change RegExps per web-reality, i.e. throw when invalid ranges are present, is up at https://github.com/tc39/ecma262/pull/984

**Comment by jirkamarsik** [comment]
@anba, yes, moving the `SyntaxError`s out of the runtime of `RexExpCreate` and putting them directly into the grammar (as in your PR) seems a lot cleaner. Thanks!

**Comment by jirkamarsik** [comment]
OK, the spec has been changed upstream, so I am closing this issue.
https://github.com/tc39/ecma262/pull/984
