### ISSUE TITLE
INTERPRETING.md doesn't mention how to handle async+negative tests

### ISSUE THREAD

**Issue by anba** [tc39/test262#1229]
https://github.com/tc39/test262/blob/765f273ac41ea2927cf00ae1812795683015117a/test/language/statements/for-await-of/async-func-decl-dstr-array-elem-init-yield-ident-invalid.js#L8-L11

According to the current rules in INTERPRETING.md, this file (and the six other files async+negative) can never pass, because it must throw an early SyntaxError and also print the string `Test262:AsyncTestComplete`.

**Comment by rwaldron** [comment]
You're right, there is no existing explanation for that, however I believe there is no test that can be written that would actually need that combination of INTERPRETING.md flag semantics: "execution" is a runtime concept, and negative early SyntaxError tests are expected to failure before execution ever occurs. I think we just need to remove the async flag from these templates/cases (as long as none of the tests they produce are testing runtime semantics)
