### ISSUE TITLE
Feature tag generator code

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1232]
Lots of test files with generator code are not feature tagged. e.g. `language/expressions/yield`.

**Comment by thejoshwolfe** [comment]
FYI, i've experimented with creating a tool that can edit the yaml frontmatter of tests.

https://github.com/thejoshwolfe/test262/tree/frontmatter/tools/frontmatter

The tool is a long way from ready-to-go, but it's looking promising so far. I solved some of the "hard" problems, like how to edit just one field of the top-level yaml dictionary without clobbering the formatting of the `info` field.

It still needs work wrt tolerating windows line endings, and, of course, it's only the part of the puzzle that edits frontmatter, not the part that detects actual features in the JavaScript test. Right now it just verifies that the `harness/features.yml` dependencies are being included properly, which is redundant with the linter that already exists.

**Comment by rwaldron** [comment]
There are currently no files in that directory that are missing the `generators` feature.
