### ISSUE TITLE
Add coverage for proposal trimStart/trimEnd

### ISSUE THREAD

**Issue by spectranaut** [tc39/test262#1237]
This is a check list for coverage of the trimStart/trimEnd propsal:
https://github.com/tc39/proposal-string-left-right-trim

## trimStart
- esid: sec-string.prototype.trimstart
- [x] *length.js* function length
- [x] *name.js* function name
- [x] *prop-desc.js* property descriptor
- TrimString
  - RequireObjectCoercible
    - [x] *this-value-not-obj-coercible.js* TypeError if `this` is undefined
    - [x] *this-value-not-obj-coercible.js* TypeError if `this` is null
  - ToString
    - [x] *this-value-boolean-true.js* Return "true" if `this` is type Boolean true
    - [x] *this-value-boolean-false.js* Return "false" if `this` is type Boolean false
    - [x] *this-value-symbol.js* TypeError if `this` is Symbol
    - ToPrimitive
      - [x] Abrupt complete if get attribute Symbol.toPrimitive abrupt completes
      - [x] Abrupt complete if Symbol.toPrimitive abrupt completes
      - [x] "Symbol.toPrimitive" is always called before "toString" and "valueOf"
      - [x] TypeError if Symbol.toPrimitive returns a object
      - OrdinaryToPrimitive
        - [x] "toString" is always called before "valueOf" 
        - [x] "valueOf" used in case of nothing else
        - [x] TypeError if "Symbol.toPrimitive", "toString", and "valueOf" not defined
        - [x] TypeError if "toString" returns object
        - [x] TypeError if "valueOf" returns object
        - [x] Abrupt complete if toString abrupt completes
        - [x] Abrupt complete if valueOf abrupt completes
        - [x] Abrupt complete if get attribute toString abrupt completes
        - [x] Abrupt complete if get attribute valueOf abrupt completes 
    - NumberToString
      - [x] *this-value-number-nan.js* Given NaN, return "NaN"
      - [x] *this-value-number-infinity.js* Given Infinity, return "Infinity"
      - [x] *this-value-number-negative0.js* Given -0, return "-0"
      - [x] *this-value-number-1.js* Given 1, return "1"
- [x] Given a string with any whitespace and line terminantors at index 0, return a string without them

## trimEnd

- esid: sec-string.prototype.trimend
- [x] *length.js* function length
- [x] *name.js* function name
- [x] *prop-desc.js* property descriptor
- TrimString
  - RequireObjectCoercible
    - [x] *this-value-not-obj-coercible.js* TypeError if `this` is undefined
    - [x] *this-value-not-obj-coercible.js* TypeError if `this` is null
  - ToString
    - [x] *this-value-boolean-true.js* Return "true" if `this` is type Boolean true
    - [x] *this-value-boolean-false.js* Return "false" if `this` is type Boolean false
    - [x] *this-value-symbol.js* TypeError if `this` is Symbol
    - ToPrimitive
      - [x] Abrupt complete if get attribute Symbol.toPrimitive abrupt completes
      - [x] Abrupt complete if Symbol.toPrimitive abrupt completes
      - [x] "Symbol.toPrimitive" is always called before "toString" and "valueOf"
      - [x] TypeError if Symbol.toPrimitive returns a object
      - OrdinaryToPrimitive
        - [x] "toString" is always called before "valueOf" 
        - [x] "valueOf" used in case of nothing else
        - [x] TypeError if "Symbol.toPrimitive", "toString", and "valueOf" not defined
        - [x] TypeError if "toString" returns object
        - [x] TypeError if "valueOf" returns object
        - [x] Abrupt complete if toString abrupt completes
        - [x] Abrupt complete if valueOf abrupt completes
        - [x] Abrupt complete if get attribute toString abrupt completes
        - [x] Abrupt complete if get attribute valueOf abrupt completes 
    - NumberToString
      - [x] *this-value-number-nan.js* Given NaN, return "NaN"
      - [x] *this-value-number-infinity.js* Given Infinity, return "Infinity"
      - [x] *this-value-number-negative0.js* Given -0, return "-0"
      - [x] *this-value-number-1.js* Given 1, return "1"
- [x] Given a string with any whitespace and line terminantors at the last indexed location, return a string without them

## trimRight
- esid: #sec-string.prototype.trimright
  - [ ] *length.js* function length
  - [ ] *name.js* function name
  - [ ] *prop-desc.js* property descriptor
  - [ ] reference to trimRight the same as reference to trimEnd

## trimLeft
- esid: sec-string.prototype.trimleft
  - [ ] *length.js* function length
  - [ ] *name.js* function name
  - [ ] *prop-desc.js* property descriptor
  - [ ] reference to trimLeft the same as reference to trimStart

**Comment by leobalter** [comment]
Tests are covered
