### ISSUE TITLE
typeCoercion.js includes BigInt literal without "features: [BigInt]"

### ISSUE THREAD

**Issue by Constellation** [tc39/test262#1252]
New `typeCoercion.js` includes BigInt literal like `0n`. And it causes some test failures like `test262/test/built-ins/String/prototype/indexOf/position-tointeger.js` if VM does not support BigInt literal.
But `test262/test/built-ins/String/prototype/indexOf/position-tointeger.js` is essentially unrelated to BigInt.

Since BigInt is new feature, and since `typeCoercion.js` is not marked with `features: [BigInt]`, `BigInt(0)` is better way.

**Comment by leobalter** [comment]
Harness files are not required to contain any frontmatter, and for that we don't expect runners to parse harness files for features tags, those should be used on the tests files including them, as the one you mentioned has the features tag for BigInt, already.

The features.yml includes features requirements for includes. Our built-in linter tool will confirm every test including typeCoercion.js has the features BigInt included.

We might need to revisit this, but for now this is the best we have.
