### ISSUE TITLE
Is tools/lint/requirements.txt redundant?

### ISSUE THREAD

**Issue by foolip** [tc39/test262#1285]
It's identical to tools/generation/requirements.txt, which is what .travis.yml references. That is also the only place that "requirements.txt" appears in the repo, so at least no tooling cares about tools/lint/requirements.txt.

**Comment by leobalter** [comment]
if you browse the tools folder you might find way more things that are irrelevant.

While it feels like a duplicate, both files allow the generation and tools to be treated as separate individual tools. They have different goals and might even be extracted or moved to separate repos if ever necessary.

It doesn't hurt.

Maybe travis should handle both differently? @jugglinmike WDYT?

**Comment by jugglinmike** [comment]
I share @foolip's mistrust of duplication, but I also agree with @leobalter's assessment about separation. Being explicit in this way might seem silly today, but it sets a precedent for any future changes that is probably more hygienic overall.

I've submitted gh-1363 to help solidify this practice.

(Sorry for the delayed response--this thread got lost among many others in my inbox.)

**Comment by foolip** [comment]
https://github.com/tc39/test262/pull/1363 fixes this for me, thanks @jugglinmike!
