### ISSUE TITLE
Replace the python packager with a node module

### ISSUE THREAD

**Issue by smikes** [tc39/test262#130]
Right now I don't believe it's even documented anywhere how to use the `packager.py` script to build the test262 website.

(For the record, it's

```
$ cd tools/packaging
$ python packager.py VERSION
```

)

What's more, the website hasn't been rebuilt for >1 year.

I propose to replace the current python script(s) with a new npm module that can be used in place of packager.py ..  once packager is gone, all the python code can be removed.

I would initially implement `test262-packager` as a byte-compatible port of packager (warts and all).  Once that's written and tested, we can land it as a dependency of test262 and then the future will involve refactoring and rewriting to get a more modern website generator that generates a more modern website.  Without, perhaps, quite so much base64-encoding. ;-)

Thoughts, comments, objections?

**Comment by leobalter** [comment]
This can't be really fixed for now, or until we re-create the website.
