### ISSUE TITLE
uncallableAndIsHTMLDDA should be callable

### ISSUE THREAD

**Issue by bakkot** [tc39/test262#1304]
At least, as I understand it, it's important that `document.all` be able to fill the contract of `uncallableAndIsHTMLDDA`. (If nothing else because the spec says hosts should not create any objects with the `[[IsHTMLDDA]]` slot except for `document.all`.

But [per the WHATWG spec](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#HTMLAllCollection-call), `document.all` when called with no arguments does *not* throw a type error - it just returns null. So it _can't_ fulfill the "for which Call(obj, any value, «») throws a TypeError." part of the contract of `uncallableAndIsHTMLDDA`.

This might require rewriting parts of #1287 and #1299, unfortunately. Sorry for not catching this before that landed. (Downsides of this sort of cross-spec test...)

cc @jswalden

**Comment by jswalden** [comment]
Yeah.  I'm writing up a comment describing what we need for this stuff (possibly two separate functions :-( ), sec.

**Comment by jswalden** [comment]
So the value returned by `$262.uncallableAndIsHTMLDDA` is currently specified to be something that, when called with no arguments, throws a `TypeError`.  That's not what the three tests that use it, actually need.

### [yield*](https://github.com/tc39/test262/blob/23bc183bb8e7c33a35d54a92794423bdf9cfe4ce/test/annexB/language/expressions/yield/star-iterable-return-emulates-undefined-throws-when-called.js) ###

The steps after the `return` property is gotten as `return` are:

1. Let `innerReturnResult` be `? Call(return, iterator, « received.[[Value]] »)`.
1. If `Type(innerReturnResult)` is not Object, throw a `TypeError` exception.

It's easy to make `document.all` invoked with one argument return `null` and thus throw that `TypeError`: make the argument `""`.  So we can make the argument `""` to fix the test to work with `document.all` there.

### [`IteratorClose`](https://tc39.github.io/ecma262/#sec-iteratorclose) ###

The steps after the `return` property is gotten as `return` are:

1. Let `innerResult` be `Call(return, iterator, « »)`.
1. If `completion.[[Type]]` is `throw`, return `Completion(completion)`.
1. If `innerResult.[[Type]]` is `throw`, return `Completion(innerResult)`.
1. If `Type(innerResult.[[Value]])` is not Object, throw a `TypeError` exception.

Calling `document.all` with no arguments [returns `null`](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#HTMLAllCollection-call), passing by the completion-test steps will throw a `TypeError`.

### [`@@asyncIterator` lookup](https://tc39.github.io/proposal-async-iteration/#sec-getiterator) ###

The steps after the `@@asyncIterator` property is gotten as `method` are:

1. Let `iterator` be `? Call(method, obj)`.
1. If `Type(iterator)` is not Object, throw a `TypeError` exception.

Again, calling `document.all` with no arguments returns `null`, triggering the `TypeError` throw.

So what do we need?  It appears that having `$262.uncallableAndIsHTMLDDA` return an object that is

1. callable,
1. (optional, ideally) has an [[IsHTMLDDA]] internal slot, and
1. when called with no arguments or with `""` as the sole argument, returns a non-object

covers all three cases, and is satisfied, with the smallest possible set of requirements.

I'll let everyone think about a better name in parallel by cutting off this comment here.  Maybe `fakeDocumentAll` or something that suggests the idea without enumerating all of these unwieldy requirements.

**Comment by bakkot** [comment]
Personally, I'd be happiest to just say the API returns "the HTML `document.all` object", and have hosts which don't expose that skip those tests in the same way they might skip any other test which relies on an unsupported feature. It's far simpler, and, well, we all know that's what it's meant to be testing anyway; I don't see a reason to describe its requirements rather than just naming it.

**Comment by bakkot** [comment]
Fixed by #1305.
