### ISSUE TITLE
Broken error message in test

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/test262#1355]
Found [this test](https://github.com/tc39/test262/blob/master/test/language/statements/switch/S12.11_A1_T4.js), which [throws its error with the wrong value](https://github.com/tc39/test262/blob/master/test/language/statements/switch/S12.11_A1_T4.js#L46) on failure.

**Comment by leobalter** [comment]
why is it wrong? The test is poorly written, but it still sounds as valid.

```js
eval('Number(false)') // evaluates to 0;

SwitchTest(eval('Number(false)') // is basically the same as:

SwitchTest(0); should return 6

// as:
function SwitchTest(value){
  var result = 0;

  switch(value) {
    case 0:
      result += 2;
    case 1:
      result += 4;
      break;
    /* ... */
  }

  return result;
}
``` 

So `SwitchTest(eval('Number(false)')) === 6` should be true...

In any case, this whole test is poorly written and the respective coverage deserves a nice refactoring.

**Comment by isiahmeadows** [comment]
@leobalter 

> why is it wrong? The test is poorly written, but it still sounds as valid.

The issue isn't that it throws incorrectly. It's that the error message itself appears erroneous. (You more or less agreed with me on this, just without realizing it.)

**Comment by leobalter** [comment]
Oh I see! (I think)

Are you interested in sending a patch to fix it?

**Comment by isiahmeadows** [comment]
@leobalter [Sure!](https://github.com/tc39/test262/pull/1358)
