### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/test262#136]
<https://github.com/tc39/test262/blob/master/CONTRIBUTING.md#test-case-names> still says:

> Test cases are often named by the portion of the spec or draft spec they reference.  A test for ECMAScript 5.1 section [8.7.2 PutValue](http://www.ecma-international.org/ecma-262/5.1/#sec-8.7.2) should be placed in the directory `test262/suite/ch08/8.7/8.7.2/` and have a filename which contains the substring `8.7.2`.  A test for ECMAScript 6.0 draft section [25.4.4.1 Promise.all](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise.all) should be placed in directory `test262/suite/es6/ch25/25.4/25.4.4/25.4.4.1` and have a filename that contains the substring `25.4.4.1`.

This doesn’t seem to be true anymore. Can the contribution guide be updated?

**Comment by smikes** [comment]
This is fixed in pending PR #151 -- @mathiasbynens , is that right?

**Comment by mathiasbynens** [comment]
Yep.
