### ISSUE TITLE
Incorrect build for /language/function-code/switch-dflt-decl-strict.js

### ISSUE THREAD

**Issue by qfox** [tc39/test262#1364]
The file in [test/language/function-code/switch-dflt-decl-strict.js](https://github.com/tc39/test262/tree/master/test/language/function-code/switch-dflt-decl-strict.js) is missing half its headers and incorrect has `[onlyStrict]`, which leads to false positives. The source file [src/annex-b-fns/func/switch-dflt.template](https://github.com/tc39/test262/tree/master/src/annex-b-fns/func/switch-dflt.template) correctly has the `[noStrict]` tag and I'm not sure where it sheds this (I'm not a py dev).

If that is the wrong source file then I'm not sure which is but the output is wrong regardless as this is a func statement inside a default statement is a syntax error in strict mode.

I think there may be multiple such problems with this template. I didn't see a related issue filed when quickly going through the open list.

**Comment by rwaldron** [comment]
> The source file src/annex-b-fns/func/switch-dflt.template correctly has the [noStrict]

https://github.com/tc39/test262/blob/master/test/language/function-code/switch-dflt-decl-strict.js isn't generated from source. 

I'm going to look at the rest of these.
