### ISSUE TITLE
Negative tests for complex rest properties are missing

### ISSUE THREAD

**Issue by adrianheine** [tc39/test262#1365]
As I pointed out in https://github.com/tc39/test262/issues/865#issuecomment-343862188. @rwaldron originally promised those in https://github.com/tc39/test262/issues/1050#issuecomment-303495480.

**Comment by rwaldron** [comment]
I've re-read through all of the issues and PRs from 2017, and looked through existing test coverage and I'm not sure what's missing. We won't be adding tests for arbitrary invalid syntax, unless the spec explicitly calls out a syntax error.

**Comment by adrianheine** [comment]
Ok :)
