### ISSUE TITLE
Which specification do the test names refer to?

### ISSUE THREAD

**Issue by realisation** [tc39/test262#1368]
I'm trying to find the specification the test names refer to so I can include the tests pertinent to my project, but the current specification here https://tc39.github.io/ecma262/#sec-fundamental-objects does not map to the file names. 

Where can those be found?

**Comment by caitp** [comment]
Likely http://www.ecma-international.org/ecma-262/5.1/, but really it depends on when the test was checked in, and if it’s been updated to new conventions or not

**Comment by realisation** [comment]
Ah, looks like there is no entirely reliable source of truth here. I'm
gonna poke around on this tomorrow morning so I'll report my findings

**Comment by jugglinmike** [comment]
In case it helps, we're no longer using that naming convention. From the
project contribution guidelines:

> **Note** The project is currently transitioning from a naming system based on
> specification section numbers. There remains a substantial number of tests
> that conform to this outdated convention; contributors should ignore that
> approach when introducing new tests and instead encode this information using
> the id frontmatter tag.

**Comment by jugglinmike** [comment]
Whoops! It looks like that documentation is out of date. It should refer to a frontmatter tag named `esid`, not `id`. [A fix is on the way.](https://github.com/tc39/test262/pull/1374)
