### ISSUE TITLE
Coverage area: document.all

### ISSUE THREAD

**Issue by littledan** [tc39/test262#1372]
V8's test262 test harness doesn't yet expose anything for document.all-like objects. The only test262 tests I see failing due to that omission are related to iteration. I would've expected there to be some additional tests failing, such as ensuring that the document.all-like object will be `===` to neither `null` nor `undefined` (which would fail for us, as it is just `undefined`). There's a bunch of places in the spec where SameValue(undefined) comes up; a few more of these could be tested.

**Comment by bakkot** [comment]
See previously at #1184, at which I believe the consensus was that those tests belong in the web platform tests. (Actually, I see you commented in that thread agreeing with that, if I'm reading it correctly, so now I'm confused.)

**Comment by littledan** [comment]
I'm confused too--why is are there tests like this checked in? https://github.com/tc39/test262/blob/master/test/annexB/language/expressions/yield/star-iterable-return-emulates-undefined-throws-when-called.js#L13

**Comment by littledan** [comment]
About my previous comment: I'd be OK either way on the question, really. Now that I see it wouldn't be much work to expose in V8, and also that the document.all semantics question comes up in a big way for things like the optional chaining operator, I could see the case for having good test262 tests.

**Comment by bakkot** [comment]
> I'm confused too--why is are there tests like this checked in? 

See discussion in #1287, but briefly, if I recall correctly, it's because they're mostly testing ES algorithms which don't directly reference `document.all`, rather than testing `document.all` per se.

**Comment by rwaldron** [comment]
@jswalden ping

**Comment by jswalden** [comment]
I'm not entirely certain what's being asked here.  If the question is why that test's checked in, https://github.com/tc39/test262/issues/1372#issuecomment-350346621 is right.  Submitting such test in w-p-t would result in someone there having to learn a bunch of very silly ECMA goo well beyond their usual ambit, and squarely in TC39's wheelhouse and competencies.

I do think we could have more testing of places that do Type(x) is Undefined or SameValue(x, `undefined`).  (The latter is less common, I think.)  We should be sure to have tests that throw `[[IsHTMLDDA]]` objects at those places, that would suss out mis-implementation by loose-equality comparison to `undefined`.  I wouldn't make it a super-high priority, but it looks like this issue just flags it as a concern and nothing more.

**Comment by gsnedders** [comment]
https://github.com/web-platform-tests/wpt/blob/master/html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/document-all.html already has tests in WPT for this (and has since 2015), predating TC39 specifying [[IsHTMLDDA]].
