### ISSUE TITLE
Several test262 bugs

### ISSUE THREAD

**Issue by rrexx** [tc39/test262#143]
After running test262 on a new interpreter for the last few weeks, i've collected a list of what i think are bugs in the unit tests. I was mistaken about earlier bugs because i was unaware of changes to ES6 prototypes. In the end i was pleasantly surprised by how few genuine bugs i found.

The following test for timezone specific values, probably PST. They fail in Firefox ...
test/built-ins/Date/S15.9.3.1_A5_T1.js
test/built-ins/Date/S15.9.3.1_A5_T2.js
test/built-ins/Date/S15.9.3.1_A5_T3.js
test/built-ins/Date/S15.9.3.1_A5_T4.js
test/built-ins/Date/S15.9.3.1_A5_T5.js
test/built-ins/Date/S15.9.3.1_A5_T6.js

In the following test, y should have been initialized with an array, not NaN. The test gives false positives when pow() is called.
test/built-ins/Math/pow/S15.8.2.13_A23.js
y = NaN; y[0] = -Math.PI; y[1] = -Math.E; ...

In the following tests, getPrototypeOf should return the prototype of the constructor. These tests expect the constructor to return the .prototype not .__proto__. I dont think this is related to the prototype [[class]] change in ES6. The tests fail in Firefox.
test/built-ins/Object/getPrototypeOf/15.2.3.2-2-12.js
test/built-ins/Object/getPrototypeOf/15.2.3.2-2-13.js
test/built-ins/Object/getPrototypeOf/15.2.3.2-2-14.js
test/built-ins/Object/getPrototypeOf/15.2.3.2-2-15.js
test/built-ins/Object/getPrototypeOf/15.2.3.2-2-16.js
test/built-ins/Object/getPrototypeOf/15.2.3.2-2-17.js
test/built-ins/Object/getPrototypeOf/15.2.3.2-2-18.js

The following test successfully deletes Array.length but then expects Array.length not to be undefined. Fails in Firefox
test/built-ins/Array/S15.4.3_A2.2.js

The following test has an unexpected space in the unicode string. Firefox says the length is 4 not 2
test/language/source-text/6.1.js

The for-in tests currently don't test for an expression on the left hand side, only for a simple variable.

We had some harness problems that prevented running several hundred tests, so i might find more bugs in the next few weeks. I suspect some tests don't contain valid harness directives.

**Comment by anba** [comment]
> The following test for timezone specific values, probably PST. They fail in Firefox ...
> test/built-ins/Date/S15.9.3.1_A5_T1.js
> test/built-ins/Date/S15.9.3.1_A5_T2.js
> test/built-ins/Date/S15.9.3.1_A5_T3.js
> test/built-ins/Date/S15.9.3.1_A5_T4.js
> test/built-ins/Date/S15.9.3.1_A5_T5.js
> test/built-ins/Date/S15.9.3.1_A5_T6.js

Confirmed. Related discussion on [test262-discuss](
https://mail.mozilla.org/pipermail/test262-discuss/2012-September/000125.html) and [bug report](https://bugs.ecmascript.org/show_bug.cgi?id=293) in the old bug tracker.

> In the following test, y should have been initialized with an array, not NaN. The test gives false positives when pow() is called.
> test/built-ins/Math/pow/S15.8.2.13_A23.js
> y = NaN; y[0] = -Math.PI; y[1] = -Math.E; ...

Yes, that initialization doesn't really make sense.


> 
> In the following tests, getPrototypeOf should return the prototype of the constructor. These tests expect the constructor to return the .prototype not .proto. I dont think this is related to the prototype [[class]] change in ES6. The tests fail in Firefox.
> test/built-ins/Object/getPrototypeOf/15.2.3.2-2-12.js
> test/built-ins/Object/getPrototypeOf/15.2.3.2-2-13.js
> test/built-ins/Object/getPrototypeOf/15.2.3.2-2-14.js
> test/built-ins/Object/getPrototypeOf/15.2.3.2-2-15.js
> test/built-ins/Object/getPrototypeOf/15.2.3.2-2-16.js
> test/built-ins/Object/getPrototypeOf/15.2.3.2-2-17.js
> test/built-ins/Object/getPrototypeOf/15.2.3.2-2-18.js

15.2.3.2-2.{12-17} are a breaking change in ES6, _NativeError_ constructors now inherit from `Error`. Filed https://bugs.ecmascript.org/show_bug.cgi?id=3514 to document this change in [Annex E](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-additions-and-changes-that-introduce-incompatibilities-with-prior-editions). 
15.2.3.2-2-18 should work the same in ES5 and ES6, the [[Prototype]] of the `JSON` object didn't change in ES6.


> The following test successfully deletes Array.length but then expects Array.length not to be undefined. Fails in Firefox
> test/built-ins/Array/S15.4.3_A2.2.js

That's another ES6 change, the `length` property of function instances is now configurable. After it has been deleted, `Array.length` will now resolve to the `length` property on `Function.prototype`. Tricky! :smile: 

> The following test has an unexpected space in the unicode string. Firefox says the length is 4 not 2
> test/language/source-text/6.1.js

That's not a space character (`A0`) but part of the UTF-8 encoding (`F0 90 92 A0`). Depending on how you open the test files, you may need to explicitly set the encoding to UTF-8.

**Comment by rrexx** [comment]
Hi anba, thanks for replying. I hate to argue with you :) but i disagree on a few points.

Regarding the seven getPrototypeOf tests ...

These all look something like ...
Object.getPrototypeOf(TypeError) === Error

However, TypeError is a constructor, and so its prototype is the Function prototype ...
Object.getPrototypeOf(TypeError) === Function.____proto____ (correct in Firefox)

Whoever wrote these tests misunderstood what getPrototypeOf does. It returns the ____proto____ of an instance. It doesnt return the .prototype of the constructor ...
Object.getPrototypeOf(TypeError) !== TypeError.prototype

Sure i may be wrong, but i cannot conceive any way these tests could be correct.

And regarding language/source-text/6.1.js ... that JavaScript file doesnt contain a byte order mark. The W3C standard says that if it doesnt have a BOM, then it is ISO 8859-1. This test will fail in a browser unless the harness explicitly specifies charset=utf-8 in the script tag, which isnt needed for any of the other tests i've run yet. This should probably at least be mentioned in the test comments for that file. I just assumed the file had a BOM.

**Comment by anba** [comment]
> Regarding the seven getPrototypeOf tests ...
> 
> These all look something like ...
> Object.getPrototypeOf(TypeError) === Error
> 
> However, TypeError is a constructor, and so its prototype is the Function prototype ...

The [[Prototype]] of `TypeError` is no longer `Function.prototype`, it has been changed to `Error`:

From ES6 [19.5.6.2  Properties of the NativeError Constructors](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-properties-of-the-nativeerror-constructors)

> The value of the [[Prototype]] internal slot of a NativeError constructor is the Error constructor object (19.5.1).

And previously in ES5 [15.11.7.5 Properties of the NativeError Constructors](http://ecma-international.org/ecma-262/5.1/#sec-15.11.7.5)
> The value of the [[Prototype]] internal property of a NativeError constructor is the Function prototype object (15.3.4).

---

> And regarding language/source-text/6.1.js ... that JavaScript file doesnt contain a byte order mark. The W3C standard says that if it doesnt have a BOM, then it is ISO 8859-1. This test will fail in a browser unless the harness explicitly specifies charset=utf-8 in the script tag, which isnt needed for any of the other tests i've run yet. This should probably at least be mentioned in the test comments for that file. I just assumed the file had a BOM.

I don't think W3C standards are relevant in this case, for example the Unicode Consortium recommends to omit BOM in UTF-8 documents. Having said that the default encoding still needs to be documenting in the CONTRIBUTING.md file, just like the default timezone and any other currently undocumented default...

**Comment by anba** [comment]
> We'll be relying heavily on test262 this year and will let you know if we find any other bugs that are not caused by our failure to read the ES6 spec properly. Maybe later we can contribute some tests for features that are not being tested yet.

Sounds great and test contributions are always welcome! :smile:

**Comment by bterlson** [comment]
I think this is closed now but @rrexx please let us know if you find issues!
