### ISSUE TITLE
ES6-specific tests with an es5id?

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#144]
eg. 

test/built-ins/Array/from/S22.1.2.1_T1.js

```js
/*---
es5id: 22.1.2.1_T1
description: Testing Array.from when passed a String
author: Hank Yates (hankyates@gmail.com)
includes: [runTestCase.js]
---*/
```

But that can't possibly map to an valid es5 section, because there is no "22" and obviously no "Array.from". I read through https://github.com/tc39/test262/pull/51 and didn't see anything that answered my question. Need advice! Thanks!

**Comment by rwaldron** [comment]
cc @jugglinmike

**Comment by smikes** [comment]
My guess: artifact from automatic conversion setting "es5id" from test name before tests were named with words instead of sections. 

Can't run "git blame" from here (ski hill) but you could probably verify that. Fix is es5id->es6id

**Comment by bterlson** [comment]
Agree, looks like an artifact. Should be es6id.

**Comment by rwaldron** [comment]
Great! Thanks for the follow up. I will make a pass at updating all of these

**Comment by rwaldron** [comment]
Ok, digging in and noticing that not all ES6-specific files have a `es6id` or `es5id`. Should they?

**Comment by smikes** [comment]
>  noticing that not all ES6-specific files have a es6id or es5id. Should they?

Yes, but that was decided after the frontmatter was rewritten and after the names were changed.  The current plan is to update the `es?id` frontmatter as tests are created/updated, with maybe a cleanup pass before the tests are pushed live to the website.

PRs very welcome of course.

**Comment by rwaldron** [comment]
Excellent! I did this yesterday :)

**Comment by smikes** [comment]
Looks good!

You may be interested in the related bikesheds #107, #109, #111 where the `features` frontmatter element is informally specified.

**Comment by rwaldron** [comment]
I'm going to do a final pass through all the files to see if I missed anything, then PR.

I'll take a look at the links you posted—thanks!
