### ISSUE TITLE
> 100 tests failures introduced after f95b56ab28c5f18150f30fbfa889a4f6ba0e50a1

### ISSUE THREAD

**Issue by anba** [tc39/test262#1447]
NOTE: I've haven't verified all failures are genuine test failures.

[test/built-ins/Object/setPrototypeOf/bigint.js]

SyntaxError: unexpected token "<name>", expected ")" instead (line 16, column 53)

[test/built-ins/TypedArray/prototype/fill/BigInt/fill-values-conversion-operations.js]

ReferenceError: cannot resolve reference: "testTypedArrayConversions"

[test/built-ins/TypedArray/prototype/filter/BigInt/speciesctor-get-species-custom-ctor-returns-another-instance.js]

TypeError: element types are not compatible (Testing with BigInt64Array.)

[test/built-ins/TypedArray/prototype/map/BigInt/return-new-typedarray-conversion-operation.js]

ReferenceError: cannot resolve reference: "testTypedArrayConversions"

[test/built-ins/TypedArray/prototype/set/BigInt/array-arg-src-tonumber-value-conversions.js]

ReferenceError: cannot resolve reference: "testTypedArrayConversions"

[test/built-ins/TypedArray/prototype/set/BigInt/typedarray-arg-set-values-diff-buffer-other-type-conversions-sab.js]

ReferenceError: cannot resolve reference: "testTypedArrayConversions"

[test/built-ins/TypedArray/prototype/set/BigInt/typedarray-arg-set-values-diff-buffer-other-type-conversions.js]

ReferenceError: cannot resolve reference: "testTypedArrayConversions"

[test/built-ins/TypedArray/prototype/slice/BigInt/detached-buffer-zero-count-custom-ctor-other-targettype.js]

TypeError: element types are not compatible (Testing with BigInt64Array.)

[test/built-ins/TypedArray/prototype/slice/BigInt/speciesctor-get-species-custom-ctor-returns-another-instance.js]

TypeError: element types are not compatible (Testing with BigInt64Array.)

[test/built-ins/TypedArray/prototype/subarray/BigInt/speciesctor-get-species-custom-ctor-returns-another-instance.js]

TypeError: element types are not compatible (Testing with BigInt64Array.)

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/bufferbyteoffset-throws-from-modulo-element-size-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/bufferbyteoffset-throws-from-modulo-element-size.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-is-negative-throws-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-is-negative-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-is-negative-zero-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-is-negative-zero.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-is-symbol-throws-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-is-symbol-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-throws-from-modulo-element-size-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-throws-from-modulo-element-size.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-to-number-detachbuffer.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-to-number-throws-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/byteoffset-to-number-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/custom-proto-access-throws-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/custom-proto-access-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/defined-length-and-offset-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/defined-length-and-offset.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/defined-length-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/defined-length.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/defined-negative-length-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/defined-negative-length.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/defined-offset-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/defined-offset.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/detachedbuffer.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/excessive-length-throws-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/excessive-length-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/excessive-offset-throws-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/excessive-offset-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/invoked-with-undefined-newtarget-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/invoked-with-undefined-newtarget.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/is-referenced-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/is-referenced.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/length-access-throws-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/length-access-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/length-is-symbol-throws-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/length-is-symbol-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/length-to-number-detachbuffer.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/new-instance-extensibility-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/new-instance-extensibility.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/proto-from-ctor-realm-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/proto-from-ctor-realm.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/returns-new-instance-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/returns-new-instance.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/toindex-bytelength-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/toindex-bytelength.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/toindex-byteoffset-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/toindex-byteoffset.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/typedarray-backed-by-sharedarraybuffer.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/use-custom-proto-if-object-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/use-custom-proto-if-object.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/use-default-proto-if-custom-proto-is-not-object-sab.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/buffer-arg/use-default-proto-if-custom-proto-is-not-object.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/custom-proto-access-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/init-zeros.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/is-infinity-throws-rangeerror.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/is-negative-integer-throws-rangeerror.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/is-symbol-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/new-instance-extensibility.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/proto-from-ctor-realm.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/returns-object.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/toindex-length.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/undefined-newtarget-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/use-custom-proto-if-object.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/length-arg/use-default-proto-if-custom-proto-is-not-object.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/no-args/custom-proto-access-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/no-args/new-instance-extensibility.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/no-args/proto-from-ctor-realm.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/no-args/returns-object.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/no-args/undefined-newtarget-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/no-args/use-custom-proto-if-object.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/no-args/use-default-proto-if-custom-proto-is-not-object.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-as-array-returns.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-as-generator-iterable-returns.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-conversion-operation-consistent-nan.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-conversion-operation.js]

ReferenceError: cannot resolve reference: "testTypedArrayConversions"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-custom-proto-access-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-iterating-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-iterator-not-callable-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-iterator-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-length-excessive-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-length-is-symbol-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-length-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-new-instance-extensibility.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-proto-from-ctor-realm.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-throws-from-property.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-throws-setting-obj-to-primitive-typeerror.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-throws-setting-obj-to-primitive.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-throws-setting-obj-tostring.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-throws-setting-obj-valueof-typeerror.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-throws-setting-obj-valueof.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-throws-setting-property.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-throws-setting-symbol-property.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-undefined-newtarget-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-use-custom-proto-if-object.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/object-arg/object-arg-use-default-proto-if-custom-proto-is-not-object.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-custom-proto-access-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-detached-when-species-retrieved-different-type.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-detached-when-species-retrieved-same-type.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-new-instance-extensibility.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-access-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-custom-species-proto-from-ctor-realm.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-custom-species.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-not-object-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-species-access-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-species-not-ctor-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-species-null.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-species-prototype-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-species-undefined.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-returns-new-typedarray.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-proto-from-ctor-realm.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-same-ctor-buffer-ctor-access-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-same-ctor-buffer-ctor-species-custom-proto-from-ctor-realm.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-same-ctor-buffer-ctor-species-custom.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-same-ctor-buffer-ctor-species-not-ctor.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-same-ctor-buffer-ctor-species-null.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-same-ctor-buffer-ctor-species-prototype-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-same-ctor-buffer-ctor-species-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-same-ctor-buffer-ctor-species-undefined.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-same-ctor-buffer-ctor-value-not-obj-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-same-ctor-returns-new-cloned-typedarray.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-undefined-newtarget-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/internals/DefineOwnProperty/BigInt/conversion-operation.js]

ReferenceError: cannot resolve reference: "testTypedArrayConversions"

[test/built-ins/TypedArrays/internals/DefineOwnProperty/BigInt/tonumber-value-detached-buffer.js]

TypeError: cannot convert number to BigInt (Testing with BigInt64Array.)

[test/built-ins/TypedArrays/internals/Set/BigInt/conversion-operation.js]

ReferenceError: cannot resolve reference: "testTypedArrayConversions"

[test/built-ins/TypedArrays/internals/Set/BigInt/key-is-minus-zero.js]

TypeError: cannot convert number to BigInt (Testing with BigInt64Array.)

[test/built-ins/TypedArrays/internals/Set/BigInt/key-is-not-integer.js]

TypeError: cannot convert number to BigInt (Testing with BigInt64Array.)

[test/built-ins/TypedArrays/internals/Set/BigInt/key-is-out-of-bounds.js]

TypeError: cannot convert number to BigInt (Testing with BigInt64Array.)

[test/built-ins/TypedArrays/internals/Set/BigInt/tonumber-value-detached-buffer.js]

TypeError: cannot convert number to BigInt (Testing with BigInt64Array.)

[test/built-ins/TypedArrays/of/BigInt/argument-is-symbol-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/argument-number-value-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/custom-ctor-does-not-instantiate-ta-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/custom-ctor-returns-other-instance.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/custom-ctor-returns-smaller-instance-throws.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/custom-ctor.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/inherited.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/invoked-as-func.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/nan-conversion.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/new-instance-empty.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/new-instance-from-zero.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/new-instance-using-custom-ctor.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/new-instance.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/built-ins/TypedArrays/of/BigInt/this-is-not-constructor.js]

ReferenceError: cannot resolve reference: "testWithTypedArrayConstructors"

[test/harness/testTypedArray.js]

Test262Error: All TypedArray constructors are accounted for

**Comment by ljharb** [comment]
(link to f95b56ab28c5f18150f30fbfa889a4f6ba0e50a1)

**Comment by leobalter** [comment]
Thanks for catching this, @anba.

I'm pretty sure I fixed this before but apparently I lost part of the work in some rebase/squash. It's so frustrating.

a PR is on the way.

**Comment by spectranaut** [comment]
Fix by this and other recent PRs:
https://github.com/tc39/test262/pull/1448
