### ISSUE TITLE
Suspicious tests for non-existent name property of anonymous built-in functions

### ISSUE THREAD

**Issue by iamstolis** [tc39/test262#1450]
There are several tests (like `built-ins/Promise/reject-function-name.js`) that check that an anonymous builtin function does not have `name` property:

```
assert.sameValue(Object.prototype.hasOwnProperty.call(rejectFunction, "name"), false);
```

The comment included in such tests quotes

```
  17 ECMAScript Standard Built-in Objects:
    Every built-in Function object, including constructors, that is not
    identified as an anonymous function has a name property whose value
    is a String.
```

This sounds like a misunderstanding to me. This sentence is an implication, i.e., it says that if a built-in function is not anonymous then the function has a `name` property. It does not say that such property is not allowed (as an implementation-specific extension) for anonymous built-in functions. In other words "a conforming implementation of ECMAScript" may provide some name for these functions as such an extension is not forbidden in "Forbidden Extensions" section of the specification.

Hence, these tests should be either removed or updated such that they allow the `name` property and check attributes of such a property based on the following part of the specification:

```
Unless otherwise specified, the name property of a built-in function object, if it exists, has the attributes { [[Writable]]: false, [[Enumerable]]: false, [[Configurable]]: true }.
```

**Comment by anba** [comment]
And later in https://tc39.github.io/ecma262/#sec-function-instances-name:
> Anonymous functions objects that do not have a contextual name associated with them by this specification do not have a name own property but inherit the name property of %FunctionPrototype%.

**Comment by iamstolis** [comment]
Thanks for pointing out this well hidden (for me, at least) piece of information. Maybe the tests can be updated to include this pointer as well (to avoid any potential future confusion of someone else) ;-).

**Comment by ljharb** [comment]
https://github.com/tc39/ecma262/issues/1049 seems relevant here, and this seems answered :-)
