### ISSUE TITLE
Missing coverage: Function.prototype.toString revision behavior on a Proxied function

### ISSUE THREAD

**Issue by ajklein** [tc39/test262#1453]
We just got a [report](https://crbug.com/v8/7484) in v8 about non-compliance with a new bit of logic in the [Function.prototype.toString revision proposal](https://tc39.github.io/Function-prototype-toString-revision/). In particular, step 3 of [the algorithm](https://tc39.github.io/Function-prototype-toString-revision/#proposal-sec-function.prototype.tostring) says:

> If Type(func) is Object and IsCallable(func) is true, then return an implementation-dependent String source code representation of func. The representation must have the syntax of a NativeFunction.

This is a change in behavior from the current spec, which throws a TypeError in this case. This doesn't seem to be covered by any test262 test.

@michaelficarra @erights to verify that I'm reading the proposal correctly.

**Comment by ljharb** [comment]
I agree that you're reading the proposal correctly; however I'm surprised at this change, and it seems like it's an unintentional change in the proposal.

**Comment by michaelficarra** [comment]
This was an intentional change in response to https://github.com/tc39/Function-prototype-toString-revision/issues/3. I recall talking about it in committee, but I think it was only in side conversations.
