### ISSUE TITLE
Clean up BigInt TypedArrays tests per feedback

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1461]
@anba is giving an amazing feedback for the recently added tests for BigInt TypedArrays, here is a ctrl-c ctrl-v from https://github.com/tc39/test262/pull/1448#issuecomment-368989914

---

There are no longer any test failures when this PR is applied, but some of the BigInt-TypedArray tests still need to be updated to work correctly for BigInts:

harness/testBigIntTypedArray.js
- [x] `@param {Array} selected - [ ] An optional Array with filtered typed arrays`, but "selected" parameter not present.
- [x] Multiple callers to testWithBigIntTypedArrayConstructors still provide this unused "selected" parameter

test/built-ins/TypedArrays/ctors-bigint/buffer-arg/bufferbyteoffset-throws-from-modulo-element-size-sab.js
- [x] `TA.BYTES_PER_ELEMENT === 1` never fulfillable -> remove
- [x] also present in other files

test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-access-throws.js
- [x] `TA === Int8Array ? Int16Array : Int8Array;`, never fulfillable -> test with BigInt typed arrays here?

test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-not-object-throws.js
- [x] `TA === Int8Array ? sample2 : sample1`, similar issue to above
- [x] also present in other files

test/built-ins/TypedArray/prototype/copyWithin/BigInt/{name,length,prop-desc,invoked-as-func,invoked-as-method,this-is-not-object,this-is-not-typedarray-instance}.js
- [x] Unnecessary tests
- [x] Also present for other methods

test/built-ins/TypedArray/prototype/fill/BigInt/fill-values-conversion-once.js
- [x] Should refer to BigInt conversion instead of ToNumber

test/built-ins/TypedArray/prototype/fill/BigInt/fill-values-non-numeric.js
- [x] Missing coverage for non-convertable values like `undefined` or `null`?
- [x] (Symbols are covered in test/built-ins/TypedArray/prototype/fill/BigInt/fill-values-symbol-throws.js)

test/built-ins/TypedArray/prototype/includes/BigInt/fromIndex-equal-or-greater-length-returns-false.js
- [x] Search element should be BigInt value, otherwise the return value is always `false`.
- [x] Also an issue in other includes(), indexOf(), lastIndexOf(), etc. tests.

test/built-ins/TypedArray/prototype/set/BigInt/array-arg-return-abrupt-tointeger-offset-symbol.js
- [x] Change `[1]` to `[1n]` to avoid possible false-positives because ToBigInt(1) also throws a TypeError.
- [x] Issue also present in other set() tests.

test/built-ins/TypedArray/prototype/set/typedarray-arg-set-values-diff-buffer-other-type-sab.js
- [x] `var src = new BigInt64Array(sab)` should use BigUint64Array if TA === BigInt64Array.
- [x] Issue also present in source file test/built-ins/TypedArray/prototype/set/typedarray-arg-set-values-diff-buffer-other-type-sab.js

test/built-ins/TypedArray/prototype/sort/BigInt/sortcompare-with-no-tostring.js
- [x] Is there a missing `delete Number.prototype.toString` here and in the source file?

test/built-ins/TypedArrays/ctors-bigint/buffer-arg/bufferbyteoffset-throws-from-modulo-element-size.js
- [x] `TA.BYTES_PER_ELEMENT === 1` is always false
- [x] Issue also present in other files.

test/built-ins/TypedArrays/ctors-bigint/buffer-arg/invoked-with-undefined-newtarget.js
- [x] Replace `new ArrayBuffer(4)` with `new ArrayBuffer(8)` or `new ArrayBuffer(TA.BYTES_PER_ELEMENT)`
- [x] Also in SharedArrayBuffer version

test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg/typedarray-arg-detached-when-species-retrieved-different-type.js
- [x] Replace `var targetType = TA !== Int32Array ? Int32Array : Uint32Array;` with BigInt typed array types.

test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/typedarray-arg/typedarray-arg-other-ctor-buffer-ctor-not-object-throws.js
- [x] Replace `TA === Int8Array ? sample2 : sample1` with BigInt types
- [x] Also in other files in this directory

test/built-ins/TypedArrays/from/BigInt/custom-ctor-returns-smaller-instance-throws.js
- [x] Replace `[1, 2]` with `[1n, 2n]` to avoid false-positives.
- [x] Issue also present in other files in this directory

test/built-ins/TypedArrays/internals/DefineOwnProperty/BigInt/key-is-greater-than-last-index.js
- [x] Replace `value: 42` with `value: 42n` to avoid false-positives.
- [x] Issue also present in other files in this directory

test/built-ins/TypedArrays/internals/Set/BigInt/detached-buffer-realm.js
- [x] Replace `sample[0] = 0;` with `sample[0] = 0n;` to avoid false-positives.

**Comment by rwaldron** [comment]
I'll clean these up.

**Comment by spectranaut** [comment]
@anba, you wrote:
> test/built-ins/TypedArray/prototype/includes/BigInt/fromIndex-equal-or-greater-length-returns-false.js
>     Search element should be BigInt value, otherwise the return value is always false.

This seems pretty weird. Do you think it would be better if the spec had the function error at this point, for BigInt TypedArrays, or, that they comparison is allowed? That really might throw of a user, as "==" otherwise works as expected/returns a value between a BigInt and a Number.

**Comment by spectranaut** [comment]
hey @anba I'm also a bit confused about your comment here:

> test/built-ins/TypedArray/prototype/set/typedarray-arg-set-values-diff-buffer-other-type-sab.js
>    var src = new BigInt64Array(sab) should use BigUint64Array if TA === BigInt64Array.

Is this concern covered in the tests I added here?
https://github.com/tc39/test262/pull/1478/files#diff-d5d8cd2db8668d4bf2a8f51f1ab434e3
https://github.com/tc39/test262/pull/1478/files#diff-f6257383bf55bc5fff97f4e6fc3e8ee7

**Comment by rwaldron** [comment]
Completed
