### ISSUE TITLE
Test failures at 52f70e2f637731aae92a9c9a2d831310c3ab2e1e

### ISSUE THREAD

**Issue by anba** [tc39/test262#1470]
Test failures at 52f70e2f637731aae92a9c9a2d831310c3ab2e1e

test/built-ins/AsyncFromSyncIteratorPrototype/next/return-promise.js
- Test has `async` flag but doesn't call `$DONE`.

test/built-ins/AsyncFromSyncIteratorPrototype/return/iterator-result-unwrap-promise.js
test/built-ins/AsyncFromSyncIteratorPrototype/throw/iterator-result-unwrap-promise.js
- `$DONE` function is called multiple times. (Calling `$DONE` multiple times should be avoided since it can mask errors.)

test/built-ins/TypedArrays/ctors/buffer-arg/bufferbyteoffset-throws-from-modulo-element-size.js
Caused by: Error: Expected a RangeError to be thrown but no exception was thrown at all (Testing with Int8Array.)
- Int8Array, Uint8Array, and Uint8ClampedArray should be excluded for this test, cf. SharedArrayBuffer version of this test.

test/built-ins/TypedArrays/ctors/buffer-arg/byteoffset-throws-from-modulo-element-size.js
Caused by: Error: Expected a RangeError to be thrown but no exception was thrown at all (Testing with Int8Array.)
- Int8Array, Uint8Array, and Uint8ClampedArray should be excluded for this test, cf. SharedArrayBuffer version of this test.

test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/other-ctor-returns-new-typedarray.js
Caused by: Error: Expected SameValue(«0», «7») to be true (Testing with BigInt64Array.)
- `sample1` and `sample2` need to be initialised with `length=7`, so the assertion `assert.sameValue(typedArray.length, 7)` can be tested.

**Comment by littledan** [comment]
cc @cxielarko

**Comment by cxielarko** [comment]
The last failure is fixed in ce9419779fc61d5cdfa37a5cda7b6828c67221da (from #1467)

**Comment by rwaldron** [comment]
@spectranaut set me as a reviewer in a PR when ready—thanks!!

**Comment by leobalter** [comment]
these should be fixed by #1481, thank you @anba
