### ISSUE TITLE
Typed array constructor test invalid for Int8/Uint8 

### ISSUE THREAD

**Issue by psmarshall** [tc39/test262#1471]
https://github.com/tc39/test262/blob/master/test/built-ins/TypedArrays/ctors/buffer-arg/bufferbyteoffset-throws-from-modulo-element-size.js isn't correct for Int8Arrays and Uint8Arrays, which have an elementSize == 1, and can be validly constructed from an ArrayBuffer with length == 1.

Not sure what the best way to fix the test is, hence filing an issue rather than a PR.

**Comment by anba** [comment]
Also see #1470 for other issues in TypedArray tests.

**Comment by leobalter** [comment]
@psmarshall can you file a PR to fix this, please? I'd be happy to review.

**Comment by spectranaut** [comment]
This has been fixed in: https://github.com/tc39/test262/pull/1481

Also the file path as been renamed, see it here: https://github.com/tc39/test262/blob/master/test/built-ins/TypedArrayConstructors/ctors/buffer-arg/bufferbyteoffset-throws-from-modulo-element-size-sab.js
