### ISSUE TITLE
Weaken tests about NaN canonicalization

### ISSUE THREAD

**Issue by littledan** [tc39/test262#1476]
TC39 reached consensus on https://github.com/tc39/ecma262/pull/758 , which permits certain kinds of flexibility with NaN canonicalization. test262 includes tests that are invalid with that patch, some of which you can find listed in https://github.com/v8/v8/blob/master/test/test262/test262.status#L226 . If someone is interested in volunteering, it'd be great if we had a test PR to match the spec PR.

cc @ajklein

**Comment by rwaldron** [comment]
cc @leobalter @spectranaut @nomadtechie

**Comment by rwaldron** [comment]
@littledan @ajklein 

(noting the relevant change here)

> either the same encoding for each implementation distinguishable *NaN* value, or an implementation-defined canonical value.

IIUC, Test262 could satisfy the desired flexibility by just checking if the NaN bit pattern is in range? (Between 7FF0000000000000 and 7FFFFFFFFFFFFFFF, or FFF0000000000000 and FFFFFFFFFFFFFFFF)

**Comment by littledan** [comment]
@rwaldron Well, if the NaN bit pattern is in range, it would be spec-compliant. The specification implies something a little more specific, but something which is pretty hard to write a test for as it's a hard to get at the particular shared implementation-dependent pattern.

Between the complexity of writing more specific tests, and @jfbastien's explanation that real implementations that don't do canonicalization are unlikely to satisfy even the newly more relaxed specification anyway, and the committee having repeatedly expressed being OK with V8's lack of NaN canonicalization, I'd be fine if we just had tests as you describe.

**Comment by leobalter** [comment]
being in range doesn't mean we would observe canonicalization. The spec might become more relaxed but still requires some minimal matching for each production form of `NaN`. e.g.: `0/0` will always match the same bit pattern in Float arrays, canonicalized or not with other productions, like `Infinity/Infinity`.

**Comment by rwaldron** [comment]
> being in range doesn't mean we would observe canonicalization

My interpretation is that since there are "options", that we can't depend on one or the other and must not explicitly test for matching NaN encodings, instead we'll just check that a NaN is a valid NaN and that's it.

**Comment by littledan** [comment]
I agree with Leo that it would be possible to construct a test which is a little more specific--you could run several different scenarios and check that, each time, you rather get the same value out or a single canonical one shared between them. It could be tricky to get at the cases that might trip up a real implementation, though--to have full test coverage would require knowledge of details of a particular implementation.

**Comment by rwaldron** [comment]
> to have full test coverage would require knowledge of details of a particular implementation.

This matches my understanding. For now, I'm going to relax the tests so that they simply assert that _any_ valid NaN encoding is acceptable. We can iterate on these over time (if necessary), but I believe that will correct the issue of implementations failing the tests listed in https://github.com/v8/v8/blob/master/test/test262/test262.status#L226

**Comment by rwaldron** [comment]
I've added a commit on the V8 issue, but anyone that comes this way and can verify: https://bugs.chromium.org/p/v8/issues/detail?id=5116#c11
