### ISSUE TITLE
Too few 9s in number of days backwards from 1970 to produce RangeError

### ISSUE THREAD

**Issue by ediosyncratic** [tc39/test262#1486]
https://github.com/tc39/test262/blob/7da91bceb9ce7613f87db47ddd1292a2dda58b42/test/suite/ch15/15.9/15.9.5/15.9.5.43/15.9.5.43-0-8.js#L19

The test specifies a date 99999999 days before 1970; 99999999 days is 273790 years and most of another, putting this in year 1970 -273791 = -271821; this *is* representable in the extended year format (only six digits plus a sign) and *is* within the range that the spec [0] says should be supported:

> ECMAScript requires the ability to specify 6 digit years (extended years); approximately 285,426 years, either forward or backward, from 01 January, 1970 UTC.

* [0] http://www.ecma-international.org/ecma-262/7.0/index.html#sec-extended-years

Adding an extra 9 to the number of days backwards from 1970 to look fixes this.
Discovered because it failed for a correct implementation inside the guts of Qt, [QTBUG-67010](https://bugreports.qt.io/browse/QTBUG-67010) and I've added an extra 9 to our copy of the test.

I'm unable to work out where this test has landed, or whether it has even survived (or been fixed on the way) in the new layout on master; I'm hoping you can tie this issue report to wherever it went !

**Comment by anba** [comment]
The test looks correct to me, it's now located at https://github.com/tc39/test262/blob/master/test/built-ins/Date/prototype/toISOString/15.9.5.43-0-8.js.

From https://tc39.github.io/ecma262/#sec-time-values-and-time-range
> The actual range of times supported by ECMAScript Date objects is slightly smaller: exactly -100,000,000 days to 100,000,000 days measured relative to midnight at the beginning of 01 January, 1970 UTC. This gives a range of 8,640,000,000,000,000 milliseconds to either side of 01 January, 1970 UTC.

And `new Date(1970, 0, -99999999, 0, 0 + timeZoneMinutes - 60, 0, -1)` is outside of that range.

**Comment by rwaldron** [comment]
Thanks for triaging this @anba

**Comment by ediosyncratic** [comment]
hmm ... in that case, surely there's a problem with the part of the spec I quoted above, as [0] ?
1e8 days is approximately 273791 years, so claiming it's approximately "approximately 285,426 years" is clearly wrong.

**Comment by ediosyncratic** [comment]
Duly filed: https://github.com/tc39/ecma262/issues/1176

**Comment by ediosyncratic** [comment]
OK, closer examination reveals:
* timeZoneMinutes is evaluated *now* so uses the currently-applicable time-zone data for the zone; it's -8 hours in the zone in which the tests are run (PST8PDT), when that zone is in DST; the test passes for me when the zone *isn't* in DST, so the offset is -7 hours, but fails in DST.
* the Date() constructor first builds a local time that's long before the invention of time-zones; this gets to be UTC()ed before it gets TimeClip()ped; and UTC() uses the zone information at the target time, not the current zone information.
* I'm using the time-zone database (which the spec encourages); it typically starts each zone's history with a pre-history of its mean solar time; in this case, because I made the mistake of representing PST8PDT by America/Vancouver, it's 12 minutes and 28 seconds West of the nominal meridian for -8 hours; so the call to UTC() puts the test time (just) back inside the range, instead of just one millisecond outside the range, as intended.  I shall switch to using America/Los_Angeles (7m2s *East* of the relevant meridian) instead !
