### ISSUE TITLE
Coverage: Promise.all with non-iterable

### ISSUE THREAD

**Issue by bakkot** [tc39/test262#1490]
A value can fail to be iterable in all kinds of exciting ways, including:

- Being `null` or `undefined`
- Missing a`Symbol.iterator` field or otherwise having it be non-callable
- Having a getter for `Symbol.iterator` which throws
- Having an `Symbol.iterator` method which returns non-objects

When provided any of these as its first argument, `Promise.all` is meant to return a rejected promise, rather than throwing. For at least the last of these, v8 throws, so I suspect there's a hole in the coverage.

**Comment by ljharb** [comment]
https://tc39.github.io/ecma262/#sec-promise.all says that a nullish argument should definitely throw and not return a rejected promise. GetIterator can also throw synchronously, as can the IsConstructor check.

**Comment by bakkot** [comment]
@ljharb, that's not my reading. Remember that abstract operations can't "throw" per se; they just return completion records, which may be abrupt completion records representing thrown exceptions. None of the steps past `NewPromiseCapability` are using [`ReturnIfAbrupt`](https://tc39.github.io/ecma262/#sec-returnifabrupt) or the `?` or `!` macros to unwrap a completion record; they instead use [`IfAbruptRejectPromise`](https://tc39.github.io/ecma262/#sec-ifabruptrejectpromise), which is like `ReturnIfAbrupt` except that it returns a rejected promise rather than throwing.

**Comment by ljharb** [comment]
Step 2 explicitly says to throw a TypeError if it’s a primitive, at least.

On a reread, you’re correct about GetIterator check, but the IsConstructor check and Construct and IsCallable calls inside NewPromiseCapability have a ?, meaning they unpack an abrupt completion using ReturnIfAbrupt.

**Comment by bakkot** [comment]
Step 2 says to throw a TypeError if the *receiver* is primitive.

Errors in NewPromiseCapability do cause synchronous throws, yes. This issue is just about the argument, though, not the receiver. Though I guess it would also be good to assert the synchronous behavior if that's not covered.

**Comment by ljharb** [comment]
aha, thanks, that clarifies my misunderstanding :-) I now completely agree with your original issue, and apologies for the confusion.

My copy of Chrome seems to return a resolved promise for `Promise.all([{ [Symbol.iterator]() {return null} }])`, but it seems like it should return a rejected one?

Either way, we should definitely have tests that cover all of this behavior!

**Comment by bakkot** [comment]
> apologies for the confusion

No worries, this stuff is inherently confusing.

> My copy of Chrome seems to return a resolved promise for Promise.all([{ [Symbol.iterator]() {return null} }]), but it seems like it should return a rejected one?

Because you wrapped in it an array, it's doing the right thing - you're getting a promise for an array containing the object, just like you'd get a promise for an array containing 0 from `Promise.all([0])`; it's never even reading `[Symbol.iterator]`.

The [bug in Chrome](https://bugs.chromium.org/p/v8/issues/detail?id=7553) is from `Promise.all({ [Symbol.iterator]() {return null} })`, which throws instead of returning a rejected promise.

**Comment by rwaldron** [comment]
This is totally awesome
