### ISSUE TITLE
Test failures at b07c546b8aa9ae6ded0599673e9e643a5ee4e7ea

### ISSUE THREAD

**Issue by anba** [tc39/test262#1492]
4 test files with errors at b07c546b8aa9ae6ded0599673e9e643a5ee4e7ea

https://github.com/tc39/test262/blob/b07c546b8aa9ae6ded0599673e9e643a5ee4e7ea/test/built-ins/AsyncFromSyncIteratorPrototype/throw/iterator-result-unwrap-promise.js#L49
- `yield* obj;` needs to be `return yield* obj;`, otherwise the return value of the `throw()` handler will be ignored.

https://github.com/tc39/test262/blob/b07c546b8aa9ae6ded0599673e9e643a5ee4e7ea/test/built-ins/Atomics/wait/negative-index-throws.js#L27
- Doesn't throw a RangeError because `ToIndex(-0.999) == 0` 

https://github.com/tc39/test262/blob/b07c546b8aa9ae6ded0599673e9e643a5ee4e7ea/test/built-ins/Atomics/wait/negative-index-throws.js#L29
- Doesn't throw a RangeError because `ToIndex(-0.00000000000000001) == 0` 

https://github.com/tc39/test262/blob/b07c546b8aa9ae6ded0599673e9e643a5ee4e7ea/test/built-ins/Atomics/wait/negative-index-throws.js#L30
- Doesn't throw a RangeError because `ToIndex(NaN) == 0` 

https://github.com/tc39/test262/blob/b07c546b8aa9ae6ded0599673e9e643a5ee4e7ea/test/built-ins/TypedArray/prototype/map/return-new-typedarray-conversion-operation-consistent-nan.js#L53
- Missing function invocation -> `return NaNs[i++]();`.

https://github.com/tc39/test262/blob/b07c546b8aa9ae6ded0599673e9e643a5ee4e7ea/test/harness/verifyProperty-value-error.js#L32
- `«0»` is incorrect in the expected assertion message.

**Comment by nomadtechie** [comment]
@anba thanks for the feedback -- I'm the owner for `test262/test/built-ins/Atomics/wait/negative-index-throws.js` and I'll update the input values.

**Comment by anba** [comment]
Additional failures at 5d6899522ad913003f83e1127f84f5d068112460

test/built-ins/Promise/race/iter-arg-is-string-resolve.js
- Invalid: Promise.race doesn't resolve anything if the iterable is empty.

test/built-ins/Promise/all/iter-arg-is-string-resolve.js
- Calles $DONE multiple times which makes it easy to hide errors.

test/built-ins/Promise/all/iter-step-err-no-close.js
- Contains call to $DONE in non-async test case.

test/built-ins/Atomics/wait/cannot-suspend-throws.js
- This test assumes the main thread cannot wait, which isn't necessarily true, e.g. in JavaScript shell environments.
- Maybe add a separate flag, so consumers can opt-out if the main thread can wait in these environments?

https://github.com/tc39/test262/blob/5d6899522ad913003f83e1127f84f5d068112460/test/built-ins/Atomics/wait/undefined-index-defaults-to-zero.js#L27
- 10ms timeout is way too short

https://github.com/tc39/test262/blob/5d6899522ad913003f83e1127f84f5d068112460/test/built-ins/Atomics/wait/wait-index-value-not-equal.js#L35
- ToInt32(Infinity) === 0, so this test waits and eventually times-out.

https://github.com/tc39/test262/blob/5d6899522ad913003f83e1127f84f5d068112460/test/built-ins/Atomics/wait/was-woken-before-timeout.js#L45
- s/assert.sameValue/assert/
