### ISSUE TITLE
Feature flag for more Intl tests using particular data?

### ISSUE THREAD

**Issue by littledan** [tc39/test262#1515]
It's currently difficult to write many completely "correct" tests against ECMA-402 (Intl). ECMA-402 defines the shape of internationalization data in general, but it doesn't define what the data is. And it shouldn't define what the data is--over time, conventions change, data quality improves, and the same code outputs different results, without either of the two results being "wrong".

However: This state presents a problem for testing. It's not possible to write a completely correct test262 test which checks that the string output is any particular string--the only tests that are completely correct test more superficial things about the form. So far, JS implementations have been maintaining non-upstreamed individual tests for this purpose.

I was wondering, what if we made a feature flag behind which we could share Intl tests which assume a little bit about locale data? For example, it could be a feature flag for en-US data, and we could use our subjective judgment to keep the tests generally within what is unlikely to change over time. This would enable more tests to be written and shared between implementations in test262. We could update the standard harness to skip these tests by default, and implementations could specifically opt into them, to minimize confusion.

@anba has found a ton of observable differences in behavior between ECMA-402 implementations which don't actually have to do with differences in underlying locale data, but rather how things are hooked up on top of that. I think the lack of test262 test coverage in this area is a cause, and this category of tests is an important component.

@ms2ger is beginning to write tests for various Stage 3 Intl proposals; in this context, it would be great to figure out if we could add a test category like this.

**Comment by rwaldron** [comment]
@littledan I don't think this is a valid use of "feature" flags. "feature" flags are tagging a test file to indicate that a specific language feature is being used or tested in that file. It's also not clear to me how a "feature" flag would do anything special to change some observable aspect of a test. Could you write an example test that includes the sort of "en-US data" you're thinking of?

**Comment by littledan** [comment]
As an example, we could test, "if NumberFormat has the en-US locale, then 2.3 is formatted as "2.3"'.

Without some kind of assumptions on what data looks like, it's hard to write many tests about Intl. These tests are useful even if they are technically assuming more than what the spec says.

We discussed this kind of testing in the April 2018 Intl call and a bunch of browser vendors and specification authors would like to share tests here. It would be the easiest to use test262, to have all the tests in one place and since everyone has harnesses set up in the right place already.

Maybe feature is the wrong idea, I was just suggesting someplace that we could place a flag. I'd be fine representing the metadata some other way. The higher level question is whether this is permissible within test262, and if so, how.

Would you prefer to see these tests in test262 or to land someplace else that major JS implementations would share, for example in web-platform-tests or someplace else?

**Comment by littledan** [comment]
cc @jackhorton

**Comment by jackhorton** [comment]
One thing I would mention is that now that formatToParts is available, I think it would be great if these tests were based entirely on calling formatToParts and ensuring that some subset of the parts are present and the types are accurate, but not necessarily in some pre-determined order with pre-determined spelling. For instance, if I wanted to test formatting todays date (April 24th, 2018), I would prefer the test to check that the resulting parts list has a month, day, and year, and that the numeric year is 2018 and the numeric month is 4 and the numeric day is 24, but not that the date is in a specific format, so that "4/24/2018" and "24-4-2018" are equally valid resulting strings. Even this brings up some questions about implementation-defined format selection, but even that could probably be worked around by using lookup instead of best fit.

**Comment by littledan** [comment]
@jackhorton Those seem like good tests to write to check into test262 without this flag. Do you think we could get good coverage of Intl overall using only that? It seems a little difficult to me.

For example, V8 has local tests for PluralRules that exercise Arabic to get at a lot of different pluralization forms. Should tests like these need to be written several times and not shared between ECMA-402 implementations?

**Comment by jackhorton** [comment]
I think "ensuring that the parts are present" might be doable for current test262's datetimeformat coverage, since there are 7 mandatory formats that implementations must have. Checking the values of each part is probably still data-dependent (for instance, ChakraCore's test runner has an issue when using Windows Kit ICU where it thinks the default time zone is GMT rather than, in my case, PST, and this causes issues when checking the values of formatted parts). As far as I can tell, there are no required formats for NumberFormat, but PartitionNumberPattern may cover enough that the type could be checked for NumberFormat as well. I don't know what could be checked without relying on data for Collator or PluralRules

**Comment by rwaldron** [comment]
> I was wondering, what if we made a feature flag behind which we could share Intl tests which assume a little bit about locale data? For example, it could be a feature flag for en-US data, and we could use our subjective judgment to keep the tests generally within what is unlikely to change over time


This sounds good to me. I'm going to do pass through all of the existing Intl tests to detect and generate tag and subtag for extant occurrences.

**Comment by rkirsling** [comment]
I think the original question here highlights a serious existing problem for Intl tests.

As a particular example, [intl402/RelativeTimeFormat/prototype/format/en-us-numeric-auto.js](https://github.com/tc39/test262/blob/master/test/intl402/RelativeTimeFormat/prototype/format/en-us-numeric-auto.js) is written to assume ICU 65 (see https://unicode-org.atlassian.net/browse/ICU-20654).

In an ideal world, all engines could be expected to use the latest ICU at any given time, but this isn't the world we live in, nor is it the world ECMA-402 specifies. In particular, WebKit recently introduced a minimum ICU version of 60.2 and _none_ of its platforms are using a more recent version than 64.2.

It is incredibly frustrating to need to skip that entire test when only a tiny piece of it depends upon ICU version. It's also frustrating that this test was updated with the knowledge of it being dependent upon ICU version, yet there is no flagging mechanism to identify it as such.

(_Another common issue seems to be four-digit integral parts: see https://github.com/tc39/test262/pull/1669#issuecomment-615534315 for instance._)

**Comment by littledan** [comment]
The flagging mechanism is the `locale:` metadata: that says that the test depends on some particular meaning of some particular locale. Maybe we could have a metadata tag that's like "tested with this version of this software" (or a comment format?). I'd be up for any improvements to documentation here.

Overall, even if they're imperfect, I'm glad we have `locale: ` tests upstream in test262--this is much better than the previous situation, where we were simply unable to share these kinds of tests at all.

One way through, separately from improving the metadata: If some parts of a test are dependent on specific aspects of a locale, and other parts of a test are not, it could be a good change to contribute upstream in test262 to split the test in two, so you only have to disable one of them.
