### ISSUE TITLE
split Atomics tests using BigInt

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1527]
BigInt tests should go in separate files in the Atomics tests.

Things like this following code are good enough for a new separate test file:

```js
if (typeof BigInt !== "undefined") {
  views.push(BigInt64Array);
  views.push(BigUint64Array);
}
```

One important thing to solve here is to allow a correct filtering of tests by features. A support for Atomics without BigInt should be allowed without losing test coverage.

**Comment by rwaldron** [comment]
I had this on my hand-written to-ask-Leo-about list ;)
