### ISSUE TITLE
Atomics/wait/waiterlist-order-of-operations-is-fifo.js fails intermittently

### ISSUE THREAD

**Issue by anba** [tc39/test262#1530]
Let's assume the scheduler preempts execution between these two lines, then the test case will fail. 

https://github.com/tc39/test262/blob/42ca7bbf9353194105120c2f3863478f1b9a4b14/test/built-ins/Atomics/wait/waiterlist-order-of-operations-is-fifo.js#L35-L36

To make it more likely to trigger a context switch for local testing, you could add `for (var i = 0; i < 10000; ++i) {}` between the two lines.

**Comment by rwaldron** [comment]
I'm going to do another pass on the Atomics tests this week, I'm going to also be removing all uses of `Date.now()` in favor of `$262.agent.monotonicNow()`

**Comment by leobalter** [comment]
@anba can you confirm if the problem persists? I believe it's fixed by #1533

**Comment by anba** [comment]
Yes, it still persists &rarr; https://treeherder.mozilla.org/#/jobs?repo=try&revision=8c0d9506ca4c9b697f1a3048c6e12644c3242b36&selectedJob=185592613

We're currently marking the following tests as having intermittent failures in SpiderMonkey:
- built-ins/Atomics/wait/waiterlist-block-indexedposition-wake.js
- built-ins/Atomics/wait/waiterlist-order-of-operations-is-fifo.js
- built-ins/Atomics/wake/count-defaults-to-infinity-missing.js
- built-ins/Atomics/wake/count-defaults-to-infinity-undefined.js
- built-ins/Atomics/wake/wake-all-on-loc.js
- built-ins/Atomics/wake/wake-all.js
- built-ins/Atomics/wake/wake-in-order.js
- built-ins/Atomics/wake/undefined-index-defaults-to-zero.js

We're still at a8f7012587250b32ffb43a3cbd8da8a9f9d1565e, so when we update to a more recent test262 version additional Atomics test may need to marked as intermittent for us.

**Comment by leobalter** [comment]
Thanks @anba! This info is valuable!

I need to get some updates after 56091a0c5fc0bbc172d039056685bc6992a6528b, I'll see how to check it from here.

**Comment by leobalter** [comment]
this should be fixed by #1617
