### ISSUE TITLE
Linter: ensure files have a consistent EOLs as LF, avoid CRLF

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1555]
the inconsistency is causing me trouble, we could use .gitattributes and some linter to avoid CRLF eol, preferring LF

**Comment by leobalter** [comment]
Now I wonder if it affects files that should have CRLF by purpose... this is so annoying.

**Comment by jugglinmike** [comment]
We will certainly have a need for CRLF in a few files, so `.gitattributes` may not be a good fit. [Linting infractions can be ignored per-file and per-rule](https://github.com/tc39/test262/blob/8d7dd538f1aa575312922f9ef49353f0c26287f3/tools/lint/lint.py#L40-L42), so we should be able to lint for this.

**Comment by rwaldron** [comment]
> We will certainly have a need for CRLF in a few files

For ref: https://tc39.github.io/ecma262/#prod-LineTerminator

**Comment by jugglinmike** [comment]
Thanks, Rick!
