### ISSUE TITLE
Big Int comparison with NaN returns undefined

### ISSUE THREAD

**Issue by caiolima** [tc39/test262#1559]
According the https://tc39.github.io/proposal-bigint/#sec-abstract-relational-comparison, when one of the operands are ```NaN```and the other is BigInt, the result is ```undefined```.

Test [test262/test/language/expressions/less-than/bigint-and-non-finite.js](https://github.com/tc39/test262/blob/master/test/language/expressions/less-than/bigint-and-non-finite.js) is asserting the wrong  outcome.

**Comment by ljharb** [comment]
See https://tc39.github.io/ecma262/#sec-relational-operators-runtime-semantics-evaluation - if the abstract relational comparison returns `undefined`, the operation returns `false`.

`>` / `<` / `<=` / `>=` can only ever return booleans.

**Comment by caiolima** [comment]
Oh. Thanks!
