### ISSUE TITLE
Atomics/wake/{count-defaults-to-infinity-missing,wake-all,wake-in-order}.js fail intermittently 

### ISSUE THREAD

**Issue by anba** [tc39/test262#1566]
Mozilla recently updated test262 which resulted in intermittent failures for three `Atomics.wake` tests:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1463110
- https://bugzilla.mozilla.org/show_bug.cgi?id=1462950
- https://bugzilla.mozilla.org/show_bug.cgi?id=1462975
- https://bugzilla.mozilla.org/show_bug.cgi?id=1412233#c14

All three test files have relatively short timeout values in common, for example:

https://github.com/tc39/test262/blob/c440a325a2677be17f2fd1376cf295ea40c1cd9d/test/built-ins/Atomics/wake/count-defaults-to-infinity-missing.js#L65

https://github.com/tc39/test262/blob/c440a325a2677be17f2fd1376cf295ea40c1cd9d/test/built-ins/Atomics/wake/wake-all.js#L49

https://github.com/tc39/test262/blob/c440a325a2677be17f2fd1376cf295ea40c1cd9d/test/built-ins/Atomics/wake/wake-in-order.js#L44

I haven't investigated this in detail, but (too) short timeouts are often problematic in CI environments which have different resource constraints when compared to local PCs. 

Also see #1288.

**Comment by leobalter** [comment]
this should be fixed by #1617
