### ISSUE TITLE
test262/built-ins/Atomics/wake/wake-rewake-noop is flaky

### ISSUE THREAD

**Issue by gsathya** [tc39/test262#1593]
I haven't investigated this in detail but the V8 bots show that this test is flaky:
* https://bugs.chromium.org/p/v8/issues/detail?id=7841

**Comment by binji** [comment]
Copied my comment from https://bugs.chromium.org/p/v8/issues/detail?id=7841#c16:

I took a look at test262/built-ins/Atomics/wake/wake-in-order, and it seems to rely on timing for ordering.

The `Atomics.store` call happens in order `0 1 2`, but there's no guarantee that the agents that are spin-looping will be scheduled in that order. I added a print statement:

```
  while (Atomics.load(ia, ${SPIN + i}) === 0)
      /* nothing */ ;
  print('waiting ' + ${i});
```

And got the following output:

```
  waiting 1
  waiting 0
  waiting 2
```

**Comment by leobalter** [comment]
thanks for the feedback, @binji! I have time scheduled this week to fix this.

**Comment by rwaldron** [comment]
@binji it's likely that this issue doesn't exist anymore, but the necessary changes may be pending in #1533 . 

I'm curious about your description above: does this implementation conform to the explicit "first in first out" semantics defined in the spec? Is it that they are awoken in the correct order, but have no guarantee of which waiter proceeds with execution first?

**Comment by binji** [comment]
Yes, they will be woken in the order that they started waiting, but the test will sometimes have them wait in the wrong (i.e. unexpected) order.

**Comment by rwaldron** [comment]
> but the test will sometimes have them wait in the wrong (i.e. unexpected) order.

Ok, this is where the issue lies in the test. Thanks for the additional clarification. I'll update the pending test in #1533 to caAlso, pture the order that the agents went to sleep and then compare it to the order in which they wake. Also, I'm going to nest the test code in a loop so that it's run several times.

**Comment by leobalter** [comment]
@binji @gsathya #1533 is finally merged, can you retry running Test262 with the latest changes? Please let me know if you find anything else missing to be covered there.

**Comment by rwaldron** [comment]
Since there hasn't been a response in over two years, I want to assume this is resolved. Please reopen if there are further issues.
