### ISSUE TITLE
Improve assert.throws.early error messages in case of late errors

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/test262#1595]
Sometimes, engines implement runtime errors that are supposed to be early errors instead. In those cases, when running a `assert.throws.early` test, you currently get an error message like:

```
Expected a SyntaxError to be thrown but no exception was thrown at all
```

It would be more clear to say:

```
Expected an early SyntaxError to be thrown but no early exception was thrown at all
```

Or, even better:

```
Expected an early SyntaxError to be thrown but instead, a SyntaxError was thrown at runtime
```

The latter would require a bit of coding: if `Function(code)` fails, then try `eval(code)` in a `try`-`catch`. If that one does throw the expected exception, the error message can be enhanced.

**Comment by leobalter** [comment]
I'm not sure this could unwrap problems from how eval is implemented.

I also don't want to recommend using this method anywhere in Test262. Ideally the best format for testing early errors is through flags with the negative tags.

I understand this would require a change for the tests on RegExp property escapes. So here are some options:

1. Split `RegExp/property-escapes` tests into several negative tests. As these tests are generated, this is probably easy. This way we can get rid of relying on any function or eval wrapper and check for actual early/parsing errors. Remove assert.throws.early.
2. Move `assert.throws.early` to a dedicated helper for RegExp property escapes, use a includes tag for loading the helper.
3. Do n. 1 + n. 2, duplicating the tests into native early errors and early errors for wrapped up code.

> The latter would require a bit of coding: if Function(code) fails, then try eval(code) in a try-catch. If that one does throw the expected exception, the error message can be enhanced.

This could be done if we go with n. 2 or 3, but I remember we got some negative feedback on wrapping code for throws.early in both a Function ctor and eval. Also, consider indirect eval calls.

I'm in preference for n. 1, but happy to support other format if you're interested.

WDYT, @mathiasbynens?

**Comment by mathiasbynens** [comment]
AFAICT, 1 doesn't solve the problem. 

[Negative tests](https://github.com/tc39/test262/blob/master/CONTRIBUTING.md#negative) check for the exception to be thrown during the specified `phase` (modulo bugs like #1621).

I'm saying that, if an engine throws the correct exception, but just during the wrong phase, that should be communicated in the error message, or even be configured to count as "passing" the test for known bugs. Rationale: it's better to throw the correct exception during the wrong phase (and to test for it), than it is to not even throw the exception at all (or to skip the test).

Imagine #1621 is fixed, and we have the following test (which is supposed to throw an early `SyntaxError`):

```js
/*---
negative:
  phase: parse
  type: SyntaxError
---*/

/?/;
```

V8 has a long-standing bug where it throws the error at runtime instead of at parse time, so it would fail the test, and get the following error message:

```
FAIL test/foo.js (default)
  Expected test to throw error of type SyntaxError, but did not throw error
```

I'm asking for that message to be improved into something like:

```
FAIL test/foo.js (default)
  Expected test to throw SyntaxError during parse phase, but it threw SyntaxError during runtime phase
```

...and later, as a separate request, for the possibility of marking such variations as acceptable.

V8 has known bugs where it throws exceptions at runtime instead of at parse time. Ideally, we'd still run those tests, to make sure we at least throw the right exception.

**Comment by mathiasbynens** [comment]
**Update:** #1621 is working as intended, and negative tests for the parse phase specifically need to have the following line as enforced by https://github.com/tc39/test262/blob/e9a5a7f918c0f9c4a9f1224d25a6d55147953225/tools/lint/lib/checks/negative.py#L5:

```
throw "Test262: This statement should not be evaluated.";
```

That means my above example would be:

```js
/*---
negative:
  phase: parse
  type: SyntaxError
---*/

throw "Test262: This statement should not be evaluated.";

/?/;
```

For V8, because we throw the `/?/` error too late, this results in:

```
FAIL test/foo.js (default)
  Expected test to throw error of type SyntaxError, got Test262: This statement should not be evaluated.
```

However, as a workaround in V8's test runner, we could strip out those `throw` lines, reducing the test to this:

```js
/*---
negative:
  phase: parse
  type: SyntaxError
---*/

/?/;
```

This test passes in V8.

This way, we don't have to skip the test, and we can still verify that we at least throw an exception of the correct type (even if we throw it too late).

**Comment by mathiasbynens** [comment]
Either way, this is a V8 issue, and not a Test262 issue, so I'm gonna close this. Thanks, everyone!
