### ISSUE TITLE
Add documentation for `implementation-contributed` directories

### ISSUE THREAD

**Issue by nomadtechie** [tc39/test262#1597]
New `implementation-contributed` directory should have documentation which reflects:

- What is this directory, and why was it created? 
- How does it fit in with `test262/tests`, and what is the long-term goal?
- How will these tests be managed and curated?
- How should consumers of `test262/tests` treat these tests? 

In additonal to the general to documention, it would be great to have sections for each of the implemention directories to further capture specific information which might be helpful. Ex: A link to the original source, or helpful information which will be useful at the time of curation.

I'm currently working on automation tooling which will extend port select tests from `webkit/JSTests/` into `test262/implementation-contributed/javascriptcore` on a daily basis. 

I'm happy to add this documentation once the scripts and automation are complete. 

Current placeholder for empty directory:
 https://github.com/tc39/test262/tree/master/implementation-contributed/javascriptcore

**Comment by rwaldron** [comment]
Excellent 👍
