### ISSUE TITLE
Generators Tests

### ISSUE THREAD

**Issue by smikes** [tc39/test262#160]
I'll write some generators tests from 1st principles — similar to the Promise tests, by reviewing the spec, pulling out testable assertions, and creating tests of those assertions.

Target directory is `test/language/generators`

Spec section is 14.4 <https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generator-function-definitions>

Is there any prior work that I should be aware of?  It looks like there are quite a few generators tests in `mjsunit/es6/generators-*` so perhaps I should wait until those are ported over?  /cc @rwaldron

**Comment by anba** [comment]
The standard warning notice: Generators in V8 are not 100% spec compatible, so you still need to inspect each and every test to ensure the current V8 semantics match the spec. 

Apart from that, here are some more tests:
http://hg.mozilla.org/mozilla-central/file/tip/js/src/tests/ecma_6/Generators
http://hg.mozilla.org/mozilla-central/file/tip/js/src/jit-test/tests/generators
https://github.com/anba/es6draft/tree/master/src/test/scripts/suite/semantic/generator
https://github.com/anba/es6draft/tree/master/src/test/scripts/suite/syntax/generator

**Comment by rwaldron** [comment]
@smikes yeah, probably smart to get the V8 tests moved over and then you can fill in the blanks.

**Comment by smikes** [comment]
Actually, I took a look at the V8 tests and there's not a lot of overlap between what they test and my approach, so I started writing some tests.  Initial PR at https://github.com/tc39/test262/pull/167

There is a *lot* of surface to test here…  Spec coverage spreadsheet at https://docs.google.com/spreadsheets/d/1ftzAmHwdCU4IVtC-iH9Zwk1FoSs062fufoNq_CAz-UM/edit

**Comment by bterlson** [comment]
We have a bunch of generator tests now.
