### ISSUE TITLE
Remove assert.throws.early in favor of negative tests?

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/test262#1622]
`assert.throws.early` was added here: https://github.com/tc39/test262/pull/1002

@leobalter [says](https://github.com/tc39/test262/issues/1595#issuecomment-402638285):

> I also don't want to recommend using this method anywhere in Test262. Ideally the best format for testing early errors is through flags with the negative tags.

**Can we make this recommendation official by deprecating and removing `assert.throws.early`?**

`assert.throws.early` only seems to be [used](https://github.com/tc39/test262/search?q=%22assert.throws.early%22) in some Unicode property escape tests (which I'll happily rewrite as negative tests instead) and in this file which just tests the harness: https://github.com/tc39/test262/blob/master/test/harness/assert-throws-early-referenceerror.js

**Comment by littledan** [comment]
I like this idea. If an engine's test harness handles early errors well, it can get better accuracy that way than with `assert.throws.early`, as I [explained here](https://github.com/tc39/test262/pull/1002#issuecomment-297662366).

**Comment by leobalter** [comment]
> Can we make this recommendation official by deprecating and removing assert.throws.early?

sure!

@mathiasbynens I think it would be easier if you first update the tests using it. If you prefer, I can add a deprecation message in the documentation, just let me know.

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/unicode-property-escapes-tests/pull/9

**Comment by mathiasbynens** [comment]
https://github.com/tc39/test262/pull/1633

**Comment by mathiasbynens** [comment]
Now that #1633 is merged, the only remaining usage of `assert.throws.early` is in `test/harness/*` itself. I guess it can be removed now?

**Comment by mathiasbynens** [comment]
@leobalter?

**Comment by leobalter** [comment]
@mathiasbynens I can do it this week. Thanks
