### ISSUE TITLE
Wrong github profile announcement

### ISSUE THREAD

**Issue by smigniot** [tc39/test262#1635]
Dear user tc39,

The github profile for tc39, namely https://github.com/tc39
Does contain a "user site/link URL", namely http://ecma-international.org/memento/TC39.htm

As of 2018-07-10T18:40:00, this url does *not* resolve - but to 404

1. You may want to change the URL of the tc39 user
2. In case this URL resolves differently in different countries, the 404 was obtained from France, using Firefox on Android
3. As a matter of fact this issue is not specific to the test262 repository but no mechanism exists to open an issue at the parent level

**Comment by leobalter** [comment]
Confirmed the 404, but the link is correct. The website needs to be fixed and the page restored. In any case, I changed the link to https://www.ecma-international.org/memento/tc39-rf-tg.htm

cc @littledan @bterlson @ljharb @bmeck 

> As a matter of fact this issue is not specific to the test262 repository but no mechanism exists to open an issue at the parent level

This is not the proper repo for this report but that's fine. Thanks for reporting!

**Comment by jmdyck** [comment]
> Confirmed the 404, but the link is correct.

I don't think it is. "TC" should be "tc", i.e.:
http://ecma-international.org/memento/tc39.htm
(which is 200 OK).

**Comment by leobalter** [comment]
@jmdyck the TC39 org was using the uppercase TC, that's something new on Ecma's website.

As we have ecma262, 402, test262, etc I think it's ok to point to the rf-tg link. I needed something to fix the 404, now we can bikeshed over which link we want to use.

**Comment by littledan** [comment]
@jmdyck TC39 does all of its work within its RFTG. We are working on better documentation to describe the situation, but it is not yet complete.
