### ISSUE TITLE
incorrect options in test262/test/intl402/Locale/constructor-options-numeric-valid.js

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/test262#1639]
@Ms2ger 
I think the options in test262/test/intl402/Locale/constructor-options-numeric-valid.js is set incorrectly

"
for (const [numeric, expected] of validNumericOptions) {
  const options = { numeric };
"
this make all the options be
{undefined},
{false},
{true},
{null},
{0},
{0.5},
{ false},
which does not make sense.
I believe it should be
"
for (const [numeric, expected] of validNumericOptions) {
  const options = { numeric: numeric };
"
so the options will be 
{numeric: undefined},
{numeric: false},
{numeric: true},
{numeric: null},
{numeric: 0},
{numeric: 0.5},
{numeric:  false},

to test the numeric option

**Comment by ljharb** [comment]
`{ numeric }` is a shorthand introduced in ES2015 for `{ numeric: numeric }`. This is working as intended.
