### ISSUE TITLE
built-ins/Atomics/wait/value-not-equal.js invokes $262.agent.report() with number argument

### ISSUE THREAD

**Issue by iamstolis** [tc39/test262#1640]
`built-ins/Atomics/wait/value-not-equal.js` tests invokes `$262.agent.report()` with a `number` argument. This function is supposed to be called with `string` argument only:
```
report - a function that takes a string and places it in a transmit queue whence the parent will retrieve it. Messages should be short.
```
according to `INTERPRETING.md`.

The test should be updated to convert the `number` to `string` explicitly (i.e. `$262.agent.report(String(Atomics.store(i32a, 0, ${value})))`) or the description of `report` should be updated to mention that the function should convert the argument to `string`.

Sure, it is a minor issue but our runner failed to execute this test because of this discrepancy.

**Comment by rwaldron** [comment]
@iamstolis 

> Sure, it is a minor issue but our runner failed to execute this test because of this discrepancy.

Curious: which runner/engine is this for? 

---------------------------------------


Looking at the cases that report the returned value of `Atomics.store()`, I think I'd rather go with: 

> or the description of report should be updated to mention that the function should convert the argument to string.

That's sort of been implicit all along, but we should settle on it and document.

**Comment by iamstolis** [comment]
> Curious: which runner/engine is this for?

[JavaScript engine](https://github.com/graalvm/graaljs) of [GraalVM](https://www.graalvm.org/)
