### ISSUE TITLE
Possible test bug in Array.prototype.flatMap

### ISSUE THREAD

**Issue by rhuanjl** [tc39/test262#1666]
I believe that there is an error in the tests for the use of the thisArg in Array.prototype.flatMap

https://github.com/tc39/test262/blob/48d95ac3c4ac56018748c0d243c831f4c0bfb103/test/built-ins/Array/prototype/flatMap/thisArg-argument.js#L15-L32

Testing with eshost these appear to fail with SpiderMonkey, JSC and v8 AND with the draft implementation of flatMap I'm working on for Chakracore.

The basic issue is that the thisArg is no longer a primitive once it's used as a thisArg - but compareArray checks for strict equality.

e.g. for the first test the comparison is:

```[{Type: Object, Value : "TestString"}] === [{Type : String, Value : "TestString"}]``` - which is false.

**Comment by ljharb** [comment]
In strict mode, it would remain a primitive.  Perhaps that file is merely missing the pragma?

**Comment by rhuanjl** [comment]
Ah it has an onlyStrict flag at the top of the file - I'm probably just doing something wrongly, I will re-check and confirm back later.

**Comment by rhuanjl** [comment]
Sorry - not an error I was just the test incorrectly.

Thanks for the quick reply @ljharb .
