### ISSUE TITLE
Await binding in global is not allowed in strict mode

### ISSUE THREAD

**Issue by pvdz** [tc39/test262#1667]
The test in [`test262 / test / language / expressions / await / await-BindingIdentifier-in-global.js`](https://github.com/tc39/test262/blob/master/test/language/expressions/await/await-BindingIdentifier-in-global.js) should throw when parsing it in strict mode. I suspect there'll be more tests in this line that have the same problem.

I think the fix is to add `flags: [noStrict]`. The test case(s) probably also needs a mirror to assert the reverse in strict mode.

----

https://tc39.github.io/ecma262/#sec-identifiers-static-semantics-early-errors

```
> IdentifierReference: await
> BindingIdentifier: await
> LabelIdentifier: await
>   It is a Syntax Error if the goal symbol of the syntactic grammar is Module.

> Identifier:IdentifierName but not ReservedWord
>   It is a Syntax Error if this phrase is contained in strict mode code and the StringValue of IdentifierName is: "implements", "interface", "let", "package",  "private", "protected", "public", "static", or "yield".
```

This would mean that the binding should trigger an error when parsing with the module goal. The read afterwards when asserting the type should also trigger a syntax error in any strict mode.

Tracing that statement to confirm the assertion leads to the right production:

```
> `assert(await instanceof Function);`
>
> ExpressionStatement[Yield, Await]:
>   [lookahead ∉ { {, function, async [no LineTerminator here] function, class, let [ }] Expression[+In, ?Yield, ?Await];
> Expression[In, Yield, Await]:
>   AssignmentExpression[?In, ?Yield, ?Await]
> ...
> LeftHandSideExpression[Yield, Await]:
>   CallExpression[?Yield, ?Await]
>     CallExpression[?Yield, ?Await]Arguments[?Yield, ?Await]
> Arguments[Yield, Await]:
>    (ArgumentList[?Yield, ?Await])
>       AssignmentExpression[+In, ?Yield, ?Await]
> ...
> RelationalExpression[In, Yield, Await]:
>   RelationalExpression[?In, ?Yield, ?Await] instanceof ShiftExpression[?Yield, ?Await]
> RelationalExpression[In, Yield, Await]:
>   ShiftExpression[?Yield, ?Await]
> NewExpression[Yield, Await]:
>   MemberExpression[?Yield, ?Await]
> PrimaryExpression[Yield, Await]:
>   IdentifierReference[?Yield, ?Await]
>     Identifier      (because `Await` param will not be set)
>        IdentifierName but not ReservedWord
```

This leads to the rule above; cannot be `await` in module goal.

**Comment by jugglinmike** [comment]
This test seems valid to me.

The first early error disallows `await` as an IdentifierReference in module code.  The second concerns strict mode code, but it doesn't mention `await`.

Since Test262 tests are intended to be interpreted as scripts unless they specify the `module` flag, this test describes both a strict and non-strict script. In both cases, `await` is a valid IdentifierReference.

**Comment by pvdz** [comment]
> Since Test262 tests are intended to be interpreted as scripts unless they specify the module flag

Ah. That explains it. Thanks :)

Turns out most tests actually run fine in module mode as well. Guess it's no big surprise that it's mostly these kinds of cases where it makes the difference.
