### ISSUE TITLE
assert.arrayLikeEqual => assert(compareArray(...))

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#169]
This pattern: `assert(compareArray(...))` has now appeared in 3 batches of tests. 

https://github.com/tc39/test262/pull/168/files#r24922454

**Comment by jugglinmike** [comment]
@bterlson I count 62 files with this pattern. An alternative to a new helper assertion would be to remove `compareArray.js` and "explode" these assertions to explicitly test array-like length and  elements in each test, eg

```diff
diff --git a/test/language/computed-property-names/to-name-side-effects/object.js b/test/language/computed-property-names/to-name-side-effects/object.js
index 2b8ac96..153a871 100644
--- a/test/language/computed-property-names/to-name-side-effects/object.js
+++ b/test/language/computed-property-names/to-name-side-effects/object.js
@@ -30,7 +30,9 @@ assert.sameValue(object.a(), 'A', "`object.a()` returns `'A'`. Defined as `a() {
 assert.sameValue(object.b(), 'B', "`object.b()` returns `'B'`. Defined as `[key1]() { return 'B'; }`");
 assert.sameValue(object.c(), 'C', "`object.c()` returns `'C'`. Defined as `c() { return 'C'; }`");
 assert.sameValue(object.d(), 'D', "`object.d()` returns `'D'`. Defined as `[key2]() { return 'D'; }`");
-assert(
-  compareArray(Object.keys(object), ['a', 'b', 'c', 'd']),
-  "`compareArray(Object.keys(object), ['a', 'b', 'c', 'd'])` returns `true`"
-);
+var keys = Object.keys(object);
+assert.sameValue(keys.length, 4);
+assert.sameValue(keys[0], 'a');
+assert.sameValue(keys[1], 'b');
+assert.sameValue(keys[3], 'c');
+assert.sameValue(keys[4], 'd');
```

Which would you prefer?

**Comment by domenic** [comment]
Much prefer `assert.arrayLikeEqual` (maybe `arrayLikeEquivalent` or something to convey that it's a vague test).

**Comment by leobalter** [comment]
I really want this feature and I'm asking why I never saw this issue before.

we already use `sameValue` for a strict-like comparisons (and NaN), my suggestion is just using a simple name: `equal` or `deepEqual` sounds better for me for simplicity and bias using other test frameworks.

**Comment by leobalter** [comment]
One great advantage to write this is to provide better failures as `assert(compareArray` only tells if the value is true or false.

**Comment by leobalter** [comment]
@jugglinmike while I like the explicitly, I would like to review all the cases using compareArray before I come in w/ a patch.

**Comment by caiolima** [comment]
I also like @jugglinmike approach. It makes our life easier debugging and makes the element with error easily.
