### ISSUE TITLE
Python set up questions

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/test262#1691]
I am trying to follow [these instructions](
https://github.com/tc39/test262/blob/master/CONTRIBUTING.md#procedurally-generated-tests) to run generator for tests which I need [for my PR](
https://github.com/tc39/test262/pull/1483). When I run `pip install --requirement tools/generation/requirements.txt`, I'm getting various errors (on macOS Mojave beta) on different Python versions. Which version of Python should I use? Also I think it will be really helpful to create Docker image with all environment set up to have at least reproducible errors.

**Comment by leobalter** [comment]
@chicoxyzzy I use the latest Python 2 available.

```
$ python --version
Python 2.7.15

$ pip --version
pip 10.0.1 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
```

I'd be game to have a Docker image but I have 0 experience with it. I also wonder how it would work with Travis CI.

@jugglinmike WDYT about using a Docker image here?

**Comment by leobalter** [comment]
btw, I use python from Homebrew but I had to hack the version I'm using because Homebrew is really trying to force Python3 as default.

**Comment by chicoxyzzy** [comment]
I was able to install PyYAML with pip. Now when I run `python make.py` I got an error 
```
➜  test262 git:(catch-parameter-default-value) ✗ python make.py
Running target: build
> /usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python tools/generation/generator.py create --out test src
Traceback (most recent call last):
  File "tools/generation/generator.py", line 9, in <module>
    from lib.expander import Expander
  File "<my_home_path>/test262/tools/generation/lib/expander.py", line 6, in <module>
    from case import Case
  File "<my_home_path>/test262/tools/generation/lib/case.py", line 8, in <module>
    from util.parse_yaml import parse_yaml
  File "<my_home_path>/test262/tools/generation/lib/util/parse_yaml.py", line 4, in <module>
    import yaml, re
ImportError: No module named yaml
Traceback (most recent call last):
  File "make.py", line 78, in <module>
    targets['build']()
  File "make.py", line 34, in wrapped
    return orig()
  File "make.py", line 45, in build
    SRC_DIR)
  File "make.py", line 24, in shell
    raise Exception('Command failed: ' + cmd_str)
Exception: Command failed: /usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python tools/generation/generator.py create --out test src
```

**Comment by ljharb** [comment]
What’s done in python that couldn’t be done in node?

**Comment by leobalter** [comment]
> ImportError: No module named yaml

Somehow it's not yet finding the PyYAML module you installed. I'm not sure if you're using the same related pip, and I'm not experienced enough with Python to tell what is exactly missing from this point. :(

**Comment by leobalter** [comment]
@ljharb We historically use python to not give a preference for any implementation of JS, plus as guarantee every implementor will use a dependency that is common to everyone, not requiring anyone to install "node".

**Comment by ljharb** [comment]
makes sense but now i have to install python, as a JS dev

**Comment by chicoxyzzy** [comment]
I was able to run `make.py` under virtualenv

**Comment by chicoxyzzy** [comment]
> to not give a preference for any implementation of JS

We have different versions of Node like Node with v8, Node ChakraCore, SpiderNode

**Comment by leobalter** [comment]
> makes sense but now i have to install python, as a JS dev 

you usually have Python installed by default in your dev env. That was a thing we have for years, dating before I started working with Test262. I wouldn't choose Python if that was up to my own decision. If we want something neutral and available to everyone's dev environments, I would choose Perl. :)

> We have different versions of Node like Node with v8, Node ChakraCore, SpiderNode

There is a lot of politics involved with the technical decisions we make for this project and telling all the implementors to use Node - or anything else. I'll try, but I'm more comfortable reaching out in person during the next meeting in September.

**Comment by chicoxyzzy** [comment]
> I would choose Perl

Now I'm happy with Python 😅

**Comment by tkellen** [comment]
@chicoxyzzy Mind giving this a shot?

https://github.com/tc39/test262/pull/1692

**Comment by chicoxyzzy** [comment]
Since #1703 was merged, I'll try to set up everything from scratch to find out if there are any unobvious steps now. I'll provide feedback here later.

**Comment by chicoxyzzy** [comment]
Everything works just fine with `pyenv` or `virtualenv` for me now
