### ISSUE TITLE
Initial tests of Symbol.species

### ISSUE THREAD

**Issue by smikes** [tc39/test262#172]
This is an interesting one.

According to https://kangax.github.io/compat-table/es6/ , at this time only core-js and Echo provide support for this.

**Comment by leobalter** [comment]
This might be covered already. @jugglinmike, would you confirm it?

**Comment by jugglinmike** [comment]
I'm pretty confident that this is not completely covered yet. I will write up a more thorough review this afternoon.

**Comment by jugglinmike** [comment]
Here's where we stand today:

- [x] The Symbol value itself
- The Symbol-named accessor properties on built-in objects:
  - [ ] `RegExp` (partial--missing test for return value)
  - [ ] `Array` (partial--missing test for return value)
  - [x] `%TypedArray%`
  - [ ] `Map` (partial--missing test for return value)
  - [ ] `Set` (partial--missing test for return value)
  - [ ] `ArrayBuffer` (partial--missing test for return value)
  - [x] `Promise`
- The use of the value from within various algorithms
  - SpeciesConstructor
    - TypedArraySpeciesCreate
      - [ ] `%TypedArray%.prototype.filter`
      - [ ] `%TypedArray%.prototype.map`
      - [ ] `%TypedArray%.prototype.slice`
      - [ ] `%TypedArray%.prototype.subarray`
    - CloneArrayBuffer
      - [ ] `%TypedArray%.prototype.set`
      - [x] `TypedArray(typedArray)`
    - [x] `RegExp.prototype[@@split]`
    - [x] `TypedArray(typedArray)`
    - [x] `ArrayBuffer.prototype.slice`
    - [x] `Promise.prototype.then`
  - ArraySpeciesCreate
    - [ ] `Array.prototype.concat`
    - [ ] `Array.prototype.filter`
    - [ ] `Array.prototype.map`
    - [ ] `Array.prototype.slice`
    - [ ] `Array.prototype.splice`

I've opened https://github.com/tc39/test262/pull/596 to introduce tests for the
missing accessor properties. I know you are still working on most of the
TypedArray methods mentioned above, @leobalter, so I will leave those to you.
For my part, I will commit to testing for this feature in the operation of the
Array prototype methods.

**Comment by jugglinmike** [comment]
Tests for ArraySpeciesCreate are now available at gh-600.

**Comment by leobalter** [comment]
@jugglinmike I think we got this solved, right? I'll check this up again next week.

**Comment by jugglinmike** [comment]
Yes, I've just confirmed that between gh-596, gh-600, and your work on
TypedArrays, we've covered all the occurrences of this Symbol. Closing as
"resolved." Thanks for following up on this!
