### ISSUE TITLE
Rationale for `assert()` expecting literal `true` instead of any truthy value?

### ISSUE THREAD

**Issue by smikes** [tc39/test262#173]
This bit me last night, because I was doing

```
assert(Symbol.species, 'Symbol.species exists');
```

which failed because `assert` expects a true value.  I switched it to

```
assert(Symbol.species !== undefined, 'Symbol.species exists');
```

which works fine.  Just wondering what the rationale was, since this seems to have been a deliberate choice, and I certainly won't be the last person who's bitten by it.

**Comment by domenic** [comment]
I think @arv talked me into it. In a language-level suite, you shouldn't use concepts like truthiness. You should be more precise in a given assertion.

For example, your second test will pass with `Symbol.species === 0`, whereas your first will fail.

**Comment by smikes** [comment]
Fair enough.  It certainly shaped my assertion choices, I found myself preferring `assert.sameValue()` for later assertions, so I think it helped me be less sloppy overall.

**Comment by bterlson** [comment]
It forces you to be explicit. Many values are truthy but you should be testing for one specific value not any value that happens to be truthy.
