### ISSUE TITLE
Cover Number#toString on top of literal numbers

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1732]
This is feedback after reviewing this [contributed test folder](https://github.com/tc39/test262/blob/master/implementation-contributed/javascriptcore/stress/)

- [ ] Cover Number#toString on top of literal numbers but number objects only.

examples: `0..toString(2); 0..toString(4); 0..toString(8); 0..toString(16); 0..toString(32);`

**Comment by rwaldron** [comment]
I realize it's been 2 years since you created this issue, but I'm trying to figure out which tests you were referring to and having no luck.

**Comment by leobalter** [comment]
I can't remember the origin tests, maybe they've been removed as this issue is open?

IIRC, I've seen a case using `..method` and created the exmaples here. Just adding test file(s) for `<literal>..toString(n)` should be good enough, I believe.
