### ISSUE TITLE
Add coverage for fn_name.arguments going to inner scopes.

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1733]
This is feedback after reviewing this [contributed test](https://github.com/WebKit/webkit/blob/master/JSTests/stress/assign-argument-in-inlined-call.js)

- [ ] Add coverage for fn_name.arguments going to inner scopes.

**Comment by rwaldron** [comment]
This was covered in 6a428b4a40feca6733b47e13b6b719cfe14ecf51
