### ISSUE TITLE
String values in assert.sameValue should be quoted

### ISSUE THREAD

**Issue by smikes** [tc39/test262#174]
This looks weird:

```
FAIL test/built-ins/Symbol/species/Symbol.species.in_RegExp.js
     RegExp[Symbol.species] exists per spec
     Exp: no error
     Got: Error: Expected SameValue(returnThis, get [Symbol.species]) to be true
```

This looks better:
```
FAIL test/built-ins/Symbol/species/Symbol.species.in_RegExp.js
     RegExp[Symbol.species] exists per spec
     Exp: no error
     Got: Error: Expected SameValue("returnThis", "get [Symbol.species]") to be true
```

Comparing empty strings also looks weird without quotes:

```
     Got: Error: Expected SameValue(, expected) to be true
```

**Comment by domenic** [comment]
yeah, but then you wonder about strings with `"` inside them, and then you're like, "I know, I'll escape them!" but then what about strings with `\"` inside them, and pretty soon you're reimplementing `JSON.stringify`...

**Comment by smikes** [comment]
`JSON.stringify` is exactly what I'd apply ;-)

**Comment by domenic** [comment]
And then we have the usual using-high-level-features-in-the-assertion-library problem...

**Comment by smikes** [comment]
http://img.pandawhale.com/post-31089-lego-wonder-woman-dangit-gif-I-hSUu.gif

**Comment by smikes** [comment]
How about French quotes?   «»

**Comment by bterlson** [comment]
I don't see a problem with french quotes, personally.

**Comment by domenic** [comment]
French quotes, or even smart quotes perhaps, work for me.

**Comment by smikes** [comment]
K. I will write a pr with French quotes. As long as it's not backticks.
