### ISSUE TITLE
Add test appending small value in a very long array

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1743]
This is feedback after reviewing this [contributed test](https://github.com/tc39/test262/blob/master/implementation-contributed/javascriptcore/stress/concat-append-one-with-sparse-array.js)

- [ ] Append a small value in a very long array test is slow but maybe worth considering?

This is not connect to any specific part of the specs and creates a slow test. Should weight the value before addition.

**Comment by rwaldron** [comment]
I think this belongs in a stress test suite.
