### ISSUE TITLE
Review coverage for Object#hasOwnProperty, add coercions for the this value

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1748]
This is feedback after reviewing this [contributed test](https://github.com/tc39/test262/blob/master/implementation-contributed/javascriptcore/stress/exception-in-to-property-key-should-be-handled-early-in-object-methods.js)

- [ ] Review coverage for Object#hasOwnProperty, add coercions for the this value

**Comment by rwaldron** [comment]
These cases are all covered in: 

- https://github.com/tc39/test262/tree/main/test/built-ins/Object/prototype/hasOwnProperty
- https://github.com/tc39/test262/tree/main/test/built-ins/Object/prototype/propertyIsEnumerable
