### ISSUE TITLE
Needs coverage for Promise.all and racing handling of a local @@species

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1751]
This is feedback after reviewing this [contributed test](https://github.com/tc39/test262/blob/master/implementation-contributed/javascriptcore/stress/ignore-promise-species.js)

- [ ] add coverage for Promise.all and racing handling of a local @@species

**Comment by shvaikalesh** [comment]
Coverage for `@@species` being ignored is already there:
* [`Promise.all`](https://github.com/tc39/test262/blob/master/test/built-ins/Promise/all/species-get-error.js)
* [`Promise.allSettled`](https://github.com/tc39/test262/blob/master/test/built-ins/Promise/allSettled/species-get-error.js)
* [`Promise.race`](https://github.com/tc39/test262/blob/master/test/built-ins/Promise/race/species-get-error.js)
