### ISSUE TITLE
Add coverage for checking reserved names as global variables, using escape sequences.

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1759]
This is feedback after reviewing this [contributed test](https://github.com/tc39/test262/blob/master/implementation-contributed/javascriptcore/stress/reserved-word-with-escape.js) 

- [ ] Add coverage for checking reserved names - mostly var - as global variables, using escape sequences.

**Comment by rwaldron** [comment]
This is covered more extensively in https://github.com/tc39/test262/tree/master/test/language/identifiers
