### ISSUE TITLE
Review propertyHelper.js assertions for truthiness vs. === true

### ISSUE THREAD

**Issue by smikes** [tc39/test262#176]
I think the propertyHelper.js assertions for `enumerable: false` (etc) only check not-truthiness, instead of checking === false.  I will review them tomorrow and PR as needed.

I will try to finish up my work on Symbol.species.  I have a potential spec bug that I will raise tomorrow re: required function names.

Any code that needs reviewing or any other things worth taking a look at?  Suggestions welcome, /cc @bterlson @anba @domenic @rwaldron

**Comment by leobalter** [comment]
My best guess is that this is already fixed.
