### ISSUE TITLE
Prevent invalid YAML frontmatter in more cases

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/test262#1827]
https://github.com/tc39/test262/pull/1821/files#r222811633

We should apply the same fix as in #1821 to all the other frontmatter properties that output `foo: [bar, baz]`, i.e. `flags` and `includes` and possibly others.

Ref. #1817.

**Comment by rwaldron** [comment]
Superseded by [YAML formatting restrictions](https://github.com/tc39/test262/issues/1997)
