### ISSUE TITLE
Several dynamic-import tests flagged as async don't call $DONE

### ISSUE THREAD

**Issue by jdalton** [tc39/test262#1829]
Via https://github.com/tc39/test262/pull/1588#discussion_r222833499:

Based on [INTERPRETING](https://github.com/tc39/test262/blob/377f07f502890284d1e89ecb6b66343464fe14c0/INTERPRETING.md) async flagged tests should print `'Test262:AsyncTestComplete'` or `'Test262:AsyncTestFailure: ' + reason` by way of [`doneprintHandle`](https://github.com/tc39/test262/blob/master/harness/doneprintHandle.js). Without printing a complete or fail the interpretation can hit a test timeout and mark it as a test failure.

Tests affected:

```
test/language/module-code/dynamic-import/usage/nested-if-braceless-eval-gtbndng-indirect-update-dflt.js
test/language/module-code/dynamic-import/usage/nested-if-braceless-eval-gtbndng-indirect-update.js
test/language/module-code/dynamic-import/usage/nested-if-braceless-returns-promise.js
```

**Comment by rwaldron** [comment]
Excellent! Thanks for the report
