### ISSUE TITLE
buggy intl402/Locale/constructor-tag-tostring.js

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/test262#1847]
I think intl402/Locale/constructor-tag-tostring.js is buggy
At least one error here
for (const input of errors) {
  assert.throws(CustomError, function() {
    new Intl.Locale(input);
  }),
  `new Intl.Locale(${input}) throws CustomError`);
}

the ) between the } and , should be removed.
I think there are other problem in that test.

@rwaldron @Ms2ger

**Comment by FrankYFTang** [comment]
this is fixed by https://github.com/tc39/test262/pull/1841

**Comment by Ms2ger** [comment]
Broken in #1798.

CC @littledan @gsathya
