### ISSUE TITLE
numeric literal in 15.2.3.6-2-17-1

### ISSUE THREAD

**Issue by jmdyck** [tc39/test262#185]
test/built-ins/Object/defineProperty/15.2.3.6-2-17-1.js
has the line:
     Object.defineProperty(obj, 000001, {});
but 000001 is not a valid token according to the main body of the spec.
(I think it's valid according to Annex B.)

**Comment by anba** [comment]
Legacy issue: https://bugs.ecmascript.org/show_bug.cgi?id=1532

Old bug reports from bugs.ecmascript.org should probably be merged to the GH issue tracker.
