### ISSUE TITLE
string literal in S15.5.4.11_A5_T1

### ISSUE THREAD

**Issue by jmdyck** [tc39/test262#186]
test/built-ins/String/prototype/replace/S15.5.4.11_A5_T1.js
has the line:

    $ERROR('.... /^(a+)\1*,\1+$/ ....'+...);

but the occurrences of `\1` within a string literal are not valid according to the main body of the spec.
(Looks like it's a LegacyOctalEscapeSequence in Annex B.)

**Comment by anba** [comment]
Another legacy issue: https://bugs.ecmascript.org/show_bug.cgi?id=1531
