### ISSUE TITLE
regex named groups tests using eval

### ISSUE THREAD

**Issue by bakkot** [tc39/test262#1882]
The tests in the following files are checking for syntax errors in regex literals using `eval`:
- [non-unicode-malformed.js](https://github.com/tc39/test262/blob/3936950114fcdf49ece33bbbc52b71ac4ebbb32c/test/built-ins/RegExp/named-groups/non-unicode-malformed.js)
- [non-unicode-property-names.js](https://github.com/tc39/test262/blob/3936950114fcdf49ece33bbbc52b71ac4ebbb32c/test/built-ins/RegExp/named-groups/non-unicode-property-names.js)
- [unicode-malformed.js](https://github.com/tc39/test262/blob/3936950114fcdf49ece33bbbc52b71ac4ebbb32c/test/built-ins/RegExp/named-groups/unicode-malformed.js)
- [unicode-property-names.js](https://github.com/tc39/test262/blob/3936950114fcdf49ece33bbbc52b71ac4ebbb32c/test/built-ins/RegExp/named-groups/unicode-property-names.js)

This makes them much less useful for parsers (ref #1356). Would y'all accept a PR splitting each negative test from these into its own file with the standard parse-error frontmatter?

(cc @jugglinmike)

**Comment by leobalter** [comment]
@bakkot sure thing! This would require lots of test files (one per each case) but I'd welcome a PR.
