### ISSUE TITLE
early-dup-export-as-star-as.js path incorrect.

### ISSUE THREAD

**Issue by jdalton** [tc39/test262#1883]
The path here is a bare import and needs the relative "./" path prefix:

* https://github.com/tc39/test262/blob/d1ad8e8fbc75132bacef6712e6b792d15275a3fb/test/language/module-code/early-dup-export-as-star-as.js

* https://github.com/tc39/test262/blob/d1ad8e8fbc75132bacef6712e6b792d15275a3fb/test/language/module-code/early-dup-export-star-as-dflt.js

**Comment by rwaldron** [comment]
Thanks!
