### ISSUE TITLE
assertFalse in test/intl402/Segmenter/prototype/segment/segment-*-iterable.js

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/test262#1904]
The following fail because there are no definition of assertFalse

test/intl402/Segmenter/prototype/segment/segment-word-iterable.js
test/intl402/Segmenter/prototype/segment/segment-grapheme-iterable.js
test/intl402/Segmenter/prototype/segment/segment-line-iterable.js
test/intl402/Segmenter/prototype/segment/segment-sentence-iterable.js

assertFalse(iter.following());

should be
assert.sameValue(false, iter.following());

@Ms2ger

**Comment by leobalter** [comment]
for consistency please use the first argument for the actual value and the second for the expected one.

```js
assert.sameValue(iter.following(), false);
```

**Comment by leobalter** [comment]
@FrankYFTang: I just sent a new PR with a quick fix on #1905

**Comment by Ms2ger** [comment]
Thanks for fixing; it shouldn't happen again.
