### ISSUE TITLE
No tests for Number.prototype.toLocaleString()

### ISSUE THREAD

**Issue by keithamus** [tc39/test262#195]
The spec defines that [Number.prototype.toLocaleString exists](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-number.prototype.tolocalestring), and is used for the new ES-402 Intl spec.

There are no existing tests for Number.prototype.toLocaleString in test262.

I believe it is likely that they can be based off of an existing set - for example the [Date.prototype.toLocaleString set](https://github.com/tc39/test262/tree/master/test/built-ins/Date/prototype/toLocaleString).

**Comment by leobalter** [comment]
This is implementation defined, we can't test this.

> If an ECMAScript implementation does not include the ECMA-402 API the following specification of the toLocaleString method is used.

>  This function is implementation-dependent, and it is permissible, but not encouraged, for it to return the same thing as toString.
