### ISSUE TITLE
Add a test for "undeclared = (this.undeclared = 5);" in global scope

### ISSUE THREAD

**Issue by DavidBruant** [tc39/test262#1964]
```js
"use strict";
var ok = false;
try {
    undeclared = (this.undeclared = 5);
} catch (exc) {
    ok = exc instanceof ReferenceError;
}
assertEq(ok, true);
```

Found here: https://bugzilla.mozilla.org/show_bug.cgi?id=605515
Apparently, Firefox still fails this part of the spec

I tried to look for an existing test, but it was too hard and i failed
I'm happy to contribute the test if directed to the right direction

**Comment by mathiasbynens** [comment]
It seems https://github.com/tc39/test262/tree/master/test/language/identifier-resolution might be a reasonable location for a new test. @leobalter @rwaldron WDYT?
