### ISSUE TITLE
Invalid tests in "computed-property-names"

### ISSUE THREAD

**Issue by anba** [tc39/test262#198]
The following tests are invalid.

test/language/computed-property-names/class/method/constructor-cannot-be-generator.js
test/language/computed-property-names/class/method/constructor-cannot-be-getter.js
test/language/computed-property-names/class/method/constructor-cannot-be-setter.js
test/language/computed-property-names/class/method/constructor-no-duplicate-1.js
test/language/computed-property-names/class/method/constructor-no-duplicate-2.js
test/language/computed-property-names/class/method/constructor-no-duplicate-3.js

- Expected: Valid to create a property named "constructor" if the property name is a computed property name

test/language/computed-property-names/class/static/generator-constructor.js
test/language/computed-property-names/class/static/getter-constructor.js
test/language/computed-property-names/class/static/method-constructor.js
test/language/computed-property-names/class/static/setter-constructor.js

- Expected: Valid to create a static property named "constructor"

test/language/computed-property-names/class/static/generator-prototype.js
test/language/computed-property-names/class/static/getter-prototype.js
test/language/computed-property-names/class/static/method-prototype.js
test/language/computed-property-names/class/static/setter-prototype.js

- Expected: `TypeError` at runtime.

**Comment by rwaldron** [comment]
I can clean this up.

**Comment by rwaldron** [comment]
I'm not sure about this: 


> test/language/computed-property-names/class/method/constructor-cannot-be-generator.js
> test/language/computed-property-names/class/method/constructor-cannot-be-getter.js
> test/language/computed-property-names/class/method/constructor-cannot-be-setter.js
> test/language/computed-property-names/class/method/constructor-no-duplicate-1.js
> test/language/computed-property-names/class/method/constructor-no-duplicate-2.js
> test/language/computed-property-names/class/method/constructor-no-duplicate-3.js
>
> - Expected: Valid to create a property named "constructor" if the property name is a computed property name

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-static-semantics-constructormethod specifically, the non-normative note: 

"Early Error rules ensure that there is only one method definition named "constructor" and that it is not an accessor property or generator definition."


https://people.mozilla.org/~jorendorff/es6-draft.html#sec-class-definitions-static-semantics-early-errors

Have I misinterpreted this?

**Comment by rwaldron** [comment]
> test/language/computed-property-names/class/static/generator-constructor.js
> test/language/computed-property-names/class/static/getter-constructor.js
> test/language/computed-property-names/class/static/method-constructor.js
> test/language/computed-property-names/class/static/setter-constructor.js
>
> - Expected: Valid to create a static property named "constructor"

Fixed




> test/language/computed-property-names/class/static/generator-prototype.js
> test/language/computed-property-names/class/static/getter-prototype.js
> test/language/computed-property-names/class/static/method-prototype.js
> test/language/computed-property-names/class/static/setter-prototype.js
> 
> - Expected: TypeError at runtime.

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-class-definitions-static-semantics-early-errors

ClassElement : static MethodDefinition
  - It is a Syntax Error if HasDirectSuper of MethodDefinition is true.
  - It is a Syntax Error if PropName of MethodDefinition is "prototype".

**Comment by anba** [comment]
The early error rules only cover properties with the bare name "constructor" (or "prototype").

**Comment by rwaldron** [comment]
That's very strange.

**Comment by anba** [comment]
Specifically, PropName (12.2.5.6) of a ComputedPropertyName is `empty`.

**Comment by anba** [comment]
Related: https://bugs.ecmascript.org/show_bug.cgi?id=4140

**Comment by rwaldron** [comment]
That's helpful, thanks.

**Comment by rwaldron** [comment]
@anba 

> Expected: TypeError at runtime.

Can you point me to this?

**Comment by anba** [comment]
.prototype property of classes is non-writable + non-configurable (14.5.14 step 16 -> 9.2.8 step 8).

```
js> Object.getOwnPropertyDescriptor(class {}, "prototype")
{ value: {}, writable: false, enumerable: false, configurable: false }
```

**Comment by rwaldron** [comment]
> 14.5.14 step 16 -> 9.2.8 step 8

That's what I needed, thanks!

**Comment by rwaldron** [comment]
So, that wasn't done yet...

**Comment by anba** [comment]
test/language/computed-property-names/class/method/constructor-cannot-be-generator.js
test/language/computed-property-names/class/method/constructor-cannot-be-getter.js
test/language/computed-property-names/class/method/constructor-cannot-be-setter.js

Still need to be updated.

**Comment by rwaldron** [comment]
@anba https://github.com/tc39/test262/pull/202

**Comment by bterlson** [comment]
Alright I think this is actually done now :)
