### ISSUE TITLE
Invalid tests in test/language/block-scope

### ISSUE THREAD

**Issue by anba** [tc39/test262#201]
test/language/block-scope/syntax/for-in/missing-identifier-let-disallowed-as-bound-name.js

- Expected: `let` is allowed as IdentifierReference in `for-in` (lookahead restriction only applies to `let [`).

test/language/block-scope/syntax/let-declarations/without-initialisers-in-statement-positions-case-expression-statement-list.js
test/language/block-scope/syntax/let-declarations/without-initialisers-in-statement-positions-default-statement-list.js

- Expected: `LexicalDeclaration` is allowed (DefaultClause -> StatementList -> Declaration -> LexicalDeclaration), and `Initializer` expression is not mandatory.
 
test/language/block-scope/syntax/function-declarations/in-statement-position-label-statement.js

- Expected: Labelled function declarations are only allowed per B.3.2, but the test case is not placed in the "annexB" directory.

**Comment by rwaldron** [comment]
What would I do without you? :)

**Comment by rwaldron** [comment]
> test/language/block-scope/syntax/for-in/missing-identifier-let-disallowed-as-bound-name.js

> - Expected: let is allowed as IdentifierReference in for-in (lookahead restriction only applies to let [).

In https://people.mozilla.org/~jorendorff/es6-draft.html#sec-for-in-and-for-of-statements-static-semantics-early-errors : 

IterationStatement :
  for ( ForDeclaration in Expression ) Statement
  for ( ForDeclaration of AssignmentExpression ) Statement

- It is a Syntax Error if the BoundNames of ForDeclaration contains "let".


> Expected: LexicalDeclaration is allowed (DefaultClause -> StatementList -> Declaration -> LexicalDeclaration), and Initializer expression is not mandatory.

Fixed

> Expected: Labelled function declarations are only allowed per B.3.2, but the test case is not placed in the "annexB" directory.

Fixed.

**Comment by anba** [comment]
`for (let in {}) { }` should parse as
`for (LeftHandSideExpression in Expression) Statement`
where `LeftHandSideExpression` is the `IdentifierReference` "let". 

The early error restriction only applies to `for (let let in {}) { }`.

**Comment by rwaldron** [comment]
@anba thanks for the clarification.

For reference: 

```
ForDeclaration : 
  LetOrConst ForBinding

LetOrConst :  
  let 
  const 

ForBinding : BindingIdentifier
  
```

I will file bugs for V8 and SpiderMonkey
