### ISSUE TITLE
Extra new line in YAML frontmatter breaks our parser

### ISSUE THREAD

**Issue by gsathya** [tc39/test262#2034]
New line after the `info:` block is breaking our YAML parser.

```
diff --git a/test/language/expressions/postfix-decrement/arguments.js b/test/language/expressions/postfix-decrement/arguments.js
index 6e6bc0c89d..3d12f33026 100644
--- a/test/language/expressions/postfix-decrement/arguments.js
+++ b/test/language/expressions/postfix-decrement/arguments.js
@@ -6,7 +6,6 @@ esid: sec-update-expressions
 description: >
   It is an early Syntax Error if AssignmentTargetType of LeftHandSideExpression is strict. (arguments)
 info: |
-
   sec-identifiers-static-semantics-assignmenttargettype
 
     If this IdentifierReference is contained in strict mode code and StringValue of Identifier is "eval" or  "arguments", return strict.
```

Off topic but it looks like this was introduced quite recently with https://github.com/tc39/test262/pull/2005, why wasn't the CI run against this? Would it have caught this breakage?

**Comment by gsathya** [comment]
Following tests are affected:
  'language/expressions/postfix-decrement/arguments': [FAIL],
  'language/expressions/postfix-decrement/arguments-nostrict': [FAIL],
  'language/expressions/postfix-decrement/eval': [FAIL],
  'language/expressions/postfix-decrement/eval-nostrict': [FAIL],
  'language/expressions/postfix-increment/arguments': [FAIL],
  'language/expressions/postfix-increment/arguments-nostrict': [FAIL],
  'language/expressions/postfix-increment/eval': [FAIL],
  'language/expressions/postfix-increment/eval-nostrict': [FAIL],
  'language/expressions/prefix-decrement/arguments': [FAIL],
  'language/expressions/prefix-decrement/arguments-nostrict': [FAIL],
  'language/expressions/prefix-decrement/eval': [FAIL],
  'language/expressions/prefix-decrement/eval-nostrict': [FAIL],
  'language/expressions/prefix-increment/arguments': [FAIL],
  'language/expressions/prefix-increment/arguments-nostrict': [FAIL],
  'language/expressions/prefix-increment/eval': [FAIL],
  'language/expressions/prefix-increment/eval-nostrict': [FAIL],

**Comment by leobalter** [comment]
I've been working on these and I experimented with some of the RegExp in the parseTestRecord fix. This is helping me with the linter. I should have a PR for the linter on Monday.
