### ISSUE TITLE
Missing test case for private fields storing functions

### ISSUE THREAD

**Issue by caiolima** [tc39/test262#2066]
Some VM's, such as JSC, treats ```o.member()``` as a special AST node. In such case, it would be valuable having a test case for private fields covering ```o.#member()``` case, where ```#member = () => 'test252';``` for example.

**Comment by littledan** [comment]
Sounds like a great idea to test the combination here, analogously to how many template tests get at other combinations.

**Comment by leobalter** [comment]
#2067 should have fixed this.
