### ISSUE TITLE
default class export test.

### ISSUE THREAD

**Issue by jdalton** [tc39/test262#2068]
Just giving a heads up, one of our users [noticed that there's a gap](https://github.com/standard-things/esm/issues/725) in test coverage for:
```js
export default function Test() {}
Test.something = "ok";
```

**Comment by leobalter** [comment]
Thanks for reporting this! I'll take a look.

**Comment by adrianheine** [comment]
Just wanted to report the same. There's also the inverse case of `class Test {}; export default class Test {};` that's not covered.
