### ISSUE TITLE
Private access from `super` is invalid syntax

### ISSUE THREAD

**Issue by caiolima** [tc39/test262#2071]
Test `src/class-elements/private-field-super-access-throws.case` is verifying private fields super access. However this is invalid syntax and should throw SyntaxError instead.

Looking private fields proposal, we have changes on [`MemberExpression`](https://tc39.github.io/proposal-class-fields/#prod-MemberExpression), however this rule doesn't include `super.PrivateIdentifier` as valid. Check [https://tc39.github.io/ecma262/#prod-MemberExpression](https://tc39.github.io/ecma262/#prod-MemberExpression) for clarification.

**Comment by adrianheine** [comment]
I don't understand why `SuperProperty` . `PrivateIdentifier` is not valid. `MemberExpression` . `PrivateIdentifier` is valid, and `SuperProperty` is a valid `MemberExpression`.

**Comment by caiolima** [comment]
Hi @adrianheine.
`SuperProperty`.`PrivateIdentifier` is valid. What is not valid is `super`.`PrivateIdentifier`. The identifier `super` alone is not a valid syntax. It needs to be a `SuperCall` (I.e `super()`) or a `super.property`. Does it make sense?

**Comment by adrianheine** [comment]
Yeah, thanks, that makes sense :)
