### ISSUE TITLE
get and set in MethodDefinition must not be escaped

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/test262#2078]
@verwaest found this gem. Only SpiderMonkey and xs get this one right:

```
$ eshost -e "eval(\"({\\\\u0067et x() { print('hello')}})\").x"
#### V8 --harmony
hello
undefined

#### SpiderMonkey
SyntaxError: missing : after property id:

#### JavaScriptCore
hello
undefined

#### Chakra
hello
undefined

#### V8
hello
undefined

#### xs
SyntaxError: escaped keyword
```

https://tc39.github.io/ecma262/#sec-method-definitions

**Comment by leobalter** [comment]
https://test262.report/browse/language/expressions/object/method-definition/escaped-get.js
https://test262.report/browse/language/expressions/object/method-definition/escaped-set.js

V8 is passing for these tests. I'll identify what makes it fail and accept the escaped version.

**Comment by leobalter** [comment]
running locally, V8 is not passing as you reported...

**Comment by leobalter** [comment]
and it was a human error, I updated V8 locally and it's not capturing the syntax error as test262.report shows. 

@mathiasbynens do you think we need more tests than those files I listed above? I'll close this issue but feel free to reopen it if necessary.

**Comment by mathiasbynens** [comment]
It was [fixed](https://github.com/v8/v8/commit/a94c91ca4825c90c2015c5f800aaebcc0b345625) in V8 after I posted this issue. The commit includes a bunch of other similar cases (where escaped keywords previously got accepted incorrectly). It would be good to make sure these are all covered in Test262.

Thanks!
