### ISSUE TITLE
Missing coverage for interaction of rest properties with number literal keys and numeric computed keys

### ISSUE THREAD

**Issue by adrianheine** [tc39/test262#2089]
Examples:
```js
const source = { 1: 'one', 2: 'two' };
const { 1.: _, ...rest } = source;
assert(!(1 in rest));
```
```js
const source = { 1: 'one', 2: 'two' };
const { 1e0: _, ...rest } = source;
assert(!(1 in rest));
```
```js
const source = { 1: 'one', 2: 'two' };
const { [1+0]: _, ...rest } = source;
assert(!(1 in rest));
```

**Comment by leobalter** [comment]
Thanks for reporting this. It's an interested part to be covered.

cc @caiolima

**Comment by caiolima** [comment]
Sorry for delay here! I'll update this later this week.

**Comment by rwaldron** [comment]
@leobalter @caiolima did this ever get resolved?

**Comment by caiolima** [comment]
I don't think it was solved. I don't remember adding those cases and last update on obj rest tests are from https://github.com/tc39/test262/commit/29627e892be455f2685057a68d62c64e0d7aa30c

**Comment by shvaikalesh** [comment]
JSC bug: [Add the property to be excluded from the rest operation of the object as string](https://bugs.webkit.org/show_bug.cgi?id=216437).

A coverage PR is on the way.

**Comment by rwaldron** [comment]
Resolved in https://github.com/tc39/test262/commit/be99a3e519841d2f495cc64a272a1e3eb4440b5b
