### ISSUE TITLE
missing coverage for static methods in classes

### ISSUE THREAD

**Issue by devsnek** [tc39/test262#2090]
for the following class: `class X { static y() {} }`

my engine was returning `'static y() {}'` for `X.y.toString()`. the correct behaviour would be to not include the `static` part, and just return `'y() {}'`.

Unfortunately this was not caught by test262, and from searching through the tests i was unable to find anything testing this specific case.

**Comment by littledan** [comment]
Cc @michaelficarra

**Comment by michaelficarra** [comment]
This is already being tested both in https://github.com/tc39/test262/blob/9339f8a5ce1faab7ec823e479e19f2334553bdba/test/built-ins/Function/prototype/toString/method-class-expression-static.js#L11-L17 and https://github.com/tc39/test262/blob/9339f8a5ce1faab7ec823e479e19f2334553bdba/test/built-ins/Function/prototype/toString/method-class-statement-static.js#L11-L21

**Comment by devsnek** [comment]
ok so it appears the test runner was skipping tests that use `nativeFunctionMatcher.js` lol sorry about the wild goose chase.

**Comment by michaelficarra** [comment]
Yeah I was pretty surprised to see this issue; the `Function.prototype.toString` tests are pretty thorough.
