### ISSUE TITLE
built-ins/Function/prototype/toString/method-computed-property-name.js

### ISSUE THREAD

**Issue by patrick-soquet** [tc39/test262#2092]
Sorry if it has already been reported, but in this test case
`let g = { [ { a(){} }.a ](){ } }["a(){}"];`
requires that 
`{ a(){} }.a.toString()` 
returns 
`"a(){}"`
while it should be OK to return something like
`"function a (){[native code]}"`
Thank you !

**Comment by ljharb** [comment]
This is already correct; see the recently merged stage 4 proposal for improving Function.prototype.toString.
