### ISSUE TITLE
Tests related to ES5 step 13.2.19 are not valid in ES6

### ISSUE THREAD

**Issue by caitp** [tc39/test262#211]
Per https://people.mozilla.org/~jorendorff/es6-draft.html#sec-forbidden-extensions --- for strict functions, and for functions created by new syntactic forms (method definitions, generators, arrow functions, class constructors), no "own" properties "caller" or "arguments" are created.

These properties are defined as accessors which throw, only on the intrinsic %FunctionPrototype% object, with `PropertyDescriptor {[[Get]]: thrower, [[Set]]: thrower, [[Enumerable]]: false, [[Configurable]]: true}).`

Tests relating to this should probably live in a new directory specific to "forbidden extensions" under "language", and should be updated to reflect the current state of the spec

**Comment by caitp** [comment]
List of affected tests:

(Some of these may no longer exist, or may no longer be invalid --- list was collected from the ES5 build of test262 in v8, not yet culled fixed es6 tests from the list)
-  '13.2-29-s'
-  '13.2-30-s'
-  '13.2-31-s'
-  '13.2-32-s'
-  '13.2-33-s'
-  '13.2-34-s'
-  '13.2-35-s'
-  '13.2-36-s'
-  'S13.2.3_A1'
-  '15.3.4.5-20-1'
-  '15.3.4.5-20-4'
-  '15.3.4.5-20-5'
-  '15.3.4.5-21-1'
-  '15.3.4.5-21-4'
-  '15.3.4.5-21-5'

**Comment by anba** [comment]
> --- nah I'm pretty sure those are all still broken :>

Yep -> https://github.com/anba/es6draft/blob/master/src/test/resources/excludelist.xml#L68-L83
