### ISSUE TITLE
Add coverage for Promise.allSettled proposal

### ISSUE THREAD

**Issue by rpamely** [tc39/test262#2112]
This issue is to track the progress of the test262 coverage of the stage 3 Promise.allSettled proposal. https://github.com/tc39/proposal-promise-allSettled

Suggestions for tests welcome, and I will update this text. The tests for Promise.all are a good place to start.

@mathiasbynens @jasonwilliams

**Comment by rpamely** [comment]
@domenic previously posted when reviewing the spec:

> Reviewing the spec text, I was reminded of the extra care we put in to making Promise.all behave reasonably in the face of weird promise subclasses and similar scenarios, e.g. with the [[AlreadyResolved]] internal slot. I think those are pretty exhaustively tested in existing test262, and this issue is about making sure the same is done for Promise.allSettled.
> 
> When writing test262 tests, please be sure to test all the same weird edge cases that can occur as with Promise.all---plus the extra ones introduced by the reject element function and its interactions.

**Comment by mathiasbynens** [comment]
@anba wrote some tests while working on his SpiderMonkey implementation: https://phabricator.services.mozilla.com/D25209#change-qATBO8Ktuxxu

**Comment by astlaurent1** [comment]
I got myself up and running with one test: https://github.com/astlaurent1/test262/commit/ade44b415ec4743526cca848ebab271ecee382cd. I had copied over a test from the Promise.all directory that I thought would behave the same, but I found slightly different behavior

Note: I'm running against a webpack'd version of the shim: https://github.com/astlaurent1/Promise.allSettled/commit/631acd603fd556ab8005165c785a64faf71f0cbb (use the file in `dist/` as the prelude)

Oh and `--prelude` is broken without this: https://github.com/bocoup/test262-stream/pull/23

**Comment by leobalter** [comment]
@astlaurent1 I'm porting the tests from Promise.all, I had my commits online but didn't open a PR while it's still a WIP. Now you can see it here: https://github.com/tc39/test262/pull/2124

One thing to consider is that a test should not be adapted to a shim, and maybe the shim might need a fix as well.

**Comment by leobalter** [comment]
Also, the plan is to review and port tests from SpiderMonkey to Test262, I just need to finish one thing to start another.

**Comment by astlaurent1** [comment]
@leobalter Very cool! Thank you for commenting. My efforts were still a good learning exercise (and uncovered a recent bug in test262-harness), so no wasted time there

Is there a communication channel where people discuss what they're working on? I'd like to contribute in general, and would prefer to know that I'm not duplicating efforts when I pick something up

> One thing to consider is that a test should not be adapted to a shim, and maybe the shim might need a fix as well.

Oh, absolutely! I highlighted the behavior difference with this in mind, but did not communicate that explicitly.

**Comment by leobalter** [comment]
Coverage is done. 

> Is there a communication channel where people discuss what they're working on?

@astlaurent1 Not much other than flagging on the issues/PRs here. There is a #test262 channel on Mozilla IRC but it's not very active.
