### ISSUE TITLE
testing HostEnsureCanCompileStrings

### ISSUE THREAD

**Issue by mikesamuel** [tc39/test262#2120]
It's possible to test corner cases around [HostEnsureCanCompileStrings](https://tc39.github.io/ecma262/#sec-hostensurecancompilestrings) from a browser or command line using tricks like those in [tc39/ecma262 issue #1495](https://github.com/tc39/ecma262/issues/1495):

> ```html
> <meta http-equiv="Content-Security-Policy" content="script-src 'nonce-test'">
> <script nonce="test">
> // Code to run with HostEnsureCanCompileStrings is false
> </script>
> ```

or

> ```sh
> $ npx node@10 --disallow_code_generation_from_strings -e '// Code to run'
> ```

Quite a few of these interactions could be tested if there was simply a way to get HostEnsureCanCompileStrings to throw for a particular testcase without breaking tests that assumes it returns normally like those under [test/language/eval-code](https://github.com/tc39/test262/tree/master/test/language/eval-code).

Even more interactions could be tested if it could be turned off only for particular values of *calleeRealm*.

**Comment by mikesamuel** [comment]
Apparently web-platform-tests provides an alternative for JS engines that are used in browsers.

**Comment by rwaldron** [comment]
The associated PR https://github.com/tc39/ecma262/pull/1498 hasn't had author activity since June 2019. We can reopen here if there is anything that needs to be done in Test262
