### ISSUE TITLE
YAML issues with indentated front matter?

### ISSUE THREAD

**Issue by arv** [tc39/test262#215]
The following files have indented the front matter:

built-ins/Array/prototype/Symbol.iterator/property-descriptor.js
built-ins/Array/prototype/Symbol.iterator/prototype/Symbol.toStringTag/property-descriptor.js
built-ins/Array/prototype/Symbol.iterator/prototype/next/property-descriptor.js
built-ins/Array/prototype/entries/property-descriptor.js
built-ins/Array/prototype/keys/property-descriptor.js

This is causing issues on one of our (v8) bots. It is probably picking up a YAML parser that does not work as expected.

@smikes

**Comment by smikes** [comment]
Thanks!  I will take a look at it. If it is using the fallback parser (monkeyYaml) then indeed, it's vulnerable to indentation.

**Comment by smikes** [comment]
Candidate fix in PR #216 ; unfortunately my environment has the 'real' YAML parser so the easiest way to test is to throw it to the wolves...
