### ISSUE TITLE
en-us-numeric-auto.js seems broken

### ISSUE THREAD

**Issue by jorendorff** [tc39/test262#2205]
Commit 6fd738d added some exceptions in intl402/RelativeTimeFormat/prototype/format/en-us-numeric-auto.js, but the script isn't written to handle an element that doesn't have all three properties `1`, `0`, and `-1`. Consequently, this test now asserts that `rtf.format(1, "minute")` returns **undefined**.

**Comment by leobalter** [comment]
I believe this has been handled by 9d0072df3d and 6fd738d396.
