### ISSUE TITLE
invoke-resolve-get-error-close might be wrong

### ISSUE THREAD

**Issue by devsnek** [tc39/test262#2206]
built-ins/Promise/all/invoke-resolve-get-error-close.js
built-ins/Promise/race/invoke-resolve-get-error-close.js
built-ins/Promise/allSettled/invoke-resolve-get-error-close.js

I believe that: these tests expect that `returnCount` is `0`, but `IteratorClose` calls `return`, which increments `returnCount` to `1`.

If this is correct, I will open a PR to fix it.

**Comment by devsnek** [comment]
tentatively cc @leobalter

**Comment by shvaikalesh** [comment]
`IteratorClose` is called only if `iteratorRecord.[[Done]] is false`, which won't happen if `Get(constructor, "resolve")` returns abrupt completion, right?

**Comment by leobalter** [comment]
nice! yes, and the info is already mentioning this:

```
    11. Let result be PerformPromiseAll(iteratorRecord, C, promiseCapability).
    12. If result is an abrupt completion,
        a. If iteratorRecord.[[done]] is false, let result be
           IteratorClose(iterator, result).
        b. IfAbruptRejectPromise(result, promiseCapability).
```

> If this is correct, I will open a PR to fix it.

please!
