### ISSUE TITLE
Double Rounding Floating Point Tests Lacking Commentry on Motivation for Test

### ISSUE THREAD

**Issue by edgemaster** [tc39/test262#222]
I've spent quite a while trying to work out the motivation for two floating point tests: 
- ch08/8.5/S8.5_A2.1.js
- ch08/8.5/S8.5_A2.2.js

It'd be helpful if some comment could be added explaining the motivation for these tests. I've found what appears to be the inspiration/reason for these test cases here:
http://www.vinc17.org/research/extended.en.html#intro-dr

**Comment by Yaffle** [comment]
@edgemaster where to find shose files?

**Comment by Yaffle** [comment]
@edgemaster 
I think you are talking about
https://github.com/tc39/test262/blob/master/test/language/types/number/S8.5_A2.1.js and
https://github.com/tc39/test262/blob/master/test/language/types/number/S8.5_A2.2.js

If yes, the information about "round to nearest, ties to even" can be found at your link OR at
http://en.wikipedia.org/wiki/Rounding#Round_half_to_even

Actually, both those tests are not well written:
1) they should use `2 / Number.EPSILON + 2` for `x`, so the test will not depend on hardcoded number of mantissa bits.
2) those files have same tests, one of them can be removed.

**Comment by edgemaster** [comment]
Sorry, yes -- I hadn't realised the test suite had been reorganised, I've been working with the ES5 branch.
My knowledge of Floating Point rounding is nowhere good enough to comment on those tests, other than trying to debug an implementation from the details given at the moment in the testcases is infuriating!
(It was an x87 floating point unit bug...)

**Comment by leobalter** [comment]
> It was an x87 floating point unit bug...

Closing. Please re-open if necessary.
