### ISSUE TITLE
do not use compareArray(Object.keys(...

### ISSUE THREAD

**Issue by drsm** [tc39/test262#2226]
It doesn't guarantee an order of keys.
see `test262/test$ grep -r 'compareArray(Object.keys(' .`

**Comment by leobalter** [comment]
I strongly believe it does. PTAL at the code behind compareArray:

```
function compareArray(a, b) {
  if (b.length !== a.length) {
    return false;
  }

  for (var i = 0; i < a.length; i++) {
    if (b[i] !== a[i]) {
      return false;
    }
  }
  return true;
}
```

The same goes for `Object.keys`, which relies in the order of [`[[OwnPropertyKeys]]`](https://tc39.es/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys).

Would you mind clarifying what I'm missing here?

**Comment by drsm** [comment]
@leobalter 

Hi!

> The same goes for Object.keys, which relies in the order of [[OwnPropertyKeys]].

The `Object.keys()` gets [7.3.21 EnumerableOwnPropertyNames](https://tc39.es/ecma262/#sec-enumerableownpropertynames)
> 7.3.21.5 Order the elements of properties so they are in the same relative order as would be produced by the Iterator that would be returned if the EnumerateObjectProperties internal method were invoked with O.

And [13.7.5.15 EnumerateObjectProperties ( O )](https://tc39.es/ecma262/#sec-enumerate-object-properties) does not guarantee any order:
> The mechanics and order of enumerating the properties is not specified but must conform to the rules specified below.

For Object.keys() here is a guarantee that the order of `for in` is the same, but is is unspecified.

 So, the proper implementation may return items in chronological order, I think.

Please correct me if I'm wrong.

**Comment by leobalter** [comment]
the rules specified for EnumerateObjectProperties requires observation of [[OwnPropertyKeys]] and [[GetOwnProperty]]. Object.keys also won't get any value making it pretty static.

In this case, or at least with the examples pointed in the tests, the `for in` order here is pretty static and predictable as well.

If I'm not wrong, the loose part of EnumerateObjectProperties relates to dynamic modifications of the properties and their enumerability doing iteration within the given object.

Using a proxy or calling EnumerableOwnPropertyNames with a `kind` argument different than `key` would make allow it being non-static.

This might be different in a module namespace object but there are no matching tests for these cases using `compareArray(Object.keys(..`

cc @allenwb, who can help with more information on this.

**Comment by drsm** [comment]
[Here](https://github.com/tc39/test262/blob/master/test/language/computed-property-names/object/method/number.js) is the test that fails for `njs` :
```js
var object = {
  a() { return 'A'; },
  [1]() { return 'B'; },
  c() { return 'C'; },
  [ID(2)]() { return 'D'; },
};
assert(
  compareArray(Object.keys(object), ['1', '2', 'a', 'c']),
  "`compareArray(Object.keys(object), ['1', '2', 'a', 'c'])` returns `true`"
);
```
as it returns property keys in order they are defined (chronological):
```js
>> var ID = (x) => x
undefined
>> var o = { a() { return 'A'; }, [1]() { return 'B'; }, c() { return 'C'; },  [ID(2)]() { return 'D'; }, }
undefined
>> Object.keys(o)
[
 'a',
 '1',
 'c',
 '2'
]
>> var a = [];
undefined
>> for (var k in o) a.push(k); a
[
 'a',
 '1',
 'c',
 '2'
]
```
And it is not a bug.

I think, the proper test should be:
```js
assert(
  compareArray(Object.getOwnPropertyNames(object), ['1', '2', 'a', 'c']),
  "`compareArray(Object.getOwnPropertyNames(object), ['1', '2', 'a', 'c'])` returns `true`"
);
```

**Comment by nicolo-ribaudo** [comment]
`Object.keys` uses [`EnumerableOwnPropertyNames`](https://tc39.es/ecma262/#sec-enumerableownpropertynames), which calls `[[OwnPropertyKeys]]`. For ordinary objects (like yours) it [defers](https://tc39.es/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys) to [`OrdinaryOwnPropertyKeys`](https://tc39.es/ecma262/#sec-ordinaryownpropertykeys), which is specified to first return numeric properties (step 2).

So yes, in your example it is a bug.

**Comment by drsm** [comment]
@nicolo-ribaudo 

But at step 5 of `EnumerableOwnPropertyNames` keys got from `OrdinaryOwnPropertyKeys` are reordered same way as in `for in`.

**Comment by jugglinmike** [comment]
In brief: I agree with @drsm that `Object.keys` is not suitable for use in this context.

Repeating the text that's been quoted above:

> The mechanics and order of enumerating the properties is not specified [...]

That seems pretty cut-and-dry to me. You might accuse me of cherry-picking, though, since that statement is immediately followed by a qualifier:

> [...] but must conform to the rules specified below.

Before we consider "the rules specified below," we should recognize how inconsistent it would be for the spec to make the first claim only to immediately reverse it with the following phrase. Reducing it down, it would read, "The order of properties is not specified except that it is."

Thankfully, there's (a little) more evidence in "the rules specified below."

> Enumerating the properties of the target object includes enumerating properties of its prototype, and the prototype of the prototype, and so on, recursively

The word "includes" does not imply an order, even if the plain-English list that follows does. (Consider, "the array includes 1 and 2 and 3.") Even within each prototype enumeration, the spec seems to be trying to avoid specifying an order:

> EnumerateObjectProperties must obtain the own property keys of the target object by calling its [[OwnPropertyKeys]] internal method.

This is how the keys are "obtained", but it doesn't dictate how they are enumerated.

**Comment by leobalter** [comment]
Thanks for the review, @jugglinmike! I helped me connecting some dots I missed before.

@drsm thanks for reporting this! I'll work on a fix for these tests soon.

**Comment by leobalter** [comment]
@drsm please checkout #2320 and let me know if I'm missing anything else.

**Comment by drsm** [comment]
@leobalter 

Thank you for the patch!
Looks fine.
