### ISSUE TITLE
Expand tests for WeakSet and WeakMap using the GC hook and FinalizationGroup

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#2227]
With the light of the new Garbage Collector (`$262.gc()`) and WeakRefs/FinalizationGroup, we can improve this test suite adding tests for WeakSet and WeakMap.

One idea for this new coverage, but not limited to, is to create a test for FinalizationGroup#cleanupSome calling the callback for an emptied object that was stored in a WeakMap and a WeakSet.

This can also assert the clearance of the same object in every list.

**Comment by mathiasbynens** [comment]
> This can also assert the clearance of the same object in every list.

Could you clarify how this could work? As long as you have a reference to a `WeakMap`/`WeakSet` key, it won't be garbage-collected (even when you call `$262.gc()`). If you no longer have a reference to the key, `$262.gc()` collects it. But then how would you assert that the key is gone (seeing as you no longer can have a reference to it)?

**Comment by leobalter** [comment]
I believe at this point we've handled this but I've missed reporting here. IIRC we resolved we can't reuse the GC property for deterministic ends to assert in Test262.
