### ISSUE TITLE
Test some RegularExpressionLiteral vs. DivPunctuator hard cases

### ISSUE THREAD

**Issue by jorendorff** [tc39/test262#2230]
[QuickJS](https://bellard.org/quickjs/) claims to pass test262, but its implementation of ASI isn't up to spec. It fails to parse examples like `{} /x/` (should be a regexp) and `of / 2` (should be division). Is it possible we don't have tests for such cases yet?

**Comment by leobalter** [comment]
@rwaldron and I are currently working to add QuickJS to eshost and run Test262 using test262-harness, so we could even add them to https://test262.report. 

I'd like to see the results from Test262 with it as 100% would be quite impressive. Although, I know it does not support some features like realms and TCO so it's not really 100%, but I hope to see a total percentage even removing the non supported parts.

**Comment by rwaldron** [comment]
I started working on an `eshost` runtime and agent yesterday, but ran into an issue where Fabrice has implemented `$262` in a special `run-test262` program, but not in `qjs` and with built in way to enable it. I'm going to email him and ask if he could make that possible.

**Comment by rwaldron** [comment]
I've just sent an email explaining the needs we have for Test262 and hopefully my ask isn't too much :D I'll post an update here when I know more.

**Comment by leobalter** [comment]
Browsing the tests I've found this test case only that relates to this issue:

```js
{1} 2
```

I'll expand the coverage to include the mentioned cases.

**Comment by leobalter** [comment]
this should be fixed at #2243 and #2244, thanks for the report!
