### ISSUE TITLE
Object.create properties parameter can be a non-object

### ISSUE THREAD

**Issue by kmiller68** [tc39/test262#2237]
JSC got a bug report on this. It appears all other engines pass the test but I didn't see a test262 checking correct behavior. I made this test for JSC, perhaps it could be ported to test262?

```js
let toObjectablePrimitives = [true, false, 1, 2, "hello", Symbol(), BigInt(1)];

for (let primitive of toObjectablePrimitives)
    Object.create({}, 2);

try {
    Object.create({}, null);
} catch (e) {
    if (!(e instanceof TypeError))
        throw e;
}
```

**Comment by leobalter** [comment]
sure thing! Sounds like something is missing from this for loop:

```js
for (let primitive of toObjectablePrimitives)
    Object.create({}, 2);
```

Should it be `Object.create({}, primitive);`?

**Comment by kmiller68** [comment]
Ooof! nice catch...

**Comment by leobalter** [comment]
I'm currently browsing the existing tests and looking for any match. So far I believe we are missing these cases in Test262.

I'm writing a port test and I'll ping you soon.

**Comment by kmiller68** [comment]
I reran all the test262 tests with my change and I didn't see any tests change behavior, so I doubt this behavior is covered. Anyway I fixed the test on my end and had to make some changes. Here's the never version we have for reference:

```js
let toObjectablePrimitives = [true, false, 1, 2, "", Symbol(), BigInt(1)];

for (let primitive of toObjectablePrimitives)
    Object.create({}, primitive);

function shouldThrow(props) {
    try {
        Object.create({}, props);
    } catch (e) {
        if (!(e instanceof TypeError))
            throw e;
    }
}

shouldThrow("hello");
shouldThrow(null);
```

**Comment by leobalter** [comment]
Yes, I'm actually making a case for non-empty strings to finish the assertions.

**Comment by YaoHouyou** [comment]
@kmiller68 
Is this inspired by the JSC bug report.
https://bugs.webkit.org/show_bug.cgi?id=199744

Thank you very much!
