### ISSUE TITLE
gc-cleanup-not-prevented-with-wr-deref.js is invalid

### ISSUE THREAD

**Issue by kmiller68** [tc39/test262#2239]
I was looking through the new WeakRef tests and I noticed gc-cleanup-not-prevented-with-wr-deref.js, which I think has two bugs.

1) I think the WeakRef constructor prevents collection until the next event loop turn: https://tc39.es/proposal-weakrefs/#sec-weak-ref-target step 4.

2) There is no guarantee that as GC collect the target, which means it's still valid to return target at the assertion point.

Maybe I'm wrong though?

**Comment by leobalter** [comment]
> 1. I think the WeakRef constructor prevents collection until the next event loop turn: https://tc39.es/proposal-weakrefs/#sec-weak-ref-target step 4.

This is correct. I'd need to make the test async to fix this.

>  2. There is no guarantee that as GC collect the target, which means it's still valid to return target at the assertion point.

This part is super tricky.

If we see Execution:

> At any time, if an object obj is not live, an ECMAScript implementation may perform the following steps atomically:

It is not explicit if the steps must be part of a Garbage Collection or if they are optional during the GC.

Taking the facts we have, Execution is not guaranteed even with a GC hook and this invalidates almost all the tests we have relying on it.

cc @mhofman @gsathya @mathiasbynens.

I'd like to confirm the intention of Execution here, and possibly set the text for it to describe execution must happen in a GC.

**Comment by leobalter** [comment]
one thing that could be done is specifying the `$262.gc` hook should always trigger Execution.

**Comment by kmiller68** [comment]
Even still, the object might not be dead to the VM. Some implementations use a conservative GC, which means if any number on the C stack looks like a pointer to a JS object that object will be kept alive. So even if you require `$262.gc()` trigger Execution, that doesn't mean any WeakRef or FinalizationGroup will be cleared/run, respectively.

**Comment by kmiller68** [comment]
Also, it needs to be more than just async because microtasks don't clear the keepAlive list. You'll probably need a hook into the VM to turn the event loop.

**Comment by leobalter** [comment]
@kmiller68 my example could be like this: 

```js
var deref = false;
var derefAsync = false;

function emptyCells() {
  var wr;
  (function() {
    var a = {};
    wr = new WeakRef(a);
  })();
  $262.gc();
  deref = wr.deref();
  return Promise.resolve().then(() => {
    $262.gc();
    derefAsync = wr.deref();
  });
}

emptyCells().then(() => {
  assert.sameValue(derefAsync, undefined);
});

assert.sameValue(typeof deref, 'object', 'object is still in the agent.[[KeptAlive]] list');
```

or even shortened to something like:

```js

var derefAsync = false;

function emptyCells() {
  var wr;
  (function() {
    var a = {};
    wr = new WeakRef(a);
  })();
  return Promise.resolve().then(() => {
    $262.gc();
    derefAsync = wr.deref();
  });
}

emptyCells().then(() => {
  assert.sameValue(derefAsync, undefined);
});
```

It's only possible if we enforce GC to run the Execution steps, in this case, this might be a requirement for the `$262.gc` only. Do you think this is doable?

**Comment by leobalter** [comment]
> Also, it needs to be more than just async because microtasks don't clear the keepAlive list. You'll probably need a hook into the VM to turn the event loop.

OMG... you're correct. We need more hooks.

In this case, it's only worth investing if we can secure a call to Execution in Test262. Setting it from the specs or requiring it at the `$262.gc` hook. If we can't solve this, we can't rely on many tests here.

**Comment by mhofman** [comment]
> > Also, it needs to be more than just async because microtasks don't clear the keepAlive list. You'll probably need a hook into the VM to turn the event loop.
> 
> OMG... you're correct. We need more hooks.
> 
> In this case, it's only worth investing if we can secure a call to Execution in Test262. Setting it from the specs or requiring it at the `$262.gc` hook. If we can't solve this, we can't rely on many tests here.

There are really 3 integration points for the host:
- Execution to clear out slots after an object has been collected
- ClearKeptObjects to clear the WeakRef keep alive list
- HostCleanupFinalizationGroup to schedule execution of the CleanupFinalizationGroup at a later point.

The first 2 are can easily be triggered by direct test hooks.
ClearKeptObjects and CleanupFinalizationGroup should not interrupt synchronous execution. There is no mandate in the JS spec about a full task turn, just that the HTML integration document, the jobs are performed at the micro-task checkpoint.

We could very well add a "drain weakref host jobs" hook that performs both ClearKeptObjects and queued CleanupFinalizationGroup, and take a callback when they have been performed. Most likely this can be shimmed by a simple `setImmediate` equivalent. In https://github.com/tc39/test262/pull/2192#issuecomment-502253154 I called it task because of the HTML integration.

**Comment by mhofman** [comment]
> Even still, the object might not be dead to the VM. Some implementations use a conservative GC, which means if any number on the C stack looks like a pointer to a JS object that object will be kept alive. So even if you require `$262.gc()` trigger Execution, that doesn't mean any WeakRef or FinalizationGroup will be cleared/run, respectively.

Couldn't the `$262.gc()` hook mandate a full GC, aka all non-live objects should be collected. These tests are pretty simple and a collecting VM will collect the test objects.

**Comment by leobalter** [comment]
@mhofman are you gonna be at the TC39 meeting next week? I'm planning to discuss with implementors there to figure out a matching API for Test262. So far, it seems pretty hard to find something we could reuse for at least V8, JSC and SpiderMonkey. I hope the personal interaction in the meeting will help developing a solution.

**Comment by mhofman** [comment]
Nope, I'm helping with the WeakRefs specs due to interest, but I'm not a TC39 member ;)

**Comment by leobalter** [comment]
@mhofman if you don't work for a member org you could definitely come as an invited expert. I can't cover expenses but would be helpful to have you there or in a next meeting for sure.

Saying that there are some stuff to report about the explored options:

1. `$262.gc()` + event loop hook in the `$262` as well: not possible as it enforces determinism from some of the engines
2. Promise based `$262.gc().then(...)` to resolve after a event loop following an actual cleanup. Also not possible to determine when from some conservative GC.
3. Tentative loop execution... `for (let i = 0; i < 10000; ++i) { runTest(); } if (testPassedAtLeastOnce()) $test262Passed();`. We've historically never held flaki tests and I'm not sure I can accept this.


---

There isn't any amazing option here, but Test262 needs to serve multiple engines. Let's hope we discover some nice working solution.

**Comment by kmiller68** [comment]
> Couldn't the `$262.gc()` hook mandate a full GC, aka all non-live objects should be collected. These tests are pretty simple and a collecting VM will collect the test objects.

Right but live means VM live, not programmer live. Liveness within a VM could mean that an object that doesn't seem live to the programmer is still visible to the VM.

**Comment by mhofman** [comment]
I was referring to live according to the discussion in https://github.com/tc39/proposal-weakrefs/issues/105 and the PR https://github.com/tc39/proposal-weakrefs/pull/142

**Comment by kmiller68** [comment]
Ah, sorry, I should be more clear about what I was trying to say in spec language. The key is the [Evaluation section](https://tc39.es/proposal-weakrefs/#sec-weakref-execution) has a "may" at the top of it. That "may" implies that the Evaluation operation run on a non-live object may or may not clear WeakRefs and/or run finalizers. Perhaps there should be a note to make that clearer.

**Comment by mhofman** [comment]
Right, that section needs to stay a may to allow non collecting and partial collection to be compliant.
However we can very well require the `gc` test hook to require a "must" for execution.

**Comment by kmiller68** [comment]
Sure, but JSC will never be able to implement such a hook as our GC implementation does not allow us to do so.

**Comment by mhofman** [comment]
To extend on @leobalter's suggestion, we may need a `$262.gc(target).then(...)` with a timeout/rejection if the engine cannot collect the specified target.
This is actually how I wrote most of the tests in my shim.

A failure to collect would not be a failure of the test, but a "skip". I don't know if there is precedent in test262 for tests skipped at execution?

**Comment by gsathya** [comment]
cc @mathiasbynens

**Comment by kmiller68** [comment]
> To extend on @leobalter's suggestion, we may need a `$262.gc(target).then(...)` with a timeout/rejection if the engine cannot collect the specified target.
> This is actually how I wrote most of the tests in my shim.
> 
> A failure to collect would not be a failure of the test, but a "skip". I don't know if there is precedent in test262 for tests skipped at execution?

That might work, you'd have to be careful to do the GC in a different turn and not synchronously.

**Comment by gsathya** [comment]
> That might work, you'd have to be careful to do the GC in a different turn and not synchronously.

It sounds like this might be the path forward then. Making the gc() hook run async is fine for us too. 

@leobalter @mathiasbynens can we migrate the tests to use an async gc()?

**Comment by mathiasbynens** [comment]
Before we go down that road, I’d like to get more formal confirmation from @kmiller68 that this would actually solve the issue. (He previously said “[t]hat might work”, which gives me hope.)

Making `$262.gc()` async wouldn’t require any changes on the V8 or SpiderMonkey side, since synchronous engine-specific `gc()` calls would just continue to work. We’d just have to update the tests.

**Comment by mhofman** [comment]
> That might work, you'd have to be careful to do the GC in a different turn and not synchronously.

Right, and it's actually pretty awkward to write:
```javascript
// basic hook implementation using full gc()
$262.asyncGc = function(target) {
  target = null;
  return Promise.resolve().then(() => {
    gc();
  });
}

function emptyCells() {
  var target = {};
  var wr = new WeakRef(target);
  return $262.clearKeptObjects().then(() => {
    var gcPromise = $262.asyncGc(target);
    target = null;
    return gcPromise;
  }.then(() => {
    return wr.deref();
  });
}

emptyCells().then((derefAsync) => {
  assert.sameValue(derefAsync, undefined);
});
```

Maybe some of the target clearing dance can be hidden in the gc test hook / helper?
```javascript
// basic hook implementation using full gc()
$262.asyncGc = function(options) {
  options.target = null;
  gc();
  return Promise.resolve();
}

function emptyCells() {
  var gcOptions = {target: {}};
  var wr = new WeakRef(gcOptions.target);
  return $262.clearKeptObjects().then(() => {
    return $262.asyncGc(gcOptions);
  }.then(() => {
    return wr.deref();
  });
}

emptyCells().then((derefAsync) => {
  assert.sameValue(derefAsync, undefined);
});
```

The first approach forces the asyncGc implementation to defer gc() execution. However, while the second approach doesn't have that constraint, it does look more awkward in relying on the asyncGc helper to clear "external" references.

Where it also gets interesting with asyncGc is in testing that `WeakRef` does keep the object.

```javascript
function emptyCells() {
  var target = {};
  var wr = new WeakRef(target);
  var gcPromise = $262.asyncGc(target);
  target = null;
  return gcPromise.then(() => {
    // target should not have been collected.
    // Are we here because asyncGc doesn't actually ensure target was collected
    // Or because the ClearKeptObjects job was executed during the asyncGc call?
    return wr.deref();
  }, (err) => {
    // Could err be indicative of why the object couldn't be collected?
    return wr.deref();
  });
}

emptyCells().then((deref) => {
  assert.sameValue(typeof deref, 'object', 'object is still in the agent.[[KeptAlive]] list');
});
```

The second approach (asyncGc clears the `options.target` reference) is probably less problematic in this case as the implementation can more easily ensure ClearKeptObjects is not interspersed before the triggered collection. However, depending on the asyncGc and engine implementation, there is still the risk that a regular collection could automatically occur before the fulfillment callback is executed.

Maybe the simpler way is to keep a synchronous gc hook but allow a target to be provided as in the second approach? I'm not sure if this is actually doable for engines?

```javascript
var gcOptions = {target: {}};
var gcResult = $262.gc(gcOptions);
// true, specified target was collected
// false, specified target could not be collected
// undefined, collection was triggered but implementation is unable to ensure collection of a specific target
```

**Comment by kmiller68** [comment]
@mhofman I'm not sure I understand you examples. It doesn't seem like the various asyncGC functions actually return if the object was collected or not, I'm assuming that was just for simplicity.

I don't think the last example works because there's a non-zero chance that target is on the stack somewhere. Making the GC asynchronous makes it as easy as possible for an engine to collect the object. I think we should make the expectation for asyncGC be equivalent to:

```js
async function asyncGC(target) {
    let wr = new WeakRef(target); // Pretend this does not do keepAlive(target).
    await Promise.resolve();
    syncFullGC();
    if (wr.deref())
        throw "Object was not collected";
}
```

Internally, at least for JSC, this pretty easy to implement as we already have most of this functionality already. I don't know how hard this would be for other engines, so I'd be interested in hearing from them. A WeakRefs test could just be something like:

```js
async function test() {
    let target = {};
    let wr = new WeakRef(target);
    let clearing = $262.clearKeptObjects();
    let gc = $262.asyncGC(target);
    // await late because we don't want target to be captured across microtasks as it will likely not be cleared from the activation.
    await clearing;
    try {
        await gc;
        assert.sameValue(wr.deref(), undefined, "object was claimed to be collected");
    } catch (e) {
        assert.sameValue(typeof wr.deref(), 'object', "object was claimed not to be collected");
    }
}
```

**Comment by mhofman** [comment]
> @mhofman I'm not sure I understand you examples. It doesn't seem like the various asyncGC functions actually return if the object was collected or not, I'm assuming that was just for simplicity.

Right, it was for the general idea and how the target should be provided to the function. We'd have to decide how a failure to collect is communicated (rejection, return value), and how to differentiate between the collection failure scenarios (object not collectible, still observable, kept alive, or the asyncGc implementation is just unable to track collection of specific target objects).

Btw, I do not believe your example works:
`asyncGC` will only call "syncFullGC()" in a new microtask, which means the target will probably still be in the kept object list at that point because of the WeakRef in `test`.

I think there are 3 approaches in how the `asyncGc` function could look like:
- Trigger GC on a new microtask to let caller clear its references to target. Target can be passed as regular argument
- Trigger GC synchronously. Target has to be passed in a container that will be cleared by the asyncGc function.
- Trigger GC at a user provided time. Target can be passed as regular argument. Trigger can be passed as an optional argument.

Here is what the last one would look like, without async/await to avoid unnecessary test dependencies: 
```javascript
$262.asyncGc = function(target, trigger) {
  let wr = new WeakRef(target); // Pretend this does not do keepAlive(target).
  return Promise.resolve(trigger).then(() => {
    syncFullGC();
    if (wr.deref()) {
      throw "Object was not collected";
    }
  });
}

function emptyCells() {
  var target = {};
  var wr = new WeakRef(target);
  var collected = $262.asyncGc(target, $262.clearKeptObjects());
  target = null;
  return collected.then(() => {
    return wr.deref();
  });
}

emptyCells().then((derefAsync) => {
  assert.sameValue(derefAsync, undefined);
});
```

It it however subject to the same limitation as approach 1:
The spec says that the engine cannot interrupt synchronous execution when performing `ClearKeptObjects` but technically it could perform it after any microtask execution. Since approach 1 and 3 internally use a microtask before triggering the GC, there is no guarantee the `ClearKeptObjects` job will not have been performed in-between. Because of that, there is no way to test that `new WeakRef()` or `WeakRef.prototype.deref()` adds the target to the keep list.

**Comment by kmiller68** [comment]
I'm not sure I understand. AFAICT, an engine is only allowed to `ClearKeptObjects` when the embedder says so. There's no way to do this in pure JS. I was assuming the `$262.clearKeptObjects()` function would return a promise that simulates this event loop turn. I'm fine with add a restriction to testing harnesses that says `$262.clearKeptObjects()` may be the only place `ClearKeptObjects` occurs. 

As far as `asyncGC` version 1. vs 3., I'm largely indifferent, if 3. makes tests easier to write I'm ok with that.

**Comment by mhofman** [comment]
You're right, it's up to the embedder to execute the jobs, the engine itself shouldn't do it on its own.
If the testing environment can guarantee the `ClearKeptObjects` job is only run as part of the harness, then an async GC shouldn't be a problem. Or at the very least, guarantee it won't be performed until the microtask queue is drained.

It looks like 3. might make tests for `WeakRef` easier to write and shouldn't be fundamentally harder to implement than 1., but it'd be good to get confirmation from others.

**Comment by ajklein** [comment]
@leobalter thoughts on (1) vs (3)?

cc @syg

**Comment by leobalter** [comment]
Thanks for the wait and patience while I'm getting up to speed after some vacation + conferences time.

reading the options and the example given [here](https://github.com/tc39/test262/issues/2239#issuecomment-523674289), I believe I can follow on the item 3 (the one with the example), and it sounds like the easier to illustrate as well.

I'll adapt the existing tests to this approach and in the meanwhile we should get ESHost to prepare the agent.

Some documentation on `$262.clearKeptObjects()` should follow as well.
