### ISSUE TITLE
Add destructuring assignment tests for object literal accessor property targets

### ISSUE THREAD

**Issue by joeywatts** [tc39/test262#2262]
Creating this issue as a result of [this v8 bug](https://bugs.chromium.org/p/v8/issues/detail?id=9560).

Could we add tests for destructuring assignment to object literal accessor properties? Examples:

```js
[{ set prop(val) { console.log(val); } }.prop = 12 ] = [ 1 ];
({ obj: { set prop(val) { console.log(val); } }.prop = 12 } = { obj: 1 });
({ obj: { set prop(val) { console.log(val); } }.prop } = { obj: 1 });
[{ set prop(val) { console.log(val); } }.prop ] = [ 1 ];
```

**Comment by leobalter** [comment]
https://tc39.es/ecma262/#sec-assignment-operators-static-semantics-early-errors

`It is a Syntax Error if LeftHandSideExpression is either an ObjectLiteral or an ArrayLiteral and LeftHandSideExpression is not covering an AssignmentPattern.`

If you also go all the way to evaluating `{ set prop(val) { console.log(val); } }`  you will find `DestructuringAssignmentTarget : LeftHandSideExpression` and [this](https://tc39.es/ecma262/#sec-destructuring-assignment-static-semantics-early-errors):

```
DestructuringAssignmentTarget : LeftHandSideExpression
- It is a Syntax Error if LeftHandSideExpression is either an ObjectLiteral or an ArrayLiteral and if LeftHandSideExpression is not covering an AssignmentPattern.
```

these are SyntaxErrors, V8 and Chakra were both correct...

```
eshost -x '[{ set prop(val) { print(val); } }.prop = 12 ] = [ 1 ];'
#### ch

SyntaxError: Invalid destructuring assignment target

#### d8

SyntaxError: Invalid destructuring assignment target.

#### jsc
1

#### jsshell
1
```

**Comment by joeywatts** [comment]
I think `LeftHandSideExpression` would be a `MemberExpression` (`PrimaryExpression . IdentifierName` where `PrimaryExpression` is an `ObjectLiteral`), right?

**Comment by leobalter** [comment]
ok, I was considering `{ set prop(val) { console.log(val); } }.prop` without the `.prop`. That sounds right. I'm gonna take a second look.

**Comment by leobalter** [comment]
I went through the whole parsing and evaluation (manually) of `[{ set prop(val) { console.log(val); } }.prop = 12 ] = [ 1 ];` and yes, it's correct and it should execute the accessor set method.

The initializer is not even much of a difference there, but all the examples are correct. I'll make sure we have tests for that.

**Comment by leobalter** [comment]
Thanks @jugglinmike for helping me with the evaluation run through.

**Comment by leobalter** [comment]
I've found some existing tests:

- [`test/language/expressions/assignment/dstr/array-elem-put-prop-ref-no-get.js`](https://test262.report/browse/language/expressions/assignment/dstr/array-elem-put-prop-ref-no-get.js?date=2019-08-01)
- [`test/language/statements/for-await-of/async-func-decl-dstr-array-elem-put-prop-ref-no-get.js`](https://test262.report/browse/language/statements/for-await-of/async-func-decl-dstr-array-elem-put-prop-ref-no-get.js?date=2019-08-01)
- [`test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-put-prop-ref-no-get.js`](https://test262.report/browse/language/statements/for-await-of/async-gen-decl-dstr-array-elem-put-prop-ref-no-get.js?date=2019-08-01)
- [`test/language/statements/for-of/dstr/array-elem-put-prop-ref-no-get.js`](https://test262.report/browse/language/statements/for-of/dstr/array-elem-put-prop-ref-no-get.js?date=2019-08-01)

Sounds like just the `[x.y]` pattern would pass but we should get the full MemberExpression examples with the initial object literal and a property name.

I'll have a patch soon.

**Comment by leobalter** [comment]
Thanks for the report, @joeywatts! Please let me know if you find more cases!
