### ISSUE TITLE
Remove enochian-enochian locale from Intl test vectors?

### ISSUE THREAD

**Issue by bterlson** [tc39/test262#227]
Currently the locale enochian-enochian is tested in a few places in the Intl test suite. Chakra fails these tests as it does not consider this a well-formed locale. Pedantically, locales with 5-8 characters are valid per BCP47 but it includes a note in 2.2.1-5 that says 5-8 character primary language tags are unlikely to ever be included in the IANA database. As such I believe Chakra's behavior is reasonable and we should remove the enochian-enochian locale from any tests it appears in. If someone has a more user-impacting locale (no one would ever use enochian-enochian) I would be glad to hear it, though!

Worth also that Intl spec doesn't mandate support for any particular set of locales.

Objections? If not I will whip up a PR.

cc @rwaldron

**Comment by bterlson** [comment]
We can leave i-enochian as it is a grandfathered tag and supported by all current Intl implementations that I'm aware of (including Chakra).

**Comment by rwaldron** [comment]
LGTM
