### ISSUE TITLE
Consider updating PyYAML

### ISSUE THREAD

**Issue by Ms2ger** [tc39/test262#2278]
We're on 3.11; current is 5.1.2.

**Comment by Ms2ger** [comment]
We'll need to deal with https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

**Comment by leobalter** [comment]
Ref #2277

**Comment by leobalter** [comment]
cc @jugglinmike.

I don't have any objection to this change. I would just need to check if breaks anything we currently have. Unfortunately, my time is assigned to other projects until Wednesday, so I can't see it immediately.
