### ISSUE TITLE
Add test for `const a = {def\u0061ult: 12}`

### ISSUE THREAD

**Issue by weswigham** [tc39/test262#2285]
Given
```js
const a = {def\u0061ult: 12}
```

In chrome and safari this issues an error, while in firefox and chakra it does not. Some discussion in IRC seemed to lead to believing this is valid and should not error (as a property name is an [`IdentifierName`](https://tc39.es/ecma262/#prod-IdentifierName) which lacks the "no reserved words" restriction of an identifier and therefore should not be bound by the "no escapes in keywords" rule, as it is not a keyword position). There should be a test covering it - [chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=993000) and [safari](https://bugs.webkit.org/show_bug.cgi?id=200638) have bugs open to rectify their behavior.

The extended escape form:
```js
const a = {def\u{0061}ult: 12}
```
is probably also worth a test.

**Comment by bakkot** [comment]
Copying from #2286:

```js
({ def\u0061ult: 0 });
```
and
```js
({ def\u{61}ult: 0 });
```
are both legal, since `def\u0061ult` and `def\u{61}ult` are both [`IdentifierName`](https://tc39.es/ecma262/#prod-IdentifierName)s and therefore [`LiteralPropertyName`](https://tc39.es/ecma262/#prod-LiteralPropertyName)s. The restriction on keywords not containing escape sequences - which prevents `export def\u0061ult function (){}` from being legal - is not relevant in this context.

This case appears not to be covered by current tests - at least, I couldn't find one at a quick glance.

Currently, out of Chakra, JavascriptCore, SpiderMonkey, V8, and XS, only Chakra and SpiderMonkey allow the first form, and only SpiderMonkey allows the second.

**Comment by bakkot** [comment]
Though note that `({ def\u0061ult })` is forbidden, and that should probably be tested too, if it isn't.

**Comment by rkirsling** [comment]
Also note that of the five, it's only V8 that doesn't allow `foo = {}; foo.def\u{61}ult = 3;`.

**Comment by leobalter** [comment]
@weswigham @bakkot @rkirsling I believe I got this covered at #2295 and #2294. Would you mind giving a look there? Thanks!

**Comment by leobalter** [comment]
I also found this is not only with `default` but almost all the reserved words...

```js
var arr = [
    'aw\\u0061it',
    'bre\\u0061k',
    'c\\u0061se',
    'c\\u0061tch',
    'cl\\u0061ss',
    '\\u0063onst',
    '\\u0063ontinue',
    'd\\u0065bugg\\u0065r',
    'd\\u0065f\\u0061ult',
    'd\\u0065l\\u0065t\\u0065',
    '\\u0064o',
    '\\u0065ls\\u0065',
    '\\u0065xport',
    '\\u0065xt\\u0065nds',
    'fin\\u0061lly',
    '\\u0066or',
    'fun\\u0063tion',
    'i\\u0066',
    '\\u0069mport',
    '\\u0069n',
    'inst\\u0061n\\u0063\\u0065of',
    'n\\u0065w',
    'r\\u0065turn',
    'sup\\u0065r',
    'swit\\u0063h',
    'th\\u0069s',
    't\\u0068row',
    'tr\\u0079',
    'typ\\u0065of',
    'v\\u0061r',
    'voi\\u0064',
    'whil\\u0065',
    'w\u0069th',
    'yi\\u0065ld',

    '\\u0065num',

    'impl\\u0065ments',
    'interf\\u0061\\u0061e',
    'p\\u0061\\u0061kage',
    'prote\\u0061ted',
    'priv\\u0061te',
    'publi\\u0061',
    'l\\u0065t',
    'st\\u0061ti\\u0061',
];

arr.forEach(name => {
    var obj = {};
    try {
        eval(`obj.${name} = 42;`);
        console.log(`ok ${eval('"'+name+'"')}`);
    } catch(e) {
        console.log(`fail ${eval('"'+name+'"')}`);
    }
})
```

is printint a lot of failures as well.
