### ISSUE TITLE
Add tests for Opt. Chain. inside Opt.Chain. computed property names

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#2292]
Based on https://bugs.webkit.org/show_bug.cgi?id=200199#c17

```js
x?.[y?.z];
```

Also, "what happens when `y?.z` fails".

**Comment by leobalter** [comment]
cc @bcoe let me know if you're interested in doing this otherwise I'll try to work on this specific part.

**Comment by bcoe** [comment]
I was hoping to add tests for the expansions of OptionalChain here:

https://github.com/tc39/test262/blob/master/test/language/expressions/optional-chaining/optional-chain.js

I can add one for `x?.[y?.z];` tomorrow. My expectation would be, when `y?.z` results in undefined, it would be equivalent to:

```
x[undefined]
```

which agrees with what I'm seeing in the babel plugin:

```
const a = {undefined: 99};
const b = null;
const val = a?.[b?.c];
console.info(val); // outputs 99.
```

does this sound right @rkirsling?

**Comment by leobalter** [comment]
By convention we ideally have granular test files to capture units and provide a better map on actual failures. I believe this is good enough to be checked within new files.

I believe it's also pretty important to test the order of evaluation on each of these, like:

```js
var x = {
  get k() {
    console.log('x.k');
    return {};
  }
};

var y = {
  get z() { console.log('y.z'); return 'foo'; }
};

x.k?.[y?.z]; // ??? x.k, y.z OR y.z, x.k
```

and also:

```
var x = undefined;
var y = {
  get z() { throw new Test262Error(); }
};

x?.[y?.z]; // which is quite similar to x?.[y.z]
```

**Comment by rkirsling** [comment]
Note too, that there are a bunch of similar (in syntax but not semantics) edge cases in this vicinity:
```js
x?.[y?.z]
x?.(y?.z)
(x?.y)?.(z)
(x?.y)(z)
```

**Comment by rkirsling** [comment]
Looks like we addressed the case mentioned in the topic here, but we still need the call-related ones I pointed out. I think this is important coverage prior to reaching Stage 4 as it's a plausible yet easily-overlooked path; I can help out with this today.

Basically we should be able to re-use these:
https://github.com/WebKit/webkit/blob/master/JSTests/stress/optional-chaining.js#L112-L116
