### ISSUE TITLE
Organizing Generator Prototype tests

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#230]
Currently, Test262 places tests relating to generators in one of two directories (depending on the syntactic form used to create the generator function):

- `language/statements/generator/`
- `language/expressions/generator/`

I'm now authoring tests for [generator objects](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generator-objects)--specifically prototype methods like `next`, `return`, and `throw`. I'm not sure where to place these files, though.

We could limit ourselves to working within the above directories, maybe introducing new subdirectories like `language/statements/generator/return/` and `language/expressions/generator/return/`. It's possible that some VM incorrectly relates the generator function syntax to the generator prototype behavior, making dedicated tests for both cases potentially useful. This seems highly unlikely, though, so the utility of maintaining alternate versions of these tests seems minimal.

I don't think either of these locations are intuitive for tests for generator objects or the generator prototype. Instead, I'd like to propose a new sub-directory under the [recently-introduced](https://github.com/tc39/test262/pull/212) `built-ins/intrinsics/`: `built-ins/intrinsics/GeneratorPrototype/`. (And although `built-ins/GeneratorFunction/` was previously discussed on IRC, I think `built-ins/intrinsics/` would be a good target for those tests, too.)

@bterlson What do you think?

**Comment by bterlson** [comment]
I think built-ins/Generator and built-ins/Generator/prototype makes the most sense to me. I'm skeptical about instrinsics as a subfolder now that I think about it because aren't all built-ins intrinsics? Probably the intent is to separate things that are accessible from global scope vs. things that aren't? I'm not sure it's necessary. Unless @caitp disagrees, I think built-ins/Generator/* is the most rational way to go.

**Comment by caitp** [comment]
as I said on IRC, feel free to move `intrinsics/*` to`built-ins/*`, and rename `FunctionPrototype` to `Function.prototype`, or move `built-ins/*`to `intrinsics/*`to match draft lingo --- either way is fine

**Comment by jugglinmike** [comment]
Got it. Thanks, folks!
