### ISSUE TITLE
Test await-expr-func-expression may be incorrect

### ISSUE THREAD

**Issue by joshualitt** [tc39/test262#2300]
Test test/language/module-code/top-level-await/await-expr-func-expression tests modules, which require strict parsing. However, the test specifies multiple top level functions with the same identifier, fn. I think this is not allowed?

**Comment by leobalter** [comment]
You're corrent, I'm gonna fix it.

**Comment by leobalter** [comment]
@joshualitt this should be addressed #2319. Please, let me know if you find anything else.
