### ISSUE TITLE
cross-realm feature missing in some class private field tests

### ISSUE THREAD

**Issue by bellard** [tc39/test262#2324]
The cross-realm feature is missing in the following class private field tests:

- test/language/expressions/class/private-getter-brand-check-multiple-evaluations-of-class-realm-function-ctor.js
- test/language/expressions/class/private-getter-brand-check-multiple-evaluations-of-class-realm.js
- test/language/expressions/class/private-method-brand-check-multiple-evaluations-of-class-realm-function-ctor.js
- test/language/expressions/class/private-method-brand-check-multiple-evaluations-of-class-realm.js
- test/language/expressions/class/private-setter-brand-check-multiple-evaluations-of-class-realm-function-ctor.js
- test/language/expressions/class/private-setter-brand-check-multiple-evaluations-of-class-realm.js
- test/language/expressions/class/private-static-field-multiple-evaluations-of-class-realm.js
- test/language/expressions/class/private-static-getter-multiple-evaluations-of-class-realm.js
- test/language/expressions/class/private-static-method-brand-check-multiple-evaluations-of-class-realm.js
- test/language/expressions/class/private-static-setter-multiple-evaluations-of-class-realm.js

**Comment by leobalter** [comment]
Thanks @bellard! I believe #2328 should address all the fixes, WDYT?

**Comment by bellard** [comment]
Yes it is OK !
