### ISSUE TITLE
How to contribute security tests?

### ISSUE THREAD

**Issue by natashenka** [tc39/test262#2327]
We discussed adding some security/robustness test to test262 at TC39 a while ago https://github.com/tc39/security/issues/5 . I have some questions about how contribute them. The contribution guidelines say you need an ESID, which these test won't have, as they are generally testing malformed or unusual JavaScript, and they only fail if they cause a crash. Is there something I can put in instead. Also, is it appropriate to put the test for each builtin in the current test directory, or should I start a separate security directory?

**Comment by rwaldron** [comment]
Please reopen for further discussion
