### ISSUE TITLE
ECMA-402 PR coverage: Add calendar and numberingSystem options

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#2331]
Ref: https://github.com/tc39/ecma402/pull/175

I've might already have tests for this, see https://github.com/tc39/ecma402/pull/175#issuecomment-494533901

Close it if coverage is confirmed.

**Comment by caiolima** [comment]
We are missing coverage on invalid options throwing `RangeError`.

**Comment by caiolima** [comment]
BTW, I'm going to work on that now.

**Comment by leobalter** [comment]
Closing after #2480
