### ISSUE TITLE
Test262 Web Runner stuck at test 1193 while running tests 

### ISSUE THREAD

**Issue by aBilalMujeeb** [tc39/test262#2338]
Test262 Web Runner stuck at test 1193 while running tests. The tests that I could see running but without any output are 

1. annexB -> language -> function_code -> global-switch-dflt-eval-global-existing-non-enumerable-global-init.js
2. annexB -> language -> global_code -> if-decl-no-else-global-skip-early-err-try.js
3. build-ins -> Array -> name.js

**Environment** I am using chrome 76 on Ubuntu desktop.
**Test Runner** https://bakkot.github.io/test262-web-runner/

**Comment by leobalter** [comment]
Please report it to the project's repo: http://github.com/bakkot/test262-web-runner
