### ISSUE TITLE
Date tests are not timezone-independent

### ISSUE THREAD

**Issue by joyeecheung** [tc39/test262#2341]
In the `test/built-ins/Date/S15.9.3.1_A*.js` tests, e.g.

https://github.com/tc39/test262/blob/ef7fd2bc27e7c10b4a71d2edc632a2934742a13e/test/built-ins/Date/S15.9.3.1_A5_T5.js#L19

On a machine with a timezone different from UTC this will fail.

Can these tests be written in a way that's independent from timezones, or can the timezone be specified in the front matter for test runners to adapt?

**Comment by joyeecheung** [comment]
hm, this actually seems to be a false alarm, as I can only reproduce this in one implementation. I'll close it for now.

**Comment by anba** [comment]
This is a dup of #1984, which [contains a link](https://github.com/tc39/test262/issues/1984#issuecomment-445824542) to the underlying issue in v8: <https://bugs.chromium.org/p/v8/issues/detail?id=7863>.
