### ISSUE TITLE
__proto__ duplicate in object in group should not be error

### ISSUE THREAD

**Issue by pvdz** [tc39/test262#2344]
According to `test262/test/annexB/language/expressions/object/__proto__-duplicate.js` the following is an error:

`````js
({
  __proto__: null,
  other: null,
  '__proto__': null
});
`````

However, the spec says:

https://tc39.es/ecma262/#sec-object-initializer-static-semantics-early-errors

> When ObjectLiteral appears in a context where ObjectAssignmentPattern is required the following Early Error rules are not applied. 
> In addition, they are not applied when initially parsing a CoverParenthesizedExpressionAndArrowParameterList or CoverCallExpressionAndAsyncArrowHead.

Since the object appears in a group which matches the cover grammar, could somebody please explain why this still considered an error?

cc @jugglinmike @mathiasbynens

**Comment by jugglinmike** [comment]
Hi there, Peter.

The word "initially" seems important here. That could explain why code like the following is *not* a syntax error:

    ({ __proto__: x, __proto__: y }) => {};

While code like the following is a syntax error:

    ({ __proto__: x, __proto__: y });

I've never gotten the hang of cover grammars, though, so take this interpretation with a grain of salt. @littledan does that sound right to you? Is this a case where the ([relatively new](https://github.com/tc39/ecma262/commit/6f1aa96edb03e0e3e3ff87f3dffe93e3d61947ad)) ["covering" term](https://tc39.es/ecma262/#sec-syntactic-grammar) could be helpful?

(A point of clarification: the link Peter shared is to text in section 12, but they're describing rules in Annex B. I think [this](https://tc39.es/ecma262/#sec-__proto__-property-names-in-object-initializers) is what they had in mind. The spec text is identical, so I assume this was just a typo.)

**Comment by jmdyck** [comment]
As I understand it, when you're "initially parsing" a CoverFoo, you (theoretically) don't know enough to apply *any* early error rules. That has to wait until you know more of the context.

So, with the original example, the parenthesized stuff does indeed match CoverParenthesizedExpressionAndArrowParameterList, which is not subject to early error rules. But then the context requires that it be 'reparsed' as a ParenthesizedExpression, which *is* (via [12.2.10.1]( https://tc39.es/ecma262/#sec-grouping-operator-static-semantics-early-errors), bullet 2) subject to early error rules, including (eventually) the rule in B.3.1 that says the ObjectLiteral is a Syntax Error.

(But take that with a grain of salt too.)

**Comment by pvdz** [comment]
Ok, that makes sense.

In my implementation I don't actually reparse anything when applying a cover grammar (or regex u-flag), so "initially" is all I do :p Rather I forward all required information and pick what to keep once a key marker is found (the arrow, for example). So in this case I'll mark the object illegal-unless-pattern or something.

I feel the wording in the spec could be improved on this. Or in the test case. But I suppose the "initially" is correct.
