### ISSUE TITLE
ECMA-402 PR Coverage: Add dayPeriod option

### ISSUE THREAD

**Issue by sffc** [tc39/test262#2357]
Spec PR: https://github.com/tc39/ecma402/pull/346

According to https://github.com/tc39/ecma402/pull/346#issuecomment-500932203 and the meeting minutes, there are partial tests added in https://github.com/tc39/test262/pull/2194 and https://github.com/tc39/test262/pull/2217. Please verify if additional tests need to be added.

@FrankYFTang

**Comment by caiolima** [comment]
I think we have enough coverage to consider this complete. Missing tests are potentially edge-cases.
