### ISSUE TITLE
ECMA-402 PR Coverage: Revert tests for quarter option

### ISSUE THREAD

**Issue by sffc** [tc39/test262#2358]
Spec PR: https://github.com/tc39/ecma402/pull/345

We decided to pull this PR pending further discussion with CLDR.  However, some tests may have been added in #2194.  Please remove these tests if necessary.

@FrankYFTang

**Comment by FrankYFTang** [comment]
This is all done in https://github.com/tc39/test262/pull/2232

**Comment by FrankYFTang** [comment]
Somehow I missed one . Here is the PR to remove it
https://github.com/tc39/test262/pull/2368
