### ISSUE TITLE
A few QuickJS bugs that are not covered by test262

### ISSUE THREAD

**Issue by bellard** [tc39/test262#2370]
Here are a few bugs recently corrected in QuickJS that are not tested in test262:

* `decodeURIComponent("%ED%AF%BF")` should throw a URIError (UTF-8 code corresponding to a surrogate pair).

* `delete "abc"[100]` should return true

* `delete null.a` should throw a TypeError

* `delete super.a` should throw a ReferenceError in a method

* eval() should call the corresponding binding if it is defined:

```
var g_call_count = 0;

function f1(eval)
{
    eval(1, 2);
}

function f2(eval)
{
    eval(...[1, 2]);
}

function g(a, b) {
    assert.sameValue(a, 1);
    assert.sameValue(b, 2);
    g_call_count++;
}

f1(g);
f2(g);
assert.sameValue(g_call_count, 2);
```

**Comment by leobalter** [comment]
while everything is correct, I have one nit:

> `delete null.a` should throw a TypeError

`null.a` itself should throw a TypeError alone...

**Comment by bellard** [comment]
I agree that according to the standard the exception happens in the 
evaluation of the "dot" property accessor. However in QuickJS the 
RequireObjectCoercible() test of section 12.3.2.1 is done in the delete 
operator. Hence the test is still interesting for the engines which use 
the same implementation trick.
