### ISSUE TITLE
assert._formatValue causing test failures

### ISSUE THREAD

**Issue by devsnek** [tc39/test262#2372]
after updating test262 this week, `Array/prototype/flatMap/array-like-objects-nested.js` has started failing with this stack trace:

```
RangeError: should not even consider the length property
    at get length (test/test262/test/built-ins/Array/prototype/flatMap/array-like-objects-nested.js:48:38)
    at <anonymous> (test/test262/harness/assert.js:142:119)
```

`assert._formatValue` is trying to print out the length getter, and that causes the test to fail.

**Comment by leobalter** [comment]
thanks for reporting! I'm gonna get this fixed.
