### ISSUE TITLE
test/built-ins/FinalizationGroup/prototype/cleanupSome/poisoned-callback-throws.js issues

### ISSUE THREAD

**Issue by mhofman** [tc39/test262#2392]
There 2 problems with [poisoned-callback-throws.js](https://github.com/tc39/test262/blob/08844700fe701dc4ef204ca14e140667ceb32ad4/test/built-ins/FinalizationGroup/prototype/cleanupSome/poisoned-callback-throws.js)
- Line 58 has a typo [`iteraror`](https://github.com/tc39/test262/blob/08844700fe701dc4ef204ca14e140667ceb32ad4/test/built-ins/FinalizationGroup/prototype/cleanupSome/poisoned-callback-throws.js#L58). @leobalter mentioned in https://github.com/tc39/test262/pull/2353#issuecomment-533639401 that the typo was fixed in a followup commit, but the change doesn't seem to have made it.
- I would argue that the whole section ([L57-L61](https://github.com/tc39/test262/blob/08844700fe701dc4ef204ca14e140667ceb32ad4/test/built-ins/FinalizationGroup/prototype/cleanupSome/poisoned-callback-throws.js#L57-L61)) about checking the iterator is superfluous for this test as it's already tested in [built-ins/FinalizationGroup/FinalizationGroupCleanupIteratorPrototype/next-job-not-active-throws](https://github.com/tc39/test262/blob/08844700fe701dc4ef204ca14e140667ceb32ad4/test/built-ins/FinalizationGroup/FinalizationGroupCleanupIteratorPrototype/next-job-not-active-throws.js). In particular v8 now passes the base test about bubbling the error, but fails the iterator part.

**Comment by leobalter** [comment]
I probably missed committing the typo fix, thanks for reporting that. PTAL #2394

> I would argue that the whole section (L57-L61) about checking the iterator is superfluous 

I have to disagree then, as it's far from being superfluous:

For both tests we have a call to `fg.cleanupSome(callback);`, in one of then we have a normal completion, and for the other we have an abrupt completion.

In the specs we have:

```
  5. Set finalizationGroup.[[IsFinalizationGroupCleanupJobActive]] to true.
  6. Let result be Call(callback, undefined, « iterator »).
  7. Set finalizationGroup.[[IsFinalizationGroupCleanupJobActive]] to false.
  8. If result is an abrupt completion, return result.
```

I want to make sure **step 7** always happens, even in an abrupt completion from **step 6**.

In other words, if the result from **step 6** is an abrupt completion, first set `finalizationGroup.[[IsFinalizationGroupCleanupJobActive]]` to **false** and then return it.

---

Executing the tests with the current v8 implementation shows this is not happening:

```
$ test262-harness -t 32 --hostType=d8 --hostPath=v8 --hostArgs='--harmony-weak-refs' test/built-ins/FinalizationGroup/prototype/cleanupSome/poisoned-callback-throws.js
FAIL test/built-ins/FinalizationGroup/prototype/cleanupSome/poisoned-callback-throws.js (default)
  Test262Error: iterator.next throws a TypeError if IsFinalizationGroupCleanupJobActive is false Expected a TypeError to be thrown but no exception was thrown at all

FAIL test/built-ins/FinalizationGroup/prototype/cleanupSome/poisoned-callback-throws.js (strict mode)
  Test262Error: iterator.next throws a TypeError if IsFinalizationGroupCleanupJobActive is false Expected a TypeError to be thrown but no exception was thrown at all

Ran 2 tests
0 passed
2 failed
```

This tests failure should provide a valuable information, as the error happens **after** we check for the abrupt completion being returned from the callback:

```js
   // here we asserted the abrupt completion from poisoned is returned
  assert.throws(Test262Error, function() {
    fg.cleanupSome(poisoned);
  });

  // We reassure it's been called
  assert.sameValue(called, 1);

  assert.sameValue(typeof iterator, 'object');
  assert.sameValue(typeof iterator.next, 'function');

  // Here is where the test is currently failing on V8
  assert.throws(TypeError, function() {
    iterator.next();
  }, 'iterator.next throws a TypeError if IsFinalizationGroupCleanupJobActive is false');
```

So the part pointed as "superfluous" is providing useful information, and removing these would give an incomplete information of a test passing.

**Comment by mhofman** [comment]
You're right, I didn't think about it this way!

However, I feel this test is still conceptually testing 2 things at once. Because the last step is broken in V8, you have to check the error message to differentiate from a failure of the first step.

Would it make sense to duplicate the test, one with check for the iterator, and one without, and name them accordingly, e.g.
poisoned-callback-throws
poisoned-callback-iterator-not-active-next-throws

**Comment by leobalter** [comment]
I could do that but requires me reusing the same content from the one we would stop at just calling the callback. I'm not sure how the fragmentation would help but I'd be welcome to a PR doing this work.

**Comment by mhofman** [comment]
I understand. I'm not sure what's best or how test262 currently handles similar cases. 

Basically this is an if/else branch in spec steps, but with no sub step for one of the branch. If there was a separate step for both branches, wouldn't there be 2 tests with duplicate code?
