### ISSUE TITLE
Incorrect tests on Optional Chaining

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#2409]
> I'm not sure if some of these tests were correct?

> None of these are SyntaxError with `.`, so `?.` should not change that:

[test/language/statements/for-of/dstr/obj-prop-elem-target-obj-literal-optchain-prop-ref.js](https://github.com/tc39/test262/blob/master/test/language/statements/for-of/dstr/obj-prop-elem-target-obj-literal-optchain-prop-ref.js)
[test/language/statements/for-of/dstr/array-elem-nested-memberexpr-optchain-prop-ref.js](https://github.com/tc39/test262/blob/master/test/language/statements/for-of/dstr/array-elem-nested-memberexpr-optchain-prop-ref.js)
[test/language/statements/for-of/dstr/obj-prop-elem-target-memberexpr-optchain-prop-ref.js](https://github.com/tc39/test262/blob/master/test/language/statements/for-of/dstr/obj-prop-elem-target-memberexpr-optchain-prop-ref.js)
[test/language/statements/for-of/dstr/array-elem-put-obj-literal-optchain-prop-ref.js](https://github.com/tc39/test262/blob/master/test/language/statements/for-of/dstr/array-elem-put-obj-literal-optchain-prop-ref.js)
[test/language/statements/for-in/dstr/obj-prop-elem-target-obj-literal-optchain-prop-ref.js](https://github.com/tc39/test262/blob/master/test/language/statements/for-in/dstr/obj-prop-elem-target-obj-literal-optchain-prop-ref.js)
[test/language/statements/for-in/dstr/obj-prop-elem-target-memberexpr-optchain-prop-ref.js](https://github.com/tc39/test262/blob/master/test/language/statements/for-in/dstr/obj-prop-elem-target-memberexpr-optchain-prop-ref.js)
[test/language/statements/for-in/dstr/array-elem-put-obj-literal-optchain-prop-ref.js](https://github.com/tc39/test262/blob/master/test/language/statements/for-in/dstr/array-elem-put-obj-literal-optchain-prop-ref.js)
[test/language/statements/for-in/dstr/array-elem-nested-memberexpr-optchain-prop-ref.js](https://github.com/tc39/test262/blob/master/test/language/statements/for-in/dstr/array-elem-nested-memberexpr-optchain-prop-ref.js)

_Originally posted by @rkirsling in https://github.com/tc39/test262/pull/2270#issuecomment-545880743_

**Comment by leobalter** [comment]
@rkirsling would you mind push a patch for this?

**Comment by rkirsling** [comment]
Certainly—is it okay to simply remove them though? I wasn't sure how we could salvage them.

**Comment by leobalter** [comment]
At this point yes, better than having incorrect cases
