### ISSUE TITLE
Add coverage for Promise.any proposal

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/test262#2410]
This issue is to track the progress of the test262 coverage of the stage 3 Promise.any proposal. https://github.com/tc39/proposal-promise-any. ~Tests also should cover `AggregateError`.~ (covered by https://github.com/tc39/test262/pull/2406)

I'm starting to work on this.

**Comment by chicoxyzzy** [comment]
cc @mathiasbynens @bakkot

**Comment by chicoxyzzy** [comment]
Oh, I didn't notice https://github.com/tc39/test262/pull/2406 for AggregateError from @leobalter

**Comment by leobalter** [comment]
Hi @chicoxyzzy, how is the progress on the tests for Promise.any? I have time available this week for it if you haven't started yet. Please, let me know!

**Comment by chicoxyzzy** [comment]
Hi Leo! I have asked you the same question on #tc39 IRC channel couple hours before 😀 I will work on adding `Promise.any` to JSC soon, so I will need tests for it. I didn't start yet, so you can do it or leave it to me (I was going to start tomorrow). Either way works for me 🙂

**Comment by leobalter** [comment]
It’s very nice if you wanna write the tests. I’ll focus on other features currently on Stage 3. I’m looking forward to review the tests.

**Comment by leobalter** [comment]
Coverage for AggregateError should be done.

**Comment by chicoxyzzy** [comment]
@leobalter awesome, thank you! I've started to work on Promise.any tests (using https://github.com/tc39/test262/pull/2124 as a reference)

**Comment by chicoxyzzy** [comment]
https://github.com/tc39/test262/pull/2533 is merged now, so I'll close this issue. Thank you @rwaldron! 👏
