### ISSUE TITLE
Optional chain call with super and meta properties

### ISSUE THREAD

**Issue by jridgewell** [tc39/test262#2414]
Babel and TypeScript both ran into issues with `super.method?.()` by trying to use `super` as a regular variable. Can we add tests around this, and `new.target`?

```js
class Base {
    method() {
        return this;
    }
}

class Foo extends Base {
    method() {
        super.method?.();
    }
}

function Bar() {
    return new.target?.();
}
Reflect.construct(Bar, [], function () { return this; })
```

[Babel repl](https://babeljs.io/repl/#?babili=false&browsers=ie%2011&build=&builtIns=usage&spec=false&loose=false&code_lz=MYGwhgzhAEBCkFNoG8BQ0PQLYIC4AsB7AEwAoBKFdTGgJzwFdaA7aAgSwgG5qMBfVANShIMAGKFC0BAA9cCZsRjwISNDRwESFKjRoQGABwS0AdJqLEA_KYo8aAoQDMGzYLnaFW8WjvWZ6XCZWZgQAd1NcMFoAczwbO0FUACUEJxAEd1NgLwhcWgZ3Uh8AGmgAbQBdMpc3Dy9oP2hA4LZ8Ti5oPnIgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.7.2&externalPlugins=%40babel%2Fplugin-proposal-optional-chaining%407.6.0), [Typescript repl](https://www.typescriptlang.org/play/#code/MYGwhgzhAEBCkFNoG8BQ0PQLYIC4AsB7AEwAoBKFdTGgJzwFdaA7aAgSwgG5qMBfVANShIMAGKFC0BAA9cCZsRjwISNDRwESFKjRoQGABwS0AdJqLEA-KYo8aAoQDMGzYLnaFW8WjvWZ6XCZWZgQAd1NcMFoAczwbO0FUACUEJxAEd1NgLwhcWgZ3Uh8AGmgAbQBdMpc3Dy9oP2hA4LZ8Ti5oPnIgA)

**Comment by bcoe** [comment]
@jridgewell with regards to `super.method?.()`, the expected response would be `this` in your example?

Should ` new.target?.()` throw a `TypeError`?

**Comment by bcoe** [comment]
@jridgewell with regards to `super.method?.()`, the expected response would be `this` in your example?

Should ` new.target?.()` throw a `TypeError`?

**Comment by ljharb** [comment]
No, because if `new.target` is `undefined`, the optional call would avoid it; but it might also be a function as in this example:
```js
class F extends Function { constructor() { super(); new.target?.(); } }
```

**Comment by bcoe** [comment]
I follow @jridgewell example now, will add a test if no one else beats me to it.

**Comment by jridgewell** [comment]
> with regards to `super.method?.()`, the expected result would be this in your example?

Yes.

> Should `new.target?.()` throw a TypeError?

No, as @ljharb explains.

This is primarily just to test that things that look like member expressions, but really aren't, behave properly when used in a an optional chain.
