### ISSUE TITLE
Add tests for String.prototype.replaceAll

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/test262#2417]
Ref. https://github.com/tc39/proposal-string-replaceall/issues/28

**Comment by leobalter** [comment]
Is anyone interesting in picking this up? Otherwise I'll assign it to myself in about an hour.

cc @ljharb

**Comment by mathiasbynens** [comment]
I imagine we can mostly duplicate the existing `String.prototype.replace` tests, modifying those tests where `searchValue` and `replaceValue` are both strings. At that point, we’d only have to add tests for the exception on a non-global RegExp `searchValue`.

**Comment by leobalter** [comment]
Sure thing, I'm just checking as IIRC, @ljharb has expressed intention to write these tests in the last meeting. Otherwise, I'm gonna get this covered this week. (today or tomorrow, optimistically).

**Comment by ljharb** [comment]
Feel free to do it before i find time to :-)

**Comment by leobalter** [comment]
> I imagine we can mostly duplicate the existing String.prototype.replace tests, modifying those tests where searchValue and replaceValue are both strings.

This would be amazing if we didn't have too many legacy tests.
