### ISSUE TITLE
Optional Call receiver with parentheses

### ISSUE THREAD

**Issue by jridgewell** [tc39/test262#2441]
V8, SpiderMonkey, JSC, Babel, and TypeScript have have/had incorrect receiver propagation when an optional chain is wrapped in parenthesis then called:

```js
const o = { m() { return this; } };
assert(o === (o?.m)());
```

/cc @bcoe

**Comment by jridgewell** [comment]
V8: https://bugs.chromium.org/p/v8/issues/detail?id=10024

**Comment by codehag** [comment]
Spidermonkey hasn't landed yet, but we are aware of the issue. There is no specific bug for this.

**Comment by DanielRosenwasser** [comment]
As we discussed offline, it feels like that sample should give the same behavior as

```js
const o = { m() { return this; } };
assert(o === (o.m)());
```

The current state of the spec reflects this, so it sounds like this is an easy-to-make implementation bug that needs test262 coverage.

@codehag, @rkirsling, @rbuckton, @devsnek, @avp do you have any objections to this?

**Comment by jridgewell** [comment]
Apparently SM already has a patch, and JSC is already fixed

**Comment by rkirsling** [comment]
Test case is #2436. :smile:

**Comment by jridgewell** [comment]
Babel issue: https://github.com/babel/babel/issues/10802
TypeScript issue: https://github.com/microsoft/TypeScript/issues/35476

**Comment by rwaldron** [comment]
@leobalter is this in scope for your test refactoring?

**Comment by leobalter** [comment]
#2436 addressed this.
