### ISSUE TITLE
add test for super construct check being after arguments

### ISSUE THREAD

**Issue by bmeck** [tc39/test262#2442]
refs: https://github.com/tc39/ecma262/pull/1775

seems some tests need updates:
https://github.com/tc39/test262/blob/ee3715ee56744ccc8aeb22a921f442e98090b3c1/test/language/statements/class/subclass/class-definition-null-proto-super.js#L58
https://github.com/tc39/test262/blob/ee3715ee56744ccc8aeb22a921f442e98090b3c1/implementation-contributed/v8/mjsunit/regress/regress-crbug-696622.js#L11-L14

**Comment by rwaldron** [comment]
The current tests no longer contain this code.
