### ISSUE TITLE
Add spec edge case tests for Unified NumberFormat

### ISSUE THREAD

**Issue by sffc** [tc39/test262#2449]
https://github.com/tc39/proposal-unified-intl-numberformat/pull/72 and other recent PRs have made minute detail changes to edge case behaviors in Unified NumberFormat.  There should be tests added for this behavior.

@Ms2ger

**Comment by sffc** [comment]
More specifically, add tests for all of the normative changes since Stage 3:

https://github.com/tc39/proposal-unified-intl-numberformat/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3ANORMATIVE+

**Comment by Ms2ger** [comment]
See https://github.com/tc39/test262/pull/2454 for this year's tests; I'll probably need to write some more next year.
