### ISSUE TITLE
missing coverage of super reference behaviour

### ISSUE THREAD

**Issue by devsnek** [tc39/test262#2451]
As far as I can tell, the below behaviour is not verified in test262. I just found a bug today where it was resolving super references incorrectly, which can be tested for sort of like this:

```js
class X {
  method() { return this; }
}

class Y extends X {
  method() { return super.method(); }
}

const y = new Y();
print(y.method() === y);
```

I'm not entirely sure what is and isn't covered, so I thought it would be useful to open an issue.

**Comment by rwaldron** [comment]
It's funny... I can find so many examples of `super.prop()` calls, but they always call something that returns a string or a number. I can't find explicit coverage for this case 🤷‍♂ . I wrote a test, but then realized maybe you want to write the test, so I figured I'd give you the option. Let me know what you want to do.

**Comment by devsnek** [comment]
@rwaldron if you have a test please feel free to use it :+1:
