### ISSUE TITLE
coverage reports from engine262

### ISSUE THREAD

**Issue by devsnek** [tc39/test262#2452]
I just added coverage reports to engine262, and I found that in some cases the data is actually able to find missing coverage in test262. For example, here we can see that several branches are missed for Error.prototype.toString:

![](https://gc.gy/44605382.png)

engine262 still has a lot of work to do, and thousands of tests are still skipped, but I'm hopeful that some of this data may be of use :)

Full reports are uploaded here: https://coveralls.io/github/engine262/engine262

**Comment by rwaldron** [comment]
I'm currently using these reports to aid in identifying coverage gaps.
