### ISSUE TITLE
Invalid `numberingSystem` tests

### ISSUE THREAD

**Issue by longlho** [tc39/test262#2455]
Hi there,

While working on Unified NumerFormat polyfill I noticed https://github.com/tc39/test262/pull/2383 which might not be valid as `numberingSystem` is not retrieved anywhere in current spec and proposed unified numberformat. The closest call was the iteration over `options` in https://tc39.es/ecma402/#sec-resolvelocale but that's not enough to trigger a getter. Should those tests be modified?

cc @FrankYFTang @sffc

Thanks,

LH

**Comment by sffc** [comment]
The test is for https://github.com/tc39/ecma402/pull/175, which adds those options and how to read them in Intl objects.

**Comment by longlho** [comment]
Gotcha thanks!
