### ISSUE TITLE
Missing tests for BigInt literals as ProeprtyName

### ISSUE THREAD

**Issue by caiolima** [tc39/test262#2485]
See related bug on [SpiderMonkey](https://bugzilla.mozilla.org/show_bug.cgi?id=1605835) and [JSC](https://bugs.webkit.org/show_bug.cgi?id=206888).

BigInt literals can be used as property name. In this case `{1n: "foo"}` should evaluate to an object with `{"1": "foo"}`.

**Comment by rwaldron** [comment]
Resolved
