### ISSUE TITLE
Atomics.waitAsync testing plan 

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#2511]
# Atomics.waitAsync
https://tc39.es/proposal-atomics-wait-async/

(All relevant tests must be completed for TypedArray and BigInt)

## features.txt

- [x] `Atomics.waitAsync`

## waitAsync
- esid: sec-atomics.waitasync
- [x] Check Name
    - test/built-ins/Atomics/waitAsync/name.js
- [x] Check length
    - test/built-ins/Atomics/waitAsync/length.js
- [x] Check descriptor
    - test/built-ins/Atomics/waitAsync/descriptor.js

### Atomics.waitAsync(typedArray, index, value, timeout)

1. Return DoWait(async, typedArray, index, value, timeout).
    - [x] returns a Promise that is resolved when the calling agent is notified
    - [x] returns a Promise when the sleep times out

### DoWait ( mode, typedArray, index, value, timeout )

- [x] 1. Let buffer be ? ValidateSharedIntegerTypedArray(typedArray, true)
    - [x] Test for abrupt return if ValidateSharedIntegerTypedArray throws an error
    - [x] ValidateSharedIntegerTypedArray (https://tc39.es/ecma262/#sec-validatesharedintegertypedarray):
        - [x] If Type(typedArray) is not Object, throw a TypeError exception
        - [x] If typedArray does not have a [[TypedArrayName]] internal slot, throw a TypeError exception
        - [x] Let type be the Element Type value in Table 63 for typeName. (https://tc39.es/ecma262/#table-the-typedarray-constructors)
        - [x] If waitable is true, then
            - [x] If typeName is not "Int32Array" or "BigInt64Array", throw a TypeError exception. 
            - [x] Else,
                - [x] If ! IsUnclampedIntegerElementType(type) is false and ! IsBigIntElementType(type) is false, throw a TypeError exception. (https://tc39.es/ecma262/#sec-isunclampedintegerelementtype https://tc39.es/ecma262/#sec-isbigintelementtype)
        - [x] If IsSharedArrayBuffer(buffer) is false, throw a TypeError exception.
            - [x] Type(obj) is Object and it has an [[ArrayBufferData]] internal slot.
            - [x] If bufferData is null, return false.
            - [x] If bufferData is a Data Block, return false.
            - [x] Return true.

- [x] 2. Let i be ? ValidateAtomicAccess(typedArray, index).
    - [x] Test for abrupt return if ValidateAtomicAccess throws an error
    - [x] ValidateAtomicAccess: (https://tc39.es/ecma262/#sec-validateatomicaccess)
        - [x] Let accessIndex be ? ToIndex(requestIndex)
            - [x] abrupt return if ToIndex throws an error
                - [x] If value is undefined, let index be 0 and return index
                - [x] If integerIndex < 0, throw a RangeError exception.
                - [x] Let index be ! ToLength(integerIndex).
                - [x] If ! SameValue(integerIndex, index) is false, throw a RangeError exception.
        - [x] If accessIndex ≥ length, throw a RangeError exception.

- [x] 3. If arrayTypeName is "BigInt64Array", let v be ? ToBigInt64(value).
    - [x] Test for abrupt return if ToBigInt throws an error
    - [x] Let n be ? ToBigInt(argument).
        - [x] **TODO:** drill down into ToBigInt 
        - [x] **TODO:** drill down into ToPrimitive
    - [x] Let int64bit be n modulo 2 ** 64.
    - [x] Return int64bit.

- [x] 4. Otherwise, let v be ? ToInt32(value).
    - [x] Test for abrupt return if ToInt32 throws an error
    - [x] Let number be ? ToNumber(argument)
        - [x] _ToNumber_: *(superficial cases only)*
            - [x] ToNumber(Symbol) --> Throw a TypeError exception.
            - [x] abrupt return if ToNumber throws an error
        - [x] Let int be the Number value that is the same sign as number and whose magnitude is floor(abs(number)).
        - [x] Let int32bit be int modulo 2 ** 32.
        - [x] If int32bit ≥ 2 ** 31, return int32bit - 2 ** 32; otherwise return int32bit.

- [x] 5. Let q be ? ToNumber(timeout)
    - [x] Test for abrupt return if ToNumber throws an error
    - [x] Let number be ? ToNumber(argument)
        - [x] _ToNumber_: *(superficial cases only)*
            - [x] ToNumber(Symbol) --> Throw a TypeError exception.
            - [x] abrupt return if ToNumber throws an error
- [x] 6. If q is NaN, let t be +∞, else let t be max(q, 0)
    - [x] confirm that passing a negative timeout translates to 0ms
    - [x] confirm that passing NaN as a timeout translate to +infinity

- [x] 7. If mode is sync, then
    - [x] Let B be AgentCanSuspend().
    - [x] If B is false, throw a TypeError exception.
    - [x] **TODO:** Identify a way for hosts specify the value of [[CanBlock]]

- [x] 8. Let block be buffer.[[ArrayBufferData]]. **NOT DIRECTLY OBSERVABLE**
- [x] 9. Let offset be typedArray.[[ByteOffset]]. **NOT DIRECTLY OBSERVABLE**
- [x] 10. Let indexedPosition be (i × 4) + offset. **NOT DIRECTLY OBSERVABLE**
- [x] 11. Let WL be GetWaiterList(block, indexedPosition).
    - From _GetWaiterList_: (https://tc39.es/ecma262/#sec-getwaiterlist)
        - [x] Return the WaiterList that is referenced by the pair (block, i). 

- [x] 12. Let promiseCapability be undefined. **NOT DIRECTLY OBSERVABLE**
- [x] 13. If mode is async, then
    - [x] Let promiseCapability be ! NewPromiseCapability(%Promise%).

- [x] 14. Perform EnterCriticalSection(WL).
    - [x] EnterCriticalSection:
        - [x] Wait until no agent is in the critical section for WL, then enter the critical section for WL (without allowing any other agent to enter).

- [x] 15. Let w be ! AtomicLoad(typedArray, i). **NOT DIRECTLY OBSERVABLE**
- [x] 16. If v is not equal to w, then 
    - [x] a. Perform LeaveCriticalSection(WL). 
    - [x] b. If mode is sync, then
        - [x] Return the String "not-equal".
    - [x] c. Perform ! Call(capability.[[Resolve]], undefined, « "not-equal" »).
    - [x] Return promiseCapability.[[Promise]].

- [x] 17. Let W be AgentSignifier() **NOT DIRECTLY OBSERVABLE**
- [x] 18. Let waiterRecord be a new Waiter Record { [[AgentSignifier]]: W, [[PromiseCapability]]: promiseCapability, [[Timeout]]: t, [[Result]]: "ok" }.
    - [x] **TODO**

- [x] 19. Perform AddWaiter(WL, waiterRecord).
    - [x] AddWaiter: (https://tc39.es/proposal-atomics-wait-async/#sec-addwaiter)
        - [x] **TODO:** Review changes present in proposal

- [x] 20. If mode is sync, then
    - [x] Perform Suspend(WL, W).
        - Suspend: (https://tc39.es/proposal-atomics-wait-async/#sec-suspend)
            - [x] **TODO:** Review changes present in proposal
- [x] 21. Perform LeaveCriticalSection(WL). **NOT DIRECTLY OBSERVABLE**
- [x] 22. If mode is sync, then
    - [x] Return waiterRecord.[[Result]].
- [x] 23. Return promiseCapability.[[Promise]].

**Comment by leobalter** [comment]
@rwaldron I believe the status here has changed, right?
