### ISSUE TITLE
Resolve test validity claim for built-ins/AggregateError/newtarget-proto-fallback.js

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#2515]
See: https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20Conformance.md#built-ins-1

Re: https://github.com/tc39/test262/blob/7040938bd06ded171250d1e945a969f90fb37165/test/built-ins/AggregateError/newtarget-proto-fallback.js

**Comment by anba** [comment]
That claim is correct, we're also skipping that test in Firefox, because it expects the wrong prototype.

**Comment by rwaldron** [comment]
Thanks @anba
