### ISSUE TITLE
Add test for EvaluateNew execution order

### ISSUE THREAD

**Issue by mroch** [tc39/test262#2527]
I couldn't find a test that ensures that [EvaluateNew](https://tc39.es/ecma262/#sec-evaluatenew) steps 3 and 4 come before step 6: the reference to the constructor is evaluated before the arguments.

specifically, a test case like this:

```
(function (){var a=function(){};new a((a=1))})()
```

It should (I believe) construct the function with `1` as an arg, not try to construct `1` and `TypeError`.

I think this is relevant because this currently fails in JSC (macOS 10.15.3):

```
% cat test.js
(function (){var a=function(){};new a((a=1))})()
% /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc test.js
Exception: TypeError: 1 is not a constructor (evaluating 'new a((a=1))')
test.js:1:38
global code@test.js:1:47
```

**Comment by sterpe** [comment]
Commenting so I get updates.

**Comment by leobalter** [comment]
I don't believe we have modern coverage (after 2015) for EvaluateNew, and this seems like a very interesting case to be covered. I'm getting the tests done soon.

**Comment by ljharb** [comment]
@sterpe for future reference, there’s a “subscribe” button on all issues and PRs that will ensure you get updates, without needing to comment. ❤️

**Comment by leobalter** [comment]
The most interesting part here is that it only happens in a very specific case:

- [x] `x` cannot be referenced inside the constructor used for `new`.

```js
function fn() {
  var x = function() {
    x; // just because of this
  };

  new x((x = 1));
}

fn(); // this function will pass on JSC, remove that line and it will trigger the error.
```

- `x` must be in the same function level scope, and it cannot happen in the top level scope.
