### ISSUE TITLE
Test for ASI in `continue` is ineffective

### ISSUE THREAD

**Issue by mroch** [tc39/test262#2529]
https://github.com/tc39/test262/blob/25c9e334d301944537215caba1d7f44319f3e0da/test/language/statements/continue/12.7-1.js#L11-L18

this test claims to be testing that "a continue statement without an identifier may have a LineTerminator before the semi-colon".

however, I don't think it's working as intended. if ASI does insert a semicolon after `continue`, it still passes, just with an extra empty statement.

A test like this would make sure there's no ASI happening:

```
        var sum = 0;
        for (var i = 1; i <= 10; i++) {
            if (true) continue
            ; else {}
            sum += i;
        }
```

If it inserts a semicolon, then `;` becomes an empty statement and the `else` becomes a syntax error.

**Comment by rwaldron** [comment]
Fixed
