### ISSUE TITLE
Incorrect intl402/Locale/constructor-tag.js test

### ISSUE THREAD

**Issue by iamstolis** [tc39/test262#2541]
`intl402/Locale/constructor-tag.js` test assumes that `Flob`, `ZORK` and `SPAM-gb-x-Sausages-BACON-eggs` are invalid language tags, i.e., it expects `RangeError` to be thrown when such tag is passed to `Intl.Locale` constructor. I believe that these tags are structrurally valid language tags (i.e. no `RangeError` should be thrown). The relevant production is `unicode_language_id = "root" | (unicode_language_subtag (sep unicode_script_subtag)? | unicode_script_subtag) (sep unicode_region_subtag)?  (sep unicode_variant_subtag)*`. Note that the tag may start with a script tag (see the second alternative of `unicode_language_subtag (sep unicode_script_subtag)? | unicode_script_subtag`). Hence, `Flob` is not an invalid language subtag but a valid script subtag (with `und` language subtag ommited). The same argument applies to `ZORK`. `SPAM-gb-x-Sausages-BACON-eggs` is a valid language tag starting with `SPAM` script subtag (and having `gb` region and `Sausages-BACON-eggs` private use extension).

**Comment by anba** [comment]
The quoted grammar production only allows leading script subtags for *Unicode CLDR locale identifiers*, but ECMA-402 uses *Unicode BCP 47 locale identifiers*. The difference is explained in <https://unicode.org/reports/tr35/#BCP_47_Conformance>.

**Comment by iamstolis** [comment]
Thank you for the explanation. I understand what `IsStructurallyValidLanguageTag()` is supposed to mean by now. On the other hand, I think that the description of this operation should be fixed/improved.

Yes, the operation mentions `Unicode BCP 47 Locale Identifier` term but it points to section 3.2 (instead of section 3.3) of Unicode Technical Standard 35. Even worse, it says explicitly:

> The abstract operation returns true if `locale` can be generated from the EBNF grammar in section 3.2 of the Unicode Technical Standard 35, or successor, starting with `unicode_locale_id`, and does not contain duplicate variant or singleton subtags (other than as a private use subtag). It returns false otherwise.

i.e. there is no reference to the refusal of the backward compatibility syntax (mentioned in section 3.3).

**Comment by anba** [comment]
Please file an issue at the ECMA-402 repository. Thanks!

**Comment by iamstolis** [comment]
> Please file an issue at the ECMA-402 repository.

OK, did so: https://github.com/tc39/ecma402/issues/425

I am closing this issue as the test is correct if `IsStructurallyValidLanguageTag()` operation is supposed to check whether the argument is `Unicode BCP 47 Locale Identifier` (and not check whether it argument matches `unicode_locale_id` production only).
