### ISSUE TITLE
Promise.any test bug: Promise.prototype.then uses SpeciesConstructor

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#2557]
For

- test/built-ins/Promise/any/does-not-perform-species-get-of-custom.js 
- test/built-ins/Promise/any/does-not-perform-species-get-of-promise.js 

_Promise.prototype.then uses SpeciesConstructor_

_Originally posted by @devsnek in https://github.com/tc39/test262/pull/2533_

**Comment by leobalter** [comment]
For reference, #2562 removed the erroneous tests. The PR can be used to find the content that needs fixing.

**Comment by rwaldron** [comment]
@leobalter what is left to be done?

**Comment by leobalter** [comment]
hard to remember exactly but it seems it's fixed?

I'm closing it for now blaming my past solve on not providing better information here.
