### ISSUE TITLE
export-star-as-dflt seems wrong

### ISSUE THREAD

**Issue by syg** [tc39/test262#2614]
The test seems to be testing that:

[L21](https://github.com/tc39/test262/blob/master/test/language/module-code/export-star-as-dflt.js#L21) Re-export all the imports as a named export named `default`
[L22](https://github.com/tc39/test262/blob/master/test/language/module-code/export-star-as-dflt.js#L22) Import the default export as a namespace object `ns` from itself.
[L23](https://github.com/tc39/test262/blob/master/test/language/module-code/export-star-as-dflt.js#L23) Test that the namespace object has a named export named `default`.

L21 doesn't actually make a default export (as opposed to a named export named `default`), so how does L22 import a namespace object?

@adrianheine What is this trying to test?

**Comment by syg** [comment]
There's note in Step 8.c [here](https://tc39.es/ecma262/#sec-resolveexport) that says "A default export cannot be provided by an export * or export * from "mod" declaration." though I haven't chased down where that's exactly prohibited.

**Comment by syg** [comment]
Ah, so I misunderstood the note, which narrowly only applies to `export *` and `export * from "mod"`, not `export * as`.

The test still seems wrong, however. My current understanding is L23 should be testing for `ns.x === 21`. There is no named export named `default` in the namespace object.

**Comment by syg** [comment]
Not sure what you mean by dynamic import; that test is all static imports.

**Comment by leobalter** [comment]
Nevermind, I was just saying you would see the default naming in a dynamic import, which doesn't really apply here. I believe there is actually a catch in the `default` property which is not `"*default*"`, but I'm still reading the specs for a final conclusion.

**Comment by leobalter** [comment]
https://github.com/tc39/test262/pull/1498/files/fd9b982217729a10ebcf93cd85ad99a9c4113960#r227919103

Now I understand the reason for testing and yes, the test seems wrong. Back all the way to @syg's first question: _so how does L22 import a namespace object?_

I don't think it imports the namespace so you need to import the named bindings

```js
export * as default from './export-star-as-dflt_FIXTURE.js';
import ns from './export-star-as-dflt.js';
assert.sameValue(ns.default.x, 1, 'namespace was re-exported under the name `default`');
```

there is a catch here with `ns`, which is not really a namespace but tricked me a bit.

maybe this would be more appropriate for this test:

```js
export * as default from './export-star-as-dflt_FIXTURE.js';
import * as ns from './export-star-as-dflt.js';
assert.sameValue(ns.default.x, 1, 'namespace was re-exported under the name `default`');
```

and

```js
export * as default from './export-star-as-dflt_FIXTURE.js';
import { default as value } from './export-star-as-dflt.js';
assert.sameValue(value.x, 1, 'namespace was re-exported under the name `default`');
```

**Comment by syg** [comment]
My current understanding is that `import ns` actually does work, because all default exports are, are exports named... `"default"`. So, `export * as default` actually does re-export a namespace object as the default export. (To contrast, the `"*default*"` name is a synthetic name for the spec to access the copy local to the exporting module.)

This is pretty confusing though...

**Comment by syg** [comment]
To finish the thought, my current understanding of what doesn't work is L23, which should be changed to `ns.x` from `ns.default.x`.
