### ISSUE TITLE
Missing coverage for 'String.prototype.split()'

### ISSUE THREAD

**Issue by ty5491003** [tc39/test262#2622]
Through our fuzzing work, we found an implemetation error of rhino.
Bug issue: https://github.com/mozilla/rhino/issues/664

**Testcase**:
```js
var a = '123 456 789'.split(undefined, 0);
print(a);
```

**Rhino Output**:
['123 456 789']

**Other Engines Output**:
[]

It appears all other engines pass the test but I didn't see a test262 checking this behavior. Perhaps it could be ported to test262? 

Looking forward to your reply!

**Comment by leobalter** [comment]
@ty5491003 PTAL at #2632. 

Split has a legacy coverage that pre-dates ES2015.
