### ISSUE TITLE
Need tests for \8 in templates and strict strings

### ISSUE THREAD

**Issue by rkirsling** [tc39/test262#2653]
Looks like tests for `\8` were missed from https://github.com/tc39/test262/pull/1063.

Everyone agrees that `\08` is bad outside of sloppy non-template strings, but SM, V8, XS, and ChakraCore all accept <code>\`\8\`</code> and `'\8'` regardless of mode.

Templates should hit the NotEscapeSequence early errors in [12.2.9.1](https://tc39.es/ecma262/#sec-static-semantics-template-early-errors) while strict non-templates should fail to lex altogether per the definition of CharacterEscapeSequence in [11.8.4](https://tc39.es/ecma262/#prod-CharacterEscapeSequence).

**Comment by anba** [comment]
`\8` isn't allowed in any mode per spec (*). As non-standard extension, some engines allow it in strict and non-strict mode, and other engines only allow it in non-strict mode. 

(*) [B.1.1 Numeric Literals](https://tc39.es/ecma262/#sec-additional-syntax-numeric-literals) supports noctal digits through *NonOctalDecimalIntegerLiteral*, whereas [B.1.2 String Literals](https://tc39.es/ecma262/#sec-additional-syntax-string-literals) doesn't have an equivalent production rule.

**Comment by rkirsling** [comment]
Oh hmm, you're right that B.1.2 doesn't actually call out 8 and 9 after all.

This feels really weird to have unspecified though, right? Perhaps we should add a NODIL equivalent to B.1.2 since everyone agrees on sloppy non-template strings?

**Comment by anba** [comment]
It's already planned to resolve this for ES7: https://tc39.es/archives/bugzilla/3477/ :smile:

**Comment by rkirsling** [comment]
Hah, wow! Guess I'll open a 262 ticket tomorrow then. 😅
