### ISSUE TITLE
Missing tests for Escape method

### ISSUE THREAD

**Issue by NWU-NISL** [tc39/test262#2687]
**Description:**

A QuickJS functional bug we found that when the parameter of the Escape method is "null" as the following testcase, QuickJS engine throws TypeError other than covert "null" to String as except. I think it's better to add the testcase to test262 suite.

**Testcase:**

```js
var NISLFuzzingFunc = function(){
	var x = escape(null);
	print(x);
};

NISLFuzzingFunc();
```

**QuickJs  Version**:

 [quickjs-2019-10-27](https://github.com/horhof/quickjs/releases/tag/20191027)

**QuickJs Output:**

```js
TypeError: null or undefined are forbidden
```

**Expected Output:**

```js
null
```

**ECMA262 Link:**

1. https://tc39.es/ecma262/#sec-escape-string

   **B.2.1.1 escape ( string )**

   ……

   The `escape` function is the %escape% intrinsic object. When the `escape` function is called with one argument string, the following steps are taken:

    1. **Set string to ? [ToString](https://tc39.es/ecma262/#sec-tostring)(string).**

    2. Let length be the number of code units in string.

    3. Let R be the empty String.

       ……

2. https://tc39.es/ecma262/#sec-tostring

   **7.1.17 ToString ( argument )**

   The abstract operation ToString takes argument argument. It converts argument to a value of type String according to Table 13.

   ​	……

   ​	      **Null	Return "null"**

   ​	……

**Comment by shvaikalesh** [comment]
This seems like a duplicate of #2637, but with better description.

**Comment by NWU-NISL** [comment]
> This seems like a duplicate of #2637, but with better description.

Yes, this is a more detailed description of #2637. Will this test case be added to the test262 suite?

**Comment by leobalter** [comment]
@NWU-NISL these cases are welcomed for new tests in Test262. Would you be interested in opening a PR? I'd be happy to review and merge.
