### ISSUE TITLE
built-ins/Atomics/waitAsync/poisoned-object-for-timeout-throws.js etc don't test waitAsync

### ISSUE THREAD

**Issue by marjakh** [tc39/test262#2689]
I was wondering why these tests pass for V8 which does not implement waitAsync yet :)

https://test262.report/features/Atomics.waitAsync/built-ins/Atomics/waitAsync/poisoned-object-for-timeout-throws.js?date=2020-06-27

These tests are in the waitAsync directory but they call Atomics.wait instead of Atomics.waitAsync.

built-ins/Atomics/waitAsync/poisoned-object-for-timeout-throws.js
built-ins/Atomics/waitAsync/poisoned-object-for-timeout-throws-agent.js
built-ins/Atomics/waitAsync/bigint/poisoned-object-for-timeout-throws.js
built-ins/Atomics/waitAsync/bigint/poisoned-object-for-timeout-throws-agent.js

**Comment by marjakh** [comment]
Seems to also affect built-ins/Atomics/waitAsync/validate-arraytype-before-value-coercion.js

**Comment by marjakh** [comment]
@rwaldron

**Comment by marjakh** [comment]
Ah, there are more. grepping for "Atomics.wait(" gives these tests:

built-ins/Atomics/waitAsync/bigint/negative-index-throws.js
built-ins/Atomics/waitAsync/bigint/out-of-range-index-throws.js
built-ins/Atomics/waitAsync/bigint/poisoned-object-for-timeout-throws.js
built-ins/Atomics/waitAsync/bigint/poisoned-object-for-timeout-throws-agent.js
built-ins/Atomics/waitAsync/bigint/symbol-for-timeout-throws-agent.js
built-ins/Atomics/waitAsync/negative-index-throws.js
built-ins/Atomics/waitAsync/out-of-range-index-throws.js
built-ins/Atomics/waitAsync/poisoned-object-for-timeout-throws-agent.js
built-ins/Atomics/waitAsync/poisoned-object-for-timeout-throws.js
built-ins/Atomics/waitAsync/symbol-for-timeout-throws-agent.js
built-ins/Atomics/waitAsync/validate-arraytype-before-value-coercion.js

**Comment by leobalter** [comment]
Thanks for the report, @marjakh. The typos should be addressed at #2690, and I believe @rwaldron also safe guarded the tests against false positives at 51e73466ee5146862824d378dc4ea34085439c12. 

Historically, Test262 does not have much of a way to prevent against false positives such as tests that gives a SyntaxError for a new forbidden grammar (also a SyntaxError if the feature is not yet implemented), or if a call to a method should return a TypeError exception.

At least, for the former, we've been able to enforce the tests with simple checks of feature existence, like `typeof Atomics.waitAsync`. 

I'd love for everyone to be full eyes on potential tests that could benefit Test262 out of these initial assertions and, perhaps, find a solution for syntax based tests. Those might be more up to test runners.
