### ISSUE TITLE
Verify coverage for Promise#finally subclass referring to species

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#2693]
> This test seems like a false positive. It doesn't seem like the assertions are relying on the the Promise subclass at all, but just returning what finally returns.

> I wonder if the goal was checking something like `.finally.call(MyPromise, () => {})` or the **resolved** value of the finally call.

> For the current text, I don't see why `p instanceof MyPromise` would ever be true and that's why the info metatag is ever so important in tests like this.

_Originally posted by @leobalter in https://github.com/tc39/test262/pull/2691_

---

cc @ljharb @shvaikalesh @rwaldron

This refers to the file removed in #2691 and might be interesting to verify how we can cover it properly in Test262, if necessary as in not yet covered by another test file.

Although, I'd wait until the TC39 meeting in July as we have upcoming discussion about @@species that might affect this.

**Comment by ljharb** [comment]
The test looks right to me:
```jsx
class MyPromise extends Promise {
}
const p = Promise.resolve().then(() => MyPromise.resolve());
p instanceof Promise; // true
p instanceof MyPromise; // true
```

```jsx
class MyPromise extends Promise {
  static get[Symbol.species]() {		
     return Promise;		
   }
}
const p = Promise.resolve().then(() => MyPromise.resolve());
p instanceof Promise; // true
p instanceof MyPromise; // false
```
is what i'd expect.

**Comment by leobalter** [comment]
In the first example, I can't see how `p instanceof MyPromise` would ever be true. So the custom `@@species` wouldn't affect the second example.

It seems the engines are also consistent (when they have it implemented):

```sh
➜  eshost -tsx 'class MyPromise extends Promise {
}
const p = Promise.resolve().then(() => MyPromise.resolve());
p instanceof Promise; // true
print(p instanceof MyPromise); // true'
┌────────────────┬─────────────────────────────────────────────┐
│ ChakraCore     │ false                                       │
│ engine262      │                                             │
│ JavaScriptCore │                                             │
│ Moddable XS    │                                             │
│ SpiderMonkey   │                                             │
│ V8             │                                             │
├────────────────┼─────────────────────────────────────────────┤
│ Hermes         │                                             │
│                │ SyntaxError: invalid statement encountered. │
└────────────────┴─────────────────────────────────────────────┘
```

**Comment by leobalter** [comment]
In any case, this [seems to be a duplicate](https://github.com/tc39/test262/pull/2691#discussion_r451053620).

Thanks @shvaikalesh! I'll close this down as coverage is set, but I plan to take a look at coverage if we can enforce this test.

There might be some test but it seems like easier if this test is countered with a `@@species` returning a custom ctor.

**Comment by ljharb** [comment]
hmm, you're right

**Comment by leobalter** [comment]
I believe the example is better seen without the arrow function:

```js
class MyPromise extends Promise {}

var count = 0;
function fn() {
  count++;
  return MyPromise.resolve();
}

const p = Promise.resolve().then(fn);
assert.sameValue(count, 0, 'fn remains in the async queue, MyPromise.resolve() has not been called yet');

assert(p instanceof Promise);
```

**Comment by leobalter** [comment]
Here is an example of what I mentioned: 

```js
class OtherPromise extends Promise {}

class MyPromise extends Promise {
  static get[Symbol.species]() {		
    return OtherPromise;		
  }
}

var count = 0;
function fn() {
  count++;
  return 42;
}

const p = MyPromise.resolve().finally(fn);
p instanceof OtherPromise; // true
```

**Comment by shvaikalesh** [comment]
Thank you @leobalter for review & investigation!

I wonder why `subclass-species-constructor-{resolve,reject}-count.js` have `-count` in their names?
Perhaps these tests would be more useful if we add a counter to `@@species` getter and assert its value.

**Comment by leobalter** [comment]
Maybe the name could be adjusted. I wouldn't have it in high priority, thou
