### ISSUE TITLE
The pedant in me is compelled to note that in cases where evaluating the LHS is observable the sugar is a little more complicated because you need to avoid triggering the side effects multiple times (though most implementations [get it wrong](https://github.com/tc39/ecma262/issues/467), and do in fact trigger a subset of the side effects several times). No one should care about this, though.

### ISSUE THREAD

**Issue by Thuhtet23** [tc39/test262#2709]
The pedant in me is compelled to note that in cases where evaluating the LHS is observable the sugar is a little more complicated because you need to avoid triggering the side effects multiple times (though most implementations [get it wrong](https://github.com/tc39/ecma262/issues/467), and do in fact trigger a subset of the side effects several times). No one should care about this, though.

_Originally posted by @bakkot in https://github.com/tc39/proposal-logical-assignment/issues/3#issuecomment-374631058_

**Comment by leobalter** [comment]
Please rewrite this. Help me find what’s actionable and please use a short title.

**Comment by anba** [comment]
@leobalter That's a spam account.

**Comment by leobalter** [comment]
Thanks for letting me know
