### ISSUE TITLE
built-ins/Atomics/notify/null-bufferdata-throws.js isn't testing what it says it's testing

### ISSUE THREAD

**Issue by syg** [tc39/test262#2721]
The comments suggest that it's testing for a substep in the IsSharedArrayBuffer AO when called from Atomics.notify. But the test detaches the buffer up front, which means a TypeError is thrown as part of step 1, inside the AO ValidateIntegerTypedArray.

**Comment by rwaldron** [comment]
In Ecma-262 8th edition, this test was correct. Following it backwards from [`IsSharedArrayBuffer`](http://www.ecma-international.org/ecma-262/8.0/#sec-issharedarraybuffer): 

> If bufferData is null, return false.

Which used to be called by [`ValidateSharedIntegerTypedArray`](http://www.ecma-international.org/ecma-262/8.0/#sec-validatesharedintegertypedarray): 

> If IsSharedArrayBuffer(buffer) is false, throw a TypeError exception.

Which was the first line of [`Atomics.wake`](http://www.ecma-international.org/ecma-262/8.0/#sec-atomics.wait)

> Let buffer be ? ValidateSharedIntegerTypedArray(typedArray, true).



The new semantics follow a similar path, but through different AOs. Backwards from checking the buffer in [`IsDetachedBuffer`](https://tc39.es/ecma262/#sec-isdetachedbuffer): 

> If arrayBuffer.[[ArrayBufferData]] is null, return true.

Which is called by [`ValidateTypedArray`](https://tc39.es/ecma262/#sec-validatetypedarray): 

> If IsDetachedBuffer(buffer) is true, throw a TypeError exception.

`ValidateTypedArray` is called by [`ValidateIntegerTypedArray`](https://tc39.es/ecma262/#sec-validateintegertypedarray), and `ValidateIntegerTypedArray` is called on the first line of `Atomics.notify`. 

It appears that the spec semantics need to updated, but I think the test is still correct, right?

**Comment by rwaldron** [comment]
Also, I'm seeing a new path! There are now two places where bufferData is checked.

**Comment by rwaldron** [comment]
> I'm going to try and figure out a way to detach the buffer after the first check, but before the second check.

I'm unable to find a way to do this.

**Comment by syg** [comment]
Thanks for the history here!
