### ISSUE TITLE
Strategy for Maintaining Related Tests

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#276]
In gh-267, we're working on tests for destructuring assignment. The
AssignmentPattern grammar is applied in two situations:

- [12.14.4 Runtime Semantics: Evaluation (Assignment Operators)](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-assignment-operators-runtime-semantics-evaluation)
- [13.6.4.13 Runtime Semantics: ForIn/OfBodyEvaluation ( lhs, stmt, iterator,
  lhsKind, labelSet
)](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-forin-div-ofbodyevaluation-lhs-stmt-iterator-lhskind-labelset)

At the moment, gh-267 covers the first case only. This raises a question about
test methodology and coverage expectations. The basic problem that I see is
the duplication necessary: all 116 test files in gh-267 would also be appropriate
for tests describing the pattern's usage within the initializer clause of a `for`
statement.

We could manually copy and translate the files. Although the work required to
do this is somewhat uninteresting, I'm not trying to optimize for intellectual
curiosity of the test writer (who will most likely be me in this case).
Instead, I'm worried about maintenance moving forward. As more tests are added
over time (and possibly as the grammar is refined by later specifications), it
will be the contributor's job to learn about the duplication and maintain
equivalency. This is a burdensome and easy-to-miss task, and I'm not convinced
it will be followed consistently even if we were to include instructions in
the project's CONTRIBUTING.md file.

I'd like to propose that we create a system that verifies equivalency by
inspecting file names. This would be a very rough heuristic (and easily
fooled). That said, even a simple test script like this could help future
contributors learn about this expectation in an automated way at checkin time.
It would prompt them to include the equivalent tests (and where they should
go). I like this because, as I see it, the additional documentation required is
minimal and machine-readable. Not to put the horse before the carriage, but I
see this as being driven by the `features` frontmatter. A flat file in the
root of the project could list which features need to be duplicated in which
places (and it could also blacklist specific files as necessary).

The reason I'm so concerned with this issue is because I have already come
across it to a smaller degree (see gh-204, which duplicates tests for generator
methods in class bodies, generator methods in object literals, generator
function declarations, and generator function expressions), and I expect this
to be an even larger concern for other parts of the spec (for instance,
destructuring assignment only appears in two situations, but destructuring
binding occurs in thirteen).

**Comment by bterlson** [comment]
I think this is a reasonable approach. I was actually thinking we really need a features.json file in the index containing metadata about things on a feature level. I was thinking mapping feature names to folders of tests for the feature (its not as simple as I hoped after the refactoring), but it could also be extended to include something like you propose.

It might be useful to see an example, though. Think you can whip one up?

For the record, I do think that improving the sanity of test authors is a reasonable goal - without test authors, test262 is nothing :)

**Comment by domenic** [comment]
Reminds me of @bterlson's macro-based stuff from a while back...

**Comment by jugglinmike** [comment]
> It might be useful to see an example, though. Think you can whip one up?

Sure

> The problem brings to mind @bterlson's macro-based stuff from a while back...

I'm not familiar with that, so I'm not sure if its an example of a similar problem or a similar solution. Either could be helpful here, though. Any suggestion for where I might find it?

**Comment by jugglinmike** [comment]
As requested, I've drafted a proposal for managing the necessary duplication
between test files. This necessarily required selecting some concrete
technologies. I wanted to acknowledge those up-front and assure everyone that I
have no expectations about the technologies that are ultimately selected to
implement this infrastructure.

Tech:

- yaml for configuration formatting (alternatives: JSON, ini)
- npm for process automation (alternatives: GNU make, Python script, Node.js
  script)

As I mentioned in this issue's description, we're getting ready to land over
100 tests for destructuring assignment:

    test/language/expressions/assignment/destructuring/array-elem-elision.js
    test/language/expressions/assignment/destructuring/array-elem-init-assignment.js
    test/language/expressions/assignment/destructuring/array-elem-init-evaluation.js
    test/language/expressions/assignment/destructuring/array-elem-init-in.js
    test/language/expressions/assignment/destructuring/array-elem-init-order.js
    test/language/expressions/assignment/destructuring/array-elem-init-simple-no-strict.js
    test/language/expressions/assignment/destructuring/array-elem-init-simple-strict.js
    test/language/expressions/assignment/destructuring/array-elem-init-yield-expr.js
    (+ 125 additional files)

These are limited to the pattern's use in the AssignmentExpression position. At
some point, we'll have to follow up and include equivalent tests for its usage
in `for` statements. (There's actually a little more duplication required than
I initially described because we'll have to cover both `for..in` statements and
`for..of` statements):

    test/language/statements/for-in/destructuring/array-elem-elision.js
    test/language/statements/for-in/destructuring/array-elem-init-assignment.js
    test/language/statements/for-in/destructuring/array-elem-init-evaluation.js
    test/language/statements/for-in/destructuring/array-elem-init-in.js
    test/language/statements/for-in/destructuring/array-elem-init-order.js
    test/language/statements/for-in/destructuring/array-elem-init-simple-no-strict.js
    test/language/statements/for-in/destructuring/array-elem-init-simple-strict.js
    test/language/statements/for-in/destructuring/array-elem-init-yield-expr.js
    (+ 125 additional files)

    test/language/statements/for-of/destructuring/array-elem-elision.js
    test/language/statements/for-of/destructuring/array-elem-init-assignment.js
    test/language/statements/for-of/destructuring/array-elem-init-evaluation.js
    test/language/statements/for-of/destructuring/array-elem-init-in.js
    test/language/statements/for-of/destructuring/array-elem-init-order.js
    test/language/statements/for-of/destructuring/array-elem-init-simple-no-strict.js
    test/language/statements/for-of/destructuring/array-elem-init-simple-strict.js
    test/language/statements/for-of/destructuring/array-elem-init-yield-expr.js
    (+ 125 additional files)

If all of these files specified `features: [destructuringAssignment]` in their
frontmatter, then a tool could ensure that all three locations continue to
define equivalent tests into the future. We could configure this tool with a
flat file that was checked in to the project, for instance:

File: `/parity.yml`

```
- features:
  - destructuringAssignment
  locations:
  - language/expressions/assignment/destructuring
  - language/statements/for-in/destructuring
  - language/statements/for-of/destructuring
```

With this in place, our expectations about test parity could be asserted in a
completely automated way (by future reviewers, drive-by contributors, and
continuous integration servers):

    $ npm test
    Verifying coverage... done!

    $ echo $?
    0

If someone were to add a file to just one of these locations, such as:

File: `/test/language/statements/for-of/destructuring/important.js`

```js
/*---
description: >
    Important test case that we missed.
es6id: 13.6.4
features: [destructuringAssignment]
---*/
// (test content omitted)
```

They wouldn't have to remember (or learn through research) the parity
requirement (and maintainers wouldn't have to remember to nag them). This
tooling could alert them of the problem, either when executed locally or
via continuous integration:

    $ npm test
    Verifying coverage...
    Error: Test defined without equivalent coverage

    > File: language/statements/for-of/destructuring/important.js
    > Features:
    > - destructuringAssignment
    > Expected equivalents:
    > - language/expressions/assignment/destructuring/important.js
    > - language/statements/for-in/destructuring/important.js

    Please add equivalent test cases

    $ echo $?
    1

Because this configuration specifies both feature flags *and* directory names,
even more general features can be used. For instance, the flag "generators" is
likely to be used in many different places throughout the test suite, but
parity enforcement can be restricted to the locations for GeneratorExpressions
and GeneratorDeclarations.

File: `/parity.yml`

```diff
 - features:
   - destructuringAssignment
   locations:
   - language/expressions/assignment/destructuring
   - language/statements/for-in/destructuring
   - language/statements/for-of/destructuring
+- features:
+  - generators
+  locations:
+  - language/expressions/generators
+  - language/statements/generators
```

That said, complete parity may not appropriate or even possible in all such
cases. Running with the generators example, consider the following test for
assignment of the `name` attribute:

File: `/test/language/expressions/generators/no-name.js`

```js
/*---
description: can create generator function expressions (no name)
es6id: 14.4
features: [generators]
---*/
var g = (function *() {});

assert.sameValue(g.name, '');
```

This test cannot be replicated for GeneratorDeclarations, but the parity
checker will complain anyway. One way to address this is to support
blacklisting file names, as in:

File: `/parity.yml`

```diff
 - features:
   - destructuringAssignment
   locations:
   - language/expressions/assignment/destructuring
   - language/statements/for-in/destructuring
   - language/statements/for-of/destructuring
 - features:
   - generators
   locations:
   - language/expressions/generators
   - language/statements/generators
+  unique:
+  - language/expressions/generators/no-name
```

This may be sufficient for small edge cases, but it wouldn't scale well for
features that have more substantial variations. This is appreciable even in
this running example for generators. Here, we'd want tests for the following:

```js
var a = function*(){};
var obj1 = { b: function*() {} };
var obj2 = { *c: function*() {} };
var obj3 = { ['d']: function*() {} };
class C1 { *e() {} }
var C2 = class { *f() {} };
```

A more scalable approach would be to support blacklisting by feature flag. Each
of the test files implied by the above statements could be defined with
`features: [generators, functionName]`, and this second flag could be excluded
from the parity rule:

File: `/parity.yml`

```diff
 - features:
   - destructuringAssignment
   locations:
   - language/expressions/assignment/destructuring
   - language/statements/for-in/destructuring
   - language/statements/for-of/destructuring
 - features:
   - generators
+  - !functionName
   locations:
   - language/expressions/generators
   - language/statements/generators
-  unique:
-  - language/expressions/generators/no-name
```

(The `features` flag is a far more expressive means of categorization than file
name, making it much more useful to implementors. It's currently under-used,
though. An added benefit to this approach is that it introduces a technical
motivation for more descriptive feature flags.)

One potential drawback is the duplication between frontmatter and file system.
Note how all the tests in `language/expressions/generators` must also specify
the `generators` feature flag. This seems like a small price to pay and
unlikely to cause problems.

I think that's all that would be necessary for a minimum viable product.
Despite my best efforts, I may have missed some important detail that makes
this a non-starter, so I'm all ears about that. The nice thing about this kind
of check is that it is unobtrusive--we can vet it by slowly opting in small
pieces of the test suite and learning about it's strengths/weaknesses
experimentally. But that's a lot of text! Is it at all what you had in mind,
@bterlson?

**Comment by bterlson** [comment]
I think we can give it a go and see how it progresses.

I'm not sure exactly what data model you're suggesting though. Also things start getting really complex with the ! syntax for excluding features from sets. Can we get away with just defining a list of expected file names maybe?

Also I think JSON over YAML if this is going to primarily be used (especially generated) by tools.

**Comment by jugglinmike** [comment]
> Also I think JSON over YAML if this is going to primarily be used (especially generated) by tools.

I'm glad you said this because I assumed this configuration file would be written by humans. As I see it, the file would have one entry for each set of related tests. This would be read every time the validation process ran, and the process would determine which sets of files required parity through the union of directories and features.

A contributor like me could insert a new entry when they were authoring related tests (e.g. destructuring assignment in AssignmentExpressions and in `for` statements) and this entry would be used to enforce test parity for all future contributions.

Is that different than the use case you have in mind?

**Comment by jugglinmike** [comment]
After [discussing this in the July 2015 TC-39 meeting](https://github.com/tc39/tc39-notes/blob/master/es7/2015-07/july-30.md), we decided to address this problem using procedural file generation techniques. The discussion continued in gh-470, and ultimately led to implementation of a functional tool in gh-545. The tool has recently been merged to `master`, so this issue is resolved.

Thanks for the feedback, all!
