### ISSUE TITLE
Do extra parameters of a method need to be tested?

### ISSUE THREAD

**Issue by NWU-NISL** [tc39/test262#2767]
**Description:**

ES specification claims that the `String.prototype.replace` method should be called with two parameters. When passing three or more parameters, mainstream JS engines like V8, JavaScriptCore, Charka, etc. ignore extra parameters and run correctly. But [Rhino](https://github.com/mozilla/rhino) throws a `SyntaxError` as the following test case:

```js
var func = function (argument) {
  return argument.replace("NonCommercial", "NCpattern", "($28,");
};
var Parameter0 = ";W.b[V";
func(Parameter0);
```

We would like to know if it is necessary to test this situation. Thanks.

**Rhino Version:**

rhino-1.7.11

**Rhino Output:**

```
uncaught JavaScript runtime exception: SyntaxError: invalid flag after regular expression
```

**Expected Output:**

```

```

**ECMA262 Link:**

https://tc39.es/ecma262/#sec-string.prototype.replace

**Comment by rwaldron** [comment]
No, because there is no specification that forbids a runtime from extending the API. [16.1 Forbidden Extensions](https://tc39.es/ecma262/#sec-forbidden-extensions)

**Comment by NWU-NISL** [comment]
Got it. Thanks@rwaldron

**Comment by ljharb** [comment]
However, it's still probably a good idea to file bugs on implementations that don't match web reality. Even though test262 may not allow tests that forbid things the specification *technically* allows, in practice, there is a massive pile of things that are de facto prohibited, and this case sounds like one of them.

**Comment by yeguixin** [comment]
Thanks for your advice @ljharb

**Comment by yeguixin** [comment]
Thanks for your advice @ljharb

**Comment by yeguixin** [comment]
Thanks for your advice @ljharb

**Comment by NWU-NISL** [comment]
Thanks for your advice @ljharb
