### ISSUE TITLE
Missing tests for Array.prototype.shift method

### ISSUE THREAD

**Issue by NWU-NISL** [tc39/test262#2773]
**Description:**

ES specification states that if the length property of the argument passed to `Array.prototype.shift` method cannot be changed , JS engines should throw a `TypeError`. So if the inputting argument is a function object whose length property is unconfigurable as the following test case, JS engines should throw a `TypeError`. We didn't find a similar test case from Test262 test suite.

```js
var NISLFuzzingFunc =function(array){
    return Array.prototype.shift.call(array);
};
var NISLParameter0=function(config){};
NISLFuzzingFunc(NISLParameter0);
```

The above test case triggers a bug of JavaScriptCore and Rhino(https://github.com/mozilla/rhino/issues/612).

**Engine Version:**
Rhino-1.7.11
JavaScriptCore-d940b47

**Output:**

```
 
```

**Expected Output:**

```
TypeError:"length"is read-only
```

**ECMA262 Link:**

1. https://tc39.es/ecma262/#sec-array.prototype.shift
   **22.1.3.24 Array.prototype.shift ( )**
   When the `reduceRight` method is called with one or two arguments, the following steps are taken: 
   …… 
   6. ......
      e. Else, 
        i. Assert: fromPresent is false.
       ii. Perform? [DeletePropertyOrThrow](https://tc39.es/ecma262/#sec-deletepropertyorthrow)(O, to)
      ……
2. https://tc39.es/ecma262/#sec-deletepropertyorthrow
   **7.3.9 DeletePropertyOrThrow ( O, P )**
      ......

      3. Let success be ? O.[[Delete]] (p)
      4. If success is false, throw a TypeError exception.
         ......

**Comment by rwaldron** [comment]
This _is_ tested, but not with a function object. I'll update the test to include more objects where `length` would produce this outcome.
