### ISSUE TITLE
Coverage: missing tests for Array.prototype.reduceRight method

### ISSUE THREAD

**Issue by NWU-NISL** [tc39/test262#2774]
**Description:**
We found Test262 didn't cover all variable types of the second argument for the `Array.prototype.reduceRight` method shown as the following test case: 

```js
var NISLFuzzingFunc =function(){
    var func=function(a,b){};
    var obj=[];
    return obj.reduceRight(func, undefined);
};
var NISLCallingResult =NISLFuzzingFunc();
print(NISLCallingResult);
```

When the length of the obj is 0 and the second argument of the reduceRight method is `undefined`, the test case should be executed normally without throwing any exception. But JerryScript throws a TypeError exception( https://github.com/jerryscript-project/jerryscript/issues/3463.). We would like to know if the test case needs to be added. Thanks.

**Jerryscript Version:**

996bf76

**jerryscript Output:**

```js
Script Error:TypeError:Initial value cannot be undefined.
```

**Expected Output:**

```js
undefined
```

**ECMA262 Link:**

1. https://tc39.es/ecma262/#sec-array.prototype.reduceright

**Comment by rwaldron** [comment]
It is the _presence_ of a second argument that prevents the TypeError from occuring, not whether the argument's value is `undefined` or something more meaningful. The same is true for `[].reduce(() => {}, undefined)`: 

> If _len_ is 0 and _initialValue_ is not present, throw a **TypeError** exception.
(https://tc39.es/ecma262/#sec-array.prototype.reduceright)

`undefined` is a perfectly valid _initialValue_.

**Comment by NWU-NISL** [comment]
Yes, `undefined` is a valid _initialValue_. According to the ES specification, JS engines should output `undefined` instead of throwing a TypeError exception. After inspecting, we found Test262 contains test cases where `initialValue` is [`Number`](https://github.com/tc39/test262/blob/main/test/built-ins/Array/prototype/reduceRight/15.4.4.22-5-9.js) and [`String`](https://github.com/tc39/test262/blob/main/test/built-ins/Array/prototype/reduceRight/15.4.4.22-7-10.js), but it does not cover the case where `initialValue = undefined`.   Thanks @rwaldron.

**Comment by rwaldron** [comment]
`initialValue = undefined`: https://github.com/tc39/test262/blob/5e3761f5c8347370880ca86e54a6af7c746dcc1b/test/built-ins/Array/prototype/reduceRight/15.4.4.22-9-c-ii-20.js

**Comment by NWU-NISL** [comment]
Got it. Thanks.
