### ISSUE TITLE
RegExp tests incorrectly verify that RegExp.prototype is a RegExp object

### ISSUE THREAD

**Issue by bterlson** [tc39/test262#278]
According to https://people.mozilla.org/~jorendorff/es6-draft.html#sec-properties-of-the-regexp-prototype-object, it is not.

**Comment by jugglinmike** [comment]
Canonical reference: http://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-regexp-prototype-object

@bterlson I can't find the tests mentioned in this issue's title. Maybe this has been fixed?

**Comment by bterlson** [comment]
Perhaps :)

**Comment by bterlson** [comment]
As in, I can't find it either.
