### ISSUE TITLE
Possible incomplete test coverage of String.prototype.replace method

### ISSUE THREAD

**Issue by NWU-NISL** [tc39/test262#2797]
**Description:**

We found Test262 may missing the test case where the second argument of the `String.prototype.replace` method is a regex expression. Like the following test case:

```js
var NISLFuzzingFunc=function (){
    var a = 'test'.replace('e', /^/);
    print(a);
};
NISLFuzzingFunc();
```

This test case caused a bug(https://github.com/mozilla/rhino/issues/726) of [Rhino](https://github.com/mozilla/rhino) which didn't covert the regex expression to a string.

**Rhino Version:** 

rhino-1.7.12 

**Rhino Output:**

```js
tst
```

**Expected Output:**

 ```js
t/^/st
 ```

**ECMA262 Link:**

1. https://tc39.es/ecma262/#sec-string.prototype.replace

   When the `replace` method is called with arguments searchValue and replaceValue, the following steps are taken:

   ......

   5. Let functionalReplace be [IsCallable](https://tc39.es/ecma262/#sec-iscallable)(replaceValue).
   6. If functionalReplace is false, then
      1. Set replaceValue to ? [ToString](https://tc39.es/ecma262/#sec-tostring)(replaceValue).

   ......

2. https://tc39.es/ecma262/#sec-tostring

**Comment by rwaldron** [comment]
Coverage exists for calling the `toString` method of the second argument, but not explicitly for a regexp object.
