### ISSUE TITLE
Test for fresh `let` binding in c-style for loops?

### ISSUE THREAD

**Issue by getify** [tc39/test262#28]
Apologies if I've missed it or I'm off track, but I was looking for a test tracking the feature that `let` declarations in a `for (;;)` style loop are fresh bound per iteration, and I wasn't able to find it. For that matter, I'd also like to see the test for fresh binding for `for-in` loops too.

If these tests exist and I missed them, I apologize. I spent about 30 minutes combing through and it became painfully obvious I didn't know what exactly to be looking for.

**Comment by leobalter** [comment]
this is already covered, I believe. Feel free to reopen if necessary.
