### ISSUE TITLE
Iteration test restructuring

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#281]
I'm currently working on filling out the tests for built-in iterables, and I've noticed an organizational pattern I would like to change.

Currently, tests for String iteration, Array iteration, and Set iteration are placed within `built-ins/String`, `built-ins/Array` and `built-ins/Set` respectively. With the recent addition of ES6-specific tests, it has become much more clear that the `built-ins` directory is *not* reserved for globally-accessible intrinsics, so I think a more logical place for these tests would be `built-ins/StringIteratorPrototype` `built-ins/ArrayIteratorPrototype`, and `built-ins/SetIteratorPrototype`.

@bterlson would you accept a patch to this effect?

**Comment by bterlson** [comment]
I am fine with this.
