### ISSUE TITLE
Incorrect behaviour in test

### ISSUE THREAD

**Issue by qwerasd205** [tc39/test262#2841]
I was looking through tests trying to find interesting behavior when I stumbled upon [this test](https://github.com/tc39/test262/blob/master/test/language/types/string/S8.4_A7.1.js)
```
info: <LF> between chunks of one string not allowed
es5id: 8.4_A7.1
description: Insert <LF> between chunks of one string
```
The code
```js
assert.throws(ReferenceError, function() {
  eval("var x = asdf\u000Aghjk");
});
```
is wrong, though, as you might notice it has no inner quotes so the attempted evaluation is
```js
var x = asdf<LF>ghjk;
```
Quotation marks should be added to fix this (i.e. `eval("var x = \"asdf\u000Aghjk\"")`, which instead should result in a SyntaxError, not a ReferenceError.
I would submit a PR for this myself but I really don't like dealing with git.

**Comment by qwerasd205** [comment]
There are also three similar tests with the same bug, [this one](https://github.com/tc39/test262/blob/master/test/language/types/string/S8.4_A7.2.js), [this one](https://github.com/tc39/test262/blob/master/test/language/types/string/S8.4_A7.3.js), and [this one](https://github.com/tc39/test262/blob/master/test/language/types/string/S8.4_A7.4.js)

**Comment by qwerasd205** [comment]
Additionally it seems that [this test](https://github.com/tc39/test262/blob/master/test/language/line-terminators/S7.3_A2.1_T2.js) and [this test](https://github.com/tc39/test262/blob/master/test/language/line-terminators/S7.3_A2.2_T2.js) test what these broken ones are supposed to, but correctly (Though, I haven't checked if the newlines at the start/end are the correct character)

**Comment by rwaldron** [comment]
The eval tests are all correct. Using the <LF> test as an example: 

```js
assert.throws(ReferenceError, function() {
  eval("var x = asdf\u000Aghjk");
});
```
A ReferenceError is correct, because the code itself is parsed as: 

```js
var x = asdf
ghjk
```

Which is valid, but when it's evaluated, the identifier `asdf` doesn't exist, so a ReferenceError exception occurs.

**Comment by qwerasd205** [comment]
Yes, but the *description* of the test reads "<LF> between chunks of one string not allowed," implying it is meant to test strings, not identifiers. It's *testing* the wrong thing.
