### ISSUE TITLE
Missing tests for Reflect.apply method

### ISSUE THREAD

**Issue by NWU-NISL** [tc39/test262#2844]
**Description:**

We found that Test262 may miss the test case where the third argument of the `Reflect.apply` method is non-object type, such as the following example:

```js
var f = function (){
    var a = Reflect.apply(Math.floor, undefined, undefined); 
    print(a);
};
f();
```

This test case caused a bug of QuickJS which didn't throw a `TypeError` exception when the third argument is `undefined`. 

**QuickJS Version:**

QuickJS-2020-04-12

**QuickJS Output:**

```js
NaN
```

**Expected Output:**

```js
TypeError: Reflect.apply requires the third argument be an object
```

 

**ECMA262 Link:**

1. https://tc39.es/ecma262/#sec-reflect.apply

   **27.1.1 Reflect.apply ( target, thisArgument, argumentsList )**

   When the `apply` function is called with arguments target, thisArgument, and argumentsList, the following steps are taken:

   1. If [IsCallable](https://tc39.es/ecma262/#sec-iscallable)(target) is false, throw a TypeError exception.

   2. Let args be ? [CreateListFromArrayLike](https://tc39.es/ecma262/#sec-createlistfromarraylike)(argumentsList).

      ...

2. https://tc39.es/ecma262/#sec-createlistfromarraylike

   **7.3.19 CreateListFromArrayLike ( obj [ , elementTypes ] )**

   ...

   2. If [Type](https://tc39.es/ecma262/#sec-ecmascript-data-types-and-values)(obj) is not Object, throw a TypeError exception.

   ...

**Comment by rwaldron** [comment]
There is a test that very explicitly checks this behavior: https://github.com/tc39/test262/blob/main/test/built-ins/Reflect/apply/arguments-list-is-not-array-like.js ...and qjs is actually passing that test correctly. What's failing is that qjs is treating `Reflect.apply(..., ..., undefined);` differently! I'll add a test for this and other similar cases.

**Comment by rwaldron** [comment]
Found another bug in qjs: `Reflect.apply(Math.round, null)`
