### ISSUE TITLE
File path length issue in Windows

### ISSUE THREAD

**Issue by tudorms** [tc39/test262#2865]
It looks like [this PR](https://github.com/tc39/test262/pull/2815) ([this commit](https://github.com/tc39/test262/pull/2815/commits/deb1bacc1007a6142d209eaec9bf3dcbd8756406) specifically) renamed some of the test files to exceedingly long filenames.

This is causing issues on Windows machines where the path is limited to 260 characters.

This may be worked around locally in Windows 10 by using Group Policy to turn on "Enable Win32 long paths" in Computer Configuration > Administrative Templates > System > Filesystem and running `git config --system core.longpaths true` from an administrative command prompt. But there is no solution for previous versions of Windows (or SKUs like Home) or on machines without administrative access.

Is there any way we can reverse the rename or shorten the filenames to something smaller that keeps the code OS-portable?

Thank you!

**Comment by rwaldron** [comment]
Thanks for the report. I'll take a look next week.
