### ISSUE TITLE
export-expname-from-binding-string.js is wrong

### ISSUE THREAD

**Issue by syg** [tc39/test262#2866]
https://github.com/tc39/test262/blob/ad8a5e9940ee60d1ecb6e150b7aecf09b17545dd/test/language/module-code/export-expname-from-binding-string.js#L20

That line tries to re-export an import named `Mercury`.

https://github.com/tc39/test262/blob/ad8a5e9940ee60d1ecb6e150b7aecf09b17545dd/test/language/module-code/export-expname_FIXTURE.js doesn't have an export named `Mercury`, only `☿`.

cc @bfarias-godaddy @devsnek

**Comment by syg** [comment]
@rwaldron That fix isn't right, there are other tests that do depend on that file exporting a binding named `☿`, like https://github.com/tc39/test262/blob/main/test/language/module-code/export-expname-from-string-binding.js

You'd need to export both `☿` and `Mercury` to cover all the cases.

**Comment by rwaldron** [comment]
That'll teach me to work on tests late at night 😴

**Comment by devsnek** [comment]
It seems this introduced one more bug:

![](https://gc.gy/70681663.png)
