### ISSUE TITLE
Align Detached Buffer Semantics: test update needs, from QuickJS

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#2879]
From QuickJS: 

- [x] test/built-ins/TypedArray/prototype/every/BigInt/callbackfn-detachbuffer.js:35: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all (Testing with BigInt64Array.)
    - updated
- [x] test/built-ins/TypedArray/prototype/every/callbackfn-detachbuffer.js:28: Test262Error: Expected SameValue(«1», «2») to be true (Testing with Float64Array.)
    - this one is correct
- [x] test/built-ins/TypedArray/prototype/filter/BigInt/callbackfn-detachbuffer.js:27: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all (Testing with BigInt64Array.)
    - updated
- [x] test/built-ins/TypedArray/prototype/filter/callbackfn-detachbuffer.js:20: Test262Error: Expected SameValue(«1», «2») to be true (Testing with Float64Array.)
    - this one is correct
- [x] test/built-ins/TypedArray/prototype/find/BigInt/predicate-may-detach-buffer.js:43: Test262Error: throws a TypeError getting a value from the detached buffer Expected a TypeError to be thrown but no exception was thrown at all (Testing with BigInt64Array.)
    - updated
- [x] test/built-ins/TypedArray/prototype/findIndex/BigInt/predicate-may-detach-buffer.js:36: Test262Error: throws a TypeError getting a value from the detached buffer Expected a TypeError to be thrown but no exception was thrown at all (Testing with BigInt64Array.)
    - updated
- [x] test/built-ins/TypedArray/prototype/forEach/BigInt/callbackfn-detachbuffer.js:35: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all (Testing with BigInt64Array.)
    - updated
- [x] test/built-ins/TypedArray/prototype/forEach/callbackfn-detachbuffer.js:28: Test262Error: Expected SameValue(«1», «2») to be true (Testing with Float64Array.)
    - this one is correct
- [x] test/built-ins/TypedArray/prototype/map/BigInt/callbackfn-detachbuffer.js:27: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all (Testing with BigInt64Array.)
    - updated
- [x] test/built-ins/TypedArray/prototype/map/callbackfn-detachbuffer.js:20: Test262Error: Expected SameValue(«1», «2») to be true (Testing with Float64Array.)
    - this one is correct
- [x] test/built-ins/TypedArray/prototype/reduce/BigInt/callbackfn-detachbuffer.js:36: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all (Testing with BigInt64Array.)
    - updated
- [x] test/built-ins/TypedArray/prototype/reduce/callbackfn-detachbuffer.js:29: Test262Error: Expected SameValue(«1», «2») to be true (Testing with Float64Array.)
    - this one is correct
- [x] test/built-ins/TypedArray/prototype/reduceRight/BigInt/callbackfn-detachbuffer.js:36: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all (Testing with BigInt64Array.)
    - updated
- [x] test/built-ins/TypedArray/prototype/reduceRight/callbackfn-detachbuffer.js:29: Test262Error: Expected SameValue(«1», «2») to be true (Testing with Float64Array.)
    - this one is correct
- [x] test/built-ins/TypedArray/prototype/some/BigInt/callbackfn-detachbuffer.js:35: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all (Testing with BigInt64Array.)
    - updated
- [x] test/built-ins/TypedArray/prototype/some/callbackfn-detachbuffer.js:28: Test262Error: Expected SameValue(«1», «2») to be true (Testing with Float64Array.)
    - this one is correct
- [x] test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/BigInt/detached-buffer.js:37: Test262Error:  (Testing with BigInt64Array.)
    - this one is correct
- [x] test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/detached-buffer.js:38: Test262Error:  (Testing with Float64Array.)
    - this one is correct
- [x] test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/key-is-numericindex-desc-configurable.js:25: Test262Error: side effect check Expected SameValue(«42», «0») to be true (Testing with Float64Array.)
    - this one is correct
- [x] test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/key-is-numericindex.js:26: Test262Error: Expected obj[0] to have configurable:false. (Testing with Float64Array.)
    - this one is correct
- [x] test/built-ins/TypedArrayConstructors/internals/GetOwnProperty/BigInt/index-prop-desc.js:21: Test262Error: Expected obj[0] to be configurable, but was not. (Testing with BigInt64Array.)
    - this one is correct, made consistent with test/built-ins/TypedArrayConstructors/internals/GetOwnProperty/index-prop-desc.js
- [x] test/built-ins/TypedArrayConstructors/internals/GetOwnProperty/index-prop-desc.js:22: Test262Error: descriptor should be writable; descriptor should be configurable (Testing with Float64Array.)
    - this one is correct, but had mistake in info
- [x] test/built-ins/TypedArrayConstructors/internals/Set/BigInt/detached-buffer-realm.js:36:
    - this one is correct
- [x] test/built-ins/TypedArrayConstructors/internals/Set/BigInt/detached-buffer.js:34: TypeError: cannot convert bigint to number (Testing with BigInt64Array.)

**Comment by bellard** [comment]
Some remarks:

- test/built-ins/TypedArray/prototype/every/callbackfn-detachbuffer.js: "loops" should be "1" instead of "2" because once the buffer is detached, "HasProperty(O, Pk)" returns false and the callback is no longer called:
----
Repeat, while k < len,

    Let Pk be ! ToString(𝔽(k)).
    Let kPresent be ? HasProperty(O, Pk).
    If kPresent is true, then
        Let kValue be ? Get(O, Pk).
        Let testResult be ! ToBoolean(? Call(callbackfn, thisArg, « kValue, 𝔽(k), O »)).
        If testResult is false, return false.
    Set k to k + 1.
----

The same holds for all similar tests.

- test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/key-is-numericindex-desc-configurable.js : The defineProperty should update the property "0" to 42, so the test must be modified to:

   assert.sameValue(sample[0], 42, "side effect check");

- test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/key-is-numericindex.js: the test is not correct because verifyNotConfigurable(sample, "0") is called instead of verifyConfigurable(...). But verifyConfigurable() in harness does not work because it does "delete" on the property and test that it is no longer present (see isConfigurable() in propertyHelper.js), which does not work with TypedArrays.

- test/built-ins/TypedArrayConstructors/internals/GetOwnProperty/BigInt/index-prop-desc.js,  test/built-ins/TypedArrayConstructors/internals/GetOwnProperty/index-prop-desc.js : same problem because verifyConfigurable() does not work as intended in harness.

- test/built-ins/TypedArrayConstructors/internals/Set/BigInt/detached-buffer-realm.js: the test is incorrect in strict mode because out-of-bound accesses throw an exception in this case.

**Comment by rkirsling** [comment]
My understanding here was that the typed array methods lacking explicit algorithms (e.g. [`every`](https://tc39.es/ecma262/#sec-%typedarray%.prototype.every)) aren't meant as a precise delegation to the array method so much as a hand-wavey "change what should be changed for typed arrays", in an analogous way to the methods that are made explicit (e.g. [`map`](https://tc39.es/ecma262/#sec-%typedarray%.prototype.map)). In particular, typed arrays can't have holes, so there's no per-iteration HasProperty check.

We recently discussed making all of these algorithms explicit; at that moment, it seemed like a non-urgent editorial matter, but I think this makes it more of a pressing issue. I think it's okay for the change in this PR to stand until that's resolved though.

**Comment by rkirsling** [comment]
Spec PR is ready at https://github.com/tc39/ecma262/pull/2221.

**Comment by rkirsling** [comment]
Update: tc39/ecma262#2221 got consensus in this week's plenary.
