### ISSUE TITLE
Can ungodly-long test file names be avoided?

### ISSUE THREAD

**Issue by jswalden** [tc39/test262#2881]
I just updated SpiderMonkey's test262 import.  Most of the tests run without issue, but https://github.com/tc39/test262/blob/main/test/built-ins/Object/seal/object-seal-the-configurable-attribute-of-all-own-properties-of-o-are-set-from-true-to-false-and-other-attributes-of-the-property-are-unaltered.js and https://github.com/tc39/test262/blob/main/test/built-ins/Object/seal/object-seal-the-configurable-attribute-of-own-accessor-property-of-o-is-set-from-true-to-false-and-other-attributes-of-the-property-are-unaltered.js cause some issues for us -- at one point in our infrastructure, we tar up all test262 tests, and on one machine we seem to be using an older `tar` that barfs on these two filenames (or maybe the total paths?) as being excessively long.  (There are other tests in that folder that are nearly as long, but we don't error on them.  It's not clear to me if that's because they're just short enough, or our infra only reports the first two failures.)

Would it be possible to rename these tests to something shorter and more concise?  Shoving entire sentences into test names is pretty gross.

And, thinking somewhat into the future, is there any chance test262 could maybe have a maximum-test-name-length policy?  I don't mind if it's generous, but even so, surely a sane outer limit could be well below these extents.

**Comment by jswalden** [comment]
@rwaldron You added these particular tests -- any chance you could rename them?  (and maybe ideally the others that are crazy-long in the same directory)

**Comment by rwaldron** [comment]
@jswalden these used to be named things like "S15_1.a.iii.foo_bar.js" and I'm working to rename those to something that gets generated from their `description: ...`.

Sure, I can rename them.
