### ISSUE TITLE
Proposal: `raw` frontmatter flag

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#291]
Many of the directive prologue tests are invalidated by the code transformation
that takes place prior to test execution. For instance, see
[test/language/directive-prologue/10.1.1-2gs.js](https://github.com/tc39/test262/blob/527644d21199d5e9fcab0b958c3426cbd0d0b9d6/test/language/directive-prologue/10.1.1-2gs.js):

```js
/*---
es5id: 10.1.1-2gs
description: >
    Strict Mode - Use Strict Directive Prologue is ''use strict''
    which lost the last character ';'
negative: NotEarlyError
flags: [noStrict]
---*/

"use strict"
throw NotEarlyError;
var public = 1;
```

First of all: this test is incorrect. Any attempt to execute that code should
fail with an *early* `SyntaxError`, not the `NotEarlyError` object during
runtime. The reason it passes right now is that test runners insert code into
the beginning of the test, so this code is never executed in strict mode.

One fix would be to simply change the `noStrict` flag to `onlyStrict`, but this
is generally an issue for tests involving directives; that substitution won't
work for tests that require more nuanced manipulation of the directive, e.g.
the also-incorrect
[test/language/directive-prologue/10.1.1-8gs.js](https://github.com/tc39/test262/blob/527644d21199d5e9fcab0b958c3426cbd0d0b9d6/test/language/directive-prologue/10.1.1-8gs.js):

```js
/*---
es5id: 10.1.1-8gs
description: >
    Strict Mode - Use Strict Directive Prologue is ''use strict';'
    which appears twice in the code
negative: NotEarlyError
flags: [noStrict]
---*/

"use strict";
"use strict";
throw NotEarlyError;
var public = 1;
```

In order to actually test the described behavior, these tests must be run
without the insertion of any code at all. Rather than opt all tests out of the
"default" helper logic, I think it makes sense to implement a new flag called
`raw` that instructs runners to do no pre-processing prior to execution.

```diff
 /*---
 es5id: 10.1.1-8gs
 description: >
     Strict Mode - Use Strict Directive Prologue is ''use strict';'
     which appears twice in the code
-negative: NotEarlyError
-flags: [noStrict]
+negative: SyntaxError
+flags: [raw]
 ---*/

 "use strict";
 "use strict";
-throw NotEarlyError;
+throw new Error("Not an early error");
 var public = 1;
```

Does this seem right to you, @bterlson?

**Comment by bterlson** [comment]
I like the raw flag. Raw would also mean you couldn't have includes of any sort (eg. no assert helper), which I think is ok? Alternatively, harnesses could be updated to assume includes are declarations that hoist, but that could be too large of an assumption...

**Comment by jugglinmike** [comment]
In addition to assuming correct hoisting semantics, the effect would also be a little inconsistent (you would have `assert` but you wouldn't have `NotEarlyError` or `assert.sameValue`) and more confusing overall.

**Comment by bterlson** [comment]
So you get nothing. for similar reasons the harness couldn't inject $ERROR/$DONE, etc. So basically the only thing it could do is throw an error...

Another alternative is to update harnesses to check for any directive prologues and insert their additional definitions underneath. But that seems brittle.

**Comment by anba** [comment]
It'd be easier if there was a single command line syntax to provide multiple input files for shells. Then it wouldn't be necessary to concatenate the helpers and the test source code...

Works with SpiderMonkey, JavaScriptCore and V8:
&emsp; `<js-shell> -f /tmp/fst.js -f /tmp/snd.js /tmp/test.js`

Works with Nashorn, JavaScriptCore and V8:
&emsp; `<js-shell> /tmp/fst.js /tmp/snd.js /tmp/test.js`

**Comment by jugglinmike** [comment]
Another option would be to support an "include" directive, giving test authors control over how test files are constructed prior to execution.

```diff
 /*---
 es5id: 10.1.1-8gs
 description: >
     Strict Mode - Use Strict Directive Prologue is ''use strict';'
     which appears twice in the code
 negative: NotEarlyError
 flags: [noStrict]
 ---*/

 "use strict";
 "use strict";
+// test262includes
 throw NotEarlyError;
 var public = 1;
```

...but sometimes it feels like all I do around here is propose more abstraction. It might be good to just give "raw" a try to start, since I don't expect it to be required by very many tests.

**Comment by bterlson** [comment]
Are there any 'raw' tests that want asserts today?

**Comment by jugglinmike** [comment]
I'll do some research on that and get back to you tomorrow.

**Comment by jugglinmike** [comment]
I've stepped through the tests in the `language/directive-prologue/` directory, and it looks like the following tests need the `raw` tag:

- [language/directive-prologue/10.1.1-2gs.js](https://github.com/tc39/test262/blob/21b739f1dcd008e894384a909af5c3ec458a5dcc/test/language/directive-prologue/10.1.1-2gs.js)
- [language/directive-prologue/10.1.1-5gs.js](https://github.com/tc39/test262/blob/21b739f1dcd008e894384a909af5c3ec458a5dcc/test/language/directive-prologue/10.1.1-5gs.js)
- [language/directive-prologue/10.1.1-8gs.js](https://github.com/tc39/test262/blob/21b739f1dcd008e894384a909af5c3ec458a5dcc/test/language/directive-prologue/10.1.1-8gs.js)
- [language/directive-prologue/14.1-4gs.js](https://github.com/tc39/test262/blob/21b739f1dcd008e894384a909af5c3ec458a5dcc/test/language/directive-prologue/14.1-4gs.js)
- [language/directive-prologue/14.1-5gs.js](https://github.com/tc39/test262/blob/21b739f1dcd008e894384a909af5c3ec458a5dcc/test/language/directive-prologue/14.1-5gs.js)

I can't think of any other situations where code insertion would have an effect, and a brief survey of existing tests suggests that there are none. A naive automated search also corroborates:

    $ grep noStrict test/ -r -l --null | xargs -0 grep -E "^[\"']use"
    test/language/directive-prologue/10.1.1-5gs.js:"use strict";
    test/language/directive-prologue/10.1.1-8gs.js:"use strict";
    test/language/directive-prologue/10.1.1-8gs.js:"use strict";
    test/language/directive-prologue/10.1.1-2gs.js:"use strict"

None of these tests use assertions; their only dependency is on the `NotEarlyError` object. This could easily be replaced by a `throw` statement as suggested in the original report.

This research has got me thinking about the problem more generally. ("Uh oh", you're thinking.) I've identified additional work that needs to be done in gh-301, and I've suggested a much more involved change (which would obviate this proposal) in gh-302

**Comment by jugglinmike** [comment]
Resolved via gh-340
