### ISSUE TITLE
Missing coverage: compound assignment w/ private accessor properties

### ISSUE THREAD

**Issue by marjakh** [tc39/test262#2940]
Per this V8 bug which was not caught by test262: https://bugs.chromium.org/p/v8/issues/detail?id=11360

Added V8 tests which could be repurposed as test262 tests:
https://chromium-review.googlesource.com/c/v8/v8/+/2652495/1/test/mjsunit/regress/regress-v8-11360.js

**Comment by ptomato** [comment]
I'd like to start working on this.
