### ISSUE TITLE
website network Error: net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

### ISSUE THREAD

**Issue by skychx** [tc39/test262#2955]
website link: https://test262.report/browse/?date=2020-12-16

### NetWork Error

```
GET https://test262.report/main.client.bundle.js net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
```

![image](https://user-images.githubusercontent.com/24872439/108987029-c75bfd80-76cd-11eb-956e-913a62934d73.png)

![image](https://user-images.githubusercontent.com/24872439/108987131-e65a8f80-76cd-11eb-8f70-389b2cefe560.png)

**Comment by rwaldron** [comment]
Thanks for the report. Unfortunately, test262.report is not a project that's directly controlled by Test262.
