### ISSUE TITLE
ES6 [[Set]] receiver restrictions

### ISSUE THREAD

**Issue by evilpie** [tc39/test262#296]
https://bugs.ecmascript.org/show_bug.cgi?id=4331 added new restrictions to [[Set]]. Which prevents overwriting of non-writable or accessor properties on the receiver.

I assume that there is no test for this yet, so I want to add some.

**Comment by bterlson** [comment]
I also assume not considering it's new semantics. There MIGHT be tests for the old behavior but I'm not seeing it.

**Comment by leobalter** [comment]
I believe we've got this covered at these files listed below, please re-open if necessary:

- test/language/expressions/super/prop-dot-cls-ref-strict.js
- test/language/expressions/super/prop-dot-obj-ref-non-strict.js
- test/language/expressions/super/prop-dot-obj-ref-strict.js
- test/language/expressions/super/prop-expr-cls-ref-strict.js
- test/language/expressions/super/prop-expr-obj-ref-non-strict.js
- test/language/expressions/super/prop-expr-obj-ref-strict.js
