### ISSUE TITLE
Marking legacy support projects as "deprecated"

### ISSUE THREAD

**Issue by smikes** [tc39/test262#2960]
Hi folks,

  First off, I have to say this project has really taken off and looks great!

  I have a number of legacy projects/repositories from the "bad old days" (including `test262-parser`) that I am pretty sure are no longer used anywhere in the test262 project or in its (current) dependencies.  I am planning to update the README for those repositories to mark them as deprecated.  Before I do that, is there any reason I should not do that?  Is there any language I should include/avoid?

This is the list of repositories I am proposing to modify:

https://github.com/smikes/test262-parser
https://github.com/smikes/test262-mocha-adapter
https://github.com/smikes/test262-generator
https://github.com/smikes/node-test262-runner

The text I am planning to add would be immediately below the # Title in the README.md, and would say:

```
This repository IS NO LONGER MAINTAINED.

Please refer to https://github.com/tc39/test262
```

Additionally - though this is a separate question - there may be NPM modules that were published from these repositories and included `test262` in the name.  These older packages are nearly certain to have security problems or to depend on older packages with problems.  @bterlson @rwaldron I forget if I granted maintainer access to one/both of you... perhaps we can follow that up separately.

**Comment by rwaldron** [comment]
Works for me! Thanks for all of your excellent work over the years :)

If I encounter any packages that need maintenance, I will reach out.

**Comment by smikes** [comment]
Done.
