### ISSUE TITLE
test Symbol.for('bar').toString()

### ISSUE THREAD

**Issue by dckc** [tc39/test262#2967]
the spec is pretty clear that `Symbol.for('bar').toString()` should evaluate to `"Symbol(bar)"`. Please add a test for this.

https://tc39.es/ecma262/#sec-symbol.prototype.tostring

MDN gives this example:
```
// The key is also used as the description
var sym = Symbol.for('mario');
sym.toString(); // "Symbol(mario)"
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for

context :https://github.com/Moddable-OpenSource/moddable/issues/621

cc @erights @phoddie

**Comment by jugglinmike** [comment]
Thanks for the report, @dckc! I opened gh-2970 to address this.

(I decided to use the `description` property rather than `toString` since that puts slightly less unrelated functionality under test. It still captures XS's bug, though.)
