### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#297]
While reviewing a recent pull request (gh-293), I found myself wanting to give feedback regarding coding style--things like:
- Maximum column width
- Quotation mark usage (single or double)
- White space (hard vs. soft, and width if soft)

...but I had to stop myself because I didn't know the actual policy of the project. I think that any open source project has a lot to gain from consistently-formatted source code. 

Test262 concerns the syntax of the language itself, so there will need to be provisions for tests that explicitly require formatting code that break any specific style recommendation. I don't think this effects the utility of a style guide (especially not for one as brief as I'm suggesting) as such tests will be few and far between.

Although the current level of consistency across tests is a little tough to gauge, I would like to introduce a new standard for future contributions and document these expectations in the project's contribution guidelines.

**Comment by bterlson** [comment]
Agree, these would be good to have (aside from tests for specific sequences of whitespaces or what-have-you).

* Line width of 80 seems excessive. Maybe 100? I'd like to say no hard wraps but I guess some people use editors where this doesn't work nicely?
* Single quotes ftw?!?
* 4-space tabs seems the standard in most tests I can find. Might as well formalize that.
* Probably want a point about asserting one thing per assert (Eg. don't use Boolean operators in your assertion).

Anything else we might want?

**Comment by domenic** [comment]
I think the key thing is that the style should be enforceable and preferably auto-fixable. jscs is probably the best tool for such things these days. Maybe eslint since it would allow custom rules like the don't-use-boolean-operators.

**Comment by bterlson** [comment]
I think automating this is more trouble than it's worth. A fair number of files aren't parseable. It also seems likely to clobber deliberate styles unless the developer is careful.

**Comment by domenic** [comment]
I wouldn't necessarily want to apply it retroactively, but rather to incoming files.

**Comment by bterlson** [comment]
I understand, but if you want a file for some reason to differ from the enforced styles, you would have to add your new file to some exclude list. Or if the file can't be parsed (eg. every negative syntax error). Seems like a lot of overhead for what is really easy for authors to do (once documented :-P)

**Comment by jugglinmike** [comment]
> - Line width of 80 seems excessive. Maybe 100? I'd like to say no hard wraps but I guess some people use editors where this doesn't work nicely?

Soft wrap can be nice for text, especially cases like frontmatter description/info which we don't expect to change often (so we won't miss line-by-line diffs). In my experience, hard wrapping makes source code more readable.

> - Single quotes ftw?!?
> - 4-space tabs seems the standard in most tests I can find. Might as well formalize that.
> - Probably want a point about asserting one thing per assert (Eg. don't use Boolean operators in your assertion).

Sounds good!

> I think automating this is more trouble than it's worth. A fair number of files aren't parseable. It also seems likely to clobber deliberate styles unless the developer is careful.

I was going to respond along the same lines. One approach that might scale better is another frontmatter tag, `ignoreStyle` or similar. This would let individual tests opt-in as needed. But the infrastructure required is probably non-trivial--we'd need to hook in to JSCS in a kind of unique way (or build a wrapper CLI). But this ability would also let us address the problem of invalid source code: any test with the `negative` attribute could be skipped as well.

**Comment by bterlson** [comment]
Fine with 80 or 100 line width. Diff is a good point - github's editor doesn't wrap which is *so annoying*.

I like the idea of using frontmatter to control formatting... much easier than an exclude list. And yeah, any Negative or maybe just "Negative: SyntaxError" could be excluded by default. If someone wanted to do that work I'd be down. @domenic you seem pretty passionate about it ;)

**Comment by domenic** [comment]
Hmm yeah maybe I'll try to throw together some jscs rules.

**Comment by leobalter** [comment]
I'm updating the README file to address some minimal coding style including those suggested by @bterlson [above](https://github.com/tc39/test262/issues/297#issuecomment-108481688). 

With this in mind, we can address the need of some tool later.
