### ISSUE TITLE
Need tests for "Locale Info" API

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/test262#2984]
https://github.com/tc39/proposal-intl-locale-info advanced to Stage 3 in TC39 2021-Apr meeting. We need to add tests for this in test 262

@ryzokuken  @sffc

**Comment by FrankYFTang** [comment]
v8 implementation is behind --harmony_intl_locale_info once we complete the landing of https://chromium-review.googlesource.com/c/v8/v8/+/2570218

**Comment by jugglinmike** [comment]
@ryzokuken is in the process of contributing these tests. GitHub will not allow me to assign this issue to them, so I'm assigning it to myself to communicate that it's being worked on (and avoid duplicating efforts).

**Comment by FrankYFTang** [comment]
I think this should be reopen. The test @ryzokuken  put in on #2987 is barely minimum and not enough to test the full functionality of the intended proposal. It is just the first step.

**Comment by FrankYFTang** [comment]
somehow I cannot reopen this issue.

**Comment by ryzokuken** [comment]
@FrankYFTang @jugglinmike said in #2987 

> Thanks for the patch! When we land it, I'll create a tracking issue for the follow-up you had in mind so folks know that it's a work-in-progress.

Would that work fine for you?

**Comment by FrankYFTang** [comment]
> @FrankYFTang @jugglinmike said in #2987
> 
> > Thanks for the patch! When we land it, I'll create a tracking issue for the follow-up you had in mind so folks know that it's a work-in-progress.
> 
> Would that work fine for you?

Isn't https://github.com/tc39/test262/pull/2987 landed already?

**Comment by sffc** [comment]
@ryzokuken Can you please link to the follow up issue?

**Comment by ryzokuken** [comment]
I had landed, yes. I'm not sure if @jugglinmike has made the issue yet, but I'm confident that they will soon...

**Comment by jugglinmike** [comment]
This issue ought to do just fine--reopening!

(I didn't recognize that GitHub would automatically close this issue when we merged gh-2987. That happened because the pull request's description included the text "Fixes: #2984" which is not entirely accurate).

**Comment by FrankYFTang** [comment]
Here is what we have so far https://github.com/tc39/test262/search?q=Intl.Locale-info

**Comment by FrankYFTang** [comment]
Could we identifiy what area require improvement before we close this issue?

**Comment by ryzokuken** [comment]
I went through the spec while writing these tests, they should be fairly complete to the best of my knowledge. @jugglinmike @FrankYFTang is there anything you think I might have missed? If not, we could close this and consider it done.

**Comment by jugglinmike** [comment]
I just reviewed the tests for coverage of the proposal, and they look good to me, too! Closing this issue. Thanks for the help!

(For the record, after gh-2987, @ryzokuken's followed up with a second patch to improve coverage: gh-3007.)
