### ISSUE TITLE
built-ins/Promise/race/resolve-element-function-name.js doesn't test the builtin function

### ISSUE THREAD

**Issue by twop** [tc39/test262#2985]
https://github.com/tc39/test262/blob/main/test/built-ins/Promise/race/resolve-element-function-name.js

Snippet from test
```js
let resolveElementFunction;
let thenable = {
  then(fulfill) {
    resolveElementFunction = fulfill;
  }
};

function NotPromise(executor) {
  executor(() => {}, () => {}); // <------ first arg is "resolve"
}
NotPromise.resolve = function(v) {
  return v;
};
Promise.race.call(NotPromise, [thenable]);

// simplified assert
assert(resolveElementFunction.name ==="")
```

Note that it is designed to test builtin `resolve` function name but it actually tests the name of the function passed in custom ctor. 

If the custom "resolve"  function has a proper name

```js
function NotPromise(executor) {
  executor(function res() {}, () => {}); 
}

// fails, name here is "res"
assert(resolveElementFunction.name ==="")
```

Thus, I think the test should be deleted or rewritten.

**Comment by jugglinmike** [comment]
Thanks for the report! This also applies to a few similarly-named tests in that directory. Fix here: gh-2986.

**Comment by leobalter** [comment]
The PR has been merged, is this resolved?

**Comment by jugglinmike** [comment]
Indeed it is
