### ISSUE TITLE
onlyStrict/noStrict: non-conformant?

### ISSUE THREAD

**Issue by jmdyck** [tc39/test262#299]
CONTRIBUTING.md says:
- **`onlyStrict`** - only run the test in strict mode (_not supported by the browser runner_)
- **`noStrict`** - only run the test in "sloppy" mode

This implies that non-/strictness is a mode of the implementation, but that disagrees with the spec:

> A complete ECMAScript program may be composed of both strict mode and non-strict mode ECMAScript source text units. In this case, strict mode only applies when actually executing code that is defined within a strict mode source text unit.
> In order to conform to this specification, an ECMAScript implementation must implement both the full unrestricted ECMAScript language and the strict variant of the ECMAScript language as defined by this specification. In addition, an implementation must support the combination of unrestricted and strict mode source text units into a single composite program.

So do `onlyStrict` and `noStrict` assume some non-conformant behavior of the implementation? If so, that should be stated explicitly (and the options should perhaps be deprecated/eliminated). In any event, these options need to be better explained.

**Comment by bterlson** [comment]
I agree they could be documented better. Let me attempt to explain.

ECMAScript code (when parsed with the Script goal symbol) can be run in either strict mode or non strict mode at the global level. Because most tests are not sensitive to strict mode and hence should run identically in both modes, it is up to the harness to control the strictness by prepending `"use strict"` when we want to run in strict mode. Tests my specify `onlyStrict` when harnesses should only run the test under strict mode only and `noStrict` when the harness should run the test under sloppy mode only. The default (now, thanks to some impressive work from @smikes and @anba) is to run every test under both modes.

The existing browser runner doesn't do any appending of "strict" afaict, so will always just run tests in sloppy mode. That is the meaning of the note.

Does this explain thing better?

**Comment by jmdyck** [comment]
> ECMAScript code (when parsed with the Script goal symbol) can be run in either strict mode or non strict mode at the global level.

This sounds like a statement that would be supportable by reference to the spec, but I gather it isn't meant to be?

> it is up to the harness to control the strictness by prepending "use strict" when we want to run in strict mode.

Okay, so it sounds like:
* The content of any given test file is not necessarily an "ECMAScript source text" (in the spec's terminology).
* Rather, the test harness is allowed/expected to take the file's content, transform it, and supply the result to the implementation-under-test as the source code of a script.
* One such transformation is the insertion of a Use Strict Directive:
  * For `onlyStrict`, the harness should insert a USD in order to obtain the expected result.
  * For `noStrict`, the harness should *not* insert a USD in order to obtain the expected result.
  * Without either, the harness should do 2 runs, one with the USD and one without, both obtaining the expected result.

Is that correct?

**Comment by bterlson** [comment]
> This sounds like a statement that would be supportable by reference to the spec, but I gather it isn't meant to be?

It's supportable. Scripts contain strict or non-strict code depending on the presence of "use strict" in the directive prologue. Modules are always strict.

> Is that correct?

Yes, what you say aligns with my understanding :)

**Comment by jmdyck** [comment]
> It's supportable. Scripts contain strict or non-strict code depending on the presence of "use strict" in the directive prologue. Modules are always strict.

Ah, okay. The wording you gave before suggested (to me) that a script could be run *at the discretion of the implementation* (e.g., as an implementation-dependent choice) in either strict mode or non strict mode at the global level, so that's what I was questioning.

> Yes, what you say aligns with my understanding :)

So theoretically, for a test with `onlyStrict`, it's redundant for the file to contain a USD? (And yet ~600 do.)

Conversely, for a test file that contains a global USD, it should make no difference whether the harness inserts a USD or not, so it would make no difference whether the test were flagged with `onlyStrict`, `noStrict`, or neither? (In the current suite, I count 127 files with a USD: 124 are flagged `onlyStrict`, 3 are flagged `noStrict`, and 0 have neither.)

**Comment by anba** [comment]
> So theoretically, for a test with onlyStrict, it's redundant for the file to contain a USD? (And yet ~600 do.)

Yes, it's redundant. (For the most part legacy cruft when sputnik/ietestcenter tests were imported into test262.)

> Conversely, for a test file that contains a global USD, it should make no difference whether the harness inserts a USD or not, so it would make no difference whether the test were flagged with onlyStrict, noStrict, or neither?

Global USDs in test files don't actually work (#291).

**Comment by bterlson** [comment]
> So theoretically, for a test with  onlyStrict , it's redundant for the file to contain a USD? (And yet ~600 do.)

IFF the USD is at the global level, yes.

I don't know if you invented USD but I like it as a short-hand ;)

@anba, thanks for reminding me about that issue.

**Comment by jmdyck** [comment]
> > So theoretically, for a test with onlyStrict , it's redundant for the file to contain a USD? (And yet ~600 do.)
>
> IFF the USD is at the global level, yes.

Oh? I would have thought that if the harness inserted a global USD (due to `onlyStrict`), that would render *any* USD in the file redundant. Do you have a counter-example?

> I don't know if you invented USD but I like it as a short-hand ;)

Yes, I invented it, and now you owe me a licensing fee!

**Comment by smikes** [comment]
@bterlson pay him a 10% royalty, like with Spyglass - https://en.wikipedia.org/wiki/Spyglass,_Inc.#Browser_wars

**Comment by bterlson** [comment]
> Oh? I would have thought that if the harness inserted a global USD (due to  onlyStrict ), that would render any USD in the file redundant. Do you have a counter-example?

I was referring to nested USD's like in functions.

**Comment by leobalter** [comment]
I believe the documentation changes from #508 and other issues conclusions - as in #302 - have got this one solved. Please reopen if necessary.

**Comment by leobalter** [comment]
> pay him a 10% royalty

At this point, this might be paid in USD, or just "Use Strict Directive".
