### ISSUE TITLE
Need tests for "Intl.DisplayNames v2 Proposal" 

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/test262#2997]
In 2021 May TC39 meeting https://tc39.es/intl-displaynames-v2/ is moved to Stage 3 .
We need to add tests for this proposal.

@sffc @ryzokuken  @zbraniecki

**Comment by jugglinmike** [comment]
I'm on it!

**Comment by jugglinmike** [comment]
Here's a patch: gh-3115
