### ISSUE TITLE
missing from CONTRIBUTING.md

### ISSUE THREAD

**Issue by jmdyck** [tc39/test262#3015]
CONTRIBUTING.md's Frontmatter section should define:
- the `locale` key (appears in 128 test files, all under `intl402`)
- the `flags` key's `non-deterministic` property (appears in 8 test-files, mostly under `built-ins/FinalizationRegistry`)

**Comment by jugglinmike** [comment]
Thanks, @jmdyck! I'm on the case

**Comment by jmdyck** [comment]
I later discovered that both items are documented in INTERPRETING.md, because [its Metadata section](https://github.com/tc39/test262/blob/main/INTERPRETING.md#metadata) mostly overlaps [CONTRIBUTING.md's Frontmatter section](https://github.com/tc39/test262/blob/main/CONTRIBUTING.md#frontmatter). Maybe we could eliminate one of them.
