### ISSUE TITLE
Errors in new ArrayBuffer / SharedArrayBuffer tests (related to resizable / growable arraybuffers)

### ISSUE THREAD

**Issue by marjakh** [tc39/test262#3038]
Problem 1: using .resizable instead of .growable:

built-ins/SharedArrayBuffer/options-non-object.js
built-ins/SharedArrayBuffer/options-maxbytelength-undefined.js

Problem 2: errors in variable names

built-ins/SharedArrayBuffer/prototype/maxByteLength/this-is-arraybuffer.js uses an undefined variable "sab" (should be "ab")

Problem 3: test is the wrong way around

test/built-ins/SharedArrayBuffer/prototype/growable/this-is-arraybuffer.js

Spec: if it's *not* a SAB, then throw.
Test: if it *is* a SAB, except and error thrown.

Curiously, the test file name is correct, it probably means to test the situation where `this` is an ArrayBuffer, not a SharedArrayBuffer. But the error message in the test is wrong, saying `this` cannot be a SharedArrayBuffer.

**Comment by jugglinmike** [comment]
Thanks for the report! I'll have corrections ready for review later today

**Comment by jugglinmike** [comment]
Here's the patch: gh-3040
