### ISSUE TITLE
Proposal: Automated Tests

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#306]
I'd like to write some tests for test file content. As a start, these would
assert:
- Valid YAML frontmatter syntax
- Basic frontmatter tag requirements
  - Presence of `description` tag
  - Valid configurations
    - Mutual exclusivity of `strictOnly` and `noStrict`
    - At least one of `es5id` and `es6id`
- Presence of copyright block

These assertions are admittedly a little weak, but even superficial checks like
these would have prevented past errors (e.g. gh-177, gh-225, gh-144). Because
test262 does not currently offer any automated tests, this work would involve
introducing the tooling and practices. That would reduce the friction in
implementing more substantial/helpful tests in the future (see for instance,
gh-276 and gh-297).

This will require some discussion about dependencies, but I wanted to see if
the basic proposal is desired before getting into technical details.

**Comment by jugglinmike** [comment]
This could also enforce a restriction on description length that is [currently requested in the project's contribution guidelines](https://github.com/tc39/test262/blob/12cc01484eb4253894d7e9a3478445382e80b262/CONTRIBUTING.md#description).

**Comment by leobalter** [comment]
#546 will have us one step closer to solve this.

The items you have listed here sound reasonable to me.

**Comment by rwaldron** [comment]
This was addressed by implementing a linter that runs in our CI
