### ISSUE TITLE
Typo in built-ins/TypedArrayConstructors/internals/HasProperty/resizable-array-buffer-fixed.js

### ISSUE THREAD

**Issue by marjakh** [tc39/test262#3109]
Test:

built-ins/TypedArrayConstructors/internals/HasProperty/resizable-array-buffer-fixed.js

Line 48:

expected = "false,false,false,false,falsex";

Should be:

expected = "false,false,false,false,false";

**Comment by jugglinmike** [comment]
Thanks for reporting this! I'm happy to learn an engine is executing that branch. A fix is under review here: https://github.com/tc39/test262/pull/3110.
