### ISSUE TITLE
built-ins/TypedArray/prototype/*/return-abrupt-from-this-out-of-bounds.js tests seem wrong

### ISSUE THREAD

**Issue by marjakh** [tc39/test262#3111]
I didn't check all of them, but I checked 2 of them and 100% had this problem :) Comments inline:

built-ins/TypedArray/prototype/fill/return-abrupt-from-this-out-of-bounds.js:

```
testWithTypedArrayConstructors(TA => {
  var BPE = TA.BYTES_PER_ELEMENT;
  var ab = new ArrayBuffer(BPE * 4, {maxByteLength: BPE * 5});
  var array = new TA(ab, BPE, 2);

  try {
    ab.resize(BPE * 5); <<<<<<<<<< length is now BPE * 5
  } catch (_) {}

  // no error following grow: <<<<<<<<<< this is correct
  array.fill(0);  

  try {
    ab.resize(BPE * 3); <<<<<<<<<< length is now BPE * 3
  } catch (_) {}

  // no error following shrink (within bounds): <<<<<<<<<< this is correct
  array.fill(0);  

  var expectedError;
  try {
    ab.resize(BPE * 3); <<<<<<<<<< what is this doing? the length was already BPE * 3 so this is a no-op
    expectedError = TypeError;
  } catch (_) {
    // The host is permitted to fail any "resize" operation at its own
    // discretion. If that occurs, the fill operation should complete
    // successfully.
    expectedError = Test262Error;
  }

  assert.throws(expectedError, () => {  <<<<<<<<<< this is wrong
    array.fill(0);
    throw new Test262Error('fill completed successfully');
  });
});
```

Maybe the intention was to resize so that `array` is out of bounds; that'd be resizing to 0, BPE or BPE * 2. But even then, fill shouldn't throw, afaics:
- The ResizeArrayBuffer proposal changes %TypedArray%.prototype.fill to use IntegerIndexedObjectLength instead of [[ArrayLength]]. ("Uses of [[ArrayLength]] on Integer-Indexed exotic objects are replaced with calls to IntegerIndexedObjectLength.") 
- The proposal doesn't change IsDetachedBuffer.

-> When `ab` has been resized so that `array` is out of bounds, its length will appear to be 0 and fill does nothing.

**Comment by jugglinmike** [comment]
Thanks for reporting this!

> Maybe the intention was to resize so that `array` is out of bounds; that'd be resizing to 0, BPE or BPE * 2.

Yup, that was my intention.

> But even then, fill shouldn't throw, afaics:
>
>     * The ResizeArrayBuffer proposal changes %TypedArray%.prototype.fill to use IntegerIndexedObjectLength instead of [[ArrayLength]]. ("Uses of [[ArrayLength]] on Integer-Indexed exotic objects are replaced with calls to IntegerIndexedObjectLength.")
> 
>     * The proposal doesn't change IsDetachedBuffer.
> 
> 
> -> When `ab` has been resized so that `array` is out of bounds, its length will appear to be 0 and fill does nothing.

`fill` should throw because [%TypedArray%.prototype.fill performs ValidateTypedArray](https://tc39.es/ecma262/#sec-%typedarray%.prototype.fill), and [the "Resizable ArrayBuffer" proposal modifies that operation to throw a TypeError for out-of-bounds arrays](https://tc39.es/proposal-resizablearraybuffer/#sec-validatetypedarray). This is also the case for the other methods tested with a file named `return-abrupt-from-this-out-of-bounds.js`.

In gh-3113, I've corrected the desired size in the final resize operation as per your suggestion. I've also included a comment explaining the rationale for the following statement, `expectedError = TypeError;`. Would you mind taking a look?

**Comment by marjakh** [comment]
Ah, you're right, sorry, I missed the changes in ValidateTypedArray. Thanks for fixing!

**Comment by jugglinmike** [comment]
gh-3113 mostly resolved this issue, but gh-3045 was preemptively merged before the fix could be applied there, so the problem exists in two tests. gh-3126 resolves those final mistakes.

**Comment by jugglinmike** [comment]
Now that gh-3126 has been merged, this is fully resolved. Thanks again for the report, @marjakh!
