### ISSUE TITLE
Missing test coverage for BigUint64Array & BigInt64Array backed by resizable / growable buffers

### ISSUE THREAD

**Issue by marjakh** [tc39/test262#3112]
testTypedArray.js doesn't include the BigUint64Array and BigInt64Array ctors.

It's very important to test those too, since they're often special-cased in the implementation (at least in V8) and we will get them wrong / forget to update those special cases.

Testing them is slightly painful though, as automatic conversions to and from Numbers don't exist. But it's possible to work around it.

**Comment by rwaldron** [comment]
> testTypedArray.js doesn't include the BigUint64Array and BigInt64Array ctors.

That's correct, they are in `testBigIntTypedArray.js`

Generally, tests that are written for `testTypedArray.js` have a corresponding `testBigIntTypedArray.js` version, in a subdir called `/bigint/`. Unfortunately, I don't see such tests for `resizable-arraybuffer`. I will work on getting those created.
