### ISSUE TITLE
Incorrect test expectation in type-calendar-valid.js

### ISSUE THREAD

**Issue by anba** [tc39/test262#3139]
The underscore tests in <https://github.com/tc39/test262/blob/86e23998e37e2f1d8107afa51d7be355f3f65cca/test/intl402/DisplayNames/prototype/of/type-calendar-valid.js#L29-L32> should all be moved to <https://github.com/tc39/test262/blob/main/test/intl402/DisplayNames/prototype/of/type-calendar-invalid.js>.

The underscore character "_" is only accepted for the [sep](https://unicode.org/reports/tr35/#Unicode_language_identifier) production when the [backwards-compatibility extensions](https://unicode.org/reports/tr35/#BCP_47_Conformance) are enabled. But in ECMA-402 we [only accept](https://tc39.es/ecma402/#sec-language-tags) _Unicode BCP 47 locale identifiers_, so identifiers without the backwards-compatibility extensions.

**Comment by jugglinmike** [comment]
Thanks for reporting this! And for effectively writing the commit message. Correction under review here: gh-3173

Just when you think you know a programming language...
