### ISSUE TITLE
Templates lacking proper `$DONOTEVALUATE()` support

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/test262#3160]
The following two template lack proper `$DONOTEVALUATE()` support:

- https://github.com/tc39/test262/blob/main/src/assignment-target-type/invalid/direct.template
- https://github.com/tc39/test262/blob/main/src/assignment-target-type/invalid/parenthesized.template

They wrap the test code in a function that is never called, defeating the purpose of the `$DONOTEVALUATE()` mechanism. In engines that (incorrectly) implement the error as a runtime error (instead of an early/parse error) no error is thrown because the code isn’t executed.

Could we either

a) rewrite this test without the function, or
b) keep it as-is but call the function at the end?

I think option A makes the most sense.

Affected tests:
- https://github.com/tc39/test262/blob/main/test/language/expressions/assignmenttargettype/direct-callexpression-arguments.js
- https://github.com/tc39/test262/blob/main/test/language/expressions/assignmenttargettype/parenthesized-callexpression-arguments.js

**Comment by rwaldron** [comment]
> In engines that (incorrectly) implement the error as a runtime error (instead of an early/parse error) no error is thrown because the code isn’t executed.

So the ask is for these tests to be modified, in order for V8 to continue being incorrect without being penalized? Frankly, I'd rather we went with "c) get rid of `$DONOTEVALUATE()`, restore the bare `throw new Test262Error()`, and stop giving V8 special treatment.". Unfortunately, we've already set a precedent for this particular special treatment, so I suppose we should be consistent.

**Comment by mathiasbynens** [comment]
> So the ask is for these tests to be modified, in order for V8 to continue being incorrect

Not really. For these specific tests, multiple engines (not just V8) have the runtime error behavior:

```
$ eshost -sx 'if (false) f() = 1'
#### Chakra, ChakraCore, JavaScriptCore, SpiderMonkey, V8, V8 --harmony


#### XS

SyntaxError: no reference
```

…since it’s required for web compatibility. See [crbug.com/358346](https://bugs.chromium.org/p/chromium/issues/detail?id=358346). (So arguably this is a spec bug, and we should fix the spec + tests, but in the mean time we can make the tests useful for Web-compatible engines.)

> […] without being penalized? 

Not sure what you mean by this. The `$DONOTEVALUATE` mechanism makes it possible to still get value out of these tests instead of just disabling them. The tests would still be marked as `FAIL` in test262.report, as they should. No one is trying to cheat or avoid getting penalized in any way.
