### ISSUE TITLE
valid but unusual YAML

### ISSUE THREAD

**Issue by jmdyck** [tc39/test262#3171]
In 47 recent Temporal tests, the `description` is a multi-line scalar in flow notation,  e.g.
```
description: Temporal.Calendar.prototype.dateFromFields should throw RangeError for
  input not in valid range.
```
which is valid YAML, but not something that the rest of test262 uses.
For multi-line scalars, test262 typically uses block notation, e.g.
```
description: >
  Temporal.Calendar.prototype.dateFromFields should throw RangeError for
  input not in valid range.
```
Would you like a PR to change them, or is that more bother than it's worth? (CONTRIBUTING.md isn't clear on this point.)

**Comment by jugglinmike** [comment]
@jmdyck Hopefully gh-3178 will help us avoid regressing on this
