### ISSUE TITLE
Update test262 website/wiki with new repository location

### ISSUE THREAD

**Issue by richdougherty** [tc39/test262#32]
Apologies if this isn't the correct place for reporting.

It would be really helpful if the test262 website or wiki mentioned the new Github location of the test262 code. The old Mercurial repository seems to be defunct. Here are a couple of places that mention the old location:

http://wiki.ecmascript.org/doku.php?id=test262:command
http://wiki.ecmascript.org/doku.php?id=test262:submission_process

The only place that I could find that mentioned the new location was in a [mailing list message](https://mail.mozilla.org/pipermail/test262-discuss/2013-July/000228.html), and this message was pretty hard for me to find.

**Comment by leobalter** [comment]
I don't think this can be fixed anymore. This is the right place to report this and I apologize for such a long delay to answer this issue.
