### ISSUE TITLE
built-ins/TypedArray/prototype/fill/BigInt/return-abrupt-from-this-out-of-bounds.js is wrong

### ISSUE THREAD

**Issue by marjakh** [tc39/test262#3214]
Since it's a BigInt array,

```
  array.fill(0);
```
should be

```
  array.fill(0n);
```

cc @jugglinmike  & thanks for all the fixes so far

**Comment by jugglinmike** [comment]
And thank you for keeping us informed! This same problem also applies to [`test/built-ins/TypedArray/prototype/set/BigInt/typedarray-arg-set-values-same-buffer-same-type-resized.js`](https://github.com/tc39/test262/blob/5fee61c9e84f53dd0bba28cb6928cdde092fa995/test/built-ins/TypedArray/prototype/set/BigInt/typedarray-arg-set-values-same-buffer-same-type-resized.js); both should be resolved by gh-3216.

Separately, I've submitted gh-3217 to make a similar change in situations where it's not technically necessary but might improve legibility.

**Comment by jugglinmike** [comment]
gh-3216 has been merged, so I believe this issue is resolved.
