### ISSUE TITLE
Incorrect test: test/language/expressions/await/await-throws-rejections.js

### ISSUE THREAD

**Issue by davidot** [tc39/test262#3229]
The test contains the definition of a function `foo` but never calls or otherwise invokes it.
All the code in the test:
```js
async function foo() {
  var err = {};
  var caught = false;
  try {
    await Promise.reject(err);
  } catch(e) {
    caught = true;
    assert.sameValue(e, err);
  }

  assert(caught);
}
```
File:
test/language/expressions/await/await-throws-rejections.js 
https://github.com/tc39/test262/blob/main/test/language/expressions/await/await-throws-rejections.js

**Comment by leobalter** [comment]
Thanks for reporting this, @davidot, false positives are the worst for a test suite! 

Would you like to open a PR for this one?

**Comment by jugglinmike** [comment]
Agreed with @leobalter! This concerned me enough to do a larger survey of the test suite, and that uncovered a few other instances of the same problem. gh-3241 fixes them all.
