### ISSUE TITLE
Please move Temporal tests with IANA timezone other than UTC under intl402

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/test262#3253]
Temporal tests which depends on IANA TimeZone other than UTC should be moved from builtin-ins to intl402 directory

 find Temporal/|xargs egrep -s "Asia|America|Europe|Africa"|cut -d':' -f1|sort -u

Temporal/Duration/compare/timezone-string-datetime.js
Temporal/Duration/prototype/add/relativeto-string-datetime.js
Temporal/Duration/prototype/add/timezone-string-datetime.js
Temporal/Duration/prototype/round/relativeto-string-datetime.js
Temporal/Duration/prototype/round/timezone-string-datetime.js
Temporal/Duration/prototype/subtract/relativeto-string-datetime.js
Temporal/Duration/prototype/subtract/timezone-string-datetime.js
Temporal/Duration/prototype/total/relativeto-string-datetime.js
Temporal/Duration/prototype/total/timezone-string-datetime.js
Temporal/Instant/compare/instant-string.js
Temporal/Instant/from/instant-string.js
Temporal/Instant/prototype/equals/instant-string.js
Temporal/Instant/prototype/since/instant-string.js
Temporal/Instant/prototype/toString/timezone-string-datetime.js
Temporal/Instant/prototype/toZonedDateTimeISO/timezone-string-datetime.js
Temporal/Instant/prototype/toZonedDateTime/timezone-string-datetime.js
Temporal/Instant/prototype/until/instant-string.js
Temporal/Now/plainDateISO/timezone-string-datetime.js
Temporal/Now/plainDateTimeISO/timezone-string-datetime.js
Temporal/Now/plainDateTime/timezone-string-datetime.js
Temporal/Now/plainDate/timezone-string-datetime.js
Temporal/Now/plainTimeISO/timezone-string-datetime.js
Temporal/Now/zonedDateTimeISO/timezone-string-datetime.js
Temporal/Now/zonedDateTime/timezone-string-datetime.js
Temporal/PlainDate/prototype/toZonedDateTime/basic.js
Temporal/PlainDate/prototype/toZonedDateTime/timezone-string-datetime.js
Temporal/PlainDateTime/prototype/toZonedDateTime/timezone-string-datetime.js
Temporal/PlainTime/prototype/toZonedDateTime/basic.js
Temporal/PlainTime/prototype/toZonedDateTime/timezone-string-datetime.js
Temporal/TimeZone/from/argument-primitive.js
Temporal/TimeZone/from/timezone-string-datetime.js
Temporal/TimeZone/prototype/getNextTransition/instant-string.js
Temporal/TimeZone/prototype/getOffsetNanosecondsFor/instant-string.js
Temporal/TimeZone/prototype/getOffsetStringFor/getOffsetNanosecondsFor-undefined.js
Temporal/TimeZone/prototype/getOffsetStringFor/instant-string.js
Temporal/TimeZone/prototype/getPlainDateTimeFor/getOffsetNanosecondsFor-undefined.js
Temporal/TimeZone/prototype/getPlainDateTimeFor/instant-string.js
Temporal/TimeZone/prototype/getPreviousTransition/instant-string.js
Temporal/ZonedDateTime/compare/timezone-string-datetime.js
Temporal/ZonedDateTime/compare/zoneddatetime-string.js
Temporal/ZonedDateTime/from/timezone-string-datetime.js
Temporal/ZonedDateTime/from/zoneddatetime-string.js
Temporal/ZonedDateTime/prototype/equals/timezone-string-datetime.js
Temporal/ZonedDateTime/prototype/equals/zoneddatetime-string.js
Temporal/ZonedDateTime/prototype/since/timezone-string-datetime.js
Temporal/ZonedDateTime/prototype/since/zoneddatetime-string.js
Temporal/ZonedDateTime/prototype/until/timezone-string-datetime.js
Temporal/ZonedDateTime/prototype/until/zoneddatetime-string.js
Temporal/ZonedDateTime/prototype/with/offset-undefined.js
Temporal/ZonedDateTime/prototype/withTimeZone/timezone-string-datetime.js
Temporal/ZonedDateTime/timezone-string-datetime.js

https://tc39.es/proposal-temporal/#sec-isvalidtimezonename said

"11.1.1 IsValidTimeZoneName ( timeZone )
An ECMAScript implementation that includes the ECMA-402 Internationalization API must implement the IsValidTimeZoneName abstract operation as specified in the ECMA-402 specification. If an ECMAScript implementation does not include the ECMA-402 API the following specification of the IsValidTimeZoneName abstract operation is used.
"

and
"The **minimum implementation** of IsValidTimeZoneName, supporting **only the "UTC"** time zone, performs the following steps when called:"

@ptomato @jugglinmike @Ms2ger @ryanmurakami

**Comment by ptomato** [comment]
I think this was resolved by #3377.

**Comment by FrankYFTang** [comment]
Left over 4 tests in https://github.com/tc39/test262/pull/3646
