### ISSUE TITLE
Revert or remove #3250

### ISSUE THREAD

**Issue by justingrant** [tc39/test262#3272]
The test changes in #3250 exposed a Temporal spec bug (https://github.com/tc39/proposal-temporal/issues/1878). The old tests before #3250 were validating the correct intended behavior, and they passed previously because the Temporal polyfill matches that behavior too. The spec will be updated to match that behavior.

One problem: we found this bug after the deadline for the Oct TC39 plenary meeting. That probably means that we probably can't merge the fix into the Temporal spec until after the December 2021 meeting.

How should we handle? Options include: 
a) Revert #2350, which would at least alert implementers that there's a problem, even if the spec doesn't yet match the tests
b) Remove these test cases until the Temporal spec catches up.
c) Something else?

We'd prefer (a), because we'd rather have implementers fail tests and reach out to us to find out why, vs. writing incorrect implementations and having to fix them later.  But we're flexible to whatever the Test262 maintainers think is best.

cc @Ms2ger @ptomato @12wrigja

**Comment by Bert66cool** [comment]
How do i fix this bug?

Sent from Yahoo Mail on Android 
 
  On Fri, Oct 22, 2021 at 5:27 PM, Justin ***@***.***> wrote:   


OK, we'll add this issue to our Oct slides (with a note saying that the bug was found after the advancement deadline) so we can fix the spec sooner than Dec. Thanks!

**Comment by justingrant** [comment]
> How do i fix this bug?

You don't need to. It's a spec bug that will be fixed by https://github.com/tc39/proposal-temporal/pull/1881. Once that PR is merged (assuming it gets approved by the TC39 committee) then #3274 should align Test262 with the latest spec. The Temporal polyfill and docs already reflect the desired behavior.

**Comment by Bert66cool** [comment]
Ok . which docs ?

Sent from Yahoo Mail on Android 
 
  On Fri, Oct 22, 2021 at 5:43 PM, Justin ***@***.***> wrote:   



How do i fix this bug?


You don't need to. It's a spec bug that will be fixed by tc39/proposal-temporal#1881. Once that PR is merged (assuming it gets approved by the TC39 committee) then #3274 should align Test262 with the latest spec. The Temporal polyfill and docs already reflect the desired behavior.

**Comment by Bert66cool** [comment]
?
