### ISSUE TITLE
built-ins/DataView/prototype/byteLength/resizable-array-buffer-auto.js and built-ins/DataView/prototype/byteOffset/resizable-array-buffer-auto.js?

### ISSUE THREAD

**Issue by patrick-soquet** [tc39/test262#3279]
I am implementing resizable ArrayBuffer in XS. Thank you much for the tests. I have a question about these two tests...

The byte length of a data view can be 0:

	var ab = new ArrayBuffer(1);
	var dv = new DataView(ab, 1);
	print(dv.byteOffset, dv.byteLength); // 1 0

So the last part of both tests seems wrong:

	var expectedError;
	try {
		ab.resize(1);
		expectedError = TypeError;
	} catch (_) {
		expectedError = Test262Error;
	}

Or am I misunderstanding something?

**Comment by jugglinmike** [comment]
Resolved via gh-3280. Thanks again!
