### ISSUE TITLE
Conflict between "Test Environment" helper function and a testcase

### ISSUE THREAD

**Issue by arai-a** [tc39/test262#3310]
test262 requires "Test Environment" to have helper functions:
https://github.com/tc39/test262/blob/main/CONTRIBUTING.md#test-environment
https://github.com/tc39/test262/blob/26f1f4567ee7e33163d961c867d689173cbb9065/CONTRIBUTING.md#L232-L240

there `assert` function is listed, and the following test redefines `assert` on the global.
https://github.com/tc39/test262/blob/26f1f4567ee7e33163d961c867d689173cbb9065/test/language/module-code/eval-gtbndng-indirect-faux-assertion.js#L34-L38

this doesn't work if the `assert` function is provided as global function that has `configurable: false` in the property descriptor.
and that's the case for SpiderMonkey's harness
https://searchfox.org/mozilla-central/rev/674b6582bafedc11fba6dc537769c88e9ed921d3/js/src/tests/test262/shell.js#12-21
```js
function assert(mustBeTrue, message) {
  if (mustBeTrue === true) {
    return;
  }

  if (message === undefined) {
    message = 'Expected true but got ' + assert._toString(mustBeTrue);
  }
  throw new Test262Error(message);
}
```

there should be either of the following:
  * the "Test Environment" section specify the property descriptor of each helper
  * a rule that the testcase should not redefine/rewrite/remove properties listed in "Test Environment"

**Comment by arai-a** [comment]
the `assert` definition is copied from test262 file here:
https://github.com/tc39/test262/blob/61bd4e9453ce7fc3a2127399cd972b46f721ab1c/harness/assert.js#L10-L19

**Comment by jugglinmike** [comment]
Thanks for the report! [That test declares the "raw" frontmatter flag](https://github.com/tc39/test262/blob/26f1f4567ee7e33163d961c867d689173cbb9065/test/language/module-code/eval-gtbndng-indirect-faux-assertion.js#L27), so the global object should not have an `assert` function defined initially. [Here's the description of the flag from the contribution guidelines](https://github.com/tc39/test262/blob/26f1f4567ee7e33163d961c867d689173cbb9065/CONTRIBUTING.md#flags):

> - **raw** - execute the test without any modification (no helpers will be available); necessary to test the behavior of directive prologue; implies `noStrict`

That leads me to believe that a change to Test262 may not be necessary.

Between the tests for the "hashbang" comment and the directive proglogue, Test262 currently has 28 other "raw" tests.

<details>
  <summary>Here's a list</summary>

    $ git rev-parse HEAD
    d52b510a33b526d714089937ff7d1d5794511fd4
    [mike@bruce test262](main)$ git grep -E 'flags.*\braw\b' test
    test/language/comments/hashbang/escaped-bang-041.js:flags: [raw]
    test/language/comments/hashbang/escaped-bang-u0021.js:flags: [raw]
    test/language/comments/hashbang/escaped-bang-u21.js:flags: [raw]
    test/language/comments/hashbang/escaped-bang-x21.js:flags: [raw]
    test/language/comments/hashbang/escaped-hash-043.js:flags: [raw]
    test/language/comments/hashbang/escaped-hash-u0023.js:flags: [raw]
    test/language/comments/hashbang/escaped-hash-u23.js:flags: [raw]
    test/language/comments/hashbang/escaped-hash-x23.js:flags: [raw]
    test/language/comments/hashbang/escaped-hashbang.js:flags: [raw]
    test/language/comments/hashbang/line-terminator-carriage-return.js:flags: [raw]
    test/language/comments/hashbang/line-terminator-line-separator.js:flags: [raw]
    test/language/comments/hashbang/line-terminator-paragraph-separator.js:flags: [raw]
    test/language/comments/hashbang/module.js:flags: [module, raw]
    test/language/comments/hashbang/multi-line-comment.js:flags: [raw]
    test/language/comments/hashbang/not-empty.js:flags: [raw]
    test/language/comments/hashbang/preceding-directive-prologue-sc.js:flags: [raw]
    test/language/comments/hashbang/preceding-directive-prologue.js:flags: [raw]
    test/language/comments/hashbang/preceding-empty-statement.js:flags: [raw]
    test/language/comments/hashbang/preceding-hashbang.js:flags: [raw]
    test/language/comments/hashbang/preceding-line-comment.js:flags: [raw]
    test/language/comments/hashbang/preceding-multi-line-comment.js:flags: [raw]
    test/language/comments/hashbang/preceding-whitespace.js:flags: [raw]
    test/language/comments/hashbang/use-strict.js:flags: [raw]
    test/language/directive-prologue/10.1.1-2gs.js:flags: [raw]
    test/language/directive-prologue/10.1.1-5gs.js:flags: [raw]
    test/language/directive-prologue/10.1.1-8gs.js:flags: [raw]
    test/language/directive-prologue/14.1-4gs.js:flags: [raw]
    test/language/directive-prologue/14.1-5gs.js:flags: [raw]
    test/language/module-code/eval-gtbndng-indirect-faux-assertion.js:flags: [module, raw]

</details>

How does SpiderMonkey fare when Mozilla's harness loads those?

**Comment by arai-a** [comment]
Thank you for pointing that out :)

Indeed, SpiderMonkey's harness loads scripts for helper functions before running the test,
so that part needs to be fixed in SpiderMonkey's harness.

How do you think about adding a note to "Test Environment" section that mentions the `raw` flag, so that it's clear that the helper functions aren't always defined?

**Comment by arai-a** [comment]
filed https://bugzilla.mozilla.org/show_bug.cgi?id=1742035 for SpiderMonkey test harness

**Comment by anba** [comment]
> [That test declares the "raw" frontmatter flag](https://github.com/tc39/test262/blob/26f1f4567ee7e33163d961c867d689173cbb9065/test/language/module-code/eval-gtbndng-indirect-faux-assertion.js#L27), so the global object should not have an `assert` function defined initially. [Here's the description of the flag from the contribution guidelines](https://github.com/tc39/test262/blob/26f1f4567ee7e33163d961c867d689173cbb9065/CONTRIBUTING.md#flags):
> 
> > * **raw** - execute the test without any modification (no helpers will be available); necessary to test the behavior of directive prologue; implies `noStrict`

I don't think `raw` excludes using the [test environment](https://github.com/tc39/test262/blob/main/CONTRIBUTING.md#test-environment), because
1. `raw` defines that "no helpers" are available, but "helpers" in this context refers to the use of "helpers" as defined in the [description for `includes`](https://github.com/tc39/test262/blob/main/CONTRIBUTING.md#includes). That means only the files explicitly included through `includes` count as "helpers".
    - Unless the [author](https://github.com/tc39/test262/commit/ab7617deddec3025848ac69ebdea6389b94e9a92) regarded "helpers" as being equals to "harness files". Maybe we should ask him. :smile:
2. The [test environment](https://github.com/tc39/test262/blob/main/CONTRIBUTING.md#test-environment) description states that `assert` is available for all tests. There's no exemption for `raw` tests.
3. The same goes for [test262 defined bindings](https://github.com/tc39/test262/blob/main/INTERPRETING.md#test262-defined-bindings).

But then there's also this sentence in [Handling Errors and Negative Test Cases](https://github.com/tc39/test262/blob/HEAD/CONTRIBUTING.md#handling-errors-and-negative-test-cases):
> If the test case has the `raw` flag, this disallows the test to load any harness file including `$DONOTEVALUATE`.

, which matches your interpretation of the `raw` flag.

---

So if `raw` should really mean no harness files are available at all, we should document it explicitly in more places. #3317 covers the "Test Environment" section, but as shown above, more places imply that the standard harness files are always available. And we should make sure the linter catches any possible violations. For example `raw` should disallow:
- `includes`
- `async` (because `$DONE`  isn't available)
- `onlyStrict` and `noStrict`

**Comment by jugglinmike** [comment]
Thank you, @arai-a, and thank you, @anba! I'm going to merge gh-3317 and then take on André's additional feedback. I'll do my best to make this information as consistent and concise as possible (as a start, I think the term "helpers" is a major source of ambiguity).

**Comment by jugglinmike** [comment]
Here's my attempt: https://github.com/tc39/test262/pull/3324
