### ISSUE TITLE
Wrong test in intl402/Temporal/TimeZone/from/argument-invalid.js

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/test262#3322]
Wrong test in 
https://github.com/tc39/test262/blob/main/test/intl402/Temporal/TimeZone/from/argument-invalid.js

None of the strings there are invalid according to the spec
The description said "bad offsets in ISO strings" but no where in the proposal will check the offset as long as it is valid accoring to the syntax.

@ptomato @justingrant @sffc @ryzokuken

**Comment by ptomato** [comment]
I already submitted a PR for this: https://github.com/tc39/test262/pull/3316
