### ISSUE TITLE
Missing coverage: Resizable / Growable [Shared]ArrayBuffers: Checks in DataView ctor

### ISSUE THREAD

**Issue by marjakh** [tc39/test262#3327]
This spec PR https://github.com/tc39/proposal-resizablearraybuffer/pull/81 adds more checks to DataView ctor. Afaics there are currently no test262 tests which would verify that an implementation has these in place.

cc @jugglinmike

**Comment by jugglinmike** [comment]
Verified, thanks for reporting! I'll write these tests
