### ISSUE TITLE
Proposal: Additional Metadata for Legacy Extensions

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#333]
Test262 currently organizes tests for [ES6's Annex B extensions](http://www.ecma-international.org/ecma-262/6.0/#sec-additional-ecmascript-features-for-web-browsers) in [a dedicated directory, `test/annexB/`](https://github.com/tc39/test262/tree/c295916c0976b8704661c8874d465f40fa298432/test/annexB). This works well for standalone extensions like `Object.prototype.__proto__` and `String.prototype.big`. Implementors that target web browsers can include these tests, while others may ignore them completely.

This pattern does not work for cases where Annex B extensions are in direct conflict with non-legacy behaviors. For instance, the following code [should produce a SyntaxError in progressive environments](http://www.ecma-international.org/ecma-262/6.0/#sec-regexpinitialize) but [execute successfully in browser environments](http://www.ecma-international.org/ecma-262/6.0/#sec-regular-expressions-patterns):

```
/\3/;
```

Currently, a positive test file could be created at, for instance, `test/annexB/regexp-backref-out-of-bounds.js`:

```
/*---
es6id: B.1.4
---*/
assert(/\3/.test('\3'));
```

...but an equivalent test for non-browsers is in direct conflict:

```
/*---
es6id: 21.2.2.9
negative: SyntaxError
---*/
/\3/;
```

The most obvious destination for this second test is `tests/language/literals/regexp/`. This organization isn't optimal, though, because it forces browser implementors to interpret which tests are not relevant for their VM and to maintain an appropriate black list.

Test262 is in a position to avoid this by making this distinction explicit. I'd like to propose an extension to the test file frontmatter that will allow each test to declare when its validity depends on the progressive-versus-legacy distinction.

I have ideas for specific extensions, I think it would be good to get agreement on the requirements first. Does this proposal generally sound like a good idea to you, @bterlson?

**Comment by domenic** [comment]
I think we should not include tests for non-browser environments. They are a fantasy; nobody maintains separate VMs. The ideas you propose are not worth your time, IMO.

Over time we should fix the spec to make sure there are no conflicts, maybe by incorporating Annex B into the main text. (And, if we want, add some "this is gross" badge to those sections.)

**Comment by leobalter** [comment]
While we want to attend a fair coverage of the specs, including the cases without/conflicting with the annex B, we can't afford the maintenance of this support extension. Leading us to support runtimes implementing annexB along.

I'm closing this as a _wont fix_.
