### ISSUE TITLE
possible error in callbackfn-resize-arraybuffer.js tests

### ISSUE THREAD

**Issue by phoddie** [tc39/test262#3333]
The Array tests for resizable TypedArray include shrinking the underlying ArrayBuffer in the middle of an iterator. The test below starts with a 3 element array and reduces it to 2 elements. The test appears to expect that all 3 of the original TypedArray elements are still visited.

https://github.com/tc39/test262/blob/4b7f8b49cc07a89c093475f284ef112f26a8529f/test/built-ins/Array/prototype/every/callbackfn-resize-arraybuffer.js#L26-L48

We would expect only the first two elements to be visited based on...

- Array.prototype.every tests the presence of an item (with [[HasProperty]]) and calls the callback only if the item is present (23.1.3.6, step b and c). 
- For integer-indexed exotic objects, [[HasProperty]] returns IsValidIntegerIndex if the property is a canonical numeric index (10.4.5.2).
- IsValidIntegerIndex return true only if the the index is in range (10.4.5.9).
- The Resizable ArrayBuffer proposal modifies IsValidIntegerIndex to use the length returned by IntegerIndexObjectLength instead of [[ArrayLength]] when [[ArrayLength]] is auto (https://tc39.es/proposal-resizablearraybuffer/#sec-isvalidintegerindex). 

So, in the test, since the array buffer is resized to two items in the first call to the callback, the callback will only be called twice.

The behavior of XS is also consistent with the “spirit” of Array.prototype.every in the note: "elements that are deleted after the call to every begins and before being visited are not visited.”

There appear to be similar failures in filter, forEach, and map.

cc @jugglinmike @marjakh

**Comment by jugglinmike** [comment]
Thanks for the report, @phoddie; I believe you are correct! In addition to the four tests you've identified, it appears as though I repeated the same mistake in the equivalent tests for `Array.prototype.reduce`, `Array.prototype.reduceRight`, and `Array.prototype.some` (they all implement the same semantics concerning deleted elements). I've submitted a patch to correct those tests here: gh-3358.

**Comment by phoddie** [comment]
Thanks, @jugglinmike! XS now passes all revised tests. The changes to the tests look reasonable (with the usual caveat that my experience reviewing tests is limited).
