### ISSUE TITLE
Test262 harness methods mutate test state

### ISSUE THREAD

**Issue by 12wrigja** [tc39/test262#3352]
Reading over [INTERPRETING](https://github.com/tc39/test262/blob/main/INTERPRETING.md), that document calls out that tests are always run in a fresh JavaScript environment.

I'm attempting to run a subset of the Test262 tests, specifically those for [Temporal](https://github.com/tc39/proposal-temporal), in an environment where this is not the case, and have found that some of the Test262 Harness helper methods will mutate the state of the code under test. Specifically:

 - [isConfigurable](https://github.com/tc39/test262/blob/6d0a4fdac7802980f090663895c16786c9848e66/harness/propertyHelper.js#L106) never restores the property it deletes
	 - [isWriteable](https://github.com/tc39/test262/blob/6d0a4fdac7802980f090663895c16786c9848e66/harness/propertyHelper.js#L143-L171) seems very similar to isConfigurable, except isConfigurable checks `hasOwnProperty` after deleting. Could these definitions be merged?
 - [isWriteable](https://github.com/tc39/test262/blob/6d0a4fdac7802980f090663895c16786c9848e66/harness/propertyHelper.js#L167) doesn't restore the original property descriptor, it creates a new one by directly assigning the value back.
 - [verifyProperty](https://github.com/tc39/test262/blob/6d0a4fdac7802980f090663895c16786c9848e66/harness/propertyHelper.js#L96-L98)'s option to restore the original description is off by default, instead of on.
 
 This was very surprising to me - I don't expect an `is*` method to mutate anything.
 
 Would adjustments to the harness to better support running tests like this be accepted by the maintainers? Being able to run tests like this has shown a notable speed improvement when running the Temporal test262 test suite - the current implementation takes ~3 minutes, and running them in this other environment those same tests take ~12 seconds.

**Comment by rwaldron** [comment]
Thanks for the report, however these are all well known and well understood. The key to the correct use of these functions, is to not do _other_ things in a test, ie. use the function once, then do nothing after.

**Comment by leobalter** [comment]
This fits well in the concept of tests being atomic and autonomous. Restoring a state that existed before a unit test is not ideal as it creates a dependent, non-natural scenario for new tests. It's unfortunate engines doesn't have any optimized option to fully reset their environment other than reloading them and getting a new test file. 

Some minimum quality is being prioritized over execution speed here. This helps avoiding test flakiness as some given breakage, as pointed out, is necessary.
