### ISSUE TITLE
Tests for  Async-from-Sync Iterator changes

### ISSUE THREAD

**Issue by mhofman** [tc39/test262#3387]
https://github.com/tc39/ecma262/pull/2600 reached consensus at the last plenary. It updates  Async-from-Sync Iterator objects to close the wrapped iterator in cases where the async wrapper is considered to be done, but the sync iterator isn't.

I included some examples in the presentation of where this behavior shows up, and there were a few relevant cases in the linked issue. I plan to adapt those into test262 cases, but I may not have time immediately, so creating this issue to keep track of the tests needed.

**Comment by ioannad** [comment]
@mhofman I plan to be working on these tests, here is the test plan I have so far:

## Testing plan

- For the changes to `%AsyncFromSyncIteratorPrototype%.throw` (steps 8.a-8.h), check every codepath when closing the iterator for a null iterator throw method. Using sync iterators with null `throw` methods, and:
    - A return method that does something observable (like a finally). 
        - [ ] Test that the return method was called and the iterator closed before returning a new `TypeError`.
    - A return method which throws. 
        - [ ] Test this case returns a new `TypeError`.
    - Should not define a return method. 
        - Covered by existing test262 test [throw-null.js](https://github.com/tc39/test262/blob/main/test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-null.js) (IteratorClose throws a TypeError). 
        - [ ] Modify existing test to assert we ended with a new `TypeError`.

- For the changes to `AsyncFromSyncIteratorContinuation` (steps 6-6.a.), the new codepaths are reached only when `closeOnRejection` is`true`, and `done` is `false`. All tests here must ensure the iterator was closed, so the test sync iterators should have `return` methods that do something observable (like a finally).
    - Test that valueWrapper threw and the iterator was closed in the following scenarios:
        - Entering via `%AsyncFromSyncIteratorPrototype%.next` :
            - [ ] Using a sync iterator whose `next` method throws.
            - [ ] Using a sync iterator whose `next` method is null.
        - Entering via `%AsyncFromSyncIteratorPrototype%.throw` :
            - [ ] Using a sync iterator whose `throw` method is an abrupt completion. 
            - [ ] Using a sync iterator whose `throw` method is defined (gettable) but returns null.

- For the changes to `AsyncFromSyncIteratorContinuation` (steps 12.a-12.c), check if the iterator closes when `value` is a rejected promise. Using a `result` whose `value` property is a normal completion with a rejected promise, and again a sync iterator with a `return` method that does something observable (like a finally).
    - Entering via `%AsyncFromSyncIteratorPrototype%.next`:
        - Using a sync iterator whose `next` method is a normal completion with a rejected promise.
            - [ ] Test that the iterator closed.
        
WDYT? As a next step I plan to check which of the branches above are covered by the various examples/tests in the slides and relevant issues.

**Comment by ioannad** [comment]
All tests have been now added, and current review comments addressed.

**Comment by ioannad** [comment]
Just added some more test cases that occurred to me, all new codepaths should be tested now.
