### ISSUE TITLE
Incorrect new private reference methods and accessors with logical assignment

### ISSUE THREAD

**Issue by davidot** [tc39/test262#3413]
In 1b1097dbf6e93fb17b5a8156736563370ad4700e some tests for compound assignment of private fields and methods were added.

However I believe there are a couple of incorrect tests:
For example: `test/language/expressions/compound-assignment/left-hand-side-private-reference-method-nullish.js`
```js
class C {
  #privateMethod() {}
  compoundAssignment() {
    return this.#privateMethod ??= 1;
  }
}

const o = new C();
assert.throws(TypeError, () => o.compoundAssignment(), "PutValue throws when storing the result in a method private reference");
```

Looking at: https://tc39.es/ecma262/#sec-assignment-operators-runtime-semantics-evaluation
`||=`, `&&=` and `??=` are all special cases which short circuit when the left hand side passes a condition (like ToBoolean being `true` for `||=`)

So should I would think that it should not reach the `Putvalue(lref, rval)` call and thus does not throw in these instances.

Affected tests I found which fail this.
```
test/language/expressions/compound-assignment/left-hand-side-private-reference-method-nullish.js
test/language/expressions/compound-assignment/left-hand-side-private-reference-method-or.js
test/language/expressions/compound-assignment/left-hand-side-private-reference-readonly-accessor-property-nullish.js
test/language/expressions/compound-assignment/left-hand-side-private-reference-readonly-accessor-property-or.js
```
Since `&&=` does call `PutValue` if the left hand side is true which the methods evaluate to the following tests pass but might not be quite tested what was intended.
```
test/language/expressions/compound-assignment/left-hand-side-private-reference-method-and.js
test/language/expressions/compound-assignment/left-hand-side-private-reference-readonly-accessor-property-and.js
```

**Comment by davidot** [comment]
These tests might also need to be moved as these are the only tests with `||=`, `&&=` and `??=` in the `compound-assignment` folder instead of the rest of those tests in `logical-assignment`.

**Comment by linusg** [comment]
cc @ptomato

**Comment by ptomato** [comment]
Thanks for the feedback. Here's what I propose to do:
- the read-only accessor property tests for `||=` and `??=` can be fixed by returning a falsey or nullish value, respectively, from the getter
- the private method tests for `||=` and `??=` are invalid and should be removed
- I'll move the `||=`, `??=`, and `&&=` tests to `test/language/expressions/logical-assigment` (thanks! I didn't spot that folder at first)

> Since `&&=` does call `PutValue` if the left hand side is true which the methods evaluate to the following tests pass but might not be quite tested what was intended.

It seems to me that the `&&=` tests are still correct, as they are intended to test step 7 of "_AssignmentExpression_ : _LeftHandSideExpression_ `&&=` _AssignmentExpression_". It's possible there's something I'm missing, could you elaborate?

**Comment by davidot** [comment]
> Thanks for the feedback. Here's what I propose to do:
> 
>     * the read-only accessor property tests for `||=` and `??=` can be fixed by returning a falsey or nullish value, respectively, from the getter
> 
>     * the private method tests for `||=` and `??=` are invalid and should be removed
> 
>     * I'll move the `||=`, `??=`, and `&&=` tests to `test/language/expressions/logical-assigment` (thanks! I didn't spot that folder at first)

Yeah that seems great, only thing is perhaps it would be good to also have tests for `||=` and `??=` to make sure they don't throw this error? (Maybe this is already covered I don't know)

> It seems to me that the `&&=` tests are still correct, as they are intended to test step 7 of "_AssignmentExpression_ : _LeftHandSideExpression_ `&&=` _AssignmentExpression_". It's possible there's something I'm missing, could you elaborate?

This was more that it is the third in the set, the tests are correct. 
I guess the only thing wrong is the spec they mention in the test comment but I don't think that's a huge deal.

**Comment by ptomato** [comment]
Testing the short-circuit behaviour seems like a good idea, I've added these tests in #3414 as well.
