### ISSUE TITLE
Incorrect test for deleted properties of object being enumerated using for-in

### ISSUE THREAD

**Issue by IdanHo** [tc39/test262#3458]
`test/language/statements/for-in/S12.6.4_A7_T2.js` checks that properties that were deleted during enumeration are not enumerated.
Unfortunately since it uses both the key and the accessed value for the comparison, it succeeds even when the deleted properties are enumerated, i.e. the test is ensuring the accumulated string is not `aa1ba2ca3`, but in fact when enumeration includes removed properties the generated string would be `aa1baundefinedca3`.

Discovered while implementing this behaviour in Serenity's LibJS.

**Comment by jugglinmike** [comment]
Thanks for the report! Test262's older tests can be hard to read, and this one is especially so. In any event, I've submitted a fix in gh-3463.

**Comment by jugglinmike** [comment]
Resolved via https://github.com/tc39/test262/pull/3463
