### ISSUE TITLE
CI suggestion: Drop Python 2 build & lint tests

### ISSUE THREAD

**Issue by jessealama** [tc39/test262#3480]
In our CircleCI setup, we run some build & lint tools both with Python 2 and with Python 3. The scripts that get run are exactly the same: the Python 3 build runs the same code that the Python 2 does, just with a different Python binary. Of course, the dependencies (what gets installed by pip) are surely different, but the code we wrote, in this repository, is run as-is by both Python 2 and Python 3. I wonder whether there's any additional information to be gained, at this stage in the whole Python 2-to-3 evolution, when comparing the two runs. I wager not; I would expect that either both succeed or both fail. If that's right, I would suggest that we can just drop the Python 2 CI step.

**Comment by ljharb** [comment]
Are there any implementations that rely on Python 2 to run tests?

**Comment by ptomato** [comment]
I asked in the TC39 Implementers chat and the only response was "kill it" devsnek. I think we can probably drop the Python 2 step. I can open a PR and see if anyone complains.
