### ISSUE TITLE
Tests for RegExp v flag with set notation + properties of strings

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#3496]
https://github.com/tc39/proposal-regexp-set-notation

Calling @mathiasbynens and @anba! Would either of you be up for helping out with test authoring for this?

**Comment by mathiasbynens** [comment]
FWIW we’re also tracking this here: https://github.com/tc39/proposal-regexp-set-notation/issues/52

- Generated tests for properties of strings: https://github.com/tc39/test262/pull/3360
- TODO: tests for set notation syntax + semantics

**Comment by mathiasbynens** [comment]
Some progress on generated tests for set operations + the various bits of new syntax: https://github.com/mathiasbynens/unicode-property-escapes-tests/pull/11

**Comment by mathiasbynens** [comment]
With the three different sets of tests landing, I’m inclined to close this issue. Thanks for the help & reviews, everyone!

**Comment by ptomato** [comment]
Agreed, thanks for the hard work writing all the tests!
