### ISSUE TITLE
Object.hasOwnProperty.call

### ISSUE THREAD

**Issue by legendecas** [tc39/test262#3524]
I see that this `Object.hasOwnProperty.call` exists elsewhere, but I think that was a mistake and the intention was actually to use `Object.prototype.hasOwnProperty.call`. I'm not going to block on it here, but someone should do a cleanup to use `Object.prototype.hasOwnProperty.call` or `Reflect.hasOwnProperty`.

_Originally posted by @rwaldron in https://github.com/tc39/test262/pull/3512#discussion_r866315540_

**Comment by creampnx-x** [comment]
Totally agree with you
https://github.com/airbnb/javascript#objects--prototype-builtins
