### ISSUE TITLE
Incorrect test assertions in argument-string-negative-fractional-units.js ?

### ISSUE THREAD

**Issue by anba** [tc39/test262#3544]
https://github.com/tc39/test262/blob/f7b626133dce7d56d3df20ac8822f0fc310b995e/test/built-ins/Temporal/Duration/prototype/subtract/argument-string-negative-fractional-units.js#L11-L15

Relevant steps from <https://tc39.es/proposal-temporal/#sec-temporal-parsetemporaldurationstring>:
> 9.b. Let fHoursDigits be the substring of CodePointsToString(fHours) from 1.
> 9.c. Let fHoursScale be the length of fHoursDigits.
> 9.d. Let minutesMV be ! ToIntegerOrInfinity(fHoursDigits) / 10<sup>fHoursScale</sup> × 60.
> ...
> 13.a. Let secondsMV be remainder(minutesMV, 1) × 60.
> ...
> 15.a. Let millisecondsMV be remainder(secondsMV, 1) × 1000.
> 16. Let microsecondsMV be remainder(millisecondsMV, 1) × 1000.
> 17. Let nanosecondsMV be remainder(microsecondsMV, 1) × 1000.

With `fHours = ".567890123"`, we have:
> 9.b. fHoursDigits = "567890123"
> 9.c. fHoursScale = 9
> 9.d. minutesMV = 567'890'123 / 10<sup>9</sup> × 60 = 34.073'407'380
> ...
> 13.a. secondsMV = 0.073'407'380 × 60 = 4.404'442'800
> ...
> 15.a millisecondsMV = 404.442'800
> 16. microsecondsMV = 442.800
> 17. nanosecondsMV = 800

So the nanoseconds part should be `800`, but the test files expect it to be `799`. (`799` is the correct answer when these computations are performed with Number values using IEEE-754 semantics.)

---

https://github.com/tc39/test262/blob/f7b626133dce7d56d3df20ac8822f0fc310b995e/test/built-ins/Temporal/Duration/prototype/subtract/argument-string-negative-fractional-units.js#L16-L17

Similar issue for this assertion. 
> 11.b. Let fMinutesDigits be the substring of CodePointsToString(fMinutes) from 1.
> 11.c. Let fMinutesScale be the length of fMinutesDigits.
> 11.d. Let secondsMV be ! ToIntegerOrInfinity(fMinutesDigits) / 10<sup>fMinutesScale</sup> × 60.
> ...
> 15.a. Let millisecondsMV be remainder(secondsMV, 1) × 1000.
> 16. Let microsecondsMV be remainder(millisecondsMV, 1) × 1000.
> 17. Let nanosecondsMV be remainder(microsecondsMV, 1) × 1000.

With `fMinutes = "567890123"`:
> 11.b. fMinutesDigits = "567890123"
> 11.c. fMinutesScale = 9
> 11.d. secondsMV = 567'890'123 / 10<sup>9</sup> × 60 = 34.073'407'380
> ...
> 15.a millisecondsMV = 73.407'380
> 16. microsecondsMV = 407.380
> 17. nanosecondsMV = 380

So `nanosecondsMV = 380`, but the test files expect `379`.

---

Affected test files:
- test/built-ins/Temporal/ZonedDateTime/prototype/add/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/ZonedDateTime/prototype/subtract/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/Duration/from/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/Duration/compare/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/Duration/prototype/add/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/Duration/prototype/subtract/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/PlainTime/prototype/add/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/PlainTime/prototype/subtract/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/PlainDateTime/prototype/add/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/PlainDateTime/prototype/subtract/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/Instant/prototype/add/argument-string-negative-fractional-units.js
- test/built-ins/Temporal/Instant/prototype/subtract/argument-string-negative-fractional-units.js

**Comment by gibson042** [comment]
I concur with this analysis.

**Comment by rkirsling** [comment]
This change seems unreasonable when considered from an implementation standpoint. If "799 is the correct answer when these computations are performed with Number values using IEEE-754 semantics" then 799 ought to be the correct answer—how else are we storing the suggested value `0.073'407'380`?

**Comment by anba** [comment]
> how else are we storing the suggested value 0.073'407'380?

The fractional part has to be stored as a separate integer, so the spec can't be implemented by a step-to-step translation. (This is a recurring theme in the proposal, there are many other places where implementers have to rewrite the steps to avoid having to deal with arbitrary precision decimals.)

For example in my current SpiderMonkey patches, I use this approach:

```cpp
  double minutes, seconds, milliseconds, microseconds, nanoseconds;
  if (parseResult.hoursFraction) {
    MOZ_ASSERT(parseResult.hoursFraction > 0);
    MOZ_ASSERT(parseResult.hoursFraction < 1'000'000'000);

    // Step 9.a. (Not applicable in our implementation.)

    // Steps 9.b-d.
    int64_t h = int64_t(parseResult.hoursFraction) * 60;
    minutes = h / 1'000'000'000;

    // Steps 13 and 15-17.
    int64_t min = (h % 1'000'000'000) * 60;
    seconds = min / 1'000'000'000;
    milliseconds = (min % 1'000'000'000) / 1'000'000;
    microseconds = (min % 1'000'000) / 1'000;
    nanoseconds = (min % 1'000);
  }
  ...
```
