### ISSUE TITLE
Question - assignment of CallExpression

### ISSUE THREAD

**Issue by Meir017** [tc39/test262#3650]
consider the following code
```js
function $(arg) { return arg }
$(window) = $(window).test
```
using chrome/nodejs this code throws during execution, parsing works.

based on the spec
https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-assignment-operators

![image](https://user-images.githubusercontent.com/9786571/187615418-042ed3cd-699c-42c3-ae64-ad0549d42353.png)
![image](https://user-images.githubusercontent.com/9786571/187615447-866a7a24-5530-493b-9fe4-2e78b203bbd0.png)

so the syntax of a CallExpression on the left side should be parsable.

what is the expected behavior here?

based on discussion in https://github.com/acornjs/acorn/issues/1145

**Comment by ptomato** [comment]
I believe this is answered in https://github.com/acornjs/acorn/issues/1145? If not, I can transfer this issue to tc39/ecma262
