### ISSUE TITLE
[question] `Array.of.bind(Object)()`

### ISSUE THREAD

**Issue by icecream17** [tc39/test262#3675]
![image](https://user-images.githubusercontent.com/58114641/192525801-b841aebc-5fb8-4387-a763-0913f2317581.png)

[The spec for Array.of](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.of) seems to say that the result would be to create a new Object but it creates a Number instead

Is this a bug or am I missing something?

**Comment by nicolo-ribaudo** [comment]
Step 4.a will do `new Object(1)`, and `new Object` with a number parameter returns a `Number` object.
