### ISSUE TITLE
Tests for Array.fromAsync 

### ISSUE THREAD

**Issue by Aditi-1400** [tc39/test262#3725]
[Proposal readme](https://github.com/tc39/proposal-array-from-async#readme)
[Proposal Spec Text](https://tc39.es/proposal-array-from-async/)

## Testing plan

- ### Standard tests: https://github.com/tc39/test262/pull/3747
    - [x] Property descriptor
    - [x] ~~Brand check~~ - _I think this covered by "`this` value is not a constructor" below_
    - [x] Function length
    - [x] Function name
    - [x] Not a constructor
    - [x] Prototype and extensibility ~~([blocked](https://github.com/tc39/ecma262/pull/2942#issuecomment-1304291563)?)~~

- ### Basic Functionality
    - Success cases - https://github.com/tc39/test262/pull/3809
        - [x] Creates promise
        - [x] Create new array/arrayLike in promise (with length = length property)

- ### Arguments
    - **Input** - https://github.com/tc39/test262/pull/3754
        - *Invalid input values:*
            - [x] `undefined`
            - [x] `null`
            - [x] Symbol
            - [x] Boolean
            - [x] Number + BigInt
            - [x] function
            - [x] @@asyncIterator/@@iterator throws on getting
            - [x] @@asyncIterator/@@iterator returns non-callable value
            - [x] @@iterator returns async iterator (seems like it shouldn't work?)
            - [x] asyncIterator throws on step 
            - [x] nonconforming object (arraylike without length, missing keys) - https://github.com/tc39/test262/pull/3809

        - *Valid inputs:*
            - [x] String
            - [x] Sync-iterable with no promises
            - [x] Sync-iterable with promises
            - [x] Async-iterable
            - [x] Non-iterable with no promises
            - [x] Non-iterable with promises
            - [x] @@asyncIterator returns sync iterator
        - *Tests for input*
            - [ ] Input array with boundary values

            - Covered by polyfill tests: - https://github.com/tc39/test262/pull/3791
                - [x] Output promise rejects if iteration of input fails
                - [x] Output promise rejects if element access fails
                - [x] ~~Result promise rejects if input length exceeds safe integers~~ seems impractical, tests time out
                - [x] Awaits each input value once without mapping callback (with promises)
                - [x] Result promise rejects if element's "then" method fails (with promises)
                - [x] Result promise rejects if thenable element rejects (with promises)
                - [x] Does not await input values (Async iterable)
                - [x] Result promise rejects if length access fails (non-iterable input) - https://github.com/tc39/test262/pull/3809
                - [x] Does not use array iterator prototype (non-iterable)
                - [x] Unaffected by globalThis.Symbol mutation (non-iterable) - https://github.com/tc39/test262/pull/3809

    - **Mapfn** - https://github.com/tc39/test262/pull/3790
        - *Invalid mapfn (Non callable)*
            - [x] `null`
            - [x] `{}`
            - [x] Valid string
            - [x] Boolean
            - [x] Number
            - [x] Symbol
            - [x] BigInt

        - *Valid mapfn*
            - [x] Mapfn with sync callback
            - [x] Mapfn with async callback

        - *Tests for valid mapfn* (All tests are covered in polyfill tests)
            - [x] With default undefined this
            - [x] With given thisValue
            - [x] Output promise rejects if callback fails
            - [x] Output promise rejects if mapfn is non callable
            - [x] Awaits each input value once (with promises in input)
        
        - *Tests for closing iterator and returned promise rejects*
            - [x] When mapFn completes abruptly
            - [x] When mapFn returns a promise that rejects

    - **ThisArg** - https://github.com/tc39/test262/pull/3790
        - [x] Mapfn without thisArg on non-strict mode
        - [x] Mapfn without thisArg on strict mode
        - [x] Mapfn with a valid thisArg

- ### `this` value - https://github.com/tc39/test262/pull/3809
    - [x] `this` value is a constructor
    - [x] `this` value is not a constructor
    - *Tests*
        - [x] If this is a constructor, and items doesn't have an @@iterator, returns a new instance of this
        - [x] iterator closed when property creation on `this` fails
        - [x] returned promise rejects when ^

- ### Other Tests
    - [x] Elements are added after the call to fromAsync()
    - [x] Elements are deleted after the call to fromAsync()
    - [x] Elements are updated after the call to fromAsync()
    - [x] Error accessing input's `Symbol.iterator` attribute
    - [x] Return empty array if items argument is an ArrayBuffer
    - [x] Error is thrown for all CreateDataProperty fails. - https://github.com/tc39/test262/pull/3809
    - [x] Non-writable properties are overwritten by CreateDataProperty - https://github.com/tc39/test262/pull/3809
    - [x] Input with missing values - https://github.com/tc39/test262/pull/3809
    - [ ] How much timing can we / do we need to test in terms of promise resolving?
      - I think none, since it's not deterministic

Co-authored by: @Ms2ger @ptomato @cjtenny

**Comment by Ms2ger** [comment]
Thanks @Aditi-1400!

FTR, a number of those tests are already written but need to get PRd

**Comment by HEXYEBO0** [comment]
> [Proposal readme](https://github.com/tc39/proposal-array-from-async#readme)
> [Proposal Spec Text](https://tc39.es/proposal-array-from-async/)
> 
> ## Testing plan
> 
> - ### Standard tests: https://github.com/tc39/test262/pull/3747
>     - [x] Property descriptor
>     - [ ] Brand check - _I think this covered by "`this` value is not a constructor" below_
>     - [x] Function length
>     - [x] Function name
>     - [x] Not a constructor
>     - [x] Prototype and extensibility ~~([blocked](https://github.com/tc39/ecma262/pull/2942#issuecomment-1304291563)?)~~
> 
> - ### Basic Functionality
>     - Success cases
>         - [ ] Creates promise
>         - [ ] Create new array/arrayLike in promise (with length = length property)
> 
> - ### Arguments
>     - **Input** - https://github.com/tc39/test262/pull/3754
>         - *Invalid input values:*
>             - [x] `undefined`
>             - [x] `null`
>             - [x] Symbol
>             - [x] Boolean
>             - [x] Number + BigInt
>             - [x] function
>             - [x] @@asyncIterator/@@iterator throws on getting
>             - [x] @@asyncIterator/@@iterator returns non-callable value
>             - [x] @@iterator returns async iterator (seems like it shouldn't work?)
>             - [ ] asyncIterator throws on step 
>             - [ ] nonconforming object (arraylike without length, missing keys)
> 
>         - *Valid inputs:*
>             - [x] String
>             - [x] Sync-iterable with no promises
>             - [x] Sync-iterable with promises
>             - [x] Async-iterable
>             - [x] Non-iterable with no promises
>             - [x] Non-iterable with promises
>             - [x] @@asyncIterator returns sync iterator
>         - *Tests for input*
>             - [ ] Input array with boundary values
> 
>             - Covered by polyfill tests:
>                 - [ ] Output promise rejects if iteration of input fails
>                 - [ ] Output promise rejects if element access fails
>                 - [ ] Result promise rejects if input length exceeds safe integers
>                 - [ ] Awaits each input value once without mapping callback (with promises)
>                 - [ ] Result promise rejects if element's "then" method fails (with promises)
>                 - [ ] Result promise rejects if thenable element rejects (with promises)
>                 - [ ] Does not await input values (Async iterable)
>                 - [ ] Result promise rejects if length access fails (non-iterable input)
>                 - [ ] Does not use array iterator prototype (non-iterable)
>                 - [ ] Unaffected by globalThis.Symbol mutation (non-iterable)
> 
>     - **Mapfn** - https://github.com/tc39/test262/pull/3790
>         - *Invalid mapfn (Non callable)*
>             - [ ] `null`
>             - [ ] `{}`
>             - [ ] Valid string
>             - [ ] Boolean
>             - [ ] Number
>             - [ ] Symbol
>             - [ ] BigInt
> 
>         - *Valid mapfn*
>             - [ ] Mapfn with sync callback
>             - [ ] Mapfn with async callback
> 
>         - *Tests for valid mapfn* (All tests are covered in polyfill tests)
>             - [ ] With default undefined this
>             - [ ] With given thisValue
>             - [ ] Output promise rejects if callback fails
>             - [ ] Output promise rejects if mapfn is non callable
>             - [ ] Awaits each input value once (with promises in input)
>         
>         - *Tests for closing iterator and returned promise rejects*
>             - [ ] When mapFn completes abruptly
>             - [ ] When mapFn returns a promise that rejects
> 
>     - **ThisArg** - https://github.com/tc39/test262/pull/3790
>         - [ ] Mapfn without thisArg on non-strict mode
>         - [ ] Mapfn without thisArg on strict mode
>         - [ ] Mapfn with a valid thisArg
> 
> - ### `this` value
>     - `this` value is a constructor
>     - `this` value is not a constructor
>     - *Tests*
>         - [ ] If this is a constructor, and items doesn't have an @@iterator, returns a new instance of this
>         - [ ] iterator closed when property creation on `this` fails
>         - [ ] returned promise rejects when ^
> 
> - ### Other Tests
>     - [ ] Elements are added after the call to fromAsync()
>     - [ ] Elements are deleted after the call to fromAsync()
>     - [ ] Elements are updated after the call to fromAsync()
>     - [ ] Error accessing input's `Symbol.iterator` attribute
>     - [ ] Return empty array if items argument is an ArrayBuffer
>     - [ ] Error is thrown for all CreateDataProperty fails.
>     - [ ] Non-writable properties are overwritten by CreateDataProperty
>     - [ ] Input with missing values
>     - [ ] How much timing can we / do we need to test in terms of promise resolving?
> 
> Co-authored by: @Ms2ger @ptomato @cjtenny

**Comment by ptomato** [comment]
There are two things left on the list:

- Input array with boundary values
- How much timing can we / do we need to test in terms of promise resolving?

I'm not sure what the idea is for the array with boundary values. My opinion about the second item is that we probably don't need to test the timing.

**Comment by Ms2ger** [comment]
Let's say this is done.
