### ISSUE TITLE
Invalid test for decorators

### ISSUE THREAD

**Issue by nicolo-ribaudo** [tc39/test262#3794]
https://github.com/tc39/test262/blob/main/test/language/expressions/class/decorator/syntax/class-valid/decorator-member-expr-private-identifier.js

I'm quite sure that this test is invalid, and that `@#x` is not a valid decorator (cc @pzuraq). I noticed it because Babel's implementation is throwing a syntax error for that test.

**Comment by pzuraq** [comment]
That is correct, that was a mistake in the spec and it has no logical meaning so it was updated
