### ISSUE TITLE
Encoding Expected Error Type

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#382]
As part of the ongoing effort to make Test262 more useful to JavaScript parser implementors (see gh-196), [we recently updated most tests for runtime errors to use the relatively new `assert.throws` helper method instead of the `negative` frontmatter](https://github.com/tc39/test262/pull/360). As mentioned there, not _all_ runtime errors could be refactored in this way; specifically, tests that concern errors thrown from the global scope must produce an uncaught error in order to be verified.

This means that the `negative` tag is still somewhat overloaded; it describes expected runtime errors, parser errors, and "early errors". If tests made this distinction explicit, then parser implementors would be able to automatically consume the Test262 tests.

We should update the frontmatter format to allow for this distinction. While we're at it, it wouldn't hurt to make a further distinction between parser errors. This was originally raised in gh-196; it may be relevant if tests are asserting parser errors generated from direct grammar application (invalid syntax; only SyntaxErrors), or generated due to explicit "Static Semantics" (which may be SyntaxErrors or ReferenceErrors).

One idea:

``` diff
 /*---
-negative: ReferenceError
+runtimeError: ReferenceError
 ---*/
 let x = x;
```

``` diff
 /*---
-negative: SyntaxError
+parserError: SyntaxError
 ---*/
 let x =;
```

``` diff
 /*---
-negative: SyntaxError
+parserError: early:SyntaxError
 ---*/
 let x, x;
```

Although the above makes room for invalid configurations that test runners (or [tests for the tests](https://github.com/tc39/test262/issues/306)) would have to guard against. Another approach would help avoid this and also curtail the proliferation of top-level configuration attributes:

``` diff
 /*---
-negative: ReferenceError
+negative:
+  stage: runtime
+  type: Referenceerror
 ---*/
 let x = x;
```

``` diff
 /*---
-negative: SyntaxError
+negative:
+  stage: parse
+  type: SyntaxError
 ---*/
 let x =;
```

``` diff
 /*---
-negative: SyntaxError
+negative:
+  stage: early
+  type: SyntaxError
 ---*/
 let x, x;
```

@bterlson @jmdyck Do either of these seem good to you? Or maybe something else?

**Comment by jmdyck** [comment]
The second approach makes sense to me.

(Note that in issue #196, I distinguished between 'lexical' and 'syntactic'. If this is deemed a useful distinction, it could be accommodated with another value for the 'stage' field.)

**Comment by jmdyck** [comment]
By the way, one could argue that the formerly-`negative` tests that now use `assert.throws` are still "negative tests" in that they still test the implementation's handling of erroneous input. And thus the use of `negative` to label only some negative tests is imprecise.

You might want to take this occasion to replace `negative` with something more precise like `uncaughtError`.

**Comment by jugglinmike** [comment]
> (Note that in issue #196, I distinguished between 'lexical' and 'syntactic'. If this is deemed a useful distinction, it could be accommodated with another value for the 'stage' field.)

@jmdyck This is the perfect time to introduce these distinctions, but I still don't understand this one. Can you give an example?

**Comment by jmdyck** [comment]
(Sorry, I've been meaning to answer this question over at #196, but got distracted.)

According to 5.1.4 "The Syntactic Grammar":
> When a stream of code points is to be parsed as an ECMAScript _Script_ or _Module_, it is first converted to a stream of input elements by repeated application of the lexical grammar; this stream of input elements is then parsed by a single application of the syntactic grammar.

In those terms, we can say that a _lexical_ error is a failure of one of the applications of the lexical grammar, whereas a _syntactic_ error is a failure of the application of the syntactic grammar. For instance, each of the following lines would cause a lexical error (I think):

    /* not a complete Comment
    " not a complete StringLiteral
    ` not a complete Template
    "\x1"
    /[a-z
    \u3
    @
    #1

**Comment by jugglinmike** [comment]
@michaelficarra As we discussed, I'd like this effort to result in something
that is usable by Shift, Esprima, Acorn, Uglify, Babylon, etc. I know you have
a lot of experience in the area (and connections with many other parser
writers). Could you help me define this work in order to promote adoption?

As it stands, I'm planning on changing the test files according to the *second*
format I proposed above (i.e. using `stage` and `type`). I'll also include a
distinction for lexical errors as requested by @jmdyck. Once that's done, I
assume parsers will consume the tests by using a git submodule.

Does this seem like an acceptable plan to you? Is there a need it doesn't
address? Is there anything in particular you would change about it?

**Comment by jugglinmike** [comment]
Actually @michaelficarra, I think the long-term solution may be more complicated. As discussed at the last TC-39 meeting, Test262 will likely be making use of code generation techniques to promote consistent coverage (for some subset of its tests, at least). That means consuming tests via a simple submodule may not be sufficient in the future.

@bterlson maintains [a test harness that is capable of outputting compiled test material](https://github.com/bterlson/test262-harness). Presumably, this will be updated to expand test templates when/if Test262 implements that strategy. I believe he recommends that consumers use the runner in some form. They could either use it to execute their tests, or they could use it to simply generate the files and execute their tests using the files as input. I'm just not sure consumers will tolerate a dependency on a Node.js application (especially if they aren't targeting the Node.js platform).

An alternative I've been interested in is creating a publication channel for the built files. That would simplify the consumption model, and it would also enable this project to make drastic changes to the generation approach (which is especially important in the early stages of template design/implementation). One potential downside is that receiving test material from disk is potentially slower than piping from a process, but I don't know if that will be a practical concern.

What do you think?

**Comment by michaelficarra** [comment]
Sorry I didn't get back to you sooner. Yes, that problem with submodules and potential test generation is exactly the issue I was going to raise.

> I'm just not sure consumers will tolerate a dependency on a Node.js application (especially if they aren't targeting the Node.js platform).

Are you saying the test generation would have to be done via a node application?

The process I was considering was a template system that generates the tests, which are only included in packaged releases. Then, test262 can be distributed via a variety of package managers, with a small entry point for each platform that reads the generated files and exposes them to consumers in the idiomatic format for that platform. More concretely, I imagine an npm package could be created using an `index.js` file that loads each generated (or static) test file and exposes a representation of the directory hierarchy, and a `package.json` configured to include just those tests and `index.js` in the package. Then, you could have the distributables for Ruby/Python/whatever as well in the same repo.

**Comment by jugglinmike** [comment]
> Sorry I didn't get back to you sooner.

No worries!

> Are you saying the test generation would have to be done via a node
> application?

Well, any application *could* generate the tests, but I don't think we generally want to encourage people to write their own generators. Doing that would severely limit our ability to iterate on the abstractions we use to express test "source" files, and I personally consider that to be an implementation detail. So I think that effectively, endorsing the use of any harness is equivalent to coupling to that specific harness.

> The process I was considering was a template system that generates the tests,
> which are only included in packaged releases.

This is what I had in mind, too :)

> Then, test262 can be distributed via a variety of package managers, with a
> small entry point for each platform that reads the generated files and
> exposes them to consumers in the idiomatic format for that platform

I'm having trouble understanding the need for this entry point, even with the helpful example. As described, it sounds like additional overhead where we could simply instruct consumers: "all the files in the `out/` directory are standalone JavaScript tests. Traverse that directory recursively and execute the files as you see fit." That contract would alleviate Test262 of the need to expose platform-specific files. Is there some use case that it would prevent?

**Comment by michaelficarra** [comment]
Not only does it save me the hassle of traversing your directories and reading files, but it removes my potential dependence on your internal directory structure, and most importantly, consumers do not have to parse the meta information or depend on its format.

**Comment by jugglinmike** [comment]
Directory traversal seems like a trivial hassle, and a simple contract like "everything in `out/`" seems generic enough for Test262 as a publisher and for consumers. Your point about metadata is more convincing to me, though.

The formatting itself shouldn't be a problem because YAML directly maps to the simple data structures we need. For instance, the difference to JavaScript consumers will be: text like "-description: My test name" vs. serialized data like `{ description: "My test name" }`. Any change we would consider "breaking" to one (i.e. renaming the attribute) would also break the other.

But parsing is a little different. Is it an undue requirement that consumers parse YAML? Many platforms include YAML parsing in their standard library, but even on those platforms, [it isn't always an option](https://code.google.com/p/v8/issues/detail?id=4263).

Here's what it sounds like we want:

- A publication system that produces standalone pure-JavaScript test files
- One script for each supported platform that exposes an in-memory listing of
  all the generated files (both relative file location and meta data)

Is that right? (Keep in mind that even if it is, I'm just some guy. We'll have to convince @bterlson before I can start work on this.)

**Comment by jmdyck** [comment]
Sorry, I'm not clear on how today's comments (about test generation and publication systems) relate to the preceding comments (about expressing the expected outcome for tests that throw uncaught exceptions).

**Comment by leobalter** [comment]
I believe we've already got this solved. Please reopen if necessary or an early error of mine.
