### ISSUE TITLE
Need test for ECMA402 #758 Normative: Change the hourCycle default logic 

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/test262#3876]
https://github.com/tc39/ecma402/pull/758 is going to be discussed in Sept 2023 TC39 meeting.

**Comment by jufemaiz** [comment]
https://github.com/tc39/test262/pull/3885 <-- is this the work for this issue?

**Comment by jufemaiz** [comment]
@FrankYFTang did it make the sept 2023 discussion?

https://github.com/tc39/ecma402/projects/2 doesn't show it on the list.

**Comment by FrankYFTang** [comment]
> @FrankYFTang did it make the sept 2023 discussion?

TG2 discussed that on 2023-04-06 and reach agreement that 
"
FYT: Action item: add test. Consensus that we’ll present at TG1 in May?
SFC: I think for both of these.
Conclusion
TG2 agreement "

See https://github.com/tc39/ecma402/blob/master/meetings/notes-2023-04-06.md#normative-change-the-hourcycle-default-logic-758 

Somehow no body present this to the May [TC39  meeting](https://github.com/tc39/agendas/blob/main/2023/05.md) nor [July TC39 meeting](https://github.com/tc39/agendas/blob/main/2023/07.md).
I put that on the TC39 September agenda on  https://github.com/tc39/agendas/blob/main/2023/09.md 
And that will be discussed on "10:00 to 17:00 JST (Asia/Tokyo) on 26 September 2023"

**Comment by jufemaiz** [comment]
Thanks for the comprehensive feedback on this! It's been a little challenging to dig into and work out what's what + where.
