### ISSUE TITLE
cjtenny would like to become a maintainer

### ISSUE THREAD

**Issue by cjtenny** [tc39/test262#3950]
Hi! I'm a TC39 delegate from Igalia who's been working on test262 for a while now, most recently on reviews and tests for the Temporal and RegExp modifiers proposals. I brought this up in the maintainer's meeting yesterday, and it was decided a good next step would be for me to post it here for visibility. The maintainers in the meeting approved but want to leave room for comment. If any TC39 delegate has concerns or feedback, feel free to deliver them to the maintainers. Otherwise, they'll consider this approved in a week.

Looking forward to helping clear the backlog of tests and reviews :crossed_fingers: 

@tc39/test262-maintainers

**Comment by ljharb** [comment]
Sounds like this is approved. Welcome!

**Comment by cjtenny** [comment]
Thank you very much!
