### ISSUE TITLE
Tests of Iterator.prototype.constructor/toStringTag are broken

### ISSUE THREAD

**Issue by iamstolis** [tc39/test262#3993]
#3970 updated the following tests (in order to reflect a recent normative change)
```
built-ins/Iterator/prototype/Symbol.toStringTag/prop-desc.js
built-ins/Iterator/prototype/Symbol.toStringTag/weird-setter.js
built-ins/Iterator/prototype/constructor/prop-desc.js
built-ins/Iterator/prototype/constructor/weird-setter.js
```

Unfortunately, these tests are broken now.

`prop-desc.js` tests use `verifyConfigurable()` that deletes the tested property. So, the subsequent assertions fail. `verifyConfigurable()` must be the last statement of the test (if used at all).

`weird-setter.js` tests pass too few arguments to `assert.throws()` i.e. they fail to specify the type of the expected error.

**Comment by bakkot** [comment]
cc @michaelficarra

**Comment by michaelficarra** [comment]
Opened #3996.
