### ISSUE TITLE
Bad normalization form test expects TypeError, but should be RangeError

### ISSUE THREAD

**Issue by littledan** [tc39/test262#400]
http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.normalize in step 7 throws a RangeError, but built-ins/String/prototype/normalize/return-abrupt-from-form-as-symbol on line 19 expects a TypeError.

**Comment by jugglinmike** [comment]
The algorithm doesn't make it as far as step 7 of String.prototype.normalize. Step 5 reads: "Let f be ToString(form)." [When invoked with a Symbol value, the ToString abstract operation throws the TypeError described by the test](http://www.ecma-international.org/ecma-262/6.0/#sec-tostring). This abrupt completion value is returned by String.prototype.normalize in the following step.

**Comment by littledan** [comment]
Oh, I see, thanks! WAI
