### ISSUE TITLE
Question: NPM Registry

### ISSUE THREAD

**Issue by SwhiteMHC** [tc39/test262#4063]
Hi,

Is there a reason test262 is not registered with the public NPM registry? I am doing a security review and this package is flagged as potentially vulnerable to a Dependency Confusion attack in my project.

Thank you for any context.

**Comment by ljharb** [comment]
Because it's not meant to be consumed in that way.

How are you using it in your project, and for what purpose?

**Comment by SwhiteMHC** [comment]
@ljharb I am not. However two packages in my node_modules i.e. @eslint-community/regexpp and @acorm-import-assertions both make use of it.

**Comment by ljharb** [comment]
Both of those list it in devDependencies, so there's no possibility you'll install it, and whatever is doing your security review doesn't seem to understand how npm dependency graphs work or else it'd only be looking at dependencies/peerDependencies/optionalDependencies/bundleDependencies/bundledDependencies.

**Comment by SwhiteMHC** [comment]
@ljharb I can confirm omitting the dev dependencies from installation resolves the issue. Thank you for the additional context. Please feel free to close the issue.
