### ISSUE TITLE
`new Iterator()` should throw `TypeError`?

### ISSUE THREAD

**Issue by sosukesuzuki** [tc39/test262#4068]
The following assertion is included in the file [/test/built-ins/Iterator/newtarget-or-active-function-object.js](https://github.com/tc39/test262/blob/main/test/built-ins/Iterator/newtarget-or-active-function-object.js):

```js
assert.throws(TypeError, () => {
  new Iterator();
});
```

Is this correct?

According to section 3.1.1.1 of the proposed specification [^1],

> it is designed to be subclassable. It may be used as the value of an extends clause of a class definition.

However, section 3.1.1.1.1 [^2] states:

> 2. Return ? OrdinaryCreateFromConstructor(NewTarget, "%Iterator.prototype%").

This does not mention throwing a `TypeError`.

Should a call to `new Iterator()` throw a `TypeError`, or should it return a value that inherits from `Iterator.prototype`?

[^1]: https://tc39.es/proposal-iterator-helpers/#sec-iterator-constructor
[^2]: https://tc39.es/proposal-iterator-helpers/#sec-iterator

**Comment by nicolo-ribaudo** [comment]
When you do `new Iterator`, NewTarget and "the active function object" are equal (both `Iterator`) and so step 1 of 3.1.1.1.1 throws.

**Comment by sosukesuzuki** [comment]
Ahh I got it.., thanks
