### ISSUE TITLE
Various ECMA links 404

### ISSUE THREAD

**Issue by linusg** [tc39/test262#4092]
All of these:

- https://github.com/search?q=repo%3Atc39%2Ftest262%20%22publications%2Ffiles%22&type=code
- https://github.com/search?q=repo%3Atc39%2Ftest262%20%22publications%2Ftechreports%22&type=code

**Comment by ljharb** [comment]
I've notified the appropriate ECMA folks about this; will update here once it's resolved.

**Comment by ljharb** [comment]
These should be fixed.
