### ISSUE TITLE
Create testing plan for the RegExp.escape proposal

### ISSUE THREAD

**Issue by nicolo-ribaudo** [tc39/test262#4122]
Proposal repo: https://github.com/tc39/proposal-regex-escaping

I plan to help @greg-nagy work on this later during the summer

**Comment by ptomato** [comment]
@nicolo-ribaudo @greg-nagy Your advice appreciated on how complete is https://github.com/tc39/test262/pull/4123

**Comment by bnoordhuis** [comment]
FWIW, I note that https://github.com/tc39/proposals doesn't mention a test262 flag but it's `RegExp.escape`

**Comment by ljharb** [comment]
Thanks, I've added it. Also, closing since #4123 landed.
