### ISSUE TITLE
`test/built-ins/Proxy/revocable/tco-fn-realm.js` is missing `destructuring-assignment` feature flag

### ISSUE THREAD

**Issue by linusg** [tc39/test262#4218]
https://github.com/tc39/test262/blob/fc49c9ce163dcf501bb0457f0521900cd744cbda/test/built-ins/Proxy/revocable/tco-fn-realm.js#L9

https://github.com/tc39/test262/blob/fc49c9ce163dcf501bb0457f0521900cd744cbda/test/built-ins/Proxy/revocable/tco-fn-realm.js#L15

**Comment by ljharb** [comment]
Better would be to avoid using destructuring there at all, I think.
