### ISSUE TITLE
Improve lexical scoping tests

### ISSUE THREAD

**Issue by littledan** [tc39/test262#422]
A recent V8 bug showed that there aren't complete test262 tests that exercise lexical scoping. In particular, it was not tested that switch introduces a new scope for cases. A simple test case:

```
d8> switch (1) { case 1: let x = 2; } x
2
```

I think it'd be useful if Test262 verified that new lexical scopes are introduced when the spec says they should be.

https://code.google.com/p/v8/issues/detail?id=4377

(Another interesting test case is
`switch (0) { case 1: let x = 2 } x`
which should cause a ReferenceError.)

**Comment by rwaldron** [comment]
To clarify: 

- `switch (1) { case 1: let x = 2; } x`
- `switch (0) { case 1: let x = 2; } x`

Should both result in a ReferenceError.

**Comment by littledan** [comment]
Exactly, thanks for clarifying, returning 2 in the first test was the buggy output.

**Comment by leobalter** [comment]
This is partially covered by tests in https://github.com/tc39/test262/tree/master/test/language/statements/switch (see `scope-lex-*`)

While these tests might have already fixed this issue, I would like to extend these tests to check for the ReferenceError cases on names defined only inside the lexical scopes.
