### ISSUE TITLE
ioannad would like to become maintainer

### ISSUE THREAD

**Issue by ioannad** [tc39/test262#4224]
I'm a TC39 delegate from Igalia, who has been working on test262 issues and PRs for some months now. I would like to become test262 maintainer to be able to help further. I mentioned this during the last test262 maintainers meeting and the reception was positive, so I am creating this issue to make this wish visible and create room for any comments.
If any TC39 delegate has concerns or feedback, feel free to deliver them to the maintainers. Otherwise, they'll consider this approved in a week.

@tc39/test262-maintainers

**Comment by ptomato** [comment]
No comments, I think we can move this forward 😄

**Comment by ljharb** [comment]
Added @ioannad to the maintainers team.
