### ISSUE TITLE
Why is the Dynamic Code Brand Checks proposal not testable in test262.

### ISSUE THREAD

**Issue by ioannad** [tc39/test262#4229]
According to the proposal repo's [README](https://github.com/tc39/proposal-dynamic-code-brand-checks?tab=readme-ov-file#tests), 

> testing these require affecting the behavior of host callouts so will probably need to be specified as [web-platform-tests](https://github.com/web-platform-tests/wpt).

As [suggested](https://github.com/tc39/proposals/pull/535#issuecomment-2344079037) by @ljharb, this issue is to document the reasons this is not testable in test262, so we can reference this in the tc39/proposals in the place of tests or a testing plan for this proposal.

cc @nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
The reason that this proposal is not testable is that it is just allowing hosts to relax a language requirement.

There _may_ be objects that, when passed to `eval`, cause a host hook to be called and its result to be used as input to `eval`.

Even if we required hosts to expose one of such objects in test262, we would be basically testing a tautology: "to run this test, you must expose an object that when passed to `eval` it's causes the evaluation of another given string. Then, we test that when we pass this object to `eval` it evaluates the given string".

**Comment by ioannad** [comment]
Just for reference, in the above [mentioned proposals PR](https://github.com/tc39/proposals/pull/536) @lukewarlow mentioned the status of WPT tests for this proposal:

> https://wpt.fyi/results/trusted-types?label=master&label=experimental&aligned&q=eval this shows the various test files that test TT with eval.
> 
> https://github.com/web-platform-tests/wpt/blob/master/trusted-types%2Feval-csp-no-tt.html this is probably the one closest to testing the pure tc39 aspect of this.
