### ISSUE TITLE
A test for evaluating in order for Computed property name.

### ISSUE THREAD

**Issue by tuchida** [tc39/test262#423]
I want a test for evaluating in order for Computed property name.

For example:

``` js
var i = 0;
var o = {
  [i++]: i++,
  [i++]: i++,
  [i++]: i++
};
o;   // expect  `{ 0: 1, 2: 3, 4: 5 }`
```

``` js
var s = 'foo';
var p = {
  toString: function() {
    return s;
  }
};
var o = {
  [p]: (function() {
    s = 'bar';
    return 'abc';
  })(),
  [p]: 'efg'
};
o;  // expect `{ foo: "abc", bar: "efg" }`
```

The reason of expected is this spec.
http://ecma-international.org/ecma-262/6.0/#sec-object-initializer-runtime-semantics-propertydefinitionevaluation

> PropertyDefinition : PropertyName : AssignmentExpression
> 1. Let propKey be the result of evaluating PropertyName.
> 2. ReturnIfAbrupt(propKey).
> 3. Let exprValueRef be the result of evaluating AssignmentExpression.

**Comment by tuchida** [comment]
This test case also not found.

http://ecma-international.org/ecma-262/6.0/#sec-__proto__-property-names-in-object-initializers
> NOTE The List returned by PropertyNameList does not include string literal property names defined as using a ComputedPropertyName.

```js
var o = {
  ['__proto__']: { abc: 123 }
};
o.abc;  // expect undefined
```

**Comment by leobalter** [comment]
I need to search the tests, but if I'm not wrong, @ljharb wrote some tests to assert this order in 2016.

**Comment by ljharb** [comment]
https://github.com/tc39/test262/pulls?utf8=✓&q=is%3Apr%20author%3Aljharb leads me to https://github.com/tc39/test262/pull/453/files#diff-deacf7a445e66451128ca71123d32078R48 - is that what you mean?

**Comment by leobalter** [comment]
_I forgot to press the comment button._

---

Ok, it was @michaelficarra who [wrote the tests](https://github.com/tc39/test262/pull/739) for the order.

We don't have tests for the `['__proto__']` variation in the example above, using a _ComputedPropertyName_.

It's interesting how it's acting different in Chrome: 

```js
var a = {
  __proto__: { abc: 123 }
};
var b = {
  ['__proto__']: { abc: 123 }
};
a.abc; // 123
b.abc; // undefined
```

I'll write the tests based in the current `test/annexB/language/expressions/object/__proto__-value*` files we already have.

**Comment by leobalter** [comment]
I need to do this in a new issue so I can keep track of it. The initial topic is indeed covered.

**Comment by leobalter** [comment]
#904
