### ISSUE TITLE
Yield expression as initializer in generator parameter

### ISSUE THREAD

**Issue by michaelficarra** [tc39/test262#426]
[This test](https://github.com/tc39/test262/blob/6137f75e39f60eca0f0fbafa4bdc4ccd6915fd11/test/language/expressions/object/method-definition/generator-param-init-yield.js) claims to cause a SyntaxError. However, the spec explicitly sets to true the Yield flag of the *StrictFormalParameters* of a *GeneratorMethod*, which is passed all the way through to *Initializer* and then to *AssignmentExpression*, so that `yield` should parse as a *YieldExpression*.

Were the Yield flag not set, it would parse as an *IdentifierExpression*, not cause a SytaxError, as in [this test](https://github.com/tc39/test262/blob/master/test/language/expressions/object/method-definition/name-param-init-yield.js).

**Comment by bakkot** [comment]
Ah, this is an Early Error per 14.4.1.

**Comment by michaelficarra** [comment]
Okay, this confusion will be cleared up when we add phase information to the test cases.
