### ISSUE TITLE
language/identifiers/val-<keyword>-via-escape-hex* tests

### ISSUE THREAD

**Issue by woess** [tc39/test262#428]
I believe these tests are invalid. To quote the [spec](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-reserved-words):

11.6.2 Reserved Words

A reserved word is an IdentifierName that cannot be used as an Identifier.

NOTE The ReservedWord definitions are specified as literal sequences of specific SourceCharacter elements. **A code point in a ReservedWord cannot be expressed by a \ UnicodeEscapeSequence.**

**Comment by anba** [comment]
The note only points out that it's not possible to use escape sequences in reserved words, contrary to for example Java. But notes are not normative, the relevant specification section is actually [12.1.1 Static Semantics: Early Errors](http://ecma-international.org/ecma-262/6.0/#sec-identifiers-static-semantics-early-errors):
> - It is a Syntax Error if StringValue of IdentifierName is the same String value as the StringValue of any ReservedWord except for yield.

**Comment by woess** [comment]
Indeed. I stand corrected. Thanks for the clarification!
