### ISSUE TITLE
Writing to const variables is only a TypeError in strict mode

### ISSUE THREAD

**Issue by bakkot** [tc39/test262#429]
See the following tests:

https://github.com/tc39/test262/blob/master/test/language/statements/const/syntax/const-invalid-assignment-next-expression-for.js
https://github.com/tc39/test262/blob/master/test/language/statements/const/syntax/const-invalid-assignment-statement-body-for-in.js
https://github.com/tc39/test262/blob/master/test/language/statements/const/syntax/const-invalid-assignment-statement-body-for-of.js

Per [the ES2015 spec](http://www.ecma-international.org/ecma-262/6.0/#sec-for-statement-runtime-semantics-labelledevaluation), `const` variables are created with `CreateImmutableBinding`. Writes to immutable bindings silently [fail outside of strict mode](http://www.ecma-international.org/ecma-262/6.0/#sec-declarative-environment-records-setmutablebinding-n-v-s).

Working on PR which will fix these tests and also test the non-strict behavior.

**Comment by bakkot** [comment]
Nevermind; I [misread the spec](https://github.com/tc39/test262/pull/430#issuecomment-139423863). Thanks @ianwjhalliday.

Though I do observe that there don't seem to be any tests that *function expressions names*, which are also immutable, have this behavior. I.e.,

```js
(function x(){"use strict"; x = 1;}()); // TypeError
(function x(){x = 1; return x !== 1;}()); // write fails silently; function returns true
```

**Comment by ianwjhalliday** [comment]
You're welcome :)

I noticed that too and was surprised. Didn't know that was supposed to be the behavior.

@bterlson is that intended?

@bakkot seems like a good thing to add coverage for, in addition to eliminating the infinite loop issue.

Reviewing the spec here also has me confused about const in a for(;;) loop.  It looks like you can use const to declare the loop variable, but unlike let where you get a new copy each iteration, you get the only the one immutable binding and assignment to it anywhere would throw, including in the increment expression.  @bterlson Why wouldn't it just be like let and constant within the body of the loop?

**Comment by bterlson** [comment]
The case of assigning to a function identifier seems intentional. I would guess it's something we can't break for web compat reasons?

I'm not sure I understand the last question. I think const is like const in the body of the loop... for(const x = 0; x < 1; x++) { } throws the same error as for(;;) { const x = 0; x++; } doesn't it?

**Comment by allenwb** [comment]
@bterlson Back in the ES3 spec, the function identifier was specified as a DontDelete, ReadOnly property on a new scope object.  ES5&6 carries that semantics forward (for the obvious compatibility reasons) but expressed using lexical environments and with the addition of non-silent strict mode errors.

**Comment by ianwjhalliday** [comment]
@bterlson yes, the appears to say that const in the for loop behaves as you describe.  I just reasoned to myself why that is reasonable.
