### ISSUE TITLE
Bugs in tests of Error.isError proposal

### ISSUE THREAD

**Issue by iamstolis** [tc39/test262#4304]
Some tests of `Error.isError` proposal contain bugs:

* `built-ins/Error/isError/bigints.js` uses `new BigInt(0)` instead of `BigInt(0)` (the former does not produce bigint but throws `TypeError`).
* `built-ins/Error/isError/symbols.js` uses `new Symbol()` instead of `Symbol()` (the former does not produce symbol but throws `TypeError`).
* `built-ins/Error/isError/error-subclass.js`, `built-ins/Error/isError/errors-other-realm.js` and `built-ins/Error/isError/errors.js` invoke `AggregateError` constructor with no arguments. This results in `TypeError` (`undefined` is not iterable). It should pass `[]` instead of `undefined` to this constructor.

**Comment by ljharb** [comment]
Thanks, good catches.

**Comment by iamstolis** [comment]
#4308 fixes just 3 tests out of 5 that I reported here. `built-ins/Error/isError/errors-other-realm.js` and `built-ins/Error/isError/errors.js` use `new AggregateError()` still.
