### ISSUE TITLE
Checked binary in octal test.

### ISSUE THREAD

**Issue by tuchida** [tc39/test262#433]
https://github.com/tc39/test262/blob/0d9733e93be9e6783f56a3fd4163a4ca083b159c/test/language/literals/numeric/octal-invalid-truncated.js

This is a test case of octal numeric literal. But the test has been written binary numeric literal `0b`.

**Comment by goyakin** [comment]
Thanks @tuchida. I've pushed 26e6fd7c1779a63913cc7720cbc6c87b3b7b3285 to fix this.
