### ISSUE TITLE
Incorrect `monthCode` operations in `Temporal/PlainMonthDay/from/order-of-operations.js`

### ISSUE THREAD

**Issue by trflynn89** [tc39/test262#4331]
The test currently expects `toString` to be invoked on `monthCode`:
https://github.com/tc39/test262/blob/ea11e0e78739b2be9fd2f49787955b9c2bf54bcc/test/built-ins/Temporal/PlainMonthDay/from/order-of-operations.js#L27-L28

However, in [PrepareCalendarFields](https://tc39.es/proposal-temporal/#sec-temporal-preparecalendarfields), we invoke `TO-MONTH-CODE` on the retrieved `monthCode`:
```
vii. Else if Conversion is to-month-code, then
    1. Set value to ? ToMonthCode(value).
```

Where [ToMonthCode](https://tc39.es/proposal-temporal/#sec-temporal-tomonthcode) only performs a `ToPrimitive` operation on the month code:
```
1. Let monthCode be ? ToPrimitive(argument, string).
```

So it seems the test should be expecting `fields.monthCode.valueOf` instead. Is that right?

**Comment by ptomato** [comment]
I don't see that in my reading of the spec — I believe we go to [OrdinaryToPrimitive](https://tc39.es/ecma262/#sec-ordinarytoprimitive) where we call `valueOf` or `toString` first depending on the hint value passed to ToPrimitive. With a hint of `~string~`, we should expect `toString` to be invoked.

**Comment by trflynn89** [comment]
Ah 🤦 I misinterpreted how `TemporalHelpers.propertyBagObserver` works - I thought we were entering `ToPrimitive` with a string type, but the `monthCode` string is wrapped in an Object.

Sorry for the noise!
