### ISSUE TITLE
Correctness of built-ins/RegExp/call_with_regexp_match_falsy

### ISSUE THREAD

**Issue by littledan** [tc39/test262#436]
The test is as follows:

```js
var regExpObj = /(?:)/;
regExpObj[Symbol.match] = false;

assert.notSameValue(RegExp(regExpObj), regExpObj, "RegExp returns new object");
```

While I could see setting regExpObj.constructor to something else causing RegExp() to return a new object, I don't see how modifying Symbol.match would change anything. The spec fragment which is mentioned seems to be about the constructor. Is this test correct?

**Comment by anba** [comment]
When `@@match` is changed to falsy value (except for undefined), the [IsRegExp](http://tc39.github.io/ecma262/#sec-isregexp) abstract operation returns false (step 4). The test in [RegExp( pattern, flags )](http://tc39.github.io/ecma262/#sec-regexp-pattern-flags) step 4.a will now fail (`patternIsRegExp` is false) and a new RegExp object gets constructed.
