### ISSUE TITLE
Outdated tests in built-ins/RegExp/prototype/

### ISSUE THREAD

**Issue by yangguo-chromium** [tc39/test262#437]
S15.10.7.2_A8 and S15.10.7.2_A10 require:
__re = RegExp.prototype; __re.hasOwnProperty('global") === true

S15.10.7.1_A8 and S15.10.7.1_A10 require:
__re = RegExp.prototype; __re.hasOwnProperty('source") === true

S15.10.7.4_A8 and S15.10.7.4_A10 require:
__re = RegExp.prototype; __re.hasOwnProperty('ignoreCase') === true

S15.10.7.4_A8 and S15.10.7.4_A10 require:
__re = RegExp.prototype; __re.hasOwnProperty('multiline') === true

These tests are no longer valid due to 21.2.5: "The RegExp prototype object is an ordinary object. It is not a RegExp instance and does not have a [[RegExpMatcher]] internal slot or any of the other internal slots of RegExp instance objects."

@littledan

**Comment by anba** [comment]
The individual flags are accessor properties on `RegExp.prototype` in ES2015, e.g. [RegExp.prototype.global](http://tc39.github.io/ecma262/#sec-get-regexp.prototype.global).

**Comment by littledan** [comment]
I agree with @anba's analysis.
