### ISSUE TITLE
Missing test early error when UnicodeEscapeSequences with Keyword SV

### ISSUE THREAD

**Issue by caitp** [tc39/test262#439]
There are many tests in the tree asserting that Identifiers with the same SV as a Keyword are a SyntaxError --- but there are apparently no tests asserting that the following should be a SyntaxError:

``` js
f\u0075nction myFunc() {}

sw\u0069tch (value) { }

try { throw "boo"; } c\u0061tch (e) { }

// ... etc ...
```

Otherwise, it may be tempting to just tokenize escaped reserved words as keywords, because doing that currently passes all tests (it is obvious from the spec text that it's not allowed, but it is simpler <_<)

**Comment by rwaldron** [comment]
Coverage: https://github.com/tc39/test262/tree/master/src/identifier-names
