### ISSUE TITLE
Improve coverage for SIMD.js tests

### ISSUE THREAD

**Issue by dtig** [tc39/test262#441]
I'm porting test content in the ecmascript_simd repository to the test262 harness. Some tests do not have a strict one to one correspondence with specification section numbers and test multiple sub sections at once to reduce the number of loops and code duplication. I'm not sure on exactly what the trade off on code duplication/efficiency vs ease of testing is. Alternate suggestions on how these tests should be organized are welcome.

**Comment by leobalter** [comment]
Changing the title to reflect our current tests

**Comment by leobalter** [comment]
we have tests already merged for SIMD from the ecmascript_simd on `test/built-ins/Simd/*`. Let's reopen if necessary.
