### ISSUE TITLE
[Website] Link to Run page

### ISSUE THREAD

**Issue by hueitan** [tc39/test262#449]
Currently we cannot have the link to Run page directly.

Is it possible to make a link to Run page?

For example: 
http://test262.ecmascript.org/#run to run page
http://test262.ecmascript.org/#development to development page

![screen shot 2015-12-03 at 3 46 17 pm](https://cloud.githubusercontent.com/assets/2560096/11554605/7850044c-99d4-11e5-9723-c93c903f0d2c.png)

**Comment by leobalter** [comment]
this is a wontfix. We need to recreate the website.
