### ISSUE TITLE
Untested language features (found during my work with LambdaJS/S5)

### ISSUE THREAD

**Issue by tilk** [tc39/test262#454]
I have found several bugs in S5 (https://github.com/brownplt/LambdaS5), which is claimed to be a tested semantics for ES5. The list of bugs can be seen below:

https://github.com/tilk/LambdaCert/wiki/Issues-with-LambdaS5

Some of these bugs were actually detected by test262 tests, but some were not. I made a fork of test262 and started writing new testcases for relevant language features:

https://github.com/tilk/test262

I'm looking for feedback and help with possible inclusion of those new tests into test262.

**Comment by leobalter** [comment]
@tilk it is way easier to compare and review if you file more specific issues and even PRs for the work you've done on your fork. That might be the way to go for you to achieve the expected feedback and help.

You may want to start by splitting the issues [you documented](https://github.com/tilk/LambdaCert/wiki/Issues-with-LambdaS5) and filing a issue for each one with a reference for the files on this project, or a spec topic. 

For the commits you've made on your fork, it's good if open a PR here. You can choose between opening a PR for each of them (better for a more specific feedback) or a single PR for all of them. You might need to have them on a different branch for a better workflow.

**Comment by leobalter** [comment]
I'm game if you want to follow up with specific issues and/or PRs. Thanks!
