### ISSUE TITLE
S15.4.4.10_A3_T1.js and S15.4.4.10_A3_T2.js hang SpiderMonkey for a long time

### ISSUE THREAD

**Issue by evilpie** [tc39/test262#458]
We don't yet use ToLength instead of ToUint32 in Array#slice. So we end up calling the first `$ERROR`. That contains `... Actual:'+arr`, which is going to stringify that massive array. This is really slow for us. You could totally keep this test and just remove the `+arr` part.

**Comment by rwaldron** [comment]
You're referring to just this line, correct: https://github.com/tc39/test262/blob/master/test/built-ins/Array/prototype/slice/S15.4.4.10_A3_T2.js#L18 ?

**Comment by evilpie** [comment]
Yes.

**Comment by rwaldron** [comment]
Thanks—you're right, that's totally pointless.

**Comment by rwaldron** [comment]
cc @leobalter
