### ISSUE TITLE
U+180E is no longer in Zs; tests should be updated to reflect that

### ISSUE THREAD

**Issue by littledan** [tc39/test262#459]
A couple tests still check that we strip off U+180E as whitespace in parseInt and parseFloat: https://github.com/tc39/test262/search?utf8=%E2%9C%93&q=180E 
https://github.com/tc39/test262/blob/26e6fd7c1779a63913cc7720cbc6c87b3b7b3285/test/built-ins/parseFloat/S15.1.2.3_A2_T10.js
https://github.com/tc39/test262/blob/26e6fd7c1779a63913cc7720cbc6c87b3b7b3285/test/built-ins/parseInt/S15.1.2.2_A2_T10.js

However, it was taken out of Zs in Unicode 6.3.0. It should not be expected to be stripped off--in fact, it'd make sense to verify that this _isn't_ stripped off. A quick explanation, including what happened to browsers as a result of this test262 bug, can be found here:
http://www.hashseed.net/2014/08/in-ecma-262-5.html?m=1

**Comment by anba** [comment]
> It should not be expected to be stripped off

Agreed.

> in fact, it'd make sense to verify that this isn't stripped off.

We can't do this yet, ECMAScript first needs to be updated to require a newer Unicode version (currently [Unicode 5.1 or later](http://tc39.github.io/ecma262/#sec-conformance)).

**Comment by littledan** [comment]
I think it'd be a reasonable policy for each annual ES spec to require the most recent Unicode version at that time.

**Comment by littledan** [comment]
In the January 2016 meeting, TC39 decided to require Unicode 8.0.0 for ES2016, so it would be correct to add such a test.

**Comment by anba** [comment]
:tada: 

The following tests need to be updated for Unicode 8:

- test/built-ins/Number/S9.3.1_A2.js
- test/built-ins/Number/S9.3.1_A3_T1.js
- test/built-ins/Number/S9.3.1_A3_T2.js
- test/built-ins/parseFloat/S15.1.2.3_A2_T10.js
- test/built-ins/parseInt/S15.1.2.2_A2_T10.js
- test/built-ins/RegExp/S15.10.2.12_A1_T1.js
- test/built-ins/RegExp/S15.10.2.12_A2_T1.js
- test/built-ins/String/prototype/trim/15.5.4.20-3-2.js
- test/built-ins/String/prototype/trim/15.5.4.20-3-3.js
- test/built-ins/String/prototype/trim/15.5.4.20-3-4.js
- test/built-ins/String/prototype/trim/15.5.4.20-3-5.js
- test/built-ins/String/prototype/trim/15.5.4.20-3-6.js

**Comment by leobalter** [comment]
This should be fixed by 3a5a09eba2adb6a8c24cf6e603aefe9bfa8d75b9
