### ISSUE TITLE
Testing Runtime Internals

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#466]
There are a few aspects of the ECMAScript 2015 specification that concern implementation details which are not directly observable from the JavaScript runtime:
- Tail call optimization
- Template string caching

As far as I know, the only reliable way to test these things is through putting the runtime under severe stress and asserting that it does not crash (in the case of tail call optimization) or does crash (in the case of template string cachine). For instance, to assert tail call optimization, we might write:

``` js
function f(x) {
  if (x === 0) {
    return 0;
  }
  return f(x - 1);
}
f(9007199254740991);
```

Only runtimes which implemented proper tail calls would execute this code to completion without crashing.

Test262 already has facilities to test crashes (implemented to support negative syntax tests), but this reflects a fundamentally different approach to testing. I believe there are two considerations that need to be addressed before we can test these features.
### 1: Satisfiability

As written, tests like the above would be take an extremely long time to complete. I've selected the largest possible integer value as the number of iterations, although a smaller value would do.

The chosen value is completely arbitrary. We basically need to use a value that is "high enough" to prove that the same stack frame is being re-used but not so high as to make the test prohibitively slow. This value could be dependent on the runtime, since some systems will have less available memory than others.

The same concerns exist for testing template caching, although the bottleneck there is the heap size.

Test262 already exposes functionality that may be useful here. Many tests reference a global function named `$DONE`. [The test runner is expected to modify its expectations in the presence of such a reference](https://github.com/tc39/test262/blob/1c1a75eead413ab5152e825d3c551908667e405f/tools/packaging/test262.py#L215-L221) because these files are testing asynchronous behavior. In addition, [the behavior of this function is defined at test execution time](https://github.com/tc39/test262/blob/1c1a75eead413ab5152e825d3c551908667e405f/tools/packaging/test262.py#L301)--implementors are expected to provide the name of the host-specific printing function.

We could introduce a similar pattern for these stress tests. Global values like `$MAX_HEAP` and `$MAX_STACK` could be defined in the same way, allowing implementors to select appropriate values for their runtime.

``` js
function f(x) {
  if (x === 0) {
    return 0;
  }
  return f(x - 1);
}
f($MAX_STACK);
```

Even this approach is a little imprecise: the values cannot describe specific sizes of memory because there are no standard values for the size of JavaScript objects/stack frames. I don't think that level of precision is necessary, though. So long as implementors can specify an appropriate order of magnitude, then we can avoid excessive test execution times.
### 2: Organization

We should almost certainly create a distinctive label for these tests. Failing to do so would probably annoy implementors because the new tests could have significant impact on test run time.

I have three ideas on this:
- A new [frontmatter
  flag](https://github.com/tc39/test262/blob/1c1a75eead413ab5152e825d3c551908667e405f/CONTRIBUTING.md#flags),
  e.g. `stress`
- A new top-level directory, e.g. `test/stress/`
- A separate project/repository altogether

Any one of these would give implementors enough control to avoid running these expensive tests as necessary. I think choosing which one will come down to a subjective decision on how distinct this class of test really is.

---

If we can come to some consensus on these two issues, then I would be excited to write the tests!

**Comment by jugglinmike** [comment]
@littledan We discussed this briefly earlier today. Any thoughts?

**Comment by littledan** [comment]
These approaches sound good to me. For the way V8 has its tests set up, the top-level directory would be the easiest for us, but any of the three options would be workable.

**Comment by caitp** [comment]
```js
function stackLimit(i) {
  try {
    return stackLimit(i + 1);
  } catch(e) {
    if (e instanceof RangeError) return i + 1;
    return;
  }
}
var $MAX_STACK = stackLimit(1);
assert($MAX_STACK > 0);
```

That sort of thing probably won't take too long, and the value could be cached. Was something like that considered?

**Comment by jugglinmike** [comment]
@caitp No it was not, but that's a really neat idea! I have to admit: this is
testing my understanding of these programming language internals. Inserting
that calculation into the example code I shared does *not* produce a stack
overflow in Node.js 5.3.0 (which does not implement TCO).

Depending on how gh-467 (which I admittedly only just now opened) shakes out,
Test262 may not be able to provide caching. In that world, Test262 would simply
publish static JavaScript files. Caching could be done (and Test262 could
recommend it), but it would be a concern of the consumer.

Alternatively, we could simply inject your script at the top of every file that
contains the `$MAX_STACK` identifier. I guess it depends on how many tests need
the value and how long the computation really takes.

**Comment by jugglinmike** [comment]
...although inferring `$MAX_STACK` may not be an option, after all. I can't find any documentation of that `RangeError` in ES5 or ES2015. In any other project, we could be pragmatic about that ("good enough if it works in most VMs"), but for ECMA's test suite, I don't think we can rely on non-standard behavior.

**Comment by caitp** [comment]
Inlining could eliminate the need for tco as well, it might not be a huge surprise for a trivial function called frequently

**Comment by caitp** [comment]
And of course, standardizing the RangeError is probably not out of the cards, so

**Comment by jugglinmike** [comment]
True, but I'm not sure about using an ES2016 (at best) feature to test ES2015 semantics... but maybe there's no point in interpreting "publication date" as a signal for "feature dependency"

**Comment by caitp** [comment]
if it's interoperably a RangeError (and AFAIK it is), it's probably good enough

**Comment by anba** [comment]
> if it's interoperably a RangeError (and AFAIK it is)

It's only a `RangeError` in JSC and V8. Edge throws an `Error` object, SpiderMonkey throws an `InternalError` object.

**Comment by leobalter** [comment]
following up a conversation on freenode's #tc39 about extra memory/stress tests for SharedArrayBuffer, I believe a new test262-[repo] would be a better home for these tests.

While I would like to have the coverage completeness w/ these extras, I believe this is out of the scope for the current set of tests. Moving on to new repos, as we have the parser tests, allow us to have a better distributed maintenance.
