### ISSUE TITLE
breaking changes on new spec versions

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#472]
With a new spec draft on the go, it is great to have tests for new features and changes, but it's confusing when we have a conflict with the current released specs.

As noticed on https://github.com/tc39/test262/pull/469#discussion-diff-49886819, we have tests for a breaking change from ES2015 compared to the current ES draft, which is not final neither a release candidate.

IMHO, it seems appropriate to keep all the ES2015 tests, and I believe they should remain until the next version is released, even if they become invalid on a further version.

On the same perspective, it is valuable to have tests for the changes on the draft. We're currently accepting them tagged as `es7id: pending`. Even though, it's not easy to tell what a new test replace from a previous version.

We can have tests for both ES2015 and ES2016 living together knowing some will break. As we do not have any standardized way to cross reference them, there's no easy way to tell what to filter when you want to run your tests.

My initial idea was to propose a breaking tag referencing the old id, but after maturing this idea it seems not be valuable or not good enough to target what will be replaced. On my personal thoughts, I believe the `es7id: pending` tests are in a wrong place, perhaps another branch would do better.

@jugglinmike already mentioned a similar conflict regarding legacy @ #333 which should be considered too.

I believe this requires discussion as solving it implies in a structural change for this project.

---

PS: I just saw @littledan's PR at #471 where it says the project should follow the published draft. This is different from my first perspective when I was strictly following the ES2015 version.

Now I'm way more conflicted on maintaining tests for both versions (last release vs last draft) on breaking changes. I believe both are valuable, but I tend to say the release is more important.

I wonder if the breaking tag (or any other solution) can bring some

**Comment by domenic** [comment]
I don't think there's any value in maintaining old versions. There can be a tag that's "test262 as of the Ecma ratification date" (sometime last year), but that shouldn't impact ongoing maintenance. The purposes of test262 is to help implementations, which do not care about old drafts.

**Comment by domenic** [comment]
Furthermore I believe there was agreement on this (i.e. on test262 following master, and indeed also accepting stage 3 proposals not even in master yet) a few TC39 meetings ago.

**Comment by leobalter** [comment]
> Furthermore I believe there was agreement on this (i.e. on test262 following master, and indeed also accepting stage 3 proposals not even in master yet) a few TC39 meetings ago.

My bad, I wasn't of this yet. I'll try to fetch some of the last meeting notes and check everything regarding test262.

> I don't think there's any value in maintaining old versions.

This is exactly about a perception for what means old version where a published draft becomes valuable enough to replace the released standards.

**Comment by bterlson** [comment]
See [here](https://github.com/rwaldron/tc39-notes/blob/dd8bb263aef908509c91f58e4912482a75c1c74d/es7/2015-09/sept-24.md#8-test262-update). Test262 is now living. I think we should just check in current tests and delete any non-valid tests. Seen another way, Test262 always targets the next version of the spec.

**Comment by littledan** [comment]
I agree with @domenic . We're not working on an errata list/update for ECMAScript 2015; we're just working on ES2016. The editor is responsible for being appropriately conservative with what's brought into the spec. ES2015 includes bugs, both in terms of web-incompatible semantics that we've decided to revert, and in unreasonable behavior that we're also making improvements to. Particular released version numbers like ES2015 might serve best as historical documents as the current draft spec and test262 push forward.

Rather than IDs which point to specific spec sections, I think it'd be much more useful to have ids that are the anchors within the document. These are much more likely to be consistent across releases. You could call these esids.

**Comment by leobalter** [comment]
Thank you, @bterlson!

> @littledan: I think it'd be much more useful to have ids that are the anchors within the document

This is a very interesting idea. I'll do some research and check for possible ways to make the reference for the next versions.
