### ISSUE TITLE
Definition for frontmatter id tags

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#477]
As mentioned at https://github.com/tc39/test262/issues/472#issuecomment-173006824:

> @littledan: Rather than IDs which point to specific spec sections, I think it'd be much more useful to have ids that are the anchors within the document. These are much more likely to be consistent across releases. You could call these esids.

Based on this, and as it's easy to locate the section ids on tc39/ecma262 on each of the `emu-clause` tags, which are expected to be unique, I believe we can use the respective hash id for the Frontmatter's `id` and further versions:

```yaml
id: sec-completion-record-specification-type
```

this value can be converted to links that could be found anywhere:

- https://tc39.github.io/ecma262/#sec-completion-record-specification-type
- http://www.ecma-international.org/ecma-262/6.0/index.html#sec-constructor-properties-of-the-global-object
- mylocalcopy#sec-constructor-properties-of-the-global-object

This reference works good and it's still compatible with the previous formats, as won't conflict with the recently adopted `es7id: pending` value, which can be easily replaced by `id: pending` and it's still useful for anything on Stage 3 and it's not on the draft yet.

@goyakin, do you like this idea?

**Comment by domenic** [comment]
I think it should just be "id"

**Comment by leobalter** [comment]
Yes, it makes sense. I'll update the title and example.

**Comment by goyakin** [comment]
I think this is a good idea. The [test harness](https://github.com/bterlson/test262-harness/) doesn't use the current `es6id`, so we can start using the new one without any issues. I don't know if there's any other tool depending on `es6id` though.

I also agree with @littledan that this way we wouldn't have to keep up with changes in section numbers.

**Comment by littledan** [comment]
+1

**Comment by jugglinmike** [comment]
I'm a little late to the party, but I'd like to know more about the decision to use the name `id` instead of `esid` as suggested by @littledan. The latter is a few more characters, but I think it's preferable. Many tests will share the same value, and that contradicts commonly-held assumptions about "IDs". `esid` (or even `specid`) makes it clear that this value is reference to an identifier of some other document (and also gives a hint as to *which* document it refers).

There wasn't any discussion about why the change was made, so I thought I'd ask here.

**Comment by littledan** [comment]
Any of those names sounds good to me.

**Comment by leobalter** [comment]
I would like to reopen this issue.

After an internal - and informal - conversation with @jugglinmike and @rwaldron, It's been clear how `id` is giving a false impression it should hold an unique value for each test file. The other arguments to avoid `id` are well represented on [Mike's argument](https://github.com/tc39/test262/issues/477#issuecomment-178131536).

It's still early to fix this up.

**Comment by goyakin** [comment]
@leobalter I'm OK with `esid`.
