### ISSUE TITLE
Invalid TypedArray test

### ISSUE THREAD

**Issue by littledan** [tc39/test262#521]
built-ins/TypedArray/from/mapfn-is-not-callable.js at the end has this:

```js
assert.throws(TypeError, function() {
  TypedArray.from(arrayLike, Int8Array);
}, "mapfn is a TypedArray constructor (not callable)");

assert.sameValue(
  getIterator, 0,
  "IsCallable(mapfn) check occurs before getting source[@@iterator]"
);
```

Actually, class constructors are callable; they just throw when called. https://tc39.github.io/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist

**Comment by anba** [comment]
#518 fixes this issue.

**Comment by leobalter** [comment]
I removed it from test/built-ins/TypedArrays but missed this one.

**Comment by littledan** [comment]
Seems like this is fixed.
