### ISSUE TITLE
test262 still contains invalid tests for precision of Math operations

### ISSUE THREAD

**Issue by littledan** [tc39/test262#529]
built-ins/Math/cos/S15.8.2.7_A7
built-ins/Math/sin/S15.8.2.16_A7
built-ins/Math/tan/S15.8.2.18_A7
built-ins/Math/exp/S15.8.2.8_A6

We discussed these tests at the July 2015 TC39 meeting. There was agreement that they are invalid for the current spec text, but @sunfishcode might champion spec changes here. Until then, though, all that's valid to test for are the exact boundary conditions listed in the specification.

**Comment by littledan** [comment]
@goyakin @jugglinmike What do you think about these tests?

**Comment by jugglinmike** [comment]
I agree that those tests ought to be removed. I'm happy to file a pull request
that does this, but first: there is another set of suspicious-looking tests for
the trig functions:

- [test/built-ins/Math/cos/S15.8.2.7_A6.js](https://github.com/tc39/test262/blob/007d3b1eb76ccc7760f641d8e956e5da838b586f/test/built-ins/Math/cos/S15.8.2.7_A6.js)
- [test/built-ins/Math/sin/S15.8.2.16_A6.js](https://github.com/tc39/test262/blob/007d3b1eb76ccc7760f641d8e956e5da838b586f/test/built-ins/Math/sin/S15.8.2.16_A6.js)
- [test/built-ins/Math/tan/S15.8.2.18_A6.js](https://github.com/tc39/test262/blob/007d3b1eb76ccc7760f641d8e956e5da838b586f/test/built-ins/Math/tan/S15.8.2.18_A6.js)

It seems to me that "an implementation-dependent approximation" may not
necessarily be periodic to the (seemingly-arbitrary) precision asserted by
those tests.

Should we remove those files, as well?

**Comment by littledan** [comment]
Yes, these seem invalid to me too (v8 just happens to pass them :)

**Comment by jugglinmike** [comment]
Yesterday I added still more tests to the chopping block in gh-540. We are very limited in what we can assert according to the current spec text, but I would be interested in contributing to an effort to improve the specification in this regard. @sunfishcode do you have any interest in work like that?

**Comment by jugglinmike** [comment]
Resolved via gh-540.

@sunfishcode I'd still be interested in working with you on the spec here--even if you could spare a little time to set me off on the right foot!

**Comment by sunfishcode** [comment]
@jugglinmike I unfortunately don't have time to do any spec work for this myself right now.

When this topic was discussed at a TC39 meeting a while ago, a suggestion by someone in the room which many others in the room agreed with was that this could be approached by considering all the popular JS implementations, across popular OS/hardware platforms (some JS engines have numerical results that differ depending on which platform they're on), and then drafting spec text requiring that all implementations be within the greatest error ranges found, for each function. That would be a significant improvement over the status quo, as it would establish a minimum guarantee that applications could then depend on.

**Comment by jugglinmike** [comment]
@sunfishcode Thank you, that is exactly the context I needed to begin :)
