### ISSUE TITLE
Possible bug in toISOString/15.9.5.43-0-13.js which checks for an overflow in Date.

### ISSUE THREAD

**Issue by mythrialle** [tc39/test262#535]
The test built-ins/Date/prototype/toISOString/15.9.5.43-0-13.js checks if the RangeError is thrown when a new Date object is created with a date outside the supported range. This test fails in UTC time zone. 

I think it is because we do not add an additional 1 hour offset to account for the daylight saving time as we do with other time zones. For example, In London currently we are in UTC time zone but the created date would be in BST time zone. Hence we loose one hour and does not cause an overflow. I think there special handling is not required based on timezone. 

I created a pull request #534  to fix it. Please take a look and let me know if it is correct.  

Thanks,
Mythri.

**Comment by leobalter** [comment]
The PR is already merged. Closing.
