### ISSUE TITLE
Refactor sth.js, add unit tests, separate logic from presentation 

### ISSUE THREAD

**Issue by smikes** [tc39/test262#54]
Following on from:  (Clean-up 'simple test harness')[https://bugs.ecmascript.org/show_bug.cgi?id=41]

The simple test harness code in `sth.js` and `helper.js` is reasonably clean but lacks unit tests and mixes logic with presentation.

I propose to split the code into five separate files -- one each for the four main classes (BrowserRunner, TestLoader, Controller, Presenter) and one for the `main` function that sets everything up (anonymous function on sth.js line 682).  I would then add unit tests for each of the classes, refactoring when possible.

I would modify `packager.py` so that it concatenates these files together into a single file (e.g., `test-harness.js`) and make the generated website .html files depend on this new file.  

Ultimately a modern build system might be used to concatenate, minify, gzip, etc. etc. all the frontend files.  But for the moment, just refactoring and adding tests for existing behavior is enough.

I will start work on this after the #51 PR is disposed of.

**Comment by leobalter** [comment]
I'm afraid this can't be fixed anymore.
