### ISSUE TITLE
Number.prototype.toPrecision

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#549]
Test262 only defines surface tests for this method.

- ES5: https://es5.github.io/#x15.7.4.7
- ES6: http://www.ecma-international.org/ecma-262/6.0/#sec-number.prototype.toprecision
- ES7: https://tc39.github.io/ecma262/2016/#sec-number.prototype.toprecision

**Comment by leobalter** [comment]
It's fixed!
