### ISSUE TITLE
Number.prototype.toExponential

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#550]
Test262 only defines surface tests for this method.
- ES5: https://es5.github.io/#x15.7.4.6
- ES6: http://www.ecma-international.org/ecma-262/6.0/#sec-number.prototype.toexponential
- ES7: https://tc39.github.io/ecma262/2016/#sec-number.prototype.toexponential

**Comment by Yaffle** [comment]
@jugglinmike  wasn't this resolved by in https://github.com/tc39/test262/pull/664 ?

**Comment by leobalter** [comment]
@Yaffle yes, thanks!
