### ISSUE TITLE
TypedArrays

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#551]
There is a lot of spec text describing the behavior of Typed Arrays, e.g. the generic constructors, static methods, prototype methods, specific subclasses, and the Integer Indexed exotic object.

@leobalter has made great strides on coverage here, and he'll be continuing his efforts for the next few weeks. Please speak with Leo if you are interested in helping out!

**Comment by leobalter** [comment]
We already got a fair coverage for TypedArrays.
