### ISSUE TITLE
Module semantics

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#552]
We've tested about as much as we can test for module code that doesn't require module resolution--e.g. parsing errors and early errors. Testing module semantics will require consensus on module loading behavior (with a strong preference for simplicity). I've started a discussion along these lines in gh-519.

I have begun authoring tests bases on the feedback received so far. If anyone is interested in helping out with testing module semantics, please speak with me!

**Comment by michaelficarra** [comment]
Wow, what a coincidence; I was just going to open an issue for testing module-related code myself. In my case, I do not need module resolution/loading. I am trying to make assertions about a function declaration defined using the `export default function () {}` (unnamed) form. I don't care that it gets exported, I just want a handle to that value. I'm doing this because [the `Function.prototype.toString` revision proposal](https://github.com/tc39/Function-prototype-toString-revision) defines steps for each separate syntactic form and I want to make sure they are all covered. For now, I guess I should just hold off.

**Comment by jugglinmike** [comment]
@michaelficarra I appreciate your patience; I'll try not to keep you waiting to long.

In the mean time, I know there's value in writing tests even just for personal use. I don't know if you need to explicitly avoid loading, but if not, this might be enough:

```js
export default function () {};
import f from './self.js';
```

**Comment by jugglinmike** [comment]
I have finished writing a set of tests for module semantics. As one might
expect, this required quite a few files. In order to facilitate review, I am
submitting these as four distinct pull requests:

- gh-560 for parsing module code
- gh-561 for detecting early errors in module code
- gh-562 for instantiating declarations/bindings in module code (the bulk of
  the tests)
- gh-563 for evaluating module code

My hope is that this separation will help keep conversation well-structured and
also provide logical points for others to start/end review sessions.

(Generally, I would prefer to submit this kind of work incrementally, and I
apologize for the burden of such a large submission. Writing these tests
involved *many* iterations over the entire set--this would have resulted in a
lot of noise if it were spread out over the course of incremental submissions.)

Because the module namespace object is relatively standalone feature, I plan to
make testing that a separate effort.

**Comment by leobalter** [comment]
@michaelficarra would you link to check the mentioned PRs? They look good for me, but it would help to have someone else on the review.

**Comment by goyakin** [comment]
I plan on merging the PRs mentioned above + #565 tomorrow. Please speak up if you think otherwise.

I think it's better to get them into the `master` branch so that they can be used. We can update/refactor them later if there is a need.

**Comment by goyakin** [comment]
I just merged the aforementioned PRs.

**Comment by jugglinmike** [comment]
Excellent; thank you, @goyakin!

**Comment by leobalter** [comment]
With the last PR w/ documentation for modules I believe this is solved for now.
