### ISSUE TITLE
Reducing reliance on fnGlobalObject.js

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#568]
While reviewing [gh-567: "Add `System.global` tests"](https://github.com/tc39/test262/pull/567), I was about to suggest the use of [the `fnGlobalObject` helper function](https://github.com/tc39/test262/blob/755b0d61171a7b16fd81979bc8d6f24bb832ecc6/harness/fnGlobalObject.js) instead of a simple `this` reference to test the property value.

I'm not sure this is necessary, though, and really, I'm not sure `fnGlobalObject` is necessary in *any* case that Test262 currently uses it.

Test runners are required to execute test contents in the global scope--anything else would invalidate certain tests. The `this` keyword has long (always?) been specified as returning the global object when evaluated in global code.

If this is true, I would be in favor of simplifying the ~200 tests that include `fnGlobalObject.js` to reference `this` directly, and (more importantly) reducing the domain-specific knowledge required to author new tests.

I'd like to keep the helper around, though, because it will still be necessary for accessing the global from module code (see [gh-562: "Module semantics: declaration instantiation"](https://github.com/tc39/test262/pull/562)), and it seems possible that security restrictions (e.g. CSP in web browsers) may lead some consumers to look for a mechanism to override that function.

If there is some detail that I'm overlooking, then I'm happy to leave the usage as-is (although I may want to document the use case(s) as an in-line comment in `fnGlobalObject.js` itself).

From ES5's [11.1.1 The this Keyword](https://es5.github.io/#x11.1.1):

> The this keyword evaluates to the value of the ThisBinding of the current
> execution context.

And from [10.4.1.1 Initial Global Execution Context](https://es5.github.io/#x10.4.1.1):

> The following steps are performed to initialize a global execution context
> for ECMAScript code C:
>
> 1. Set the VariableEnvironment to the Global Environment.
> 2. Set the LexicalEnvironment to the Global Environment.
> 3. Set the ThisBinding to the global object.

**Comment by leobalter** [comment]
> If this is true, I would be in favor of simplifying the ~200 tests that include fnGlobalObject.js to reference this directly, and (more importantly) reducing the domain-specific knowledge required to author new tests.

Agreed.

> I'd like to keep the helper around, though, because it will still be necessary for accessing the global from module code (see gh-562: "Module semantics: declaration instantiation"), and it seems possible that security restrictions (e.g. CSP in web browsers) may lead some consumers to look for a mechanism to override that function.

+1 to keep the helper 

If it helps, the normative text for the global `this` changed but the value is the same:

- [ES6](https://tc39.github.io/ecma262/#sec-global-environment-records-getthisbinding)
- [current draft](https://tc39.github.io/ecma262/#sec-global-environment-records-getthisbinding)

```
8.1.1.4.11 GetThisBinding ()

1. Let envRec be the global Environment Record for which the method was invoked.
2. Return envRec.[[GlobalThisValue]]. 
```

**Comment by jugglinmike** [comment]
Resolved via gh-595
