### ISSUE TITLE
RegExp tests should avoid infinite loops

### ISSUE THREAD

**Issue by ajklein** [tc39/test262#613]
In [str-coerce-lastindex.js](../blob/master/test/built-ins/RegExp/prototype/Symbol.split/str-coerce-lastindex.js), `RegExp.prototype[Symbol.split]` is called on an object with an accessor for `lastIndex` that ignores sets and always returns `2.9`. This causes the test to loop infinitely, by my reading of [the spec](https://tc39.github.io/ecma262/#sec-regexp.prototype-@@split) (the loop starts at step 19). I would be surprised if there were other such tests, as a few other regexp tests have been seen to time out when running all of test262.

@littledan fyi

**Comment by jugglinmike** [comment]
I believe this is a valid test, but it's really difficult to see. The algorithm
is long and involved, and the variable names are not much help. I've tried to
trace the values through the steps, and I've come up with an explanation that
describes 3 iterations:

Step #     | Size | p | q | z  | e | comment
-----------|------|---|---|----|---|-------------------------------------------
14         | 4    |   |   |    |   |
15         | 4    | 0 |   |    |   |
18         | 4    | 0 | 0 |    |   |
19         | 4    | 0 | 0 |    |   | q < size; repeat
19.c       | 4    | 0 | 0 | [] |   | z is an empty array throughout, so 19.c will always be skipped and 19.d will always be taken
19.d.i     | 4    | 0 | 0 | [] | 2 |
19.d.ii    | 4    | 0 | 0 | [] | 2 |
19.d.iii   | 4    | 0 | 0 | [] | 2 | e != p; no change
19.d.iv    | 4    | 0 | 0 | [] | 2 | match "found"
19.d.iv.5  | 4    | 2 | 0 | [] | 2 |
19.d.iv.10 | 4    | 2 | 2 | [] | 2 |
19         | 4    | 2 | 2 | [] | 2 | q < size; repeat
19.d.i     | 4    | 2 | 2 | [] | 2 | setting e to same value
19.d.ii    | 4    | 2 | 2 | [] | 2 |
19.d.iii   | 4    | 2 | 3 | [] | 2 | e = p; advance q, skip iv
19         | 4    | 2 | 3 | [] | 2 | q < size; repeat
19.d.i     | 4    | 2 | 3 | [] | 2 | setting e to same value
19.d.ii    | 4    | 2 | 3 | [] | 2 |
19.d.iii   | 4    | 2 | 4 | [] | 2 | e = p; advance q; skip iv
19         | 4    | 2 | 4 | [] | 2 | q !< size; break

Does this seem right to you, @ajklein?

**Comment by ajklein** [comment]
Thank you so much for writing that up, I had the comparison at 19.d.iii wrong, and was comparing `e` to `q` (our code has much more readable names, but the fact that they don't match the spec made that harder to see).

Will fix on our end...

**Comment by ajklein** [comment]
Okay, @jugglinmike, you were so helpful that I have to ask another one. This one is in https://github.com/tc39/test262/blob/master/test/built-ins/RegExp/prototype/Symbol.match/coerce-global.js (also builtin-coerce-global.js), where a RegExp instance is given a `global` own property that returns true. This causes a much simpler infinite loop in https://tc39.github.io/ecma262/#sec-regexp.prototype-@@match (starting at step 6.e). Both v8 and jsc run afoul of this. It's possible this could also be a spec bug, but for now those tests are going to cause trouble. Please correct me if I'm wrong :)

**Comment by jugglinmike** [comment]
You are correct: those tests were invalidated in March. I'm working on a fix now; I'll report back here once I've submitted it.

**Comment by jugglinmike** [comment]
Fix and explanation now available here: https://github.com/tc39/test262/pull/614

**Comment by leobalter** [comment]
Closed w/ gh-614
