### ISSUE TITLE
Subsume tests from the WHATWG JavaScript standard

### ISSUE THREAD

**Issue by domenic** [tc39/test262#639]
The [WHATWG JavaScript standard](https://javascript.spec.whatwg.org/) has been shrinking almost to nothingness as TC39 has been standardizing de-facto behaviors that previously required a separate spec; https://github.com/whatwg/javascript/issues/29 tracks its complete obsolescence.

But, before it disappears, we should be sure to scoop up all its tests!!

Here's what I found:
- Multiline HTML comment tests: https://github.com/whatwg/javascript/issues/16 and https://mathias.html5.org/tests/javascript/comment-syntax/
- escape/unescape tests were maybe removed from test262 in the past: https://github.com/whatwg/javascript/issues/11
- Annex B string method tests: https://mathias.html5.org/tests/javascript/string/
- Array splice behavior tests: https://mathias.html5.org/tests/javascript/array/
- Date.UTC with fewer than two arguments: https://mathias.html5.org/tests/javascript/date/, assuming https://github.com/whatwg/javascript/issues/31 is correct
- Function.{arguments, caller}: https://mathias.html5.org/tests/javascript/function/
- defineGetter/defineSetter/proto: https://mathias.html5.org/tests/javascript/object/
- Regexp: https://mathias.html5.org/tests/javascript/regexp/
- Identifier tests are also available if you click on "identifiers/" at https://mathias.html5.org/tests/javascript/, but they will likely hang your browser so be careful.

**Comment by jugglinmike** [comment]
Mathias's string method tests have already been ported (indirectly, through V8's mjsunit test suite). See, for example, [this test for `String#blink`](https://github.com/tc39/test262/blob/d8f1b92cf47c3a8ba082b813ade2e3c7efc7af37/test/annexB/built-ins/String/prototype/blink/B.2.3.4.js). Tests for a number of other features listed are under review as we speak.

To anyone interested in contributing along these lines: please refer to both the "test/annexB/" directory and the project's open pull requests to avoid duplicating effort or duplicating coverage.

**Comment by rwaldron** [comment]
- Multiline HTML comment tests: https://github.com/whatwg/javascript/issues/16 and https://mathias.html5.org/tests/javascript/comment-syntax/
  - The former was closed and I don't know if it was opened elsewhere. The latter is producing a server error.. 
  - If there are any cases not covered in https://github.com/tc39/test262/tree/main/test/annexB/language/comments, then please re-open this issue and identify them. 
- escape/unescape tests were maybe removed from test262 in the past: https://github.com/whatwg/javascript/issues/11
  - If there are any cases not covered in https://github.com/tc39/test262/tree/main/test/annexB/built-ins/escape and https://github.com/tc39/test262/tree/main/test/annexB/built-ins/unescape, then please re-open this issue and identify them. 
- Annex B string method tests: https://mathias.html5.org/tests/javascript/string/
  - This link is producing a server error.
  - If there are any cases not covered in https://github.com/tc39/test262/tree/main/test/annexB/built-ins/String/prototype, then please re-open this issue and identify them. 
- Array splice behavior tests: https://mathias.html5.org/tests/javascript/array/
  - This link is producing a server error.
- Date.UTC with fewer than two arguments: https://mathias.html5.org/tests/javascript/date/, assuming https://github.com/whatwg/javascript/issues/31 is correct
  - This former is producing a server error.. 
  - The latter has no resolution.
- Function.{arguments, caller}: https://mathias.html5.org/tests/javascript/function/
  - This link is producing a server error.
- defineGetter/defineSetter/proto: https://mathias.html5.org/tests/javascript/object/
  - This link is producing a server error.
- Regexp: https://mathias.html5.org/tests/javascript/regexp/
  - This link is producing a server error.
- Identifier tests are also available if you click on "identifiers/" at https://mathias.html5.org/tests/javascript/, but they will likely hang your browser so be careful.
  - This link is producing a server error.
