### ISSUE TITLE
Bunch of tests are incompatible with DOM spec

### ISSUE THREAD

**Issue by evilpie** [tc39/test262#64]
Basically there a bunch of tests that assign to indexes on the global object. This is something that is invalid. https://bugs.ecmascript.org/show_bug.cgi?id=1453
It would be awesome if somebody could remove or modify these tests to not run in a browser environment.

**Comment by evilpie** [comment]
I came across this recently again after looking at our remaining failures in Firefox that @anba generated. If you want to have a look at https://bugzilla.mozilla.org/page.cgi?id=splinter.html&bug=977849&attachment=8816708 under "Test262 tests disabled on browser". Is anyone interested in favor of removing or somehow fixing those tests?

**Comment by leobalter** [comment]
These files definitely deserve some refactoring and a better way to flag them as web compatible.

In the meanwhile, I've set some label as we need help to prioritize and with the workforce to fix this.

**Comment by rwaldron** [comment]
The links above are in the wayback machine: https://web.archive.org/web/20141214114329/https://bugs.ecmascript.org/show_bug.cgi?id=1453

**Comment by rwaldron** [comment]
I recommend maintaining a "skip list" for tests that are incompatible with host requirements.
