### ISSUE TITLE
Are there tests against legacy magic properties that are nonconfigurable and nonwritable?

### ISSUE THREAD

**Issue by claudepache** [tc39/test262#649]
According to [6.1.7.3](https://tc39.github.io/ecma262/#sec-invariants-of-the-essential-internal-methods)

<blockquote>
     If a property P is described as a data property with Desc.[[Value]] equal to v and Desc.[[Writable]] and Desc.[[Configurable]] are both false, then the SameValue must be returned for the Desc.[[Value]] attribute of the property on all future calls to [[GetOwnProperty]] ( P ).
</blockquote>

However, as of today, many implementations define some legacy magic properties as nonconfigurable and nonwritable, but keep them changing their value over time, e.g.:
- `f.arguments` and `f.caller` for sloppy function `f` (bug observed in WebKit, V8 and Chakra);
- `RegExp.$1`, etc. (bug observed in WebKit).

Are there tests against these cases.

Suggested sample test:

``` js
function f() { return Object.getOwnPropertyDescriptor(f, 'arguments'); }

try { 
    Object.defineProperty(f, 'arguments', { writable: false, configurable: false });
}
catch (e) { }

var desc = Object.getOwnPropertyDescriptor(f, 'arguments');
if (desc && desc.configurable === false && desc.writable === false) {
    var desc2 = f();
    assert.sameValue(desc.value, desc2.value);
}
```

**Comment by jugglinmike** [comment]
Thanks for reporting; that's a very strange bug!

I think there's value in including a test for it, but it raises a question about test organization. This isn't the right place to discuss it, so I've opened gh-650 to elaborate. If you have any thoughts on the matter, please let me know!

**Comment by littledan** [comment]
It's hard to say, strictly speaking, whether these are spec violations. Is it a prohibited extension to make these objects "exotic" with respect to those properties?

**Comment by claudepache** [comment]
@littledan Objects may behave as exotically as they want, as long as they do not violate the essential invariants given in [6.1.7.3](https://tc39.github.io/ecma262/#sec-invariants-of-the-essential-internal-methods). Citing the spec:
> An implementation must not allow these invariants to be circumvented in any manner...

Among other things, the integrity of proxies depends on that.

**Comment by jugglinmike** [comment]
I've opened gh-653 to address this.
