### ISSUE TITLE
Object.defineProperties must not throw when provided undefined in place of a descriptor

### ISSUE THREAD

**Issue by claudepache** [tc39/test262#652]
Apparently, a change between ES5 and ES6 not reflected in the test suite, (neither in the few implementations I have checked, BTW).

[test/built-ins/Object/defineProperties/15.2.3.7-5-b-1.js](https://github.com/tc39/test262/blob/master/test/built-ins/Object/defineProperties/15.2.3.7-5-b-1.js) contains:

```js
var obj = {};
assert.throws(TypeError, function() {
            Object.defineProperties(obj, {
                prop: undefined
            });
});
```
(I have not checked the numerous other tests about the same step.)

However, according to [ecma262#sec-objectdefineproperties](https://tc39.github.io/ecma262/#sec-objectdefineproperties) Step 5.b, undefined values must not throw, but be ignored.

**Comment by leobalter** [comment]
It properly throws a TypeError when you call ToPropertyDescriptor passing an undefined value:

```
6.2.4.5 ToPropertyDescriptor ( Obj )

1. If Type(Obj) is not Object, throw a TypeError exception.
...

---

19.1.2.3.1 Runtime Semantics: ObjectDefineProperties ( O, Properties )

1. If Type(O) is not Object, throw a TypeError exception.
2. Let props be ? ToObject(Properties).
3. Let keys be ? props.[[OwnPropertyKeys]]().
4. Let descriptors be a new empty List.
5. Repeat for each element nextKey of keys in List order,
  a. Let propDesc be ? props.[[GetOwnProperty]](nextKey).
  b. If propDesc is not undefined and propDesc.[[Enumerable]] is true, then
    i. Let descObj be ? Get(props, nextKey).
    ii. Let desc be ? ToPropertyDescriptor(descObj).
    iii. Append the pair (a two element List) consisting of nextKey and desc to the end of descriptors.
6. For each pair from descriptors in list order,
  a. Let P be the first element of pair.
  b. Let desc be the second element of pair.
  c. Perform ? DefinePropertyOrThrow(O, P, desc).
7. Return O.

---

```

```js
var o = {};
var properties = { prop: undefined };

Object.defineProperties(o, properties);
// props = properties
// keys = [ 'prop' ]
// keys => each( nextKey ):
//   nextKey = 'prop'
//   propDesc = props.[[GetOwnProperty]]('prop')
//   propDesc = {value: undefined, writable: true, enumerable: true, configurable: true}
//   descObj = Get(props, 'prop')
//   descObj = undefined
//   desc = ToPropertyDescriptor(undefined)
//     => descObj((undefined)) is not Object, throw a TypeError exception.
```

**Comment by claudepache** [comment]
@leobalter You missed the check against undefined in step 5.b of ObjectDefineProperties:
> 5.b. If ***propDesc is not undefined*** and propDesc.[[Enumerable]]  is true, then

As I have verified, that check was not present in ES5 but is present since ES6.

**Comment by claudepache** [comment]
There was some confusion of my part: In step 5b of DefinePropertyDescriptors, the condition is `propDesc is undefined`, and not `propDesc.[[Value]] is undefined`. Sorry.

**Comment by leobalter** [comment]
It is confusing as it catches the prop descriptors to find the enumerables
properties.

Btw, `propDesc.value` is undefined, but [[Value]] is the value of propDesc.

**Comment by leobalter** [comment]
Or no, I'm in a train and will revise my last comment in a better moment.
