### ISSUE TITLE
no .next function for iterator.

### ISSUE THREAD

**Issue by akroshg** [tc39/test262#670]
Say for this [test](https://github.com/tc39/test262/blob/master/test/language/expressions/assignment/dstr-array-rest-iter-rtrn-close.js#L55), there is no .next function defined in the iterator. it gives error when I run the test on Edge, Chrome and FireFox.

**Comment by jugglinmike** [comment]
The test failures you are experiencing are indication of bugs in those
runtimes. Take a look at the "info" meta-data of that test:

>     1. If DestructuringAssignmentTarget is neither an ObjectLiteral nor an
>        ArrayLiteral, then
>        a. Let lref be the result of evaluating DestructuringAssignmentTarget.
>        b. ReturnIfAbrupt(lref).

If the evaluation of "lref" results in an abrupt completion (as is the case for
this test), the algorithm returns immediately--prior to the later invocation of
IteratorStep.

We could make this expectation more explicit by defining a "poisoned" `next`
property (an accessor that always throws), but that would not effect the
correctness of the test.

**Comment by littledan** [comment]
Given the widespread bug across runtimes, I wonder if it would make sense to rewrite those tests in a way that can get at the same thing, but without depending on the order of evaluating the lref vs other code. For V8, those test are not currently meaningfully testing the iteration protocol, just all pointing out the same bug in our implementations.

However, I'd also sympathize with leaving the tests as is--there is currently no proposal to change the semantics, and the last proposal to do a similar change (brought by Microsoft) was rejected once one implementation found it could follow the spec. cc @bterlson @efaust

**Comment by akroshg** [comment]
@littledan, yes here is chakracore as well many of those failures are one single issue.
@jugglinmike makes sense. However I like the idea of bad next function to make the intent very clear.

**Comment by bterlson** [comment]
@littledan I think we just need to fix our lref bugs :-P  But that said, the normal constraint of not testing more than we need to applies. I am in favor of eliminating the dependency on the lref semantics if possible, but I'm not sure it is. I also think it's a good idea to be aware of common failure paths and help people understand those failures, so I would also support addition of a next getter that throws.
