### ISSUE TITLE
SpreadElement used in ArrayLiteral is lacking tests

### ISSUE THREAD

**Issue by avdg** [tc39/test262#671]
I've noticed only 26 indirect test related to testing spread in `ArrayLiteral`s, they are easy to pass if spread is followed only by an identifier.  A `assignmentExpression` is allowed after the spread punctuator in current grammar.

**Comment by jugglinmike** [comment]
Thanks for the report! It's great to see parsers making use of Test262 and even better to see contributions coming back. (By the way, you may be interested in gh-196 and the proposed solution at gh-655.)

@leobalter and I recently began [a coverage audit for ES2015 features](https://github.com/bocoup/test262-v8-machinery/wiki/2016-audit), and "spread in array initializers" made our list, too.

I've submitted gh-672 to address this.

**Comment by avdg** [comment]
Thanks! And yeah, I had some doubts about these negative tests. Thanks for clarifying that error will be checked soon.

**Comment by jugglinmike** [comment]
Apologies: I'm a little confused about your comment. When you say, "some doubts
about these negative tests," are you referring to technically incorrect test
files (either in the `master` branch or in this pull request)? Or are you
referring to the difficulty of consuming tests that are expected to produce
runtime errors?

**Comment by avdg** [comment]
Uh, I rather thought about the error checking involved into these negative tests.

**Comment by avdg** [comment]
And sorry, this was a bit off topic

**Comment by jugglinmike** [comment]
No problem--I just wanted to be sure that we don't have any invalid tests!

**Comment by michaelficarra** [comment]
@avdg: You may also be interested in #559. I'd love to see UglifyJS start using those tests. I will get them published to https://github.com/tc39/test262-parser-tests ASAP.

**Comment by avdg** [comment]
@michaelficarra Are there es5.1 specific tests too?

**Comment by michaelficarra** [comment]
@avdg No. In my opinion, all of the tests should be kept up to date with the latest working draft. Anyway, the tests are now published at https://github.com/tc39/test262-parser-tests.

**Comment by avdg** [comment]
Should now be resolved in #672
