### ISSUE TITLE
Outdated test: built-ins/Object/internals/DefineOwnProperty/nan-equivalence.js

### ISSUE THREAD

**Issue by bakkot** [tc39/test262#683]
This was added in #648 as part of the discussion in tc39/ecma262#353, but the resolution of that discussion was to [remove](https://github.com/tc39/ecma262/commit/173356a09da0be2bdc89cb1e1de14089e4023205) the behavior that this test is checking for.

**Comment by leobalter** [comment]
This is right, the test needs an update. My bad to compare this with the specs before the change has merged in the specs.
