### ISSUE TITLE
detached-buffer-before-outofrange-byteoffset.js tests are probably incorrect

### ISSUE THREAD

**Issue by evilpie** [tc39/test262#731]
I was just re-implementing GetViewValue in SpiderMonkey and we keep failing these tests. I think however that tests are wrong.

`dataView.getInt8(Infinity)` should throw a RangeError by calling ToIndex(+Inf) from my understanding.
ToLength(+Inf) would be 2^53 - 1, which is obviously different from +Inf.

**Comment by evilpie** [comment]
built-ins/DataView/prototype/setInt8/range-check-after-value-conversion has the same problem with `setInt8(Infinity, poisoned) `.

**Comment by jugglinmike** [comment]
Thanks for the report! This was previously reported in the discussion of gh-685, and a patch is under review at gh-699.

**Comment by evilpie** [comment]
Sorry, I should have checked before. Hope this gets merged soon.
