### ISSUE TITLE
Coverage for trailing function commas

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#732]
[Trailing function commas](https://github.com/jeffmo/es-trailing-function-commas) is moving to Stage 4. We don't have tests for it yet.

@jeffmo agreed to provide a PR w/ tests before the proposal is merged to tc39/ecma262.

**Comment by jeffmo** [comment]
So I have a test written, now I'm trying to actually run it to verify... Having a little trouble with that.

I have the following test file in `/Users/jeffmo/Projects/test262/test/language/function-arguments-trailing-comma/function-arguments-trailing-comma.js`:

```js
/*---
description: Check that trailing commas are permitted in function argument lists
info: http://jeffmo.github.io/es-trailing-function-commas/
author: Jeff Morrison <lbljeffmo@gmail.com>
---*/

function f1(a,) {}
function f2(a, b,) {}

f1(1);
f1(1,);

f2(1, 2);
f2(1, 2,);

assert.sameValue(
  f1.length,
  1,
  "Function with 1 arg + trailing comma reports incorrect .length!",
);

assert.sameValue(
  f2.length,
  2,
  "Function with 2 args + trailing comma reports incorrect .length!",
);
```

To run the test, I've done `npm install -g test262-harness` followed by:

```bash
$ test262-harness \
test262/test/language/function-arguments-trailing-comma/function-arguments-trailing-comma.js \
--hostType node \
--hostPath /opt/homebrew/bin/node \
--test262Dir /Users/jeffmo/Projects/test262
```

This `test262-harness` command, however, doesn't output anything (I expect the test to fail given that node does not support trailing commas).

Does anyone have any clue what I might be doing wrong here?

(cc @bterlson)

**Comment by jeffmo** [comment]
To follow up: The issue seems to be fixed by using a relative path to `./function-arguments-trailing-comma.js` (rather than the "test262/..." path, which is invalid in the CWD)

**Comment by jeffmo** [comment]
Tests went in here: https://github.com/tc39/test262/pull/733

This should be good to close now
