### ISSUE TITLE
getCanonicalLocales() test: need to test the result is mutable (rather than frozen). 

### ISSUE THREAD

**Issue by jungshik** [tc39/test262#745]
In my initial  v8 implementation, I returned a frozen array. There should be a test to make sure that the result is mutable. (or do we want to revise the spec for getCanonicalLocales() to return a frozen array? ). 

Adding the following line to returned-object-is-an-array.js will do the job. 

```assert.sameValue(result.push('fr'),  2, "result.push('fr')");```

I can make a pull request (if it's better that way) once I'm done with CLA, etc. 

@zbraniecki @littledan

**Comment by jungshik** [comment]
Just heard that no need for me to sign a CLA (Google's corp CLA should work for me).

**Comment by zbraniecki** [comment]
I don't have an opinion on if we should return mutable or frozen array.

@caridy - what's your preference here?

**Comment by caridy** [comment]
We normally avoid that in ecmascript in general. In this case, since this will return a new array every time, there is not reason for freezing it.

**Comment by jungshik** [comment]
@littledan wrote in https://github.com/tc39/test262/pull/746#issuecomment-239542852

> Actually, it looks from the 402 spec like only the individual elements are made non-writable, 
> while the length is left writable (though V8 may have a bug here), so I'm not sure if this test 
> is correct.

Per his comment, I updated the test I'm adding ( https://github.com/tc39/test262/pull/746 ) as well as my v8 patch ( https://codereview.chromium.org/2239523002/). 

@caridy :  do you agree with @littledan that freezing individual elements while making the result array still expandable is what spec requires ?

**Comment by caridy** [comment]
@jungshik I have commented on the original issue here https://github.com/tc39/test262/pull/746#issuecomment-239687454
