### ISSUE TITLE
Add a test for ES change in toPrecision

### ISSUE THREAD

**Issue by littledan** [tc39/test262#759]
A spec change was recently made in ECMA262 to meet web reality in https://github.com/tc39/ecma262/commit/c2e2dd2015733e438ae8c30179315978306c6851  . V8 didn't seem to fail any test262 test before this spec change was plade, even though it implemented the new spec rather than the old. It would be nice to have a test for the new semantics. cc @bterlson @Yaffle

**Comment by bterlson** [comment]
It's tested fairly extensively already (including the exact test case in the PR), see toPrecision/exponential.js

**Comment by littledan** [comment]
Oh, I see, the tests were already "incorrect" and matched the new spec.

**Comment by bterlson** [comment]
Yeah this was a legit spec bug :)

**Comment by leobalter** [comment]
... I wanted to cast a shrugs emoji, as I'm glad to see it resolved through my test bug, but I'm more like using a facepalm for myself here.

/me runs in despair and shame.
