### ISSUE TITLE
Change tests for SuperCall error semantics change

### ISSUE THREAD

**Issue by littledan** [tc39/test262#780]
In https://github.com/tc39/ecma262/pull/685 , an early error was added for eval containing a super call when not in a constructor. This invalidates a number of test262 tests:

language/expressions/super/call-new-target-undef
language/eval-code/direct/super-call-fn
language/expressions/super/prop-dot-fn-no-super-bndng
language/expressions/super/prop-expr-fn-no-super-bndng
language/expressions/super/prop-expr-fn-eval-before-has-super

cc @bterlson @jugglinmike

**Comment by jugglinmike** [comment]
You got it! See gh-781.

**Comment by bterlson** [comment]
This can probably be closed, though we also need tests for the NewTarget change in a similar vein. I'm not sure that change invalidates any tests, however...

**Comment by leobalter** [comment]
closing this as solved while we now have #915 to address the NewTarget part (it helps me to keep track)
