### ISSUE TITLE
Meta: doneprintHandle.js naming inconsistency

### ISSUE THREAD

**Issue by bakkot** [tc39/test262#791]
[INTERPRETING.md](https://github.com/tc39/test262/blob/84e6ba81d0861c7324cb0f4202ce40acd861b1ef/INTERPRETING.md) refers to `harness/donePrintHandle.js`, but the actual file is named `harness/doneprintHandle.js`. They should be consistent.

Personally I think the actual file's name ought to be fixed, but this might not be worth the cost to consumers.

**Comment by jugglinmike** [comment]
I agree that changing the file name would be preferable but that the cost to
consumers is hard to judge. For the short term, lets consider it a typo in the
documentation--see gh-799 for a fix along those lines.
