### ISSUE TITLE
Rename $ to $262 to prevent conflict with literal $ tests (Formerly "Tests use $")

### ISSUE THREAD

**Issue by bterlson** [tc39/test262#802]
Some tests (eg. language/identifiers/start-dollar-sign.js) use $ as an identifier. According to interpreting.md, this should be invalid - tests cannot clobber $ else harnesses will fail unexpectedly. Should we update tests using `$` to use `$$` instead?

**Comment by bakkot** [comment]
I don't think it's a problem as long as the test doesn't make use of the harness or assert that the global `$` property does not exist or is undefined. The API object is supposed to be defined as writable and configurable.

I'd prefer updating the API to use a less collision-prone name, but changing the API is a cost to consumers.

**Comment by bterlson** [comment]
It is a problem because $ is necessary for the harness to operate even in cases where the test doesn't explicitly touch it (for example, every test has to call $DONE which in test262-harness wants to call $.destroy() to tear down the realm). Clobbering code injected by the harness to control the test environment seems bad generally.

I'm open to changing to a less collision prone name. I like $ for general usage of eshost, but I can easily make that binding configurable. Test262 could use $$$ or something :-P.

**Comment by bakkot** [comment]
Test262 doesn't require calling $DONE for every test or defining $.destroy; that's just a problem with test262-harness :P

But yeah, agreed that it's bad. My vote for a new name would be `$Test262API` or similar.

**Comment by bterlson** [comment]
I see now that interpreting.md was changed to require calling "print" at some point instead of $DONE. I don't understand that requirement as print should be used for diagnostics not controlling the execution of tests. Furthermore, it does not actually reflect the requirements of test262 tests currently checked in - see, eg, all the promise tests that definitely require calling $DONE.

**Comment by bakkot** [comment]
$DONE [calls print](https://github.com/tc39/test262/blob/master/harness/doneprintHandle.js).

**Comment by bterlson** [comment]
The current specification in interpreting suggests that calling print with anything other than the special string fails the test which seems wrong. Also, the harness in test262 assumes all coordination between host and harness is accomplished via stdout but for many reasons $DONE is a better way to do it (eg. you can batch multiple tests in a single host process invocation).

**Comment by bakkot** [comment]
It just says "exposes the string value of its first argument to the test runner", nothing about stdout (which doesn't even make sense in some contexts, e.g. web). In the web runner I just define `print` to be "check if the message is correct; mark current test as passing if so, mark as failing if not".

That said, it's only ever *called* from $DONE, so I'm kind of unclear what the point of it is. Legacy reasons, I'm guess, like harness/cth.js (which nothing refers to).

**Comment by bterlson** [comment]
Print is useful when writing tests. It seems wrong to say that a test with debug output should always fail.

**Comment by rwaldron** [comment]
| # | Code | Found in... |
| -- | -------------------- | ------------------------------------------------------------------------|
| 1 | `export { x as $ };` | test/language/module-code/namespace/internals/own-property-keys-so rt.js |
| 2 | `var $ = 1;` | test/language/identifiers/val-dollar-sign.js |
| 3 | `assert.sameValue($, 1);` | test/language/identifiers/val-dollar-sign-via-escape-hex4.js |
| 4 | `assert.sameValue($, 1);` | test/language/identifiers/val-dollar-sign-via-escape-hex.js |
| 5 | `var $ = 1; assert.sameValue($, 1);` | test/language/identifiers/start-dollar-sign.js |
| 6 | `assert.sameValue($, 3);` | test/language/identifiers/start-escape-seq.js |


@bterlson At the moment, I believe renaming the utility `$` to something less generic, eg. `$262` (or whatever shakes out) seems like the best long term solution. I went that way due to the unicode character and escape sequence tests above (# 3, 4, 6)


Let's decide on a path and I will assign myself to complete.

**Comment by bterlson** [comment]
$262 is fine by me.

**Comment by bakkot** [comment]
If we're changing the API, can we consider renaming the API hook currently named `print` as well, per above? Ideally to something on the `$262` (or whatever) object. (I still like `$Test262API`, but really do not care very much.)

**Comment by rwaldron** [comment]
> $262 is fine by me.

👍 

> can we consider renaming the API hook currently named print as well, 

If there's no opposition...

**Comment by bterlson** [comment]
What's wrong with print() as is? Changing will require work so I'll default to wanting it to stay unless it's bad.

**Comment by bakkot** [comment]
@bterlson, [you were the one objecting to it](https://github.com/tc39/test262/issues/802#issuecomment-269670188), no?

**Comment by bterlson** [comment]
@bakkot no, I was objecting to using print to signal test completion only (as is currently required by interpreting.md), not its name which I think is fine (and is implemented by many console hosts anyway).

**Comment by bakkot** [comment]
Ah. We should have something which serves the function which `print` currently serves per INTERPRETING.md, I think, so I am proposing that we rename whatever that is.

**Comment by bterlson** [comment]
We could call it $DONE and change nothing :)

**Comment by bakkot** [comment]
That'd be ok by me! Although I'm happier with API methods being defined on the `$` object, in general.

As an example, we could add to the API a method named `asyncTestCompletion` or whatever, which does exactly what `print` is currently specified to do. Then `doneprintHandle.js` could become

```js
function __consolePrintHandle__(msg){
	if (!$ || typeof $.asyncTestCompletion !== "function")
		print(msg);
	else
		$.asyncTestCompletion(msg);
}

function $DONE(){
	if(!arguments[0])
		__consolePrintHandle__('Test262:AsyncTestComplete');
	else
		__consolePrintHandle__('Error: ' + arguments[0]);
}
```

and maybe add a harness test for the existence of `$.asyncTestCompletion`.

Not strongly attached to any of this, though. It doesn't make hardly any difference in my implementation; I just think it's a little cleaner.

**Comment by bterlson** [comment]
$262.done would be fine by me too, but I don't see a strong need to change it since it introduces friction.

I don't know why you're calling that thing __consolePrintHandle__. It's also very close to the historic (and current [test262-compiler](https://github.com/bterlson/test262-compiler/blob/master/lib/compilerdeps.js)) definition of $ERROR which the exception of reporting non-errors as well.

I also would suggest that $.done is a better name. While interpreting.md doesn't require it anymore for some reason, it is IMO necessary to invoke it when a sync test has finished otherwise tests that don't run at all are reported as passing.

**Comment by bakkot** [comment]
`__consolePrintHandle__` is just what's already in [the file](https://github.com/tc39/test262/blob/master/harness/doneprintHandle.js).

It's a little ambiguous whether we ought to have a `done` for synchronous tests. INTERPRETING.md already says that a test only passes if 'execution completes'; hosts can chose to assert that by appending a call to something which marks the test as done, but in principle they could do it by some other means as well.

**Comment by bterlson** [comment]
In lieu of "other means" actually existing I think it makes most sense to require that $DONE is called once for each test (with exception of raw tests, I guess).
