### ISSUE TITLE
Test that __lookupGetter__/__lookupSetter__ call Proxy traps

### ISSUE THREAD

**Issue by littledan** [tc39/test262#808]
This might be useful; V8 apparently didn't do this, and it recently fixed it in https://codereview.chromium.org/2592013003/ . Not sure if other browsers had a similar bug. I don't see any tests that verify it, whereas we have tests using Proxy traps to get at a lot of other things.

**Comment by ajklein** [comment]
There are tests that check that proxy traps are called, for example, https://github.com/tc39/test262/blob/master/test/annexB/built-ins/Object/prototype/__lookupGetter__/lookup-proto-get-err.js

None of the tests check for the non-error case of Proxies, though, and that would be good to have.
