### ISSUE TITLE
Missing tests built-ins/Array/*

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#832]
- name.js ([Example](https://github.com/tc39/test262/blob/master/test/built-ins/Array/from/Array.from-name.js))
- length.js ([Example](https://github.com/tc39/test262/blob/master/test/built-ins/Array/of/length.js))
- descriptor.js ([Example](https://github.com/tc39/test262/blob/master/test/built-ins/Array/from/Array.from-descriptor.js))

**Comment by DavidBruant** [comment]
hey @rwaldron, I see https://github.com/littledan/test262/commit/d10e980278ef4e9135b4deffddaa6c01a51d9b1a suggesting this is covered. Are there other tests missing?

**Comment by leobalter** [comment]
@DavidBruant that commit is actually referring to tc39/ecma262#832.
