### ISSUE TITLE
Missing tests built-ins/Array/prototype/constructor/*

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#834]
- descriptor.js ([Example](https://github.com/tc39/test262/blob/master/test/built-ins/Array/from/Array.from-descriptor.js))

**Comment by shvaikalesh** [comment]
This was resolved in https://github.com/tc39/test262/blob/7972f9bbdc491295c28ca6cc11ee53683a451ef1/test/built-ins/Array/prototype/constructor.js

**Comment by rwaldron** [comment]
Indeed! Thanks for triaging :)
