### ISSUE TITLE
Annex B html5 string tests.

### ISSUE THREAD

**Issue by jdalton** [tc39/test262#85]
@mathiasbynens has some rad [Annex B](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-additional-ecmascript-features-for-web-browsers) string tests over on [mathias.html5.org](http://mathias.html5.org/tests/javascript/string/).
It would be great to port them over to test262.

**Comment by leobalter** [comment]
@mathiasbynens I'm sorry we just jumped ahead and got this part covered already. :) I love HTML comments in JS
