### ISSUE TITLE
Rename uses of global vars named `name` and `length`

### ISSUE THREAD

**Issue by syg** [tc39/test262#850]
There are tests that use `var name` at the top level. This ends up triggering the `name` setter on the WindowProxy in browsers. Ditto for `length`. We should rename these var names, as well disallow future tests from using them at the global level.

The web runner from I think does a regexp on the test source, and if the test contain uses of `name` or `length`, it actually deletes the properties from the window. @bakkot, is that right?

**Comment by bakkot** [comment]
@syg [Indeed](https://github.com/bakkot/test262-web-runner/blob/19ebf41bd477be242c5aea4e37f7480e5a68d60a/main.js#L340-L342).

**Comment by leobalter** [comment]
I need to figure out a good solution for these cases:

- src/dstr-assignment/array-rest-nested-obj-undefined-hole.case
- src/dstr-assignment/array-rest-nested-obj-undefined-own.case
- src/dstr-assignment/array-rest-nested-obj-undefined.case
- test/language/expressions/assignment/dstr-array-rest-nested-obj-undefined-hole.js
- test/language/expressions/assignment/dstr-array-rest-nested-obj-undefined-own.js
- test/language/expressions/assignment/dstr-array-rest-nested-obj-undefined.js
- test/language/statements/for-of/dstr-array-rest-nested-obj-undefined-hole.js
- test/language/statements/for-of/dstr-array-rest-nested-obj-undefined-own.js
- test/language/statements/for-of/dstr-array-rest-nested-obj-undefined.js
