### ISSUE TITLE
Top-level `await` should not be considered a syntax error outside of module code.

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/test262#863]
Example: [this test](https://github.com/tc39/test262/blob/master/test/language/expressions/async-arrow-function/early-errors-arrow-await-in-formals-default.js) should throw a runtime `ReferenceError` when [not parsed as a module](https://tc39.github.io/ecma262/#sec-identifiers-static-semantics-early-errors).

**Comment by bakkot** [comment]
It's a syntax error in an async function, though, as that test is, yes?

**Comment by isiahmeadows** [comment]
@bakkot I thought the parameters were parsed in the parent's async/non-async context, not in the context of the parent, so it should be legal IIRC. I may be wrong, though.

If that were defined in the body of *another* async function, I would agree.

**Comment by bakkot** [comment]
@isiahmeadows [AsyncArrowFunction](https://tc39.github.io/ecma262/#prod-AsyncArrowHead) sets `[+Await]` on its `ArrowFormalParameters`, which I *think* means that `await` is unconditionally interpreted as the start of an `AwaitExpression`, and so would be a SyntaxError in this context.

**Comment by isiahmeadows** [comment]
Okay...so does it still work in sloppy mode?

**Comment by bakkot** [comment]
It should be the same either way.

**Comment by isiahmeadows** [comment]
@bakkot I see. Thanks!
