### ISSUE TITLE
Add tests for Object rest/spread properties

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#865]
@sebmarkbage do you already have someone working on the tests for this proposal? If not, we might take this task.

**Comment by sebmarkbage** [comment]
I've started converting from the other Array rest/spread cases so that we cover the same scenarios. Unfortunately I've had to take a break on this until mid-March, so any help would be appreciated.

**Comment by littledan** [comment]
@gsathya has checked in a number of tests into V8; those might be a good starting point

**Comment by sebmarkbage** [comment]
Also see these from WebKit https://github.com/sebmarkbage/ecmascript-rest-spread/issues/32#issuecomment-279269912

**Comment by caiolima** [comment]
@sebmarkbage If you are ok, I can submit a PR with WebKit's tests here.

**Comment by sebmarkbage** [comment]
@caiolima That'd be great!

**Comment by leobalter** [comment]
Caio, for test262 perspective, this would be great and we can coordinate
the tests migration.

I'll send you an email and see if we can connect in a video call. It's not
really necessary but great as we can talk about it in our native language.
:)

**Comment by caiolima** [comment]
@leobalter sure! I'm planing to work on that tomorrow and during the weekend. I've seen that array Rest/spread tests are slightly different from the last PR I've submitted, since they are generated from sources into src/dstr-assignment, but I can figure out its pattern.

**Comment by caiolima** [comment]
@leobalter and @sebmarkbage, I've opened the PR #867 with a initial set of tests for Object Rest deconstruction. But I have 2 questions before go further:

1. What Am I supposed to put in esid field?
2. I want to add some syntax tests, but I'm confused if I should add them and also where should I place them.

I'm planing to create tests for Object Spread this weekend.

**Comment by leobalter** [comment]
#867 #890 and #892 should be covering Object Rest Spread for now. I'll check if we find more edge cases - and compare with the tests on v8. I'll follow up w/ new PRs if I find more coverages to fill.

credits to @caiolima who did a great work here!

**Comment by leobalter** [comment]
I am reopening this because of a few extra items:

- [ ] #1050
- [ ] #1132

**Comment by adrianheine** [comment]
I think the negative tests for complex rest properties are still missing.

**Comment by leobalter** [comment]
Thanks for letting me know, I'll get this fixed today.
