### ISSUE TITLE
New tests which need the $ -> $262 change

### ISSUE THREAD

**Issue by anba** [tc39/test262#875]
The following tests need to be updated to use `$262`.

- test/built-ins/Atomics/wait/did-timeout.js
- test/built-ins/Atomics/wait/good-views.js
- test/built-ins/Atomics/wait/nan-timeout.js
- test/built-ins/Atomics/wait/negative-timeout.js
- test/built-ins/Atomics/wait/no-spurious-wakeup.js
- test/built-ins/Atomics/wait/was-woken.js
- test/built-ins/Atomics/wake/wake-all-on-loc.js
- test/built-ins/Atomics/wake/wake-all.js
- test/built-ins/Atomics/wake/wake-in-order.js
- test/built-ins/Atomics/wake/wake-nan.js
- test/built-ins/Atomics/wake/wake-negative.js
- test/built-ins/Atomics/wake/wake-one.js
- test/built-ins/Atomics/wake/wake-two.js
- test/built-ins/Atomics/wake/wake-zero.js
- test/built-ins/DataView/proto-from-ctor-realm-sab.js
- test/built-ins/SharedArrayBuffer/proto-from-ctor-realm.js
- test/built-ins/TypedArrays/buffer-arg-proto-from-ctor-realm-sab.js

**Comment by leobalter** [comment]
thanks! I'm fixing it right now
