### ISSUE TITLE
undocumented flag "generated"

### ISSUE THREAD

**Issue by soliton4** [tc39/test262#885]
its not documented what the flag "generated" means

**Comment by jugglinmike** [comment]
Thanks for the heads-up! I've submitted documentation for that metadata at gh-886.

**Comment by soliton4** [comment]
i am in the process of writing a test for javascript extending languages.
my test stops every time it encounters an unimplemented flag or member. i think thats a good way to go about it.
but undocomented flags tend to irritate.

thanks for making the effort to fix it
