### ISSUE TITLE
Defining `Symbol.hasInstance` on callables

### ISSUE THREAD

**Issue by Zirak** [tc39/test262#899]
This is a half-issue, half-question. While poking around with `Symbol.hasInstance` I noticed something odd (Chrome 58, Firefox 54 and Edge 38):

```js
function foo() {}
foo[Symbol.hasInstance] = function (x) {
     console.log('hasInstance', x);
    return false;
};

'' instanceof foo;
```

In none of them was the `console.log` triggered, which is confusing. Reading [12.10.4 InstanceofOperator](https://tc39.github.io/ecma262/#sec-instanceofoperator) seems to be straightforwardly saying "grab `Symbol.hasInstance` and lacking that, do `OrdinaryHasInstance`".

Am I missing something, or is this a possible oversight?

**Comment by evilpie** [comment]
Symbol.hasInstance on the Function.prototype is not writable so your assignment fails, observe the behavior with strict mode enabled.

**Comment by Zirak** [comment]
*facepalm* [You're right](https://tc39.github.io/ecma262/#sec-function.prototype-@@hasinstance), stupid me. Thanks.
