### ISSUE TITLE
web-platform-tests "Typed Array" tests

### ISSUE THREAD

**Issue by annevk** [tc39/test262#902]
https://github.com/w3c/web-platform-tests/tree/master/typedarrays should probably be moved here? And maybe deduplicated?

**Comment by leobalter** [comment]
I just checked the files on the link above and I believe we've already got these parts covered already.

- [x] ArrayBuffer constructor
  - [x] different length arg values
  - [x] different length arg types
  - [x] length arg boundaries
  - [x] invalid values for length arg
- [x] ArrayBuffer properties, slice, byteLength, isView, etc
- [x] Uint8ClampedArray tests
  - [x] constructor
  - [x] length
  - [x] set
  - [x] subarray
- [x] general TypedArray constructors

Although, we have a lot of test files covering this and way more. While cross linking each part in this list would require me a time I don't have right now, I'm willing to help if you need to find any specific coverage in our tests.

There is a lot to explore in these links below:

- https://github.com/tc39/test262/tree/master/test/built-ins/TypedArray (mostly for the prototype properties)
- https://github.com/tc39/test262/tree/master/test/built-ins/TypedArrays (general constructors)
- https://github.com/tc39/test262/tree/master/test/built-ins/ArrayBuffer
- https://github.com/tc39/test262/tree/master/test/built-ins/DataView

Plus:

- https://github.com/tc39/test262/tree/master/test/built-ins/SharedArrayBuffer
- https://github.com/tc39/test262/tree/master/test/built-ins/Atomics

**Comment by annevk** [comment]
Okay, thanks, I'm going to suggest we drop them from web-platform-tests then.

**Comment by leobalter** [comment]
sure! One thing I would suggest is check if we can identify any specific cases we can observe for web browsers only, like different length boundaries, etc. 

I don't know anything right now that should be running differently than in the runtimes, but I live pretty much in the runtime-only box.

**Comment by annevk** [comment]
Are you testing detaching? I don't think you can get in that state just from "pure" JavaScript API.

**Comment by leobalter** [comment]
We cover detached buffers, but it needs implementation defined parts.

Considering these limits, we try to call a harness defined [`$DETACHBUFFER(buffer)`](https://github.com/tc39/test262/blob/fdd2fa9b1c2f64a2a376556af9f2cb3b90373937/harness/detachArrayBuffer.js) so tests can rely on this mode if available.

Examples:

- https://github.com/tc39/test262/blob/da4f4385fdf88ff2c8acf036efaaa62f8cd6bd58/test/built-ins/TypedArrays/internals/Get/detached-buffer.js#L21
- https://github.com/tc39/test262/blob/da4f4385fdf88ff2c8acf036efaaa62f8cd6bd58/test/built-ins/TypedArray/prototype/byteOffset/detached-buffer.js
- https://github.com/tc39/test262/blob/da4f4385fdf88ff2c8acf036efaaa62f8cd6bd58/test/built-ins/TypedArray/prototype/findIndex/detached-buffer.js
