### ISSUE TITLE
Travis CI timeout waiting for a passphrase.

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#964]
https://travis-ci.org/tc39/test262/ is failing in a timeout waiting for a passphrase.

I set the key without a passphrase as I expected it would be easier for scripting with Travis CI, it still requests a passphrase in there.

I don't know how to fix this properly.

**Comment by leobalter** [comment]
Example: https://travis-ci.org/tc39/test262/builds/220849297#L189

This is happening during the `ssh-add github-deploy-key`.

**Comment by edgemaster** [comment]
`ssh-add` seems to request a passphrase also if the provided keyfile is corrupted or malformed.

I also note that the `openssl` command outputs the error message `iv undefined`.

I've remade the ssh keys on my own fork, updated the various variable names that needed changing, and ran the CI, which seems to have got past this problem.

Speculation: Do the encryption environment variable names defined at https://travis-ci.org/tc39/test262/settings match those defined in `scripts/ci/deploy.sh` (`encrypted_7b3e5998334d_key` and `encrypted_7b3e5998334d_iv`)?

**Comment by leobalter** [comment]
I'll try this.

**Comment by leobalter** [comment]
Thanks! It's now fixed, see #996. I previously forgot to update the deploy script and to set travis to use this main repo instead of my fork.

I found it after you asked to check the encryption env variable names.
