### ISSUE TITLE
Add a test for early errors for duplicate generator and async function declarations in a block

### ISSUE THREAD

**Issue by littledan** [tc39/test262#982]
In [this PR](https://github.com/tc39/ecma262/pull/453), a web compatibility change was made to allow duplicate same-named FunctionDeclarations in a block. The change explicitly did not apply to GeneratorDeclarations or AsyncFunctionDeclarations. However, it seems like there aren't any tests to show the enforcement for these other cases, e.g., as would come up in these examples, where each line would be an early error:

```
(function() { { function* foo() {} function* foo() {} } })()
(function() { { function* foo() {} function foo() {} } })()
(function() { { function foo() {} function* foo() {} } })()
(function() { { async function foo() {} async function foo() {} } })()
```

(Footnote: In eshost tests, it looks to me like V8 is the only engine which has an error for the last one; an error for the earlier cases is currently deployed only to V8 users who have enabled a flag for advanced JS behavior.)

**Comment by anba** [comment]
#1023 adds new tests to cover syntax errors for lexical redeclarations in blocks.
