### ISSUE TITLE
There are still some tests that require argument.caller to exist and to be poisoned

### ISSUE THREAD

**Issue by hermanventer** [tc39/test262#989]
As per https://github.com/tc39/ecma262/pull/689, the requirement to poison arguments.caller has been removed from the standard.

https://github.com/tc39/test262/pull/797 was supposed to remove all references to arguments.caller from the test suite, but built-ins/Function/StrictFunction_restricted-properties.js still requires poisoned pill behavior for arguments.caller.

**Comment by leobalter** [comment]
the `test/built-ins/Function/StrictFunction_restricted-properties.js` file is checking for `caller` and `arguments` applied to function objects by [AddRestrictedFunctionProperties](https://tc39.github.io/ecma262/#sec-addrestrictedfunctionproperties) and also mentioned in the Forbidden Extensions section.

Those are not the same poison as the previous `arguments.caller`.

**Comment by leobalter** [comment]
cc @bterlson
