### ISSUE TITLE
ES6: Object.prototype.toString tests (+ @@toStringTag)

### ISSUE THREAD

**Issue by caitp** [tc39/test262#99]
V8 has support for this (for now): https://code.google.com/p/v8/source/detail?r=24783 --- The test cases I wrote for this might be suitable for adaptation into the ES6 test suite.

[There might be a few missing](https://code.google.com/p/v8/source/browse/branches/bleeding_edge/test/mjsunit/es6/object-tostring.js?spec=svn24783&r=24783), so it would be good to get a look at it.

**Comment by jugglinmike** [comment]
@caitp I think we're in pretty good shape, now; see below. Would you be
comfortable closing this issue?

    $ grep -E 'features:.*toStringTag' test/ -r -l

- [test/built-ins/ArrayIteratorPrototype/Symbol.toStringTag/property-descriptor.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/ArrayIteratorPrototype/Symbol.toStringTag/property-descriptor.js)
- [test/built-ins/MapIteratorPrototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/MapIteratorPrototype/Symbol.toStringTag.js)
- [test/built-ins/DataView/prototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/DataView/prototype/Symbol.toStringTag.js)
- [test/built-ins/Object/prototype/toString/symbol-tag-non-str.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/Object/prototype/toString/symbol-tag-non-str.js)
- [test/built-ins/Object/prototype/toString/get-symbol-tag-err.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/Object/prototype/toString/get-symbol-tag-err.js)
- [test/built-ins/Object/prototype/toString/symbol-tag-override.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/Object/prototype/toString/symbol-tag-override.js)
- [test/built-ins/Object/prototype/toString/symbol-tag-str.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/Object/prototype/toString/symbol-tag-str.js)
- [test/built-ins/GeneratorPrototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/GeneratorPrototype/Symbol.toStringTag.js)
- [test/built-ins/Map/prototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/Map/prototype/Symbol.toStringTag.js)
- [test/built-ins/WeakMap/prototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/WeakMap/prototype/Symbol.toStringTag.js)
- [test/built-ins/TypedArray/prototype/Symbol.toStringTag/this-has-no-typedarrayname-internal.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/TypedArray/prototype/Symbol.toStringTag/this-has-no-typedarrayname-internal.js)
- [test/built-ins/TypedArray/prototype/Symbol.toStringTag/prop-desc.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/TypedArray/prototype/Symbol.toStringTag/prop-desc.js)
- [test/built-ins/TypedArray/prototype/Symbol.toStringTag/name.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/TypedArray/prototype/Symbol.toStringTag/name.js)
- [test/built-ins/TypedArray/prototype/Symbol.toStringTag/this-is-not-object.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/TypedArray/prototype/Symbol.toStringTag/this-is-not-object.js)
- [test/built-ins/TypedArray/prototype/Symbol.toStringTag/return-typedarrayname.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/TypedArray/prototype/Symbol.toStringTag/return-typedarrayname.js)
- [test/built-ins/TypedArray/prototype/Symbol.toStringTag/invoked-as-func.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/TypedArray/prototype/Symbol.toStringTag/invoked-as-func.js)
- [test/built-ins/TypedArray/prototype/Symbol.toStringTag/invoked-as-accessor.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/TypedArray/prototype/Symbol.toStringTag/invoked-as-accessor.js)
- [test/built-ins/TypedArrays/prototype/Symbol.toStringTag/inherited.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/TypedArrays/prototype/Symbol.toStringTag/inherited.js)
- [test/built-ins/Set/prototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/Set/prototype/Symbol.toStringTag.js)
- [test/built-ins/ArrayBuffer/prototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/ArrayBuffer/prototype/Symbol.toStringTag.js)
- [test/built-ins/StringIteratorPrototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/StringIteratorPrototype/Symbol.toStringTag.js)
- [test/built-ins/Promise/prototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/Promise/prototype/Symbol.toStringTag.js)
- [test/built-ins/GeneratorFunction/prototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/GeneratorFunction/prototype/Symbol.toStringTag.js)
- [test/built-ins/Math/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/Math/Symbol.toStringTag.js)
- [test/built-ins/JSON/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/JSON/Symbol.toStringTag.js)
- [test/built-ins/Symbol/prototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/Symbol/prototype/Symbol.toStringTag.js)
- [test/built-ins/Symbol/toStringTag/prop-desc.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/Symbol/toStringTag/prop-desc.js)
- [test/built-ins/WeakSet/prototype/Symbol.toStringTag.js](https://github.com/tc39/test262/blob/b698c8b3ab2980cc1282cb08796d0b76337bf7d9/test/built-ins/WeakSet/prototype/Symbol.toStringTag.js)
